package com.oculus.messenger.service;

import X.AnonymousClass0Qr;
import X.AnonymousClass0VI;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class ServiceModule extends AnonymousClass0VI {

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
    }

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForServiceModule {
        public static void bind(AnonymousClass0Qr r0) {
        }
    }
}
