package com.oculus.libraryapi;

import X.AbstractC0247Xu;
import X.C00208d;
import X.I0;
import X.Pj;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class OVRLibraryModule extends I0 {
    public static volatile OVRLibraryInternal _UL__ULSEP_com_oculus_libraryapi_OVRLibraryInternal_ULSEP_INSTANCE;
    public static volatile OVRLibrary _UL__ULSEP_com_oculus_libraryapi_OVRLibrary_ULSEP_INSTANCE;

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForOVRLibraryModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_libraryapi_OVRLibraryInternal_ULSEP_BINDING_ID = 2111;
        public static final int _UL__ULSEP_com_oculus_libraryapi_OVRLibrary_ULSEP_BINDING_ID = 119;
    }

    @AutoGeneratedFactoryMethod
    public static final OVRLibrary A00(AbstractC0247Xu xu) {
        if (_UL__ULSEP_com_oculus_libraryapi_OVRLibrary_ULSEP_INSTANCE == null) {
            synchronized (OVRLibrary.class) {
                Pj A00 = Pj.A00(_UL__ULSEP_com_oculus_libraryapi_OVRLibrary_ULSEP_INSTANCE, xu);
                if (A00 != null) {
                    try {
                        _UL__ULSEP_com_oculus_libraryapi_OVRLibrary_ULSEP_INSTANCE = new OVRLibrary(C00208d.A00(xu.getApplicationInjector()));
                    } finally {
                        A00.A01();
                    }
                }
            }
        }
        return _UL__ULSEP_com_oculus_libraryapi_OVRLibrary_ULSEP_INSTANCE;
    }
}
