package com.oculus.auth.components;

import X.AbstractC06640p5;
import X.AnonymousClass0D4;
import X.AnonymousClass0DC;
import X.AnonymousClass0Pi;
import X.AnonymousClass0p1;
import X.AnonymousClass117;
import X.C01010Iv;
import com.facebook.inject.ApplicationScoped;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Eager;
import com.facebook.ultralight.Inject;
import javax.annotation.concurrent.Immutable;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_com_oculus_auth_components_AuthLogger_ULSEP_BINDING_ID"})
@ApplicationScoped
@Immutable
public final class AuthComponentRunner {
    public static volatile AuthComponentRunner _UL__ULSEP_com_oculus_auth_components_AuthComponentRunner_ULSEP_INSTANCE;
    @Inject
    @Eager
    public final AuthLogger mLogger;

    @AutoGeneratedAccessMethod
    public static final AnonymousClass0p1 _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_auth_components_AuthComponentRunner_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C01010Iv(6, r2);
    }

    @AutoGeneratedAccessMethod
    public static final AuthComponentRunner _UL__ULSEP_com_oculus_auth_components_AuthComponentRunner_ULSEP_ACCESS_METHOD(AbstractC06640p5 r1) {
        return (AuthComponentRunner) AnonymousClass117.A00(6, r1);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_auth_components_AuthComponentRunner_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C01010Iv(6, r2);
    }

    @AutoGeneratedFactoryMethod
    public static final AuthComponentRunner _UL__ULSEP_com_oculus_auth_components_AuthComponentRunner_ULSEP_FACTORY_METHOD(AbstractC06640p5 r4) {
        if (_UL__ULSEP_com_oculus_auth_components_AuthComponentRunner_ULSEP_INSTANCE == null) {
            synchronized (AuthComponentRunner.class) {
                AnonymousClass0Pi A00 = AnonymousClass0Pi.A00(_UL__ULSEP_com_oculus_auth_components_AuthComponentRunner_ULSEP_INSTANCE, r4);
                if (A00 != null) {
                    try {
                        _UL__ULSEP_com_oculus_auth_components_AuthComponentRunner_ULSEP_INSTANCE = new AuthComponentRunner(r4.getApplicationInjector());
                    } finally {
                        A00.A01();
                    }
                }
            }
        }
        return _UL__ULSEP_com_oculus_auth_components_AuthComponentRunner_ULSEP_INSTANCE;
    }

    /* JADX DEBUG: Type inference failed for r0v1. Raw type applied. Possible types: X.0DC<TContinuationResult>, X.0DC<T> */
    public <T> AnonymousClass0DC<T> runAsync(AnonymousClass0DC<T> r2, final String str, final AuthAction authAction) {
        return (AnonymousClass0DC<TContinuationResult>) r2.A09(new AnonymousClass0D4<T, T>() {
            /* class com.oculus.auth.components.AuthComponentRunner.AnonymousClass1 */

            @Override // X.AnonymousClass0D4
            public T then(AnonymousClass0DC<T> r5) throws Exception {
                Exception A0F = r5.A0F();
                AuthComponentRunner.this.mLogger.reportComponent(str, authAction, A0F);
                if (A0F == null) {
                    return r5.A0G();
                }
                throw A0F;
            }
        });
    }

    @Inject
    public AuthComponentRunner(AbstractC06640p5 r2) {
        this.mLogger = AuthLogger._UL__ULSEP_com_oculus_auth_components_AuthLogger_ULSEP_ACCESS_METHOD(r2);
    }
}
