package com.oculus.auth.components;

import X.AbstractC06640p5;
import X.AnonymousClass0DC;
import X.AnonymousClass0p1;
import X.AnonymousClass117;
import X.C003008y;
import X.C01020Iw;
import androidx.annotation.VisibleForTesting;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Eager;
import com.facebook.ultralight.Inject;
import com.oculus.auth.api.AuthMethods;
import com.oculus.auth.api.UserInfoResponse;
import com.oculus.horizon.api.ApiTaskCallback;
import javax.annotation.concurrent.ThreadSafe;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_com_oculus_auth_api_AuthMethods_ULSEP_BINDING_ID"})
@ThreadSafe
@VisibleForTesting
public class UserInfoFetcher {
    @Inject
    @Eager
    public final AuthMethods mAuthMethods;

    @AutoGeneratedAccessMethod
    public static final AnonymousClass0p1 _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_auth_components_UserInfoFetcher_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C003008y(38, r2);
    }

    @AutoGeneratedAccessMethod
    public static final UserInfoFetcher _UL__ULSEP_com_oculus_auth_components_UserInfoFetcher_ULSEP_ACCESS_METHOD(AbstractC06640p5 r1) {
        return (UserInfoFetcher) AnonymousClass117.A00(38, r1);
    }

    @AutoGeneratedFactoryMethod
    public static final UserInfoFetcher _UL__ULSEP_com_oculus_auth_components_UserInfoFetcher_ULSEP_FACTORY_METHOD(AbstractC06640p5 r1) {
        return new UserInfoFetcher(r1);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_auth_components_UserInfoFetcher_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C01020Iw(38, r2);
    }

    public AnonymousClass0DC<UserInfoResponse> fetchUserInfoAsync(String str) {
        ApiTaskCallback apiTaskCallback = new ApiTaskCallback();
        this.mAuthMethods.fetchUserInfo(str, apiTaskCallback);
        return apiTaskCallback.mCompletionSource.A00;
    }

    @Inject
    public UserInfoFetcher(AbstractC06640p5 r2) {
        this.mAuthMethods = AuthMethods._UL__ULSEP_com_oculus_auth_api_AuthMethods_ULSEP_ACCESS_METHOD(r2);
    }
}
