package com.oculus.content;

import X.AnonymousClass0J5;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class ContentModule extends AnonymousClass0J5 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForContentModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
    }
}
