package com.oculus.logging.utils;

import X.AbstractC03180ld;
import X.AnonymousClass0Hr;
import X.AnonymousClass0Qr;
import X.AnonymousClass0VC;
import X.AnonymousClass0VI;
import X.AnonymousClass0lg;
import X.AnonymousClass1TK;
import X.C01150Rm;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.inject.ProviderMethod;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import javax.inject.Provider;

@InjectorModule
public class UtilsModule extends AnonymousClass0VI {

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_logging_utils_EventManagerImpl_ULSEP_BINDING_ID = 44;
        public static final int _UL__ULSEP_com_oculus_logging_utils_EventManager_ULSEP_BINDING_ID = 92;
        public static final int _UL__ULSEP_com_oculus_logging_utils_StorageLoggingUtils_ULSEP_BINDING_ID = 60;
    }

    @ProviderMethod(asDefault = true)
    public static EventManager provideEventManager(EventManagerImpl eventManagerImpl) {
        return eventManagerImpl;
    }

    @AutoGeneratedAccessMethod
    public static final AbstractC03180ld _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_logging_utils_EventManager_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0Hr.A00(92, r1);
    }

    @AutoGeneratedAccessMethod
    public static final EventManager _UL__ULSEP_com_oculus_logging_utils_EventManager_ULSEP_ACCESS_METHOD(AnonymousClass0lg r2) {
        return (EventManager) AnonymousClass1TK.A00(92, r2, null);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_logging_utils_EventManager_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0VC.A00(92, r1);
    }

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForUtilsModule {
        public static void bind(AnonymousClass0Qr r0) {
        }
    }

    @AutoGeneratedFactoryMethod
    public static final EventManager _UL__ULSEP_com_oculus_logging_utils_EventManager_ULSEP_FACTORY_METHOD(AnonymousClass0lg r1, Object obj) {
        EventManagerImpl _UL__ULSEP_com_oculus_logging_utils_EventManagerImpl_ULSEP_ACCESS_METHOD = EventManagerImpl._UL__ULSEP_com_oculus_logging_utils_EventManagerImpl_ULSEP_ACCESS_METHOD(r1);
        C01150Rm.A00(_UL__ULSEP_com_oculus_logging_utils_EventManagerImpl_ULSEP_ACCESS_METHOD, r1);
        return _UL__ULSEP_com_oculus_logging_utils_EventManagerImpl_ULSEP_ACCESS_METHOD;
    }
}
