package com.oculus.common.quickpromotion.tooltip;

public enum QuickPromotionTooltipAnchorLabel {
    ANDROID_LIBRARY_HOME_BUTTON("ANDROID_LIBRARY_HOME_BUTTON"),
    ANDROID_LIBRARY_STORE_BUTTON("ANDROID_LIBRARY_STORE_BUTTON"),
    ANDROID_LIBRARY_SOCIAL_BUTTON("ANDROID_LIBRARY_SOCIAL_BUTTON"),
    ANDROID_LIBRARY_BROWSER_BUTTON("ANDROID_LIBRARY_BROWSER_BUTTON"),
    ANDROID_LIBRARY_TV_BUTTON("ANDROID_LIBRARY_TV_BUTTON"),
    ANDROID_LIBRARY_RECENT_FILTER("ANDROID_LIBRARY_RECENT_FILTER"),
    LIBRARY_QUICK_START_BUTTON("QUICK_START_BUTTON"),
    SHARING_CAST_BUTTON("SHARING_CAST_BUTTON"),
    SHARING_CAMERA_ROLL_BUTTON("SHARING_CAMERA_ROLL_BUTTON"),
    SOCIAL_CREATE_PARTY_BUTTON("SOCIAL_CREATE_PARTY_BUTTON");
    
    private String mAnchorLabel;

    private QuickPromotionTooltipAnchorLabel(String str) {
        this.mAnchorLabel = str;
    }

    public String getValue() {
        return this.mAnchorLabel;
    }
}
