package com.oculus.unifiedtelemetry;

/* This class is generated by JADX */
public final class R {

    public static final class anim {
        public static final int fragment_close_enter = 2130771968;
        public static final int fragment_close_exit = 2130771969;
        public static final int fragment_fade_enter = 2130771970;
        public static final int fragment_fade_exit = 2130771971;
        public static final int fragment_fast_out_extra_slow_in = 2130771972;
        public static final int fragment_open_enter = 2130771973;
        public static final int fragment_open_exit = 2130771974;
    }

    public static final class attr {
        public static final int alpha = 2130903040;
        public static final int font = 2130903041;
        public static final int fontProviderAuthority = 2130903042;
        public static final int fontProviderCerts = 2130903043;
        public static final int fontProviderFetchStrategy = 2130903044;
        public static final int fontProviderFetchTimeout = 2130903045;
        public static final int fontProviderPackage = 2130903046;
        public static final int fontProviderQuery = 2130903047;
        public static final int fontStyle = 2130903048;
        public static final int fontVariationSettings = 2130903049;
        public static final int fontWeight = 2130903050;
        public static final int ttcIndex = 2130903051;
    }

    public static final class color {
        public static final int notification_icon_bg_color = 2130968576;
    }

    public static final class dimen {
        public static final int notification_big_circle_margin = 2131034112;
        public static final int notification_content_margin_start = 2131034113;
        public static final int notification_large_icon_height = 2131034114;
        public static final int notification_right_icon_size = 2131034115;
        public static final int notification_right_side_padding_top = 2131034116;
    }

    public static final class drawable {
        public static final int notification_icon_background = 2131099648;
    }

    public static final class id {
        public static final int accessibility_custom_action_0 = 2131165184;
        public static final int accessibility_custom_action_1 = 2131165185;
        public static final int accessibility_custom_action_10 = 2131165186;
        public static final int accessibility_custom_action_11 = 2131165187;
        public static final int accessibility_custom_action_12 = 2131165188;
        public static final int accessibility_custom_action_13 = 2131165189;
        public static final int accessibility_custom_action_14 = 2131165190;
        public static final int accessibility_custom_action_15 = 2131165191;
        public static final int accessibility_custom_action_16 = 2131165192;
        public static final int accessibility_custom_action_17 = 2131165193;
        public static final int accessibility_custom_action_18 = 2131165194;
        public static final int accessibility_custom_action_19 = 2131165195;
        public static final int accessibility_custom_action_2 = 2131165196;
        public static final int accessibility_custom_action_20 = 2131165197;
        public static final int accessibility_custom_action_21 = 2131165198;
        public static final int accessibility_custom_action_22 = 2131165199;
        public static final int accessibility_custom_action_23 = 2131165200;
        public static final int accessibility_custom_action_24 = 2131165201;
        public static final int accessibility_custom_action_25 = 2131165202;
        public static final int accessibility_custom_action_26 = 2131165203;
        public static final int accessibility_custom_action_27 = 2131165204;
        public static final int accessibility_custom_action_28 = 2131165205;
        public static final int accessibility_custom_action_29 = 2131165206;
        public static final int accessibility_custom_action_3 = 2131165207;
        public static final int accessibility_custom_action_30 = 2131165208;
        public static final int accessibility_custom_action_31 = 2131165209;
        public static final int accessibility_custom_action_4 = 2131165210;
        public static final int accessibility_custom_action_5 = 2131165211;
        public static final int accessibility_custom_action_6 = 2131165212;
        public static final int accessibility_custom_action_7 = 2131165213;
        public static final int accessibility_custom_action_8 = 2131165214;
        public static final int accessibility_custom_action_9 = 2131165215;
        public static final int action_divider = 2131165216;
        public static final int actions = 2131165217;
        public static final int async = 2131165218;
        public static final int blocking = 2131165219;
        public static final int cancel_action = 2131165220;
        public static final int chronometer = 2131165221;
        public static final int end_padder = 2131165222;
        public static final int forever = 2131165223;
        public static final int fragment_container_view_tag = 2131165224;
        public static final int icon = 2131165225;
        public static final int icon_group = 2131165226;
        public static final int info = 2131165227;
        public static final int italic = 2131165228;
        public static final int jobscheduler_analytics2_high_pri = 2131165229;
        public static final int jobscheduler_analytics2_micro_batch = 2131165230;
        public static final int jobscheduler_analytics2_normal_pri = 2131165231;
        public static final int line1 = 2131165232;
        public static final int line3 = 2131165233;
        public static final int media_actions = 2131165234;
        public static final int normal = 2131165235;
        public static final int notification_background = 2131165236;
        public static final int notification_main_column = 2131165237;
        public static final int notification_main_column_container = 2131165238;
        public static final int right_icon = 2131165239;
        public static final int right_side = 2131165240;
        public static final int status_bar_latest_event_content = 2131165241;
        public static final int tag_accessibility_pane_title = 2131165242;
        public static final int tag_unhandled_key_event_manager = 2131165243;
        public static final int tag_unhandled_key_listeners = 2131165244;
        public static final int text = 2131165245;
        public static final int text2 = 2131165246;
        public static final int time = 2131165247;
        public static final int title = 2131165248;
        public static final int visible_removing_fragment_view_tag = 2131165249;
    }

    public static final class layout {
        public static final int notification_media_cancel_action = 2131296256;
        public static final int notification_template_big_media = 2131296257;
        public static final int notification_template_big_media_custom = 2131296258;
        public static final int notification_template_big_media_narrow = 2131296259;
        public static final int notification_template_big_media_narrow_custom = 2131296260;
        public static final int notification_template_custom_big = 2131296261;
        public static final int notification_template_icon_group = 2131296262;
        public static final int notification_template_lines_media = 2131296263;
        public static final int notification_template_media = 2131296264;
        public static final int notification_template_part_chronometer = 2131296265;
        public static final int notification_template_part_time = 2131296266;
    }

    public static final class string {
        public static final int app_name = 2131361792;
    }

    public static final class style {
        public static final int TextAppearance_Compat_Notification = 2131427328;
        public static final int TextAppearance_Compat_Notification_Info = 2131427329;
        public static final int TextAppearance_Compat_Notification_Info_Media = 2131427330;
        public static final int TextAppearance_Compat_Notification_Line2_Media = 2131427331;
        public static final int TextAppearance_Compat_Notification_Media = 2131427332;
        public static final int TextAppearance_Compat_Notification_Time = 2131427333;
        public static final int TextAppearance_Compat_Notification_Time_Media = 2131427334;
        public static final int TextAppearance_Compat_Notification_Title = 2131427335;
        public static final int TextAppearance_Compat_Notification_Title_Media = 2131427336;
    }
}
