package com.oculus.alpenglow.logging;

import X.AbstractC01750Lk;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class LoggingModule extends AbstractC01750Lk {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForLoggingModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_alpenglow_logging_ConfigLogger_ULSEP_BINDING_ID = 45;
        public static final int _UL__ULSEP_com_oculus_alpenglow_logging_DeviceStateLogger_ULSEP_BINDING_ID = 130;
        public static final int _UL__ULSEP_com_oculus_alpenglow_logging_InstallLogger_ULSEP_BINDING_ID = 133;
        public static final int _UL__ULSEP_com_oculus_alpenglow_logging_LoggerImpl_ULSEP_BINDING_ID = 121;
        public static final int _UL__ULSEP_com_oculus_alpenglow_logging_OSUpdateLogger_ULSEP_BINDING_ID = 81;
    }
}
