package com.oculus.alpenglow.logging;

public class LoggerConstants {
    public static final String APP_ID_KEY = "app_id";
    public static final String CANCEL_DOWNLOAD_KEY = "cancel_download";
    public static final String CONFIGURATION_FETCH_REASON_BROADCAST = "broadcast";
    public static final String CONFIGURATION_FETCH_REASON_INDUCTION = "induction";
    public static final String CONFIGURATION_FETCH_REASON_JOB_SERVICE = "job_service";
    public static final String CONFIGURATION_FETCH_REASON_PUSH = "push";
    public static final String CONFIGURATION_FETCH_RETRY_COUNT = "retry_count";
    public static final String CONFIGURATION_FETCH_SUCCESS = "success";
    public static final String CONFIGURATION_FETCH_TYPE = "type";
    public static final String CONFIGURATION_FETCH_TYPE_NORMAL = "normal";
    public static final String CONFIGURATION_FETCH_TYPE_SILENT = "silent";
    public static final String DEVICE_ID = "device_id";
    public static final String DEVICE_SERIAL = "device_serial";
    public static final String ENABLED_KEY = "enabled";
    public static final String ERROR_KEY = "error";
    public static final String ES_INSTALL_FOUND_EVENT = "enterprise_server_install_found";
    public static final String ES_INSTALL_NOOP_EVENT = "enterprise_server_install_no_op";
    public static final String ES_INSTALL_SERVICE_EVENT = "enterprise_server_install_service";
    public static final String ES_UNINSTALL_FOUND_EVENT = "enterprise_server_uninstall_found";
    public static final String ES_UNINSTALL_NOOP_EVENT = "enterprise_server_uninstall_no_op";
    public static final String ES_UNINSTALL_SERVICE_EVENT = "enterprise_server_uninstall_service";
    public static final String EVENT_CONFIGURATION_FETCH_COMPLETED = "arvr_enterprise_server_config_fetch_completed";
    public static final String EVENT_CONFIGURATION_FETCH_RETRY = "arvr_enterprise_server_config_fetch_retry";
    public static final String EVENT_CONFIGURATION_FETCH_STARTED = "arvr_enterprise_server_config_fetch_started";
    public static final String EVENT_DEVICE_STATE_UPLOAD_FAILED = "arvr_enterprise_server_device_state_upload_failed";
    public static final String EVENT_DEVICE_STATE_UPLOAD_STARTED = "arvr_enterprise_server_device_state_upload_started";
    public static final String EVENT_DEVICE_STATE_UPLOAD_SUCCEEDED = "arvr_enterprise_server_device_state_upload_succeeded";
    public static final String EVENT_KEY = "event";
    public static final String EVENT_OS_UPDATE_CONFIGURED = "arvr_enterprise_server_os_update_configured";
    public static final String FIXED_BY_CONSISTENCY = "fixed_by_consistency";
    public static final String OC_ENTERPRISE_SERVER_YADI = "arvr_enterprise_server_yadi";
    public static final String PACKAGE_KEY = "package";
    public static final String REASON = "reason";
    public static final String SCHEDULED_KEY = "scheduled";
    public static final String SIZE_KEY = "size";
    public static final String STATUS_KEY = "status";
    public static final String UNINSTALLED_KEY = "uninstalled";
    public static final String USING_OCMS = "using_ocms";
    public static final String UUID = "uuid";
}
