package com.oculus.horizon.cast;

import X.AnonymousClass0J5;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class CastModule extends AnonymousClass0J5 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForCastModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_horizon_cast_CastAnalytics_ULSEP_BINDING_ID = 248;
        public static final int _UL__ULSEP_com_oculus_horizon_cast_CastHTTPServerManagerProvider_ULSEP_BINDING_ID = 146;
        public static final int _UL__ULSEP_com_oculus_horizon_cast_NetworkUtils_ULSEP_BINDING_ID = 2072;
    }
}
