package com.facebook.quicklog.identifiers;

public class AndroidGraphServices {
    public static final int BUILD_QUERY = 17446652;
    public static final int EARLY_INIT = 17432579;
    public static final int FEED_TREE_DESERIALIZE = 17432587;
    public static final int FEED_TREE_SERIALIZE = 17432588;
    public static final int GRAPHSERVICES_THREAD_METADATA = 17437664;
    public static final int INITIALIZE_GRAPHQLCONSISTENCYJNI = 17432582;
    public static final int INITIALIZE_GRAPHQLSERVICEFACTORY = 17432584;
    public static final int INITIALIZE_GRAPHQLSERVICEJNI = 17432581;
    public static final int INITIALIZE_GRAPHSERVICEASSET = 17432583;
    public static final int INITIALIZE_QUERY_METADATA_ASSET = 17432595;
    public static final short MODULE_ID = 266;
    public static final int PARCEL_GQL_SERIALIZATION = 17432597;

    public static String getMarkerName(int i) {
        return i != 3 ? i != 19 ? i != 21 ? i != 5088 ? i != 14076 ? i != 5 ? i != 6 ? i != 7 ? i != 8 ? i != 11 ? i != 12 ? "UNDEFINED_QPL_EVENT" : "ANDROID_GRAPH_SERVICES_FEED_TREE_SERIALIZE" : "ANDROID_GRAPH_SERVICES_FEED_TREE_DESERIALIZE" : "ANDROID_GRAPH_SERVICES_INITIALIZE_GRAPHQLSERVICEFACTORY" : "ANDROID_GRAPH_SERVICES_INITIALIZE_GRAPHSERVICEASSET" : "ANDROID_GRAPH_SERVICES_INITIALIZE_GRAPHQLCONSISTENCYJNI" : "ANDROID_GRAPH_SERVICES_INITIALIZE_GRAPHQLSERVICEJNI" : "ANDROID_GRAPH_SERVICES_BUILD_QUERY" : "ANDROID_GRAPH_SERVICES_GRAPHSERVICES_THREAD_METADATA" : "ANDROID_GRAPH_SERVICES_PARCEL_GQL_SERIALIZATION" : "ANDROID_GRAPH_SERVICES_INITIALIZE_QUERY_METADATA_ASSET" : "ANDROID_GRAPH_SERVICES_EARLY_INIT";
    }
}
