package com.facebook.quicklog.identifiers;

public class BusinessInboxInMessenger {
    public static final int ACCOUNT_SWITCH_COMPLETION_FAILURE = 531052560;
    public static final int ACCOUNT_SWITCH_LOGIN_COMPLETE = 531041213;
    public static final int ACCOUNT_SWITCH_LOGIN_START = 531045185;
    public static final int ACCOUNT_SWITCH_LOGOUT_COMPLETE = 531048650;
    public static final int ACCOUNT_SWITCH_MISSING_INFO_FAILURE = 531048899;
    public static final int ACCOUNT_SWITCH_START = 531049674;
    public static final int INBOX_LOAD_COMPLETE = 531052693;
    public static final short MODULE_ID = 8103;
    public static final int NOTIFICATION_CLICK = 531050074;
    public static final int THREAD_LOAD_COMPLETE = 531048455;

    public static String getMarkerName(int i) {
        return i != 3005 ? i != 6977 ? i != 10247 ? i != 10442 ? i != 10691 ? i != 11466 ? i != 11866 ? i != 14352 ? i != 14485 ? "UNDEFINED_QPL_EVENT" : "BUSINESS_INBOX_IN_MESSENGER_INBOX_LOAD_COMPLETE" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_COMPLETION_FAILURE" : "BUSINESS_INBOX_IN_MESSENGER_NOTIFICATION_CLICK" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_START" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_MISSING_INFO_FAILURE" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_LOGOUT_COMPLETE" : "BUSINESS_INBOX_IN_MESSENGER_THREAD_LOAD_COMPLETE" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_LOGIN_START" : "BUSINESS_INBOX_IN_MESSENGER_ACCOUNT_SWITCH_LOGIN_COMPLETE";
    }
}
