package com.facebook.quicklog.identifiers;

import com.facebook.common.fragmentconstants.FragmentConstants;
import com.facebook.ultralight.UL;

public class DebugUtils {
    public static String getMarkerName(int i) {
        short s = (short) (i >> 16);
        short s2 = (short) (i & 65535);
        if (s == 14) {
            return Composer.getMarkerName(s2);
        }
        if (s == 15) {
            return Drawablehierarchy.getMarkerName(s2);
        }
        if (s == 29) {
            return Video.getMarkerName(s2);
        }
        if (s == 30) {
            return Reaction.getMarkerName(s2);
        }
        if (s == 34) {
            return Creativeediting.getMarkerName(s2);
        }
        if (s == 35) {
            return Login.getMarkerName(s2);
        }
        if (s == 61) {
            return Init.getMarkerName(s2);
        }
        if (s == 62) {
            return FriendList.getMarkerName(s2);
        }
        if (s == 74) {
            return NetworkPerf.getMarkerName(s2);
        }
        if (s == 75) {
            return Goodwill.getMarkerName(s2);
        }
        if (s == 77) {
            return NegativeFeedback.getMarkerName(s2);
        }
        if (s == 78) {
            return Auth.getMarkerName(s2);
        }
        switch (s) {
            case 3:
                return Perf.getMarkerName(s2);
            case 24:
                return Saved.getMarkerName(s2);
            case 26:
                return Timeline.getMarkerName(s2);
            case 32:
                return Groups.getMarkerName(s2);
            case 40:
                return Bookmark.getMarkerName(s2);
            case 53:
                return Notifications.getMarkerName(s2);
            case 57:
                return Ufi.getMarkerName(s2);
            case 64:
                return Registration.getMarkerName(s2);
            case 66:
                return MinutiaeObjectPicker.getMarkerName(s2);
            case 68:
                return Resources.getMarkerName(s2);
            case 84:
                return Messenger.getMarkerName(s2);
            case 85:
                return PresenceNow.getMarkerName(s2);
            case 86:
                return NowDivebar.getMarkerName(s2);
            case 87:
                return UriMap.getMarkerName(s2);
            case 88:
                return BackgroundWork.getMarkerName(s2);
            case 89:
                return Mqtt.getMarkerName(s2);
            case 90:
                return AdInterfaces.getMarkerName(s2);
            case 92:
                return InstantArticles.getMarkerName(s2);
            case 94:
                return Stacks.getMarkerName(s2);
            case 95:
                return Divebar.getMarkerName(s2);
            case 99:
                return AppTabPerf.getMarkerName(s2);
            case 101:
                return GraphStore.getMarkerName(s2);
            case 105:
                return Applinks.getMarkerName(s2);
            case 106:
                return DisturbingMedia.getMarkerName(s2);
            case 107:
                return Paginator.getMarkerName(s2);
            case 108:
                return Commerce.getMarkerName(s2);
            case 110:
                return PowerMetrics.getMarkerName(s2);
            case 112:
                return ColdStart.getMarkerName(s2);
            case 113:
                return Engagement.getMarkerName(s2);
            case 115:
                return PokesDash.getMarkerName(s2);
            case 118:
                return AdsManager.getMarkerName(s2);
            case 119:
                return ReactNativeBridge.getMarkerName(s2);
            case 120:
                return GroupsTab.getMarkerName(s2);
            case 122:
                return Relay.getMarkerName(s2);
            case 123:
                return Platform.getMarkerName(s2);
            case 124:
                return Loom.getMarkerName(s2);
            case 129:
                return QuickerExperiment.getMarkerName(s2);
            case 130:
                return Reactions.getMarkerName(s2);
            case 133:
                return GraphqlAndroidCursor.getMarkerName(s2);
            case 134:
                return Crash.getMarkerName(s2);
            case 136:
                return Dextricks.getMarkerName(s2);
            case 138:
                return Components.getMarkerName(s2);
            case 139:
                return Offers.getMarkerName(s2);
            case 141:
                return ProcAndPerf.getMarkerName(s2);
            case 143:
                return Cassie.getMarkerName(s2);
            case 148:
                return Logout.getMarkerName(s2);
            case 149:
                return GraphqlAnroidConsistency.getMarkerName(s2);
            case 151:
                return PagesLwiPerf.getMarkerName(s2);
            case 152:
                return PmaPerf.getMarkerName(s2);
            case 153:
                return Security.getMarkerName(s2);
            case 154:
                return PagesPlatform.getMarkerName(s2);
            case 156:
                return VideoHome.getMarkerName(s2);
            case 161:
                return Inspirations.getMarkerName(s2);
            case 163:
                return AndroidCamera.getMarkerName(s2);
            case 168:
                return SessionInitialization.getMarkerName(s2);
            case 169:
                return Marketplace.getMarkerName(s2);
            case 172:
                return CameraPerf.getMarkerName(s2);
            case 173:
                return ApplicationModules.getMarkerName(s2);
            case 175:
                return PerceptionCamera.getMarkerName(s2);
            case 178:
                return ComponentScript.getMarkerName(s2);
            case 179:
                return ProfileDiscoveryCuration.getMarkerName(s2);
            case 181:
                return Cloudseeder.getMarkerName(s2);
            case 182:
                return PrCamera.getMarkerName(s2);
            case 185:
                return CityGuides.getMarkerName(s2);
            case 187:
                return FeedUnitPyml.getMarkerName(s2);
            case 188:
                return Snacks.getMarkerName(s2);
            case 190:
                return Workplace.getMarkerName(s2);
            case 191:
                return Aboutpage.getMarkerName(s2);
            case 192:
                return Newsfeed.getMarkerName(s2);
            case 195:
                return JavaToJs.getMarkerName(s2);
            case 196:
                return NativeTemplates.getMarkerName(s2);
            case 197:
                return MinutiaeFeelingSelector.getMarkerName(s2);
            case 198:
                return MinutiaeObjectSelector.getMarkerName(s2);
            case 199:
                return LocalSurface.getMarkerName(s2);
            case 200:
                return CharitableGiving.getMarkerName(s2);
            case 202:
                return Stories.getMarkerName(s2);
            case 203:
                return Direct.getMarkerName(s2);
            case 204:
                return Sharesheet.getMarkerName(s2);
            case 206:
                return TestAndroid.getMarkerName(s2);
            case 207:
                return TestAndroidModule.getMarkerName(s2);
            case 208:
                return Mobileconfig.getMarkerName(s2);
            case 209:
                return Lithium.getMarkerName(s2);
            case 211:
                return ReactNativeTti.getMarkerName(s2);
            case 212:
                return Livewith.getMarkerName(s2);
            case 214:
                return TopicFollowing.getMarkerName(s2);
            case 217:
                return MessengerDiscover.getMarkerName(s2);
            case 219:
                return Accessibility.getMarkerName(s2);
            case 220:
                return AmlcameratestPerf.getMarkerName(s2);
            case 222:
                return Live.getMarkerName(s2);
            case 223:
                return BusinessIntegrity.getMarkerName(s2);
            case 224:
                return PrivacyInvalidation.getMarkerName(s2);
            case 227:
                return Facecast.getMarkerName(s2);
            case 228:
                return AndroidLocalMedia.getMarkerName(s2);
            case 229:
                return Keyframes.getMarkerName(s2);
            case 230:
                return AndroidTransliterationKeyboard.getMarkerName(s2);
            case 231:
                return CaffeTwo.getMarkerName(s2);
            case 233:
                return MessengerLite.getMarkerName(s2);
            case 234:
                return IgClientPerf.getMarkerName(s2);
            case 235:
                return Oculus.getMarkerName(s2);
            case 236:
                return MobileJsDevReload.getMarkerName(s2);
            case 238:
                return ProfileAboutRn.getMarkerName(s2);
            case 242:
                return CoreHealth.getMarkerName(s2);
            case 244:
                return ScrollPerf.getMarkerName(s2);
            case 245:
                return FeedNotLoading.getMarkerName(s2);
            case 246:
                return BoostPostPageComposer.getMarkerName(s2);
            case 248:
                return RtcPerf.getMarkerName(s2);
            case 249:
                return Camera.getMarkerName(s2);
            case 250:
                return BonfireForAndroid.getMarkerName(s2);
            case 251:
                return IgExplore.getMarkerName(s2);
            case 252:
                return AnimationPerformanceLogger.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TREEHOUSE_DEFAULT_TAB_SETTINGS_FRAGMENT:
                return IgComments.getMarkerName(s2);
            case 257:
                return Qrcode.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CREATE_NEW_PAGE_FRAGMENT:
                return IgGrowth.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_PRESENCE_TAB_FRAGMENT:
                return Hermes.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.OFFER_BARCODE_FULLSCREEN_FRAGMENT:
                return MessengerLigerNetworkPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SEARCH_RESULTS_EXPLORE_HOST_FRAGMENT:
                return LocalSurfaceAndroidPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FUNDRAISER_SINGLE_CLICK_INVITE_FRAGMENT:
                return IgStoriesEngagement.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.REACT_FRAGMENT_WITH_MARKETPLACE_SEARCH:
                return JscMobileLabMetrics.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_SCHOOL_EMAIL_VERIFICATION_FRAGMENT:
                return AndroidGraphServices.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_ACTIVITY_FRAGMENT:
                return StallTracker.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CITY_COMMUNITY_FRAGMENT:
                return IgCamera.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_STORY_DIVEIN_FRAGMENT:
                return IgClientStability.getMarkerName(s2);
            case 271:
                return MobileHome.getMarkerName(s2);
            case 272:
                return Watch.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SHARESHEET_FRAGMENT:
                return Talk.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.OLD_SHARESHEET_FRAGMENT:
                return Tigon.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.STORY_PRIVACY_SETTING_FRAGMENT:
                return EntrypointsLoggingMessenger.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.STORIES_ALLOWLIST_BLOCKLIST_SELECTION_FRAGMENT:
                return BundleSplitting.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FACECAST_SHARESHEET_FRAGMENT:
                return GroupsSimpleFeed.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TARGET_AUDIENCE_SHARESHEET_FRAGMENT:
                return IgFeedSharingProfile.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CREATE_BOOKING_APPOINTMENT_FRAGMENT:
                return VideoLoadingKit.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_SERVICE_SELECTOR_FRAGMENT:
                return IgVideo.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.APPOINTMENT_CALENDAR_FRAGMENT:
                return IgStories.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_OFFERS_FRAGMENT:
                return IgFeed.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_JOBS_FRAGMENT:
                return Maps.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FUNDRAISER_CURRENCY_SELECTOR_FRAGMENT:
                return PagesInsights.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GETQUOTE_FORM_BUILDER:
                return Movies.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_DISCUSSION_TOPICS_ASSIGN_FRAGMENT:
                return AndroidWebview.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMMUNITY_GROUPS_FRAGMENT:
                return JsiPerftest.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMMUNITY_SEARCH_FRAGMENT:
                return Fnf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMMUNITY_JOIN_GROUPS_NUX_FRAGMENT:
                return FbliteNetworkMessages.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_EDIT_TABS_REORDER_FRAGMENT:
                return AlohaTti.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_TEMPLATES_FRAGMENT:
                return ImagepipelineTwo.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_SUBSCRIPTION_SETTINGS_FRAGMENT:
                return InAppBrowser.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_MEMBER_BIO_FRAGMENT:
                return FbliteColdStartup.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NATIVE_TEMPLATES_FRAGMENT:
                return FbliteConnectionState.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_CONFIGURE_ACTION_FRAGMENT:
                return AlohaColdStarts.getMarkerName(s2);
            case 307:
                return IgDirect.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_CUSTOM_INVITE_FRAGMENT:
                return NativeTemplateJs.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.REACTION_PHOTO_GRID:
                return Ditto.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_EDIT_PAGE_ADD_TAB_FRAGMENT:
                return GroupsAdmin.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENTS_DASHBOARD_BIRTHDAY_FRAGMENT:
                return IgHashtagPage.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_VOICE_SWITCHER_FRAGMENT:
                return SurveyEngPlatformRemix.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TOPIC_FRAGMENT:
                return ProfileInitialLoad.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOYALTY_FRAGMENT:
                return CreatorAppAndroidPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOYALTY_VIEW_FRAGMENT:
                return FbliteClientPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.OFFERS_FEED_FRAGMENT:
                return Reliability.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.OFFERS_FEED_VIEW_FRAGMENT:
                return MessengerBroadcastFlow.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_SERVICE_ADD_EDIT_FRAGMENT:
                return SocialPlayer.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.REACT_FRAGMENT_WITH_JOBS_KEYWORD_QUERY_SEARCH:
                return MessengerBroadcastFlowDeprecated.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SAVED_LISTS_CREATION_FRAGMENT:
                return ThreesixtyPhotos.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FIND_WIFI_FRAGMENT:
                return PrivateGallery.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FIND_WIFI_SETTINGS_FRAGMENT:
                return ProductQuality.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TOPIC_INFO_FRAGMENT:
                return Mobilelab.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_INSIGHTS_FRAGMENT:
                return GamingDestination.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_INSIGHTS_GROUP_ACTIVITY_FRAGMENT:
                return LocalSearchAndroid.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_INSIGHTS_GROUP_MEMBER_FRAGMENT:
                return StoriesArchive.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_INSIGHTS_GROUP_PEOPLE_FRAGMENT:
                return ArDelivery.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_NATIVE_REPORTED_POST_FRAGMENT:
                return PrivacyActivityLogTti.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NOTIFICATION_SETTINGS_ADD_EMAIL_FRAGMENT:
                return MessengerLogin.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NOTIFICATION_SETTINGS_PUSH_AND_SOUNDS:
                return Mlkit.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_REQUESTER_CUSTOM_QUESTION_FRAGMENT:
                return InstantRender.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.ALBUM_FRAGMENT:
                return VideoTranscoder.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_MEMBER_REQUESTS_FRAGMENT_V2:
                return ComposerSprouts.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NOTIFICATION_SETTINGS_PHONE_NUMBER_FRAGMENT:
                return MediaUploadPipeline.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NOTIFICATION_SETTINGS_ADD_PHONE_FRAGMENT:
                return CheckoutPurchaseExperiences.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.APPLY_TEMPLATE_CONFIRM_FRAGMENT:
                return IgProfile.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_MANAGER_SETTING_FOLLOW_UP_SCHEDULE_FRAGMENT:
                return IgImagePipeline.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENTS_CREATE_EVENT_DETAILS_FRAGMENT:
                return UserFunding.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMPARISON_CARDS_FRAGMENT:
                return IgScrollPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TOPIC_FOLLOWERS_FRAGMENT:
                return StoriesFeedback.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NOTIFICATION_SETTINGS_CONFIRM_CONTACT_POINT_FRAGMENT:
                return DiskIo.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CITY_GUIDES_FRAGMENT:
                return AndroidExperimentalTti.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENTS_CREATE_EVENT_DETAILS_TOPICS_SELECTION_FRAGMENT:
                return AndroidTimeToNetworkOut.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_SEE_ALL_RELATED_GROUPS_FRAGMENT:
                return TouchResponsiveness.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.WORK_UNIFIED_INVITER_FRAGMENT:
                return WaPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_COMMERCE_SUGGESTED_SALE_GROUPS_FRAGMENT:
                return IgAppPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.MOVIES_HOME_FRAGMENT:
                return IgAppStart.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.QR_CODE_SCAN_FRAGMENT:
                return StoriesFeedUnit.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SHOW_GROUPS_CODE_FRAGMENT:
                return Kototoro.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_SCHEDULED_POSTS_FRAGMENT:
                return AdminSurfaceNt.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_GROUPS_CREATE_FRAGMENT:
                return IgNetworkPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.INSTANT_BOOKING_SETTINGS_FRAGMENT:
                return Surfaces.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCAL_SURFACE_LOCATION_PICKER:
                return Navigation.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.B2C_COMMERCE_TAB_FRAGMENT_DELETED:
                return GemstoneMatchingHome.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.INSTAGRAM_CONTACT_IMPORTER_FRAGMENT:
                return PageCreationWelcomeNt.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FUNDRAISER_CHARITY_SEARCH_INFO:
                return PageCreationNameNt.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_EDIT_COVER_FRAGMENT:
                return GamesAppAndroid.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GOOD_ADDS_UP_FRAGMENT:
                return GamesApp.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_MEMBER_QUESTION_SETTING_FRAGMENT:
                return MessengerOmnipicker.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FUNDRAISER_CREATION_OUTRO_FRAGMENT:
                return FanFunding.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.INTERN_TEST_USERS_FRAGMENT:
                return AndroidImagesInfra.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FOOD_DRINK_SEE_ALL_FRAGMENT:
                return WiktorkTest.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_DEEP_EDIT_FRAGMENT:
                return YouthCamera.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_COMMERCE_COMPOSER_AUDIENCE_VIEW_FRAGMENT:
                return FeedsAdsRerank.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_NOTE_DRAFTS_FRAGMENT:
                return MobileBoost.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.VISUAL_SEARCH_FRAGMENT:
                return GemstoneProfile.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCATION_TIMELINE_FRAGMENT:
                return Weather.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_INSIGHTS_TOP_CONTRIBUTOR_SEE_ALL_FRAGMENT:
                return Avatars.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SEARCH_RESULTS_PHOTO_VIEWER_FRAGMENT:
                return ForegroundService.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_MANAGE_ALL_LINKED_PAGES_FRAGMENT:
                return QplHealth.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCAL_SURFACE_TAB_PICKER:
                return MobileTopUps.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_SAVED_TAB_FRAGMENT:
                return VideoProfiler.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMPONENT_SCRIPT_PLAYGROUND:
                return Fury.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CONFIGURE_BOOK_NOW_FRAGMENT_HOST:
                return DownloadOnDemand.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CONSUMER_GET_QUOTE_FRAGMENT:
                return DigitalContentPayments.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FOOD_DRINK_TAG_FRAGMENT:
                return LassoAndroidColdStart.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMMERCE_LIVE_VIDEO_FEED_FRAGMENT:
                return InstantExperienceAds.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CASUAL_GROUP_TAB_FRAGMENT:
                return BotDetection.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CONSUMER_GET_QUOTE_CONFIRMATION_FRAGMENT:
                return AndroidPigeon.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.WORK_CONTACTS_FRAGMENT:
                return IgRtc.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TOPIC_DISCOVERY_TABBED_FRAGMENT:
                return IgDirectappPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CASUAL_GROUP_EDIT_FAVORITES_FRAGMENT:
                return Agora.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SHARING_SPACES_SHARESHEET_FRAGMENT:
                return Athens.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SPACE_CREATE_AND_EDIT_FRAGMENT:
                return Npx.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.VISUAL_POLL_TABBED_VOTES_FRAGMENT:
                return IgTestModule.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.ONAVO_PROTECT_OLD_BOOKMARK_INTERSTITIAL_FRAGMENT:
                return Threadview.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_MANAGER_NOTIFICATION_SETTINGS_FRAGMENT:
                return PrCameraLite.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.STORIES_MUTED_OWNERS_LIST_FRAGMENT:
                return MessengerIntegrity.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_RULES_EDIT_GROUP_RULES_FRAGMENT:
                return Internationalization.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.MULTI_EVENTS_INSTANCE_FRAGMENT:
                return Bugreport.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FB_REACT_FRAGMENT_WITH_SEARCH:
                return GemstoneInterestedTab.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_ADMIN_APPOINTMENT_REQUEST_DETAIL_FRAGMENT:
                return GemstoneConversationStarter.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.DITTO_TIMELINE_FRAGMENT:
                return IgBoomerangPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_MEMBERSHIP_ONE_SECTION_FULL_LIST_FRAGMENT:
                return IgDownloadableModule.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TARGETED_TAB_GROUP_LIST_FRAGMENT:
                return MessengerSearch.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_PHOTO_PICKER_FRAGMENT:
                return Extensions.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FACECAST_INTEGRATED_SHARESHEET:
                return LocationProducts.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_ADMIN_JOURNEY_CONTAINER_FRAGMENT:
                return FeedDeliveryHealth.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.MOVIES_THEATER_SHOWTIME_PICKER_FRAGMENT:
                return IgNavigationLatency.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CONFIGURE_REQUEST_TIME_FRAGMENT_HOST:
                return NativeTemplatesCpp.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_TAB_FRAGMENT:
                return RecommendationApp.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CONTEXTUAL_PROFILE_FRAGMENT:
                return OculusTwilight.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CASUAL_TAB_INACTIVE_GROUPS_FRAGMENT:
                return GemstoneMessaging.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_FRAGMENT:
                return IgSearch.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.BOOKMARKS_EDIT_SHORTCUTS_FRAGMENT:
                return AppChoreographer.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_RULES_VIEW_MODE_FRAGMENT:
                return ReactOtaUpdate.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_RULES_EDIT_RULE_FRAGMENT:
                return Comments.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_POST_TAG_CONSUMPTION_FRAGMENT:
                return FbliteStories.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.WATCH_FOLLOW_INTERSTITIAL_FRAGMENT:
                return HighSchoolNetworks.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_RULES_EDIT_MODE_FRAGMENT:
                return VideoAdsWatchAndBrowse.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FOX_AUDIENCE_SELECTOR:
                return TransientAnalysis.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TOUR_PERMALINK_FRAGMENT:
                return ImagepipelineBoost.getMarkerName(s2);
            case 510:
                return ProfileReliability.getMarkerName(s2);
            case 512:
                return LiveLinearVideoChannels.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_MODERN_CREATION_MEMBER_PICKER_FRAGMENT:
                return SmartCapture.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.APPOINTMENT_CALENDAR_BLOCK_TIME_SLOT_FRAGMENT:
                return Jobs.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FOX_PROFILE:
                return Crs.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_REQUEST_GROUP_APPEAL_FRAGMENT:
                return Skylight.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FOX_EDIT_PROFILE:
                return FblitePagingProvider.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SAVED_LISTS_ADD_TO_COLLECTION_FRAGMENT:
                return DarkroomCameraRollHighlights.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ACTIVE_MEMBER_SUMMARY:
                return IgNavigation.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NEW_APPOINTMENT_DETAIL_FRAGMENT:
                return CameraRoll.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_ADMIN_SURFACE_FRAGMENT_WRAPPER:
                return Superpack.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_NEW_REPORTED_POSTS_FRAGMENT:
                return DownloadableModules.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TARGETED_TAB_PENDING_REQUESTS_FRAGMENT:
                return StorySurface.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CREATOR_APP_SETTINGS_FRAGMENT:
                return CameraRollTtrc.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TIMELINE_OBSESSION_EDIT_FRAGMENT:
                return NewsfeedViewpoint.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_SUPPORT_THREAD_FRAGMENT:
                return IgQuickPromotions.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TOPICS_EDIT_TOPICS_FRAGMENT:
                return PageUnifiedInboxAndroid.getMarkerName(s2);
            case 537:
                return Spectrum.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.ONAVO_PROTECT_BOOKMARK_INTERSTITIAL_FRAGMENT:
                return Yoga.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_SUPPORT_THREADS_LIST_FRAGMENT:
                return LassoAndroidVideoPlayback.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_VOICE_SWITCHER_LIST_FRAGMENT:
                return Preload.getMarkerName(s2);
            case 542:
                return NewsCompass.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_DELETE_POST_WITH_FEEDBACK_FRAGMENT:
                return FbAppMessaging.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EDIT_PIN_ORDER_GROUPS_FRAGMENT:
                return FbliteLiteFeed.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SAVE_DASHBOARD_RN_FRAGMENT:
                return AlohaAppsInit.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_SAFETY_HUB_FRAGMENT:
                return UnifiedInbox.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FOX_FEED_FRAGMENT:
                return QplInternal.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_POST_TAG_FEED_FRAGMENT:
                return NeoParentPortal.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NOTIF_CONNECTION_CONTROLLER_FRAGMENT:
                return BusinessCrm.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_CROSS_POST_RETRY_FRAGMENT:
                return Bloks.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.VIDEOHOME_WATCH_TOPIC_FEED_FRAGMENT:
                return FbAnalyticsApp.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCAL_SERVICE_APPOINTMENT_CALENDAR:
                return CrfPlatform.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.XNETWORK_POSTING_SHARESHEET_FRAGMENT:
                return ProfileEdit.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_BROADCAST_COMPOSER_FRAGMENT:
                return InstagramShopping.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGES_TRANSPARENCY_FRAGMENT:
                return FbliteReliability.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GET_QUOTE_QUESTIONNAIRE_SETUP_FRAGMENT:
                return FblitePerfDebugging.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_MEMBER_PROFILE_FRAGMENT:
                return ThreedPhotos.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.ADS_TRANSPARENCY_FRAGMENT:
                return FbliteAsyncActions.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_EDUCATION_CENTER_FRAGMENT:
                return Contextualconfig.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TAB_HOME_FRAGMENT:
                return CrisisTtrc.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.VIDEO_CREATOR_PAGES_GROUPS_CREATE_FRAGMENT:
                return FbliteClientInstrumentation.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_COVERPHOTO_REPOSITION_FRAGMENT:
                return AnimationPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOL_FEED_FRAGMENT:
                return MessengerCowatch.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_EDUCATION_CENTER_TOPIC_FRAGMENT:
                return VideoChatLinks.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SHARESHEET_DESTINATION_PICKER_FRAGMENT:
                return PathProvider.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FUNDRAISER_FOR_STORY_CREATION_FRAGMENT:
                return ArCloudServices.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FOX_PROMPTS_FEED_FRAGMENT:
                return IgAssetUsage.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TOPIC_TAG_MANAGEMENT_CENTER_FRAGMENT:
                return FbliteLiteNotifications.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PROFILE_GROUPS_FRAGMENT:
                return IgPaymentModules.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_SERVICES_APPOINTMENT_SETTING_FRAGMENT:
                return IgInsights.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.DAILY_LAUGH_CALL_FRAGMENT:
                return SubsampledExtensions.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NATIVE_FULLSCREEN_FEED_FRAGMENT:
                return FbliteMessagingPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_CREATION_NT_FRAGMENT:
                return FbliteReponsiveness.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.DAILY_LAUGH_PLAYER_ROOT_FRAGMENT:
                return GltfScene.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TAB_DISCOVER_SPOTLIGHT_FRAGMENT:
                return Permanet.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.STORIES_ALLOWLIST_BLOCKLIST_SINGLE_LIST_FRAGMENT:
                return StoriesViewerPerformanceAndroid.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_CREATION_NAME_FRAGMENT:
                return FbliteMediaPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_ACTIVITY_ADD_NOTE_FRAGMENT:
                return ContextualProfileInitialLoad.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENT_CUSTOM_SCHEDULE_TIME_FRAGMENT:
                return Loyalty.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ABOUT_FRAGMENT:
                return CrsHealth.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.WATCH_EXPERIMENT_VIEWER_FRAGMENT:
                return RtcXPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.REQUESTED_APPOINTMENT_TAB_FRAGMENT:
                return XrPersistenceServices.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_CLIENT_LIST_FRAGMENT:
                return RtcPlatformClientPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_CLIENT_LIST_SEARCH_FRAGMENT:
                return FrescoInstrumentation.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.ATHENS_SURFACE_FRAGMENT:
                return AndroidTaskScheduling.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_UNIVERSAL_DISTRIBUTION_FRAGMENT:
                return AssistantInteractionChanged.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_CLIENT_REENGAGEMENT_CREATION_FRAGMENT:
                return LiveFeed.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_SELL_PENDING_REPLIES_FRAGMENT:
                return GemstoneOnboarding.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_CLIENT_IMPORT_VIEW_NOTES_FRAGMENT:
                return GraphqlSubscriptions.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PMA_REDIRECT_FRAGMENT:
                return IgMediaIngestion.getMarkerName(s2);
            case 644:
                return SparkBrowser.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_MANUAL_APPOINTMENT_CREATION_FRAGMENT:
                return OffFacebookActivity.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_LINKED_FOLDERS_FRAGMENT:
                return IosImageLoadPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_LEARNING_UNIT_FRAGMENT:
                return AndroidImageLoadPerf.getMarkerName(s2);
            case 653:
                return Usability.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_ADMIN_CREATE_PERSONAL_EVENT_FRAGMENT:
                return Stash.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.MAPS_FRAGMENT_VECTOR:
                return BizappStartupPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.INSTANT_EXPERIENCE_FRAGMENT:
                return FbliteScrollPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SHARESHEET_POLL_END_TIME_PICKER_FRAGMENT:
                return MobileStorage.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_KEYWORD_ALERTS_FRAGMENT:
                return AlohaSuperframe.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_INTEREST_WIZARD_SGBI_FRAGMENT:
                return AugmentedVrPlayerPerformance.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_MEMBERSHIP_TAB_FRAGMENT:
                return FbliteUnitySession.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENT_TICKET_ORDER_LIST_NT_FRAGMENT:
                return JobOrchestration.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMPOSER_PHOTO3D_PREVIEW_FRAGMENT:
                return GemstoneCommunityMatches.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_CREATE_CHAT_FRAGMENT:
                return FbliteCreation.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_RULE_ENFORCEMENT_ADMIN_VIEW_LEARN_MORE_FRAGMENT:
                return FbliteScreenDiff.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SOCAL_SEARCH_TYPEAHEAD_FRAGMENT:
                return Bigfoot.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_PEOPLE_PICKER_FRAGMENT:
                return LsPlugin.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TAB_SETTINGS_TAB_COMMON_FRAGMENT:
                return Workspeed.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_CONTENT_LIST_VIEW_STANDALONE_FRAGMENT:
                return AppPerfx.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TIMELINE_HOBBIES_FRAGMENT:
                return FeedHealth.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.JOBS_TAB_FRAGMENT:
                return RedblockNative.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FRIENDS_HOME_SECONDARY_FRAGMENT:
                return BizappFeaturePerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_RULE_BASED_AUTO_APPROVE_SETUP_FRAGMENT:
                return Pytorch.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ACTIVE_LIVING_ROOMS_FRAGMENT:
                return FriendDeepDive.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_AUTO_APPROVED_MEMBERS_FRAGMENT:
                return LocalAggregator.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.WORKSPEED_INBOX_FRAGMENT:
                return AndroidEfficiencyModule.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CARRIER_WIFI_PROFILE_SETUP_FRAGMENT:
                return Bishop.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TAB_DISCOVER_FRAGMENT:
                return Diagnostics.getMarkerName(s2);
            case 718:
                return PymkFeedUnit.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.MODULARITY_ROOT_FRAGMENT:
                return Wellbeing.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_MEMBERS_LIST_FRAGMENT:
                return AlohaEffects.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_INSIGHTS_MODERATOR_RECOMMENDATION_FRAGMENT:
                return NativeTemplatesScreens.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TAB_COLLECTION_CREATE_EDIT_FRAGMENT:
                return AndroidDitto.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_SCHEDULE_POST_FRAGMENT:
                return StoriesReliabilityAndroid.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PLACE_PREVIEW_MOVIE_THEATER_MODAL_FRAGMENT:
                return Helium.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TAB_CUSTOMIZATION_LANDING_PAGE_FRAGMENT:
                return ReactNativeSegmentTimings.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_MEMBER_TYPEAHEAD_FRAGMENT:
                return Dei.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_PRODUCT_PICKER_FRAGMENT:
                return FbliteHeroplayerAutoplayer.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_MESSAGE_SETTING_FRAGMENT:
                return CloakingDetectionIabModels.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.BIZ_APP_NT_FRAGMENT:
                return FbliteTestingInternalOnly.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_HISTORY_FRAGMENT:
                return CloakingDetectionSessionLogging.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.TOP_FRIENDS_FRAGMENT:
                return GindiTestFnttttfb.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FB_ASSISTANT_MAIN_FRAGMENT:
                return CpxChannelTab.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NATIVE_TEMPLATES_TOGGLE_NT_STATE_FROM_NATIVE_EXAMPLE_FRAGMENT:
                return ReactNativeExpressRoute.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TOPIC_TAG_MANAGEMENT_CENTER_FRAGMENT_V2:
                return LiveVideoPlayer.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.MUSIC_HOME_FRAGMENT:
                return ImageUpload.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENTS_PERMALINK_ANNOUNCEMENTS_FRAGMENT:
                return Zopt.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_POST_TAB_NT_FRAGMENT:
                return MobileMemory.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NATIVE_TEMPLATES_SCROLL_POSITION_CDS_EXAMPLE_FRAGMENT:
                return InstantGamesArcade.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_TAB_GROUPS_YOU_MANAGE_FRAGMENT:
                return OculusHome.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.BRIDGELESS_REACT_FRAGMENT:
                return IgAndroidVideoRender.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NATIVE_TEMPLATES_PROFILE_VIEW_MODEL_CDS_EXAMPLE_FRAGMENT:
                return Assistant.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_CHAT_ROOM_TRANSITION_FRAGMENT:
                return GemstoneSettings.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NATIVE_TEMPLATES_GQL_REFLOW_LIKE_COUNT_EXAMPLE_FRAGMENT:
                return GemstoneSecretCrush.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SEARCH_TOPIC_DEEP_DIVE_FRAGMENT:
                return IgAndroidIngestion.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.BIZAPP_NT_POST_DETAIL_FRAGMENT:
                return IgRavenUserDwell.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FB_SHORTS_PROFILE_FRAGMENT:
                return FbliteCdn.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SHORT_FORM_VIDEO_CREATION_SHARE_SHEET_FRAGMENT:
                return FbliteModularity.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NATIVE_TEMPLATES_NT_RENDER_CORE_FRAGMENT:
                return PlatformSharing.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCO_MAIN_FRAGMENT:
                return ShowreelNative.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.ONBOARDING_INVITE_FRAGMENT:
                return RsysClientPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NATIVE_TEMPLATES_VARIABLE_GET_REFERENCE_EXAMPLE_FRAGMENT:
                return Onevc.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.VOYAGER_MAIN_FRAGMENT:
                return OculusPanelapps.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.BIZAPP_NATIVE_POST_DETAIL_FRAGMENT:
                return AdsGrowth.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCO_HOME_FRAGMENT:
                return ReactNativeTtrc.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.BIZ_APP_FOAA_INSIGHTS_FRAGMENT:
                return RtcCoexUserInteraction.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.BIZ_APP_PROFILE_INSIGHTS_FRAGMENT:
                return Flipper.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENT_CREATE_ONLINE_SETUP_SELECTION_FRAGMENT:
                return CreatorStudioAndroid.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COLLABORATIVE_STORIES_INVITATION:
                return Essamtestingmodule.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_REQUEST_OFFER_HELP_FRAGMENT:
                return FbliteWatch.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SOCAL_CONTENT_FRAGMENT:
                return FleetBeacon.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PLACES_SURFACE_MAIN_FRAGMENT:
                return MessengerMsys.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_ADMIN_VIEWER_CONTEXT_WRAPPER_FRAGMENT:
                return WpWwwAdmin.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.MULTI_AUTHOR_STORIES_MANAGEMENT:
                return MsysBootstrapAndroid.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CROSS_GROUPS_CHATS_INBOX_FRAGMENT:
                return IgCarbon.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FB_SHORTS_PROFILE_VIDEO_CHAINING_FRAGMENT:
                return ConnectedCommerce.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_ASSISTANT_TASK_BUILDER:
                return WorkplaceFrontlineAccess.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CAMPUS_CONFIRM_EMAIL_FRAGMENT:
                return ReactNativeEntrypoints.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.MULTI_AUTHOR_STORIES_INVITATION_NUX:
                return FbStoriesPtv.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_PENDING_POST_CLUSTER_FRAGMENT:
                return AndroidNotifications.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCO_MEMBER_PROFILE_FAVORITE_PLACES_PICKER_FRAGMENT:
                return AlohaArMicdrop.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCO_MEMBER_PROFILE_FAVORITE_PLACES_SEE_ALL_FRAGMENT:
                return MarketplacePdpRelatedAdLoadTime.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NEARBY_FRIENDS_SETTINGS_FRAGMENT:
                return WpBroadcastVideo.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_ADMIN_ONBOARD_FRAGMENT:
                return WorkplaceIdentity.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCO_CHAT_FRAGMENT:
                return TwilightSocialTab.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NEARBY_FRIENDS_SEARCH_FRAGMENT:
                return IgAndroidIngestionEncoderSelection.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENT_CREATION_ONLINE_FORMAT_FRAGMENT:
                return FeedCameraUsage.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCO_NEIGHBORHOODS_CHAT_CREATE_FRAGMENT:
                return BusinessCm.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENTS_BOOKMARK_CALENDAR_MAIN_FRAGMENT:
                return FeedGapValidation.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENT_CREATION_EDIT_DETAILS_FRAGMENT:
                return StellaApp.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENT_CREATION_DESCRIPTION_AND_CATEGORY_FRAGMENT:
                return WorkplaceDraftFor.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.STAFF_SETUP_CREATE_UPDATE_FRAGMENT:
                return WpAndroidLogin.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCO_CHAT_THREAD_ALL_PARTICIPANTS_FRAGMENT:
                return WpMobileAdmin.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENTS_BOOKMARK_SEARCH_TYPEAHEAD_FRAGMENT:
                return AlohaHome.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NEARBY_FRIENDS_SHARING_FRAGMENT:
                return ZeroBalanceMeasurement.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCO_MEMBER_PROFILE_INTERESTS_PICKER_FRAGMENT:
                return MoodBase.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCO_MEMBER_PROFILE_INTERESTS_SEE_ALL_FRAGMENT:
                return WpAndroidSignup.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FBSHOPS_MALL_FRAGMENT:
                return LocalCommunities.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.UBT_TASK_FRAGMENT:
                return BirdsEyeView.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ALL_HASHTAG_TOPICS_FRAGMENT:
                return LassoBlueConsumption.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.BIZ_COMPOSER_TAG_EDIT_FRAGMENT:
                return Campus.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FOLLOWING_GROUPS_CHATS_FRAGMENT:
                return Looper.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_EDIT_POST_HASHTAG_TOPICS_FRAGMENT:
                return MessengerChatControl.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMPOSER_MEDIA_EFFECT_PREVIEW_FRAGMENT:
                return IgResponsiveness.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_MY_POSTS_SEE_ALL_FRAGMENT:
                return InstantGames.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.WORK_GROUPS_SETTINGS_FRAGMENT:
                return Acela.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUP_RULES_ENFORCEMENT_DETAILS_FRAGMENT:
                return WpWwwSafetycheck.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.LOCO_SELECT_COMPOSER_FRAGMENT:
                return IgThreadsAppKaraokeCaption.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMMUNITY_QNA_POST_COMPOSITION_FRAGMENT:
                return Rooms.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PMA_SCHEDULED_POSTS_FRAGMENT:
                return AndroidTempMediaDiskFootage.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CSR_PLAYGROUND_FRAGMENT:
                return RtcStateSync.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.APP_LOCK_SETTINGS_FRAGMENT:
                return WpFrontlineWorkingHours.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.BIZ_STORY_LIST_FRAGMENT:
                return GamingServices.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.FORUM_MEMBERS_LIST_SEE_ALL_FRAGMENT:
                return BizcomposerMediapicker.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.EVENT_CREATION_TEMPLATE_FRAGMENT:
                return WpAccessCode.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.INSPIRATION_CLOSE_FRIENDS_SETTINGS_FRAGMENT:
                return Vscode.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.PAGE_INBOX_RTC_SETTING_FRAGMENT:
                return RealtimeNt.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.UBT_INTERNAL_SETTINGS_FRAGMENT:
                return FbliteClientLogsMetadata.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.INVITE_LINK_DEEPLINK_HANDLER_FRAGMENT:
                return IgAndroidResumableTranscoding.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SIMPLE_WIFI_PROFILE_DISTRIBUTION:
                return FrescoCache.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NATIVE_BLOKS_EXAMPLES_FRAGMENT:
                return CommunityVewPerf.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.NEON_COMPOSITION_FRAGMENT:
                return WpWwwUserIntegrations.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.AMA_POST_COMPOSITION_FRAGMENT:
                return FbliteRtc.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.CLIENT_IMPORT_PERMISSION_FRAGMENT:
                return MessengerRoomsPre.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMMUNITY_QNA_GROUP_SELECT_FRAGMENT:
                return GroupMallReliability.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.WEASLEY_CLOCK_DASHBOARD_FRAGMENT:
                return IgThreadsAvvmuxerMonitor.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.UBT_DEBUG_RUN_RESULTS_FRAGMENT:
                return NekoPlayableAds.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.COMPOSER_NT_PICKER_LAUNCHER_FRAGMENT:
                return IgAndroidAvInterleave.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_ASSIST_CRITERIA_GALLERY:
                return MessengerPre.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_ASSIST_CRITERIA_FORM:
                return SharedPhoneAccountRecovery.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_ASSIST_COLLECTION_SUMMARY:
                return CompphotoAlgo.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_ASSIST_CRITERIA_ADDED:
                return OnDeviceTts.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.GROUPS_ADMIN_ASSIST_CUSTOM_KEYWORDS:
                return ReactNativeNativeModules.getMarkerName(s2);
            case FragmentConstants.ContentFragmentType.SHOPS_SELLER_ACTIONS_FRAGMENT:
                return AlohaMobileconfig.getMarkerName(s2);
            case 931:
                return AndroidImageLoadReliability.getMarkerName(s2);
            case 936:
                return VideoAdsWatchAndBrowseFullscreen.getMarkerName(s2);
            case 937:
                return TestTestTest.getMarkerName(s2);
            case 941:
                return IgVideoPipeline.getMarkerName(s2);
            case 942:
                return WorkPostPrivacy.getMarkerName(s2);
            case 944:
                return WhaleApp.getMarkerName(s2);
            case 945:
                return QplTestThree.getMarkerName(s2);
            case 948:
                return Casting.getMarkerName(s2);
            case 950:
                return CrmMobile.getMarkerName(s2);
            case 956:
                return IgMediaUpload.getMarkerName(s2);
            case 957:
                return NativeTemplatesAsyncActions.getMarkerName(s2);
            case 963:
                return FeedAdsClientRanking.getMarkerName(s2);
            case 979:
                return MessengerSafechat.getMarkerName(s2);
            case 981:
                return QplTestFour.getMarkerName(s2);
            case 982:
                return MilanChat.getMarkerName(s2);
            case 983:
                return CollaborativeStories.getMarkerName(s2);
            case 1199:
                return WearableLauncher.getMarkerName(s2);
            case 1263:
                return WorkplaceNativeAppCoworkerInvites.getMarkerName(s2);
            case 1272:
                return BizBadge.getMarkerName(s2);
            case 1394:
                return MessengerPresence.getMarkerName(s2);
            case 1408:
                return TestTestGinandi.getMarkerName(s2);
            case 1440:
                return WhatsappTest.getMarkerName(s2);
            case 1471:
                return FbliteNavigationEducation.getMarkerName(s2);
            case 1480:
                return WorkplaceForGood.getMarkerName(s2);
            case 1489:
                return StreamerGroup.getMarkerName(s2);
            case 1564:
                return IawLoadingScreen.getMarkerName(s2);
            case 1718:
                return AvatarRtcIg.getMarkerName(s2);
            case 1738:
                return FbliteClientHttp.getMarkerName(s2);
            case 1896:
                return IgAndroidFileCleanup.getMarkerName(s2);
            case 1958:
                return AlohaUserManagement.getMarkerName(s2);
            case 1984:
                return PlayableAds.getMarkerName(s2);
            case 2039:
                return GroupsCreate.getMarkerName(s2);
            case UL.id._UL__ULSEP_retrofit_RestAdapter_ULSEP_com_oculus_http_core_annotations_FacebookGraphRestAdapter_ULSEP_BINDING_ID /*{ENCODED_INT: 2085}*/:
                return WearableCalendar.getMarkerName(s2);
            case 2159:
                return RoomsInteraction.getMarkerName(s2);
            case 2322:
                return AssistantWearable.getMarkerName(s2);
            case 2438:
                return ReactNativeDevx.getMarkerName(s2);
            case 2556:
                return WearablesStoriesViewerPerformance.getMarkerName(s2);
            case 2636:
                return FbliteMediaPerfCanary.getMarkerName(s2);
            case 2804:
                return AdsExperiments.getMarkerName(s2);
            case 2872:
                return Papaya.getMarkerName(s2);
            case 2906:
                return MessengerWellbeing.getMarkerName(s2);
            case 2907:
                return SiLearning.getMarkerName(s2);
            case 3065:
                return WearableDataApp.getMarkerName(s2);
            case 3204:
                return ScreenshareFloorControl.getMarkerName(s2);
            case 3252:
                return WpWhiteboard.getMarkerName(s2);
            case 3267:
                return AlohaIdentityFunnels.getMarkerName(s2);
            case 3327:
                return RoomsDiscoveryJoinEndToEnd.getMarkerName(s2);
            case 3384:
                return BmCollabortaionCenterExtraOptionsRetailerOnboard.getMarkerName(s2);
            case 3512:
                return WearableAnalytics.getMarkerName(s2);
            case 3551:
                return WorkReporting.getMarkerName(s2);
            case 3631:
                return LiveEventPromotion.getMarkerName(s2);
            case 3643:
                return IgPreviewableVideoAd.getMarkerName(s2);
            case 3661:
                return MessengerRcs.getMarkerName(s2);
            case 3664:
                return AccountRecovery.getMarkerName(s2);
            case 3686:
                return ComposerMediaTemplatePreview.getMarkerName(s2);
            case 3791:
                return IgAndroidRecyclerviewPerf.getMarkerName(s2);
            case 3851:
                return StellaCompphoto.getMarkerName(s2);
            case 4076:
                return WearableNotifications.getMarkerName(s2);
            case 4173:
                return GamingPlayPlatform.getMarkerName(s2);
            case 4305:
                return MessengerUniversalSearch.getMarkerName(s2);
            case 4385:
                return WearableCommsNotification.getMarkerName(s2);
            case 4533:
                return GrowthNotificationLoggedOutPush.getMarkerName(s2);
            case 4584:
                return ExpressiveReshares.getMarkerName(s2);
            case 4638:
                return InstagramReporting.getMarkerName(s2);
            case 4834:
                return WpWwwRooms.getMarkerName(s2);
            case 4973:
                return ContactpointAcquisition.getMarkerName(s2);
            case 5006:
                return WearableSmartReplyService.getMarkerName(s2);
            case 5170:
                return BusinessInboxInMessengerAndroid.getMarkerName(s2);
            case 5250:
                return Stax.getMarkerName(s2);
            case 5312:
                return PrivacyAccessHub.getMarkerName(s2);
            case 5364:
                return WorkplaceMeetings.getMarkerName(s2);
            case 5382:
                return RpSignalingReliability.getMarkerName(s2);
            case 5480:
                return PublicCommunityMigration.getMarkerName(s2);
            case 5514:
                return LocoChat.getMarkerName(s2);
            case 5696:
                return IgRetailEcommerce.getMarkerName(s2);
            case 5780:
                return CloudGaming.getMarkerName(s2);
            case 5829:
                return ResponseDecompression.getMarkerName(s2);
            case 5996:
                return CpasDigitalCircular.getMarkerName(s2);
            case 6087:
                return WearableAppmanager.getMarkerName(s2);
            case 6096:
                return IgTailFetch.getMarkerName(s2);
            case 6359:
                return WearableBackup.getMarkerName(s2);
            case 6567:
                return MarketplaceReserve.getMarkerName(s2);
            case 6649:
                return WearableActivities.getMarkerName(s2);
            case 6716:
                return AlohaWorkVc.getMarkerName(s2);
            case 6751:
                return CommunityTabUserFlow.getMarkerName(s2);
            case 6838:
                return BizappInsights.getMarkerName(s2);
            case 7146:
                return IgAdsManager.getMarkerName(s2);
            case 7295:
                return WorkplaceShiftCoverQp.getMarkerName(s2);
            case 7364:
                return LoginOneTap.getMarkerName(s2);
            case 7410:
                return MarketplacePdpRelevantAdLoadTime.getMarkerName(s2);
            case 7864:
                return IgAndroidMediaCodecCapability.getMarkerName(s2);
            case 7907:
                return WearableSpeechtotext.getMarkerName(s2);
            case 8044:
                return AlohaIdentity.getMarkerName(s2);
            case 8103:
                return BusinessInboxInMessenger.getMarkerName(s2);
            case 8142:
                return InstagramSupportInbox.getMarkerName(s2);
            case 8234:
                return IgAndroidViewpagerPerf.getMarkerName(s2);
            case 8295:
                return Mcom.getMarkerName(s2);
            case 8307:
                return MessengerPerf.getMarkerName(s2);
            case 8316:
                return CommunityPopularNow.getMarkerName(s2);
            case 8353:
                return Scindia.getMarkerName(s2);
            case 8606:
                return MonzaApp.getMarkerName(s2);
            case 8741:
                return RpCopresence.getMarkerName(s2);
            case 8845:
                return AvatarRtc.getMarkerName(s2);
            case 8887:
                return WpAndroidMeetings.getMarkerName(s2);
            case 8913:
                return PrCameraVideoPerf.getMarkerName(s2);
            case 9065:
                return FbShorts.getMarkerName(s2);
            case 9284:
                return FbliteSwipeToBookmarks.getMarkerName(s2);
            case 9446:
                return ClickToMessengerAds.getMarkerName(s2);
            case 9590:
                return IgAndroidExecutor.getMarkerName(s2);
            case 9683:
                return MarketplaceReserveTest.getMarkerName(s2);
            case 9773:
                return GamingCoplay.getMarkerName(s2);
            case 9842:
                return MobileconfigService.getMarkerName(s2);
            case 9892:
                return RibPerf.getMarkerName(s2);
            case 9952:
                return WearableCamera.getMarkerName(s2);
            case 9955:
                return IgBrandedContent.getMarkerName(s2);
            case 10000:
                return AndroidAccountSettings.getMarkerName(s2);
            case 10018:
                return WearableMusic.getMarkerName(s2);
            case 10041:
                return IgReels.getMarkerName(s2);
            case 10045:
                return WorkplaceShiftCover.getMarkerName(s2);
            case 10057:
                return AlohaSip.getMarkerName(s2);
            case 10272:
                return AlohaAppstore.getMarkerName(s2);
            case 10281:
                return WhatsappCommerce.getMarkerName(s2);
            case 10396:
                return MessengerLocationSharing.getMarkerName(s2);
            case 10455:
                return MessengerSecondarySearch.getMarkerName(s2);
            case 10512:
                return QuicklogModuleForEToEDontTouch.getMarkerName(s2);
            case 10523:
                return WhatsappScrollPerf.getMarkerName(s2);
            case 10556:
                return QplTestPointsHierarchy.getMarkerName(s2);
            case 10711:
                return BizDisco.getMarkerName(s2);
            case 10741:
                return WhatsappTtrc.getMarkerName(s2);
            case 10748:
                return WearableSelfcare.getMarkerName(s2);
            case 10818:
                return MarketplaceRatingsReviews.getMarkerName(s2);
            case 10843:
                return AndroidOffsiteNotification.getMarkerName(s2);
            case 10940:
                return Investigations.getMarkerName(s2);
            case 10986:
                return BloksScreens.getMarkerName(s2);
            case 11065:
                return CafePro.getMarkerName(s2);
            case 11072:
                return FosMonetization.getMarkerName(s2);
            case 11164:
                return Ride.getMarkerName(s2);
            case 11301:
                return PapayaStore.getMarkerName(s2);
            case 11509:
                return WearableScrollPerf.getMarkerName(s2);
            case 11716:
                return FblitePrepush.getMarkerName(s2);
            case 11799:
                return TtrcPlusImages.getMarkerName(s2);
            case 11853:
                return Logdb.getMarkerName(s2);
            case 12019:
                return SocialWifi.getMarkerName(s2);
            case 12272:
                return MessengerMessageSearch.getMarkerName(s2);
            case 12308:
                return StoryReader.getMarkerName(s2);
            case 12382:
                return WearableWorkout.getMarkerName(s2);
            case 12409:
                return GroupsAdminHome.getMarkerName(s2);
            case 12443:
                return LeadgenFlowAndroid.getMarkerName(s2);
            case 12540:
                return HelpCenter.getMarkerName(s2);
            case 12571:
                return OrcaEfficiency.getMarkerName(s2);
            case 12727:
                return Memento.getMarkerName(s2);
            case 12788:
                return WearableKeyboard.getMarkerName(s2);
            case 12796:
                return IgReelsCamera.getMarkerName(s2);
            case 12842:
                return PlacePicker.getMarkerName(s2);
            case 12930:
                return FbShopTabSerp.getMarkerName(s2);
            case 13089:
                return FamilyExperiences.getMarkerName(s2);
            case 13248:
                return HelpdeskOnWorkplace.getMarkerName(s2);
            case 13271:
                return FbShops.getMarkerName(s2);
            case 13337:
                return NewsCompassSnax.getMarkerName(s2);
            case 13427:
                return IgThreadsAppStatusHeartbeat.getMarkerName(s2);
            case 13472:
                return AlohaGlobalPickerFunnel.getMarkerName(s2);
            case 13606:
                return CommunityReputation.getMarkerName(s2);
            case 13636:
                return IgContentFilterEngine.getMarkerName(s2);
            case 13737:
                return InteractiveMedia.getMarkerName(s2);
            case 13890:
                return GrowthPushNotificationDelivery.getMarkerName(s2);
            case 13904:
                return OculusSocialPlatform.getMarkerName(s2);
            case 13912:
                return LeadgenUnifiedClientSide.getMarkerName(s2);
            case 14020:
                return FbcVenice.getMarkerName(s2);
            case 14043:
                return MessengerShops.getMarkerName(s2);
            case 14071:
                return MessengerEndToEndPre.getMarkerName(s2);
            case 14161:
                return AlohaAmbient.getMarkerName(s2);
            case 14267:
                return RealtimeGraphServices.getMarkerName(s2);
            case 14372:
                return XrosKernelBenchmarks.getMarkerName(s2);
            case 14406:
                return RibReliability.getMarkerName(s2);
            case 14640:
                return WearableSpeechservice.getMarkerName(s2);
            case 14687:
                return IgProfessionalHome.getMarkerName(s2);
            case 14790:
                return AlohaMessenger.getMarkerName(s2);
            case 14812:
                return PortalWorkplaceLive.getMarkerName(s2);
            case 14869:
                return IgHomeSurface.getMarkerName(s2);
            case 15062:
                return LoginOauth.getMarkerName(s2);
            case 15121:
                return AlohaCalendar.getMarkerName(s2);
            case 15148:
                return MessengerRoomsConnection.getMarkerName(s2);
            case 15395:
                return ArEffectCustomBgIntegrityUpload.getMarkerName(s2);
            case 15413:
                return GroupApps.getMarkerName(s2);
            case 15453:
                return FbShopTab.getMarkerName(s2);
            case 15490:
                return CsrPlayground.getMarkerName(s2);
            case 15803:
                return AvatarCoPresence.getMarkerName(s2);
            case 15878:
                return MessengerSearchEditHistory.getMarkerName(s2);
            case 15899:
                return WearableConnectivity.getMarkerName(s2);
            case 16026:
                return Menu.getMarkerName(s2);
            case 16028:
                return IgAndroidInterprocessCommunication.getMarkerName(s2);
            case 16045:
                return WearableComms.getMarkerName(s2);
            case 16090:
                return WearableDevoptions.getMarkerName(s2);
            case 16091:
                return NativeTemplatesPaging.getMarkerName(s2);
            case 16232:
                return GamingGroup.getMarkerName(s2);
            case 16277:
                return BizInsightsMetricGlossary.getMarkerName(s2);
            case 16289:
                return MarketplaceLocalRatingsReview.getMarkerName(s2);
            case ConstantIds.NUM_MODULES:
                return GrowthPushDelivery.getMarkerName(s2);
            default:
                switch (s) {
                    case 6:
                        return Events.getMarkerName(s2);
                    case 7:
                        return Search.getMarkerName(s2);
                    case 8:
                        return TestModuleOne.getMarkerName(s2);
                    case 9:
                        return TestModuleTwo.getMarkerName(s2);
                    case 10:
                        return Feed.getMarkerName(s2);
                    default:
                        switch (s) {
                            case 18:
                                return Imagepipeline.getMarkerName(s2);
                            case 19:
                                return Pages.getMarkerName(s2);
                            case 20:
                                return Photos.getMarkerName(s2);
                            case 21:
                                return Places.getMarkerName(s2);
                            case 22:
                                return Privacy.getMarkerName(s2);
                            default:
                                switch (s) {
                                    case 46:
                                        return Pymk.getMarkerName(s2);
                                    case 47:
                                        return Friending.getMarkerName(s2);
                                    case 48:
                                        return FriendsNearby.getMarkerName(s2);
                                    case UL.id._UL__ULSEP_com_facebook_inject_InjectorLike_ULSEP_BINDING_ID /*{ENCODED_INT: 49}*/:
                                        return Graphql.getMarkerName(s2);
                                    default:
                                        return "UNDEFINED_QPL_MODULE";
                                }
                        }
                }
        }
    }
}
