package com.facebook.quicklog.identifiers;

public class MessengerIntegrity {
    public static final int IMPERSONATION_FETCH_SELECTED_USER_EVENT = 30279694;
    public static final int IMPERSONATION_FETCH_USER_EVENT = 30277637;
    public static final short MODULE_ID = 462;
    public static final int TIME_TO_BLOCK_ON_ANDROID_AND_IOS = 30277635;
    public static final int TIME_TO_LOAD_FEEDBACK_TAGS_ANDROID = 30277633;
    public static final int TIME_TO_LOAD_PROACTIVE_WARNING_INFO_ANDROID = 30277634;
    public static final int TIME_TO_UNBLOCK_ON_ANDROID_AND_IOS = 30277636;

    public static String getMarkerName(int i) {
        return i != 1 ? i != 2 ? i != 3 ? i != 4 ? i != 5 ? i != 2062 ? "UNDEFINED_QPL_EVENT" : "MESSENGER_INTEGRITY_IMPERSONATION_FETCH_SELECTED_USER_EVENT" : "MESSENGER_INTEGRITY_IMPERSONATION_FETCH_USER_EVENT" : "MESSENGER_INTEGRITY_TIME_TO_UNBLOCK_ON_ANDROID_AND_IOS" : "MESSENGER_INTEGRITY_TIME_TO_BLOCK_ON_ANDROID_AND_IOS" : "MESSENGER_INTEGRITY_TIME_TO_LOAD_PROACTIVE_WARNING_INFO_ANDROID" : "MESSENGER_INTEGRITY_TIME_TO_LOAD_FEEDBACK_TAGS_ANDROID";
    }
}
