package com.facebook.quicklog.identifiers;

public class WearableScrollPerf {
    public static final int LAUNCHER_APP_TRAY_SCROLL_PERF = 754256283;
    public static final int LAUNCHER_PAGER_SCROLL_PERF = 754258171;
    public static final short MODULE_ID = 11509;
    public static final int MUSIC_BROWSE_SCROLL_PERF = 754263613;
    public static final int NOTIFICATION_DETAILS_SCROLL_PERF = 754266494;
    public static final int NOTIFICATION_GROUPS_LIST_SCROLL_PERF = 754255241;
    public static final int NOTIFICATION_LIST_SCROLL_PERF = 754263648;
    public static final int SELF_CARE_PAST_WORKOUTS_SCROLL_PERF = 754260871;

    public static String getMarkerName(int i) {
        return i != 1417 ? i != 2459 ? i != 4347 ? i != 7047 ? i != 9789 ? i != 9824 ? i != 12670 ? "UNDEFINED_QPL_EVENT" : "WEARABLE_SCROLL_PERF_NOTIFICATION_DETAILS_SCROLL_PERF" : "WEARABLE_SCROLL_PERF_NOTIFICATION_LIST_SCROLL_PERF" : "WEARABLE_SCROLL_PERF_MUSIC_BROWSE_SCROLL_PERF" : "WEARABLE_SCROLL_PERF_SELF_CARE_PAST_WORKOUTS_SCROLL_PERF" : "WEARABLE_SCROLL_PERF_LAUNCHER_PAGER_SCROLL_PERF" : "WEARABLE_SCROLL_PERF_LAUNCHER_APP_TRAY_SCROLL_PERF" : "WEARABLE_SCROLL_PERF_NOTIFICATION_GROUPS_LIST_SCROLL_PERF";
    }
}
