package com.facebook.quicklog.identifiers;

public class WorkplaceShiftCover {
    public static final short MODULE_ID = 10045;
    public static final int SHIFT_COVER_ATTACHMENT_CREATION = 658311653;
    public static final int SHIFT_COVER_ATTACHMENT_DELETION = 658314754;
    public static final int SHIFT_COVER_ATTACHMENT_EDIT = 658323570;
    public static final int SHIFT_COVER_CANCEL_OFFER = 658311000;
    public static final int SHIFT_COVER_CANCEL_OFFER_COVER_FLOW = 658320532;
    public static final int SHIFT_COVER_MANAGER_APPROVE = 658312030;
    public static final int SHIFT_COVER_MANAGER_DECLINE = 658319560;
    public static final int SHIFT_COVER_OFFER_COVER = 658310259;
    public static final int SHIFT_COVER_OFFER_COVER_FLOW = 658313937;
    public static final int SHIFT_COVER_REVIEW_REQUEST_FLOW = 658325194;

    public static String getMarkerName(int i) {
        return i != 1139 ? i != 1880 ? i != 2533 ? i != 2910 ? i != 4817 ? i != 5634 ? i != 10440 ? i != 11412 ? i != 14450 ? i != 16074 ? "UNDEFINED_QPL_EVENT" : "WORKPLACE_SHIFT_COVER_SHIFT_COVER_REVIEW_REQUEST_FLOW" : "WORKPLACE_SHIFT_COVER_SHIFT_COVER_ATTACHMENT_EDIT" : "WORKPLACE_SHIFT_COVER_SHIFT_COVER_CANCEL_OFFER_COVER_FLOW" : "WORKPLACE_SHIFT_COVER_SHIFT_COVER_MANAGER_DECLINE" : "WORKPLACE_SHIFT_COVER_SHIFT_COVER_ATTACHMENT_DELETION" : "WORKPLACE_SHIFT_COVER_SHIFT_COVER_OFFER_COVER_FLOW" : "WORKPLACE_SHIFT_COVER_SHIFT_COVER_MANAGER_APPROVE" : "WORKPLACE_SHIFT_COVER_SHIFT_COVER_ATTACHMENT_CREATION" : "WORKPLACE_SHIFT_COVER_SHIFT_COVER_CANCEL_OFFER" : "WORKPLACE_SHIFT_COVER_SHIFT_COVER_OFFER_COVER";
    }
}
