package com.oculus.common.packagescache;

import X.AbstractC03180ld;
import X.AnonymousClass0Hr;
import X.AnonymousClass0Qr;
import X.AnonymousClass0VC;
import X.AnonymousClass0VI;
import X.AnonymousClass0lg;
import X.AnonymousClass1TK;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.DeclareMultiBinding;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import java.util.Set;
import javax.inject.Provider;

@InjectorModule
public abstract class PackagesCacheModule extends AnonymousClass0VI {

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_common_packagescache_PackageManagerUtils_ULSEP_BINDING_ID = 2083;
        public static final int _UL__ULSEP_java_util_Set_ULLT_com_oculus_common_packagescache_PackagesListener_ULGT__ULSEP_BINDING_ID = 4;
    }

    @AutoGeneratedAccessMethod
    public static final AbstractC03180ld _UL__ULSEP_com_facebook_inject_Lazy_ULLT_java_util_Set_ULLT_com_oculus_common_packagescache_PackagesListener_ULGT__ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0Hr.A00(4, r1);
    }

    @AutoGeneratedAccessMethod
    public static final Set _UL__ULSEP_java_util_Set_ULLT_com_oculus_common_packagescache_PackagesListener_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r2) {
        return (Set) AnonymousClass1TK.A00(4, r2, null);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_java_util_Set_ULLT_com_oculus_common_packagescache_PackagesListener_ULGT__ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0VC.A00(4, r1);
    }

    @DeclareMultiBinding
    public abstract Set<PackagesListener> getOSUpdateInfoListener();

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForPackagesCacheModule {
        public static void bind(AnonymousClass0Qr r0) {
        }
    }
}
