package com.oculus.horizon.abuse_prevention;

import X.AnonymousClass0J5;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public abstract class AbusePreventionModule extends AnonymousClass0J5 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForAbusePreventionModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_horizon_abuse_ULUNDERSCORE_prevention_AbuseAVCapture_ULSEP_BINDING_ID = 203;
        public static final int _UL__ULSEP_com_oculus_horizon_abuse_ULUNDERSCORE_prevention_AudioCapture_ULSEP_BINDING_ID = 2117;
        public static final int _UL__ULSEP_com_oculus_horizon_abuse_ULUNDERSCORE_prevention_FileReceiverManager_ULSEP_BINDING_ID = 390;
        public static final int _UL__ULSEP_com_oculus_horizon_abuse_ULUNDERSCORE_prevention_VideoUploaderMethods_ULSEP_BINDING_ID = 241;
        public static final int _UL__ULSEP_com_oculus_horizon_abuse_ULUNDERSCORE_prevention_VideoUploaderServiceManager_ULSEP_BINDING_ID = 61;
    }
}
