package com.oculus.downloader.dispatcher;

import X.AnonymousClass0J5;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public abstract class DispatcherModule extends AnonymousClass0J5 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForDispatcherModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_downloader_dispatcher_OculusDownloadListenerDispatcher_ULSEP_BINDING_ID = 48;
        public static final int _UL__ULSEP_java_util_Set_ULLT_com_oculus_downloader_OculusDownloadListener_ULGT__ULSEP_BINDING_ID = 465;
    }
}
