package com.oculus.horizon.platformplugin;

import X.AnonymousClass0J5;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public abstract class PlatformPluginModule extends AnonymousClass0J5 {
    public static volatile PlatformPluginManager _UL__ULSEP_com_oculus_horizon_platformplugin_PlatformPluginManager_ULSEP_INSTANCE;

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForPlatformPluginModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_horizon_platformplugin_PlatformPluginManager_ULSEP_BINDING_ID = 160;
        public static final int _UL__ULSEP_com_oculus_partycontroller_PartyController_ULSEP_BINDING_ID = 15;
    }
}
