package X;

import com.google.gson.internal.bind.TypeAdapters$26;
import com.google.gson.internal.bind.TypeAdapters$30;
import com.google.gson.internal.bind.TypeAdapters$32;
import com.google.gson.internal.bind.TypeAdapters$33;
import com.google.gson.internal.bind.TypeAdapters$34;
import com.google.gson.internal.bind.TypeAdapters$35;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

/* renamed from: X.14E  reason: invalid class name */
public final class AnonymousClass14E {
    public static final AnonymousClass13Y<AtomicBoolean> A00;
    public static final AnonymousClass13Y<AtomicInteger> A01;
    public static final AnonymousClass13Y<AtomicIntegerArray> A02;
    public static final AnonymousClass13Y<BigDecimal> A03 = new C01300dY();
    public static final AnonymousClass13Y<BigInteger> A04 = new C01290dX();
    public static final AnonymousClass13Y<BitSet> A05;
    public static final AnonymousClass13Y<Boolean> A06;
    public static final AnonymousClass13Y<Boolean> A07 = new AnonymousClass0dA();
    public static final AnonymousClass13Y<Number> A08;
    public static final AnonymousClass13Y<Calendar> A09;
    public static final AnonymousClass13Y<Character> A0A;
    public static final AnonymousClass13Y<Class> A0B;
    public static final AnonymousClass13Y<Currency> A0C;
    public static final AnonymousClass13Y<Number> A0D = new AnonymousClass0dc();
    public static final AnonymousClass13Y<Number> A0E = new C01330dd();
    public static final AnonymousClass13Y<InetAddress> A0F;
    public static final AnonymousClass13Y<Number> A0G;
    public static final AnonymousClass13Y<AnonymousClass13R> A0H;
    public static final AnonymousClass13Y<Locale> A0I;
    public static final AnonymousClass13Y<Number> A0J = new AnonymousClass0de();
    public static final AnonymousClass13Y<Number> A0K;
    public static final AnonymousClass13Y<Number> A0L;
    public static final AnonymousClass13Y<String> A0M;
    public static final AnonymousClass13Y<StringBuffer> A0N;
    public static final AnonymousClass13Y<StringBuilder> A0O;
    public static final AnonymousClass13Y<URI> A0P;
    public static final AnonymousClass13Y<URL> A0Q;
    public static final AnonymousClass13Y<UUID> A0R;
    public static final AnonymousClass13Z A0S;
    public static final AnonymousClass13Z A0T;
    public static final AnonymousClass13Z A0U;
    public static final AnonymousClass13Z A0V;
    public static final AnonymousClass13Z A0W;
    public static final AnonymousClass13Z A0X;
    public static final AnonymousClass13Z A0Y;
    public static final AnonymousClass13Z A0Z;
    public static final AnonymousClass13Z A0a;
    public static final AnonymousClass13Z A0b;
    public static final AnonymousClass13Z A0c = new TypeAdapters$30();
    public static final AnonymousClass13Z A0d;
    public static final AnonymousClass13Z A0e;
    public static final AnonymousClass13Z A0f;
    public static final AnonymousClass13Z A0g;
    public static final AnonymousClass13Z A0h;
    public static final AnonymousClass13Z A0i;
    public static final AnonymousClass13Z A0j;
    public static final AnonymousClass13Z A0k;
    public static final AnonymousClass13Z A0l;
    public static final AnonymousClass13Z A0m = new TypeAdapters$26();
    public static final AnonymousClass13Z A0n;
    public static final AnonymousClass13Z A0o;
    public static final AnonymousClass13Z A0p;

    static {
        AnonymousClass0eO r2 = new AnonymousClass0eO(new AnonymousClass0dV());
        A0B = r2;
        A0a = new TypeAdapters$32(Class.class, r2);
        AnonymousClass0eO r22 = new AnonymousClass0eO(new AnonymousClass0dJ());
        A05 = r22;
        A0V = new TypeAdapters$32(BitSet.class, r22);
        AnonymousClass0dB r3 = new AnonymousClass0dB();
        A06 = r3;
        A0W = new TypeAdapters$33(Boolean.TYPE, Boolean.class, r3);
        AnonymousClass0d9 r32 = new AnonymousClass0d9();
        A08 = r32;
        A0X = new TypeAdapters$33(Byte.TYPE, Byte.class, r32);
        AnonymousClass0d8 r33 = new AnonymousClass0d8();
        A0L = r33;
        A0i = new TypeAdapters$33(Short.TYPE, Short.class, r33);
        AnonymousClass0d7 r34 = new AnonymousClass0d7();
        A0G = r34;
        A0e = new TypeAdapters$33(Integer.TYPE, Integer.class, r34);
        AnonymousClass0eO r23 = new AnonymousClass0eO(new AnonymousClass0d6());
        A01 = r23;
        A0U = new TypeAdapters$32(AtomicInteger.class, r23);
        AnonymousClass0eO r24 = new AnonymousClass0eO(new AnonymousClass0d5());
        A00 = r24;
        A0S = new TypeAdapters$32(AtomicBoolean.class, r24);
        AnonymousClass0eO r25 = new AnonymousClass0eO(new AnonymousClass0df());
        A02 = r25;
        A0T = new TypeAdapters$32(AtomicIntegerArray.class, r25);
        C01320db r26 = new C01320db();
        A0K = r26;
        A0h = new TypeAdapters$32(Number.class, r26);
        C01310da r35 = new C01310da();
        A0A = r35;
        A0Z = new TypeAdapters$33(Character.TYPE, Character.class, r35);
        AnonymousClass0dZ r27 = new AnonymousClass0dZ();
        A0M = r27;
        A0l = new TypeAdapters$32(String.class, r27);
        AnonymousClass0dW r28 = new AnonymousClass0dW();
        A0O = r28;
        A0k = new TypeAdapters$32(StringBuilder.class, r28);
        AnonymousClass0dU r29 = new AnonymousClass0dU();
        A0N = r29;
        A0j = new TypeAdapters$32(StringBuffer.class, r29);
        AnonymousClass0dT r210 = new AnonymousClass0dT();
        A0Q = r210;
        A0o = new TypeAdapters$32(URL.class, r210);
        AnonymousClass0dS r211 = new AnonymousClass0dS();
        A0P = r211;
        A0n = new TypeAdapters$32(URI.class, r211);
        AnonymousClass0dR r212 = new AnonymousClass0dR();
        A0F = r212;
        A0d = new TypeAdapters$35(InetAddress.class, r212);
        AnonymousClass0dQ r213 = new AnonymousClass0dQ();
        A0R = r213;
        A0p = new TypeAdapters$32(UUID.class, r213);
        AnonymousClass0eO r214 = new AnonymousClass0eO(new AnonymousClass0dP());
        A0C = r214;
        A0b = new TypeAdapters$32(Currency.class, r214);
        AnonymousClass0dM r1 = new AnonymousClass0dM();
        A09 = r1;
        A0Y = new TypeAdapters$34(r1);
        AnonymousClass0dL r215 = new AnonymousClass0dL();
        A0I = r215;
        A0g = new TypeAdapters$32(Locale.class, r215);
        AnonymousClass0dK r216 = new AnonymousClass0dK();
        A0H = r216;
        A0f = new TypeAdapters$35(AnonymousClass13R.class, r216);
    }
}
