package com.oculus.unifiedtelemetry.unifiedlogging.utils;

import X.I0;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import com.oculus.library.utils.app.ImagesBuilder;

@InjectorModule
public class UtilsModule extends I0 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForUtilsModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_unifiedlogging_utils_SettingsManager_ULSEP_BINDING_ID = 20;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_unifiedlogging_utils_TelemetryStateMonitor_ULSEP_BINDING_ID = ImagesBuilder.IMAGE_LANDSCAPE_HEIGHT;
    }
}
