package com.oculus.horizon.platform;

import X.AbstractC06640p5;
import X.AnonymousClass0Pi;
import X.AnonymousClass0p1;
import X.AnonymousClass117;
import X.C01010Iv;
import android.os.Bundle;
import com.facebook.inject.ApplicationScoped;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.oculus.horizon.api.graphql.GraphQLParamsHelper;
import com.oculus.horizon.platformsdk.DeeplinkIntentUtils;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import javax.inject.Provider;
import org.json.JSONException;
import org.json.JSONObject;

@Dependencies({})
@ApplicationScoped
public class PlatformContext {
    public static final String TAG = "PlatformContext";
    public static volatile PlatformContext _UL__ULSEP_com_oculus_horizon_platform_PlatformContext_ULSEP_INSTANCE;
    public final Map<String, AppContext> mAppIdToContext = Collections.synchronizedMap(new HashMap());

    public static class AppContext {
        public String launchSource;
        public String launchType;
    }

    public static AppContext A00(PlatformContext platformContext, String str) {
        if (platformContext.mAppIdToContext.containsKey(str)) {
            return platformContext.mAppIdToContext.get(str);
        }
        AppContext appContext = new AppContext();
        platformContext.mAppIdToContext.put(str, appContext);
        return appContext;
    }

    @AutoGeneratedAccessMethod
    public static final AnonymousClass0p1 _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_horizon_platform_PlatformContext_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C01010Iv(381, r2);
    }

    @AutoGeneratedAccessMethod
    public static final PlatformContext _UL__ULSEP_com_oculus_horizon_platform_PlatformContext_ULSEP_ACCESS_METHOD(AbstractC06640p5 r1) {
        return (PlatformContext) AnonymousClass117.A00(381, r1);
    }

    @AutoGeneratedFactoryMethod
    public static final PlatformContext _UL__ULSEP_com_oculus_horizon_platform_PlatformContext_ULSEP_FACTORY_METHOD(AbstractC06640p5 r3) {
        if (_UL__ULSEP_com_oculus_horizon_platform_PlatformContext_ULSEP_INSTANCE == null) {
            synchronized (PlatformContext.class) {
                AnonymousClass0Pi A00 = AnonymousClass0Pi.A00(_UL__ULSEP_com_oculus_horizon_platform_PlatformContext_ULSEP_INSTANCE, r3);
                if (A00 != null) {
                    try {
                        r3.getApplicationInjector();
                        _UL__ULSEP_com_oculus_horizon_platform_PlatformContext_ULSEP_INSTANCE = new PlatformContext();
                    } finally {
                        A00.A01();
                    }
                }
            }
        }
        return _UL__ULSEP_com_oculus_horizon_platform_PlatformContext_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_horizon_platform_PlatformContext_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C01010Iv(381, r2);
    }

    public void parse(String str, Bundle bundle) {
        try {
            JSONObject jSONObject = new JSONObject(bundle.getString(GraphQLParamsHelper.KEY_ARGS));
            if (jSONObject.has("launch_type")) {
                A00(this, str).launchType = jSONObject.getString("launch_type");
            }
            if (jSONObject.has(DeeplinkIntentUtils.INTENT_KEY_LAUNCH_SOURCE)) {
                A00(this, str).launchSource = jSONObject.getString(DeeplinkIntentUtils.INTENT_KEY_LAUNCH_SOURCE);
            }
        } catch (JSONException unused) {
        }
    }

    public AppContext getAppContext(String str) {
        return A00(this, str);
    }
}
