package X;

import com.google.gson.internal.bind.TypeAdapters$26;
import com.google.gson.internal.bind.TypeAdapters$30;
import com.google.gson.internal.bind.TypeAdapters$32;
import com.google.gson.internal.bind.TypeAdapters$33;
import com.google.gson.internal.bind.TypeAdapters$34;
import com.google.gson.internal.bind.TypeAdapters$35;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

/* renamed from: X.0Fb  reason: invalid class name and case insensitive filesystem */
public final class C01220Fb {
    public static final AnonymousClass0Bd<AtomicBoolean> A00;
    public static final AnonymousClass0Bd<AtomicInteger> A01;
    public static final AnonymousClass0Bd<AtomicIntegerArray> A02;
    public static final AnonymousClass0Bd<BigDecimal> A03 = new AnonymousClass0WX();
    public static final AnonymousClass0Bd<BigInteger> A04 = new AnonymousClass0WW();
    public static final AnonymousClass0Bd<BitSet> A05;
    public static final AnonymousClass0Bd<Boolean> A06;
    public static final AnonymousClass0Bd<Boolean> A07 = new AnonymousClass0W9();
    public static final AnonymousClass0Bd<Number> A08;
    public static final AnonymousClass0Bd<Calendar> A09;
    public static final AnonymousClass0Bd<Character> A0A;
    public static final AnonymousClass0Bd<Class> A0B;
    public static final AnonymousClass0Bd<Currency> A0C;
    public static final AnonymousClass0Bd<Number> A0D = new AnonymousClass0Wb();
    public static final AnonymousClass0Bd<Number> A0E = new C02080Wc();
    public static final AnonymousClass0Bd<InetAddress> A0F;
    public static final AnonymousClass0Bd<Number> A0G;
    public static final AnonymousClass0Bd<AnonymousClass0AU> A0H;
    public static final AnonymousClass0Bd<Locale> A0I;
    public static final AnonymousClass0Bd<Number> A0J = new AnonymousClass0Wd();
    public static final AnonymousClass0Bd<Number> A0K;
    public static final AnonymousClass0Bd<Number> A0L;
    public static final AnonymousClass0Bd<String> A0M;
    public static final AnonymousClass0Bd<StringBuffer> A0N;
    public static final AnonymousClass0Bd<StringBuilder> A0O;
    public static final AnonymousClass0Bd<URI> A0P;
    public static final AnonymousClass0Bd<URL> A0Q;
    public static final AnonymousClass0Bd<UUID> A0R;
    public static final AnonymousClass0C3 A0S;
    public static final AnonymousClass0C3 A0T;
    public static final AnonymousClass0C3 A0U;
    public static final AnonymousClass0C3 A0V;
    public static final AnonymousClass0C3 A0W;
    public static final AnonymousClass0C3 A0X;
    public static final AnonymousClass0C3 A0Y;
    public static final AnonymousClass0C3 A0Z;
    public static final AnonymousClass0C3 A0a;
    public static final AnonymousClass0C3 A0b;
    public static final AnonymousClass0C3 A0c = new TypeAdapters$30();
    public static final AnonymousClass0C3 A0d;
    public static final AnonymousClass0C3 A0e;
    public static final AnonymousClass0C3 A0f;
    public static final AnonymousClass0C3 A0g;
    public static final AnonymousClass0C3 A0h;
    public static final AnonymousClass0C3 A0i;
    public static final AnonymousClass0C3 A0j;
    public static final AnonymousClass0C3 A0k;
    public static final AnonymousClass0C3 A0l;
    public static final AnonymousClass0C3 A0m = new TypeAdapters$26();
    public static final AnonymousClass0C3 A0n;
    public static final AnonymousClass0C3 A0o;
    public static final AnonymousClass0C3 A0p;

    static {
        AnonymousClass0XN r2 = new AnonymousClass0XN(new AnonymousClass0WU());
        A0B = r2;
        A0a = new TypeAdapters$32(Class.class, r2);
        AnonymousClass0XN r22 = new AnonymousClass0XN(new AnonymousClass0WI());
        A05 = r22;
        A0V = new TypeAdapters$32(BitSet.class, r22);
        AnonymousClass0WA r3 = new AnonymousClass0WA();
        A06 = r3;
        A0W = new TypeAdapters$33(Boolean.TYPE, Boolean.class, r3);
        AnonymousClass0W8 r32 = new AnonymousClass0W8();
        A08 = r32;
        A0X = new TypeAdapters$33(Byte.TYPE, Byte.class, r32);
        AnonymousClass0W7 r33 = new AnonymousClass0W7();
        A0L = r33;
        A0i = new TypeAdapters$33(Short.TYPE, Short.class, r33);
        AnonymousClass0W6 r34 = new AnonymousClass0W6();
        A0G = r34;
        A0e = new TypeAdapters$33(Integer.TYPE, Integer.class, r34);
        AnonymousClass0XN r23 = new AnonymousClass0XN(new AnonymousClass0W5());
        A01 = r23;
        A0U = new TypeAdapters$32(AtomicInteger.class, r23);
        AnonymousClass0XN r24 = new AnonymousClass0XN(new AnonymousClass0W4());
        A00 = r24;
        A0S = new TypeAdapters$32(AtomicBoolean.class, r24);
        AnonymousClass0XN r25 = new AnonymousClass0XN(new AnonymousClass0We());
        A02 = r25;
        A0T = new TypeAdapters$32(AtomicIntegerArray.class, r25);
        C02070Wa r26 = new C02070Wa();
        A0K = r26;
        A0h = new TypeAdapters$32(Number.class, r26);
        AnonymousClass0WZ r35 = new AnonymousClass0WZ();
        A0A = r35;
        A0Z = new TypeAdapters$33(Character.TYPE, Character.class, r35);
        AnonymousClass0WY r27 = new AnonymousClass0WY();
        A0M = r27;
        A0l = new TypeAdapters$32(String.class, r27);
        AnonymousClass0WV r28 = new AnonymousClass0WV();
        A0O = r28;
        A0k = new TypeAdapters$32(StringBuilder.class, r28);
        AnonymousClass0WT r29 = new AnonymousClass0WT();
        A0N = r29;
        A0j = new TypeAdapters$32(StringBuffer.class, r29);
        AnonymousClass0WS r210 = new AnonymousClass0WS();
        A0Q = r210;
        A0o = new TypeAdapters$32(URL.class, r210);
        AnonymousClass0WR r211 = new AnonymousClass0WR();
        A0P = r211;
        A0n = new TypeAdapters$32(URI.class, r211);
        AnonymousClass0WQ r212 = new AnonymousClass0WQ();
        A0F = r212;
        A0d = new TypeAdapters$35(InetAddress.class, r212);
        AnonymousClass0WP r213 = new AnonymousClass0WP();
        A0R = r213;
        A0p = new TypeAdapters$32(UUID.class, r213);
        AnonymousClass0XN r214 = new AnonymousClass0XN(new AnonymousClass0WO());
        A0C = r214;
        A0b = new TypeAdapters$32(Currency.class, r214);
        AnonymousClass0WL r1 = new AnonymousClass0WL();
        A09 = r1;
        A0Y = new TypeAdapters$34(r1);
        AnonymousClass0WK r215 = new AnonymousClass0WK();
        A0I = r215;
        A0g = new TypeAdapters$32(Locale.class, r215);
        AnonymousClass0WJ r216 = new AnonymousClass0WJ();
        A0H = r216;
        A0f = new TypeAdapters$35(AnonymousClass0AU.class, r216);
    }
}
