package X;

import com.facebook.infer.annotation.Nullsafe;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;

@InjectorModule
@Nullsafe(Nullsafe.Mode.LOCAL)
/* renamed from: X.0Gn  reason: invalid class name and case insensitive filesystem */
public final class C01400Gn extends AbstractC01750Lk {
    public static volatile C01630Kf A00;

    @AutoGeneratedAccessMethod
    public static final C01630Kf A00(AbstractC02990bJ r1) {
        return (C01630Kf) AnonymousClass13m.A00(82, r1);
    }

    @AutoGeneratedFactoryMethod
    public static final C01630Kf A01(AbstractC02990bJ r7) {
        long j;
        if (A00 == null) {
            synchronized (C01630Kf.class) {
                AnonymousClass0Qe A002 = AnonymousClass0Qe.A00(A00, r7);
                if (A002 != null) {
                    try {
                        C01640Kg A03 = A03(r7.getApplicationInjector());
                        String str = A03.A00;
                        C01640Kg.A00(A03, "com.facebook.versioncontrol.revision", str);
                        C01640Kg.A00(A03, "com.facebook.versioncontrol.branch", str);
                        String A003 = C01640Kg.A00(A03, "com.facebook.build_time", str);
                        if (A003 == null || !C01640Kg.A03.matcher(A003).matches()) {
                            j = 0;
                        } else {
                            j = Long.parseLong(A003.substring(0, A003.length() - 1));
                            DateFormat dateTimeInstance = DateFormat.getDateTimeInstance(1, 0, Locale.US);
                            dateTimeInstance.setTimeZone(TimeZone.getTimeZone("PST8PDT"));
                            dateTimeInstance.format(new Date(j));
                        }
                        A00 = new C01630Kf(j);
                    } finally {
                        A002.A01();
                    }
                }
            }
        }
        return A00;
    }

    @AutoGeneratedAccessMethod
    public static final C01640Kg A03(AbstractC02990bJ r1) {
        return (C01640Kg) AnonymousClass13m.A00(49, r1);
    }

    @AutoGeneratedAccessMethod
    public static final C01650Kl A05(AbstractC02990bJ r1) {
        return (C01650Kl) AnonymousClass13m.A00(123, r1);
    }

    @AutoGeneratedFactoryMethod
    public static final C01640Kg A02(AbstractC02990bJ r3) {
        return new C01640Kg(C01340Gg.A02(r3), A05(r3));
    }

    @AutoGeneratedFactoryMethod
    public static final C01650Kl A04(AbstractC02990bJ r1) {
        return new C01650Kl(C01340Gg.A02(r1));
    }
}
