package com.oculus.unifiedtelemetry.collectors;

import X.I0;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public abstract class CollectorsModule extends I0 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForCollectorsModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_AppCrashCollector_ULSEP_BINDING_ID = 72;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_AudioCollector_ULSEP_BINDING_ID = 2094;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_CollectorsControl_ULSEP_BINDING_ID = 61;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_FirstPartyAppsMemStatsCollector_ULSEP_BINDING_ID = 52;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_FuelGaugeCollector_ULSEP_BINDING_ID = 38;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_LowBatteryCheckScheduler_ULSEP_BINDING_ID = 128;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_NetworkStatsCollector_ULSEP_BINDING_ID = 21;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_PowerCollector_ULSEP_BINDING_ID = 76;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_StorageStatsCollector_ULSEP_BINDING_ID = 68;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_ThermalCollector_ULSEP_BINDING_ID = 94;
        public static final int _UL__ULSEP_com_oculus_unifiedtelemetry_collectors_WiFiCollector_ULSEP_BINDING_ID = 43;
        public static final int _UL__ULSEP_java_util_Set_ULLT_com_oculus_unifiedtelemetry_collectors_ICollectorWithScreenEvents_ULGT__ULSEP_BINDING_ID = 13;
        public static final int _UL__ULSEP_java_util_Set_ULLT_com_oculus_unifiedtelemetry_collectors_ICollector_ULGT__ULSEP_BINDING_ID = 93;
    }
}
