package com.oculus.app.standalone;

import X.AnonymousClass0J5;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class StandaloneApplicationLikeModule extends AnonymousClass0J5 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForStandaloneApplicationLikeModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_app_standalone_StandaloneApplicationLike_ULSEP_BINDING_ID = 518;
        public static final int _UL__ULSEP_com_oculus_base_app_ApplicationLike_ULSEP_BINDING_ID = 292;
    }
}
