package com.oculus.appmanager.installer.service;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import com.facebook.debug.log.BLog;
import com.facebook.inject.BundledAndroidModule;
import com.facebook.inject.InjectionContext;
import com.facebook.inject.InjectorLike;
import com.facebook.inject.Lazy;
import com.facebook.inject.UltralightLazy;
import com.facebook.inject.UltralightProvider;
import com.facebook.inject.UnsafeContextInjection;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Eager;
import com.facebook.ultralight.Inject;
import com.facebook.ultralight.UL;
import com.oculus.appmanager.installer.service.InstallerServiceModule;
import com.oculus.device.DeviceType;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_BINDING_ID", "_UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_BINDING_ID"})
public class DozeDelayHelper {
    private static final String ACTION_DELAY_DOZE = "delay_doze";
    private static final String DOZE_DELAY_SERVICE_CLASS = "com.oculus.appmanager.installer.service.DozeDelayService";
    private static final String TAG = "DozeDelayHelper";
    private InjectionContext _UL_mInjectionContext;
    @UnsafeContextInjection
    @Inject
    @Eager
    private final Context mContext;

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_appmanager_installer_service_DozeDelayHelper_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(InstallerServiceModule.UL_id._UL__ULSEP_com_oculus_appmanager_installer_service_DozeDelayHelper_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final DozeDelayHelper _UL__ULSEP_com_oculus_appmanager_installer_service_DozeDelayHelper_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (DozeDelayHelper) UL.factorymap.get(InstallerServiceModule.UL_id._UL__ULSEP_com_oculus_appmanager_installer_service_DozeDelayHelper_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final DozeDelayHelper _UL__ULSEP_com_oculus_appmanager_installer_service_DozeDelayHelper_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return new DozeDelayHelper(injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_appmanager_installer_service_DozeDelayHelper_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(InstallerServiceModule.UL_id._UL__ULSEP_com_oculus_appmanager_installer_service_DozeDelayHelper_ULSEP_BINDING_ID, injectorLike);
    }

    @Inject
    public DozeDelayHelper(InjectorLike injectorLike) {
        this._UL_mInjectionContext = new InjectionContext(1, injectorLike);
        this.mContext = BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike);
    }

    public void delayDoze() {
        if (!DeviceType.is6DOF()) {
            BLog.w(TAG, "Delay Doze is not supported");
            return;
        }
        BLog.i(TAG, "Delaying Doze");
        Intent intent = new Intent();
        intent.setComponent(new ComponentName(this.mContext, DOZE_DELAY_SERVICE_CLASS));
        intent.setAction(ACTION_DELAY_DOZE);
        this.mContext.startService(intent);
    }
}
