package com.oculus.downloader.init;

import com.facebook.inject.FbInjector;
import com.facebook.inject.InjectionContext;
import com.facebook.inject.InjectorLike;
import com.facebook.inject.Lazy;
import com.facebook.inject.UltralightLazy;
import com.facebook.inject.UltralightProvider;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.facebook.ultralight.UL;
import com.oculus.common.init.INeedInit;
import com.oculus.downloader.init.DownloaderInitModule;
import com.oculus.downloader.progress.DownloadProgressTracker;
import com.oculus.downloader.progress.DownloaderProgressModule;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_com_oculus_downloader_progress_DownloadProgressTracker_ULSEP_BINDING_ID"})
public class DownloaderInit implements INeedInit {
    private InjectionContext _UL_mInjectionContext;

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_downloader_init_DownloaderInit_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(DownloaderInitModule.UL_id._UL__ULSEP_com_oculus_downloader_init_DownloaderInit_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_downloader_init_DownloaderInit_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(DownloaderInitModule.UL_id._UL__ULSEP_com_oculus_downloader_init_DownloaderInit_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final DownloaderInit _UL__ULSEP_com_oculus_downloader_init_DownloaderInit_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (DownloaderInit) UL.factorymap.get(DownloaderInitModule.UL_id._UL__ULSEP_com_oculus_downloader_init_DownloaderInit_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final DownloaderInit _UL__ULSEP_com_oculus_downloader_init_DownloaderInit_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return new DownloaderInit(injectorLike);
    }

    @Inject
    public DownloaderInit(InjectorLike injectorLike) {
        this._UL_mInjectionContext = new InjectionContext(0, injectorLike);
    }

    @Override // com.oculus.common.init.INeedInit
    public void init() {
        ((DownloadProgressTracker) FbInjector.localInstance(DownloaderProgressModule.UL_id._UL__ULSEP_com_oculus_downloader_progress_DownloadProgressTracker_ULSEP_BINDING_ID, this._UL_mInjectionContext)).startTrackingChangesIfNeeded();
    }
}
