package com.oculus.time;

import X.AbstractC03180ld;
import X.AnonymousClass0Hr;
import X.AnonymousClass0VC;
import X.AnonymousClass0lg;
import X.AnonymousClass1TK;
import android.os.SystemClock;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import javax.inject.Provider;

@Dependencies({})
public class Clock {
    @AutoGeneratedAccessMethod
    public static final AbstractC03180ld _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_time_Clock_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0Hr.A00(57, r1);
    }

    @AutoGeneratedAccessMethod
    public static final Clock _UL__ULSEP_com_oculus_time_Clock_ULSEP_ACCESS_METHOD(AnonymousClass0lg r2) {
        return (Clock) AnonymousClass1TK.A00(57, r2, null);
    }

    @AutoGeneratedFactoryMethod
    public static final Clock _UL__ULSEP_com_oculus_time_Clock_ULSEP_FACTORY_METHOD(AnonymousClass0lg r0, Object obj) {
        return new Clock();
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_time_Clock_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0VC.A00(57, r1);
    }

    public long elapsedRealtime() {
        return SystemClock.elapsedRealtime();
    }

    public long now() {
        return System.currentTimeMillis();
    }

    public long uptime() {
        return SystemClock.uptimeMillis();
    }
}
