package com.oculus.http.useragent;

import X.AbstractC0096Hu;
import X.AbstractC0247Xu;
import X.AnonymousClass8f;
import X.C0515sp;
import X.I0;
import com.facebook.common.stringformat.StringFormatUtil;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.inject.ProviderMethod;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public abstract class UserAgentModule extends I0 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForUserAgentModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_http_useragent_UserAgentFactory_ULSEP_BINDING_ID = 6;
        public static final int _UL__ULSEP_java_lang_String_ULSEP_com_oculus_http_useragent_AppNameInUserAgent_ULSEP_BINDING_ID = 24;
        public static final int _UL__ULSEP_java_lang_String_ULSEP_com_oculus_http_useragent_UserAgentAppVersionMap_ULSEP_BINDING_ID = 27;
        public static final int _UL__ULSEP_java_lang_String_ULSEP_com_oculus_http_useragent_UserAgentString_ULSEP_BINDING_ID = 67;
    }

    @AutoGeneratedAccessMethod
    public static final String A01(AbstractC0247Xu xu) {
        return (String) C0515sp.A00(24, xu);
    }

    @AutoGeneratedAccessMethod
    public static final String A02(AbstractC0247Xu xu) {
        return (String) C0515sp.A00(67, xu);
    }

    /* JADX DEBUG: Multi-variable search result rejected for r1v6, resolved type: java.util.Map<java.lang.String, java.lang.String> */
    /* JADX WARN: Multi-variable type inference failed */
    @ProviderMethod
    @UserAgentString
    public static String A04(UserAgentFactory userAgentFactory) {
        UserAgentBuilder userAgentBuilder = new UserAgentBuilder(userAgentFactory.mContext);
        userAgentBuilder.mHttpAgent = System.getProperty("http.agent");
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_APP_NAME, userAgentFactory.mAppNameInUserAgent);
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_APP_VERSION, userAgentFactory.mPackageInfo.versionName);
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_BUILD_VERSION, String.valueOf(userAgentFactory.mPackageInfo.versionCode));
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_LOCALE, userAgentFactory.mLocaleProvider.get().toString());
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_PACKAGE_NAME, userAgentFactory.mContext.getPackageName());
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_APP_VERSION_MAP, AbstractC0096Hu.A03(0, 27, userAgentFactory._UL_mInjectionContext));
        String str = userAgentBuilder.mHttpAgent;
        if (str != null) {
            StringBuilder sb = new StringBuilder();
            sb.append(str);
            sb.append(" [");
            AnonymousClass8f<String> A0D = UserAgentBuilder.FIXED_ORDER_KEYS.iterator();
            while (A0D.hasNext()) {
                String next = A0D.next();
                if (userAgentBuilder.mProperties.get(next) != null) {
                    sb.append(StringFormatUtil.formatStrLocaleSafe("%s/%s;", next, UserAgentBuilder.A00(userAgentBuilder.mProperties.get(next))));
                } else {
                    throw null;
                }
            }
            AnonymousClass8f<String> A0D2 = UserAgentBuilder.OPTIONAL_KEYS.iterator();
            while (A0D2.hasNext()) {
                String next2 = A0D2.next();
                sb.append(StringFormatUtil.formatStrLocaleSafe("%s/%s;", next2, UserAgentBuilder.A00(userAgentBuilder.mProperties.get(next2))));
            }
            AnonymousClass8f<String> A0D3 = UserAgentBuilder.OPTIONAL_KEYS_SKIP_IF_NULL.iterator();
            while (A0D3.hasNext()) {
                String next3 = A0D3.next();
                if (userAgentBuilder.mProperties.get(next3) != null) {
                    sb.append(StringFormatUtil.formatStrLocaleSafe("%s/%s;", next3, UserAgentBuilder.A00(userAgentBuilder.mProperties.get(next3))));
                }
            }
            sb.append("]");
            return sb.toString();
        }
        throw null;
    }

    @AutoGeneratedFactoryMethod
    public static final String A03(AbstractC0247Xu xu) {
        return A04(UserAgentFactory.A00(xu));
    }

    @AutoGeneratedFactoryMethod
    public static final String A00() {
        return "";
    }
}
