package com.oculus.locale;

import X.AbstractC0031Bc;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class LocaleModule extends AbstractC0031Bc {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForLocaleModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_java_util_Locale_ULSEP_BINDING_ID = 68;
    }
}
