package com.oculus.horizon.platformsdk.dumper;

import X.AbstractC03180ld;
import X.AnonymousClass0Hr;
import X.AnonymousClass0RE;
import X.AnonymousClass0VC;
import X.AnonymousClass0lg;
import X.AnonymousClass1TK;
import X.C06041Om;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import java.io.PrintStream;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_ForAppContext_ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_horizon_platformsdk_DeeplinkIntentUtils_ULSEP_BINDING_ID"})
public class DeeplinkDumperPlugin {
    public static final String NAME = "deeplink";
    public AnonymousClass0RE _UL_mInjectionContext;

    public String getName() {
        return "deeplink";
    }

    @AutoGeneratedAccessMethod
    public static final AbstractC03180ld _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_horizon_platformsdk_dumper_DeeplinkDumperPlugin_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0Hr.A00(77, r1);
    }

    @AutoGeneratedAccessMethod
    public static final DeeplinkDumperPlugin _UL__ULSEP_com_oculus_horizon_platformsdk_dumper_DeeplinkDumperPlugin_ULSEP_ACCESS_METHOD(AnonymousClass0lg r2) {
        return (DeeplinkDumperPlugin) AnonymousClass1TK.A00(77, r2, null);
    }

    @AutoGeneratedFactoryMethod
    public static final DeeplinkDumperPlugin _UL__ULSEP_com_oculus_horizon_platformsdk_dumper_DeeplinkDumperPlugin_ULSEP_FACTORY_METHOD(AnonymousClass0lg r1, Object obj) {
        return new DeeplinkDumperPlugin(r1);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_horizon_platformsdk_dumper_DeeplinkDumperPlugin_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0VC.A00(77, r1);
    }

    private void doUsageCommand(PrintStream printStream) {
        printStream.format("Usage: %s <package> <deeplink messsage>", "deeplink");
        printStream.println();
    }

    public void dump(C06041Om r3) {
        throw new NullPointerException("getStdout");
    }

    @Inject
    public DeeplinkDumperPlugin(AnonymousClass0lg r3) {
        this._UL_mInjectionContext = new AnonymousClass0RE(2, r3);
    }
}
