package com.oculus.directboot;

import X.AbstractC0096Hu;
import X.AbstractC0247Xu;
import X.QC;
import android.annotation.TargetApi;
import android.content.Context;
import android.os.UserManager;
import com.facebook.acra.util.minidump.MinidumpReader;
import com.facebook.infer.annotation.Nullsafe;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;

@Dependencies({"_UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_ForAppContext_ULSEP_BINDING_ID"})
@TargetApi(MinidumpReader.MODULE_LIST_OFFSET)
@Nullsafe(Nullsafe.Mode.LOCAL)
public class DirectBootUtils {
    public QC _UL_mInjectionContext;

    public final boolean A01() {
        UserManager userManager = (UserManager) ((Context) AbstractC0096Hu.A03(0, 3, this._UL_mInjectionContext)).getSystemService(UserManager.class);
        if (userManager == null || userManager.isUserUnlocked()) {
            return true;
        }
        return false;
    }

    @AutoGeneratedFactoryMethod
    public static final DirectBootUtils A00(AbstractC0247Xu xu) {
        return new DirectBootUtils(xu);
    }

    @Inject
    public DirectBootUtils(AbstractC0247Xu xu) {
        this._UL_mInjectionContext = new QC(1, xu);
    }
}
