package com.oculus.horizon.service;

import X.AbstractC06640p5;
import X.AnonymousClass0J2;
import X.AnonymousClass0NO;
import X.AnonymousClass0QC;
import X.AnonymousClass0p1;
import X.AnonymousClass117;
import X.C003008y;
import X.C01020Iw;
import X.C03080c5;
import X.C08780ya;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.oculus.logging.utils.Event;
import com.oculus.logging.utils.EventManager;
import javax.annotation.Nullable;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_com_oculus_logging_utils_EventManager_ULSEP_BINDING_ID"})
public class ServiceLogger {
    public static final String EVENT_ENTITLEMENT_CHECK = "moonlight_entitlement_check";
    public static final String EVENT_PLATFORM_SDK_FIRST_PARTY_LOGGING = "oculus_first_party_app_event";
    public static final String EVENT_PLATFORM_SDK_LOGGING = "oculus_mobile_platform_sdk";
    public static final String EVENT_SDK_LOGGING = "moonlight_sdk";
    public static final C08780ya GSON = new C08780ya();
    public static final String KEY_MESSAGE = "message";
    public static final String KEY_SDK_APP_ID = "platform_app_id";
    public static final String KEY_SDK_APP_PACKAGE = "sdk_app_package";
    public static final String KEY_SDK_LOGS = "sdk_logs";
    public static final Class<?> TAG = ServiceLogger.class;
    public AnonymousClass0QC _UL_mInjectionContext;

    public final class FirstPartyAppEvent {
        @Nullable
        public final String event_type;

        public FirstPartyAppEvent() {
        }
    }

    @AutoGeneratedAccessMethod
    public static final AnonymousClass0p1 _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_horizon_service_ServiceLogger_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C003008y(212, r2);
    }

    @AutoGeneratedAccessMethod
    public static final ServiceLogger _UL__ULSEP_com_oculus_horizon_service_ServiceLogger_ULSEP_ACCESS_METHOD(AbstractC06640p5 r1) {
        return (ServiceLogger) AnonymousClass117.A00(212, r1);
    }

    @AutoGeneratedFactoryMethod
    public static final ServiceLogger _UL__ULSEP_com_oculus_horizon_service_ServiceLogger_ULSEP_FACTORY_METHOD(AbstractC06640p5 r1) {
        return new ServiceLogger(r1);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_horizon_service_ServiceLogger_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C01020Iw(212, r2);
    }

    private void reportPlatformSDKLogsHelper(String str, String str2, String str3, String str4) {
        Event A23 = ((EventManager) AnonymousClass0J2.A03(0, 242, this._UL_mInjectionContext)).A23(str, str4, false);
        A23.A15(KEY_SDK_APP_PACKAGE, str3);
        A23.A15(KEY_SDK_APP_ID, str2);
        A23.A5L();
    }

    public void reportEntitlementCheck(String str, String str2) {
        Event A22 = ((EventManager) AnonymousClass0J2.A03(0, 242, this._UL_mInjectionContext)).A22(EVENT_ENTITLEMENT_CHECK);
        A22.A15(KEY_SDK_APP_PACKAGE, str);
        A22.A15("message", str2);
        A22.A5L();
    }

    public void reportLowLatencySDKEvent(String str, @Nullable String str2, String str3, String str4) {
        ((EventManager) AnonymousClass0J2.A03(0, 242, this._UL_mInjectionContext)).A23(str, str4, true).A5L();
    }

    public void reportPlatformSDKFirstPartyAppLogs(String str, String str2, String str3) {
        String str4;
        try {
            str4 = ((FirstPartyAppEvent) GSON.A05(str3, FirstPartyAppEvent.class)).event_type;
            if (str4 == null || str4.isEmpty()) {
                throw new IllegalArgumentException("Missing or empty event_type");
            }
            reportPlatformSDKLogsHelper(str4, str, str2, str3);
        } catch (C03080c5 | IllegalArgumentException e) {
            AnonymousClass0NO.A03(ServiceLogger.class, "Unable to extract valid event_type from payload", e);
            str4 = EVENT_PLATFORM_SDK_FIRST_PARTY_LOGGING;
        }
    }

    public void reportPlatformSDKLogs(String str, String str2, String str3) {
        reportPlatformSDKLogsHelper(EVENT_PLATFORM_SDK_LOGGING, str, str2, str3);
    }

    public void reportSDKEvent(String str, @Nullable String str2, String str3, String str4) {
        ((EventManager) AnonymousClass0J2.A03(0, 242, this._UL_mInjectionContext)).A23(str, str4, false).A5L();
    }

    public void reportSDKLogs(@Nullable String str, String str2, String str3) {
        if (str == null) {
            str = "0";
        }
        Event A22 = ((EventManager) AnonymousClass0J2.A03(0, 242, this._UL_mInjectionContext)).A22(EVENT_SDK_LOGGING);
        A22.A15(KEY_SDK_APP_PACKAGE, str2);
        A22.A15(KEY_SDK_APP_ID, str);
        A22.A15(KEY_SDK_LOGS, str3);
        A22.A5L();
    }

    @Inject
    public ServiceLogger(AbstractC06640p5 r3) {
        this._UL_mInjectionContext = new AnonymousClass0QC(1, r3);
    }
}
