package X;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

public final class JX {
    public static final Set A00 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.adsmanager", "com.facebook.akira", "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.assistantplayground", "com.facebook.bishop", "com.facebook.creatorstudio", "com.facebook.daykira", "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.facebook.katana", "com.facebook.orca", "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.monza", "com.novi.wallet.validation", "com.novi.wallet.prodinternal", "com.novi.wallet", "com.oculus.alpenglow", "com.oculus.vrshell", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.gemini.upload", "com.oculus.vrshell.home", "com.oculus.ocms", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater", "com.facebook.pages.app", "com.facebook.bonfire", "com.facebook.study", "com.instagram.threadsapp", "com.facebook.wakizashi", "com.whatsapp", "com.whatsapp.w4b", "com.facebook.work", "com.facebook.workdev", "com.facebook.workchat")));
    public static final Set A01 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.adsmanager", "com.facebook.akira", "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.assistantplayground", "com.facebook.bishop", "com.facebook.creatorstudio", "com.facebook.daykira", "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.facebook.katana", "com.facebook.orca", "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.monza", "com.novi.wallet.validation", "com.novi.wallet.prodinternal", "com.novi.wallet", "com.oculus.alpenglow", "com.oculus.vrshell", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.gemini.upload", "com.oculus.vrshell.home", "com.oculus.ocms", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater", "com.facebook.pages.app", "com.facebook.bonfire", "com.facebook.study", "com.instagram.threadsapp", "com.facebook.wakizashi", "com.whatsapp", "com.whatsapp.w4b")));
    public static final Set A02 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.adsmanager", "com.facebook.akira", "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.assistantplayground", "com.facebook.bishop", "com.facebook.creatorstudio", "com.facebook.daykira", "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.facebook.katana", "com.facebook.orca", "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.monza", "com.novi.wallet.validation", "com.novi.wallet.prodinternal", "com.novi.wallet", "com.oculus.alpenglow", "com.oculus.vrshell", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.gemini.upload", "com.oculus.vrshell.home", "com.oculus.ocms", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater", "com.facebook.pages.app", "com.facebook.bonfire", "com.facebook.study", "com.instagram.threadsapp", "com.facebook.wakizashi", "com.whatsapp", "com.whatsapp.w4b")));
    public static final Set A03 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.globalsecurity", "com.facebook.viewpoints")));
    public static final Set A04 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.instagram.direct", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.instagram.threadsapp")));
    public static final Set A05 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.oculus.assistant", "com.oculus.companion.server", "com.oculus.alpenglow", "com.oculus.vrshell.home", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.nux.ota", "com.oculus.ocms", "com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater")));
    public static final Set A06 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.work", "com.facebook.workdev", "com.facebook.workchat")));
}
