package X;

import com.facebook.infer.annotation.Nullsafe;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;

@InjectorModule
@Nullsafe(Nullsafe.Mode.LOCAL)
/* renamed from: X.8l  reason: invalid class name and case insensitive filesystem */
public final class C00228l extends I0 {
    public static volatile K8 A00;

    @AutoGeneratedAccessMethod
    public static final K8 A00(AbstractC0247Xu xu) {
        return (K8) C0515sp.A00(87, xu);
    }

    @AutoGeneratedFactoryMethod
    public static final K8 A01(AbstractC0247Xu xu) {
        long j;
        if (A00 == null) {
            synchronized (K8.class) {
                Pj A002 = Pj.A00(A00, xu);
                if (A002 != null) {
                    try {
                        K9 A03 = A03(xu.getApplicationInjector());
                        String str = A03.A00;
                        K9.A00(A03, "com.facebook.versioncontrol.revision", str);
                        K9.A00(A03, "com.facebook.versioncontrol.branch", str);
                        String A003 = K9.A00(A03, "com.facebook.build_time", str);
                        if (A003 == null || !K9.A03.matcher(A003).matches()) {
                            j = 0;
                        } else {
                            j = Long.parseLong(A003.substring(0, A003.length() - 1));
                            DateFormat dateTimeInstance = DateFormat.getDateTimeInstance(1, 0, Locale.US);
                            dateTimeInstance.setTimeZone(TimeZone.getTimeZone("PST8PDT"));
                            dateTimeInstance.format(new Date(j));
                        }
                        A00 = new K8(j);
                    } finally {
                        A002.A01();
                    }
                }
            }
        }
        return A00;
    }

    @AutoGeneratedAccessMethod
    public static final K9 A03(AbstractC0247Xu xu) {
        return (K9) C0515sp.A00(57, xu);
    }

    @AutoGeneratedAccessMethod
    public static final KE A05(AbstractC0247Xu xu) {
        return (KE) C0515sp.A00(123, xu);
    }

    @AutoGeneratedFactoryMethod
    public static final K9 A02(AbstractC0247Xu xu) {
        return new K9(C00208d.A02(xu), A05(xu));
    }

    @AutoGeneratedFactoryMethod
    public static final KE A04(AbstractC0247Xu xu) {
        return new KE(C00208d.A02(xu));
    }
}
