package X;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

/* renamed from: X.hz  reason: case insensitive filesystem */
public final class C0433hz {
    public static final AbstractC0131Ob<AtomicBoolean> A00;
    public static final AbstractC0131Ob<AtomicInteger> A01;
    public static final AbstractC0131Ob<AtomicIntegerArray> A02;
    public static final AbstractC0131Ob<BigDecimal> A03 = new C0154Sp();
    public static final AbstractC0131Ob<BigInteger> A04 = new C0153So();
    public static final AbstractC0131Ob<BitSet> A05;
    public static final AbstractC0131Ob<Boolean> A06;
    public static final AbstractC0131Ob<Boolean> A07 = new SD();
    public static final AbstractC0131Ob<Number> A08;
    public static final AbstractC0131Ob<Calendar> A09;
    public static final AbstractC0131Ob<Character> A0A;
    public static final AbstractC0131Ob<Class> A0B;
    public static final AbstractC0131Ob<Currency> A0C;
    public static final AbstractC0131Ob<Number> A0D = new C0158St();
    public static final AbstractC0131Ob<Number> A0E = new C0159Su();
    public static final AbstractC0131Ob<InetAddress> A0F;
    public static final AbstractC0131Ob<Number> A0G;
    public static final AbstractC0131Ob<M4> A0H;
    public static final AbstractC0131Ob<Locale> A0I;
    public static final AbstractC0131Ob<Number> A0J = new C0160Sv();
    public static final AbstractC0131Ob<Number> A0K;
    public static final AbstractC0131Ob<Number> A0L;
    public static final AbstractC0131Ob<String> A0M;
    public static final AbstractC0131Ob<StringBuffer> A0N;
    public static final AbstractC0131Ob<StringBuilder> A0O;
    public static final AbstractC0131Ob<URI> A0P;
    public static final AbstractC0131Ob<URL> A0Q;
    public static final AbstractC0131Ob<UUID> A0R;
    public static final AbstractC0132Os A0S;
    public static final AbstractC0132Os A0T;
    public static final AbstractC0132Os A0U;
    public static final AbstractC0132Os A0V;
    public static final AbstractC0132Os A0W;
    public static final AbstractC0132Os A0X;
    public static final AbstractC0132Os A0Y;
    public static final AbstractC0132Os A0Z;
    public static final AbstractC0132Os A0a;
    public static final AbstractC0132Os A0b;
    public static final AbstractC0132Os A0c = new SZ();
    public static final AbstractC0132Os A0d;
    public static final AbstractC0132Os A0e;
    public static final AbstractC0132Os A0f;
    public static final AbstractC0132Os A0g;
    public static final AbstractC0132Os A0h;
    public static final AbstractC0132Os A0i;
    public static final AbstractC0132Os A0j;
    public static final AbstractC0132Os A0k;
    public static final AbstractC0132Os A0l;
    public static final AbstractC0132Os A0m = new Se();
    public static final AbstractC0132Os A0n;
    public static final AbstractC0132Os A0o;
    public static final AbstractC0132Os A0p;

    static {
        Tx tx = new Tx(new Sm());
        A0B = tx;
        A0a = new SX(Class.class, tx);
        Tx tx2 = new Tx(new C0143Sa());
        A05 = tx2;
        A0V = new SX(BitSet.class, tx2);
        SG sg = new SG();
        A06 = sg;
        A0W = new SW(Boolean.TYPE, Boolean.class, sg);
        SC sc = new SC();
        A08 = sc;
        A0X = new SW(Byte.TYPE, Byte.class, sc);
        SA sa = new SA();
        A0L = sa;
        A0i = new SW(Short.TYPE, Short.class, sa);
        S9 s9 = new S9();
        A0G = s9;
        A0e = new SW(Integer.TYPE, Integer.class, s9);
        Tx tx3 = new Tx(new S8());
        A01 = tx3;
        A0U = new SX(AtomicInteger.class, tx3);
        Tx tx4 = new Tx(new S6());
        A00 = tx4;
        A0S = new SX(AtomicBoolean.class, tx4);
        Tx tx5 = new Tx(new C0161Sw());
        A02 = tx5;
        A0T = new SX(AtomicIntegerArray.class, tx5);
        C0157Ss ss = new C0157Ss();
        A0K = ss;
        A0h = new SX(Number.class, ss);
        C0156Sr sr = new C0156Sr();
        A0A = sr;
        A0Z = new SW(Character.TYPE, Character.class, sr);
        C0155Sq sq = new C0155Sq();
        A0M = sq;
        A0l = new SX(String.class, sq);
        C0152Sn sn = new C0152Sn();
        A0O = sn;
        A0k = new SX(StringBuilder.class, sn);
        C0151Sl sl = new C0151Sl();
        A0N = sl;
        A0j = new SX(StringBuffer.class, sl);
        C0150Sk sk = new C0150Sk();
        A0Q = sk;
        A0o = new SX(URL.class, sk);
        Sj sj = new Sj();
        A0P = sj;
        A0n = new SX(URI.class, sj);
        C0149Si si = new C0149Si();
        A0F = si;
        A0d = new SH(InetAddress.class, si);
        C0148Sh sh = new C0148Sh();
        A0R = sh;
        A0p = new SX(UUID.class, sh);
        Tx tx6 = new Tx(new C0147Sg());
        A0C = tx6;
        A0b = new SX(Currency.class, tx6);
        C0145Sd sd = new C0145Sd();
        A09 = sd;
        A0Y = new SK(sd);
        C0144Sc sc2 = new C0144Sc();
        A0I = sc2;
        A0g = new SX(Locale.class, sc2);
        Sb sb = new Sb();
        A0H = sb;
        A0f = new SH(M4.class, sb);
    }
}
