package com.facebook.mobileconfig.factory.module;

import com.facebook.infer.annotation.Nullsafe;
import com.facebook.inject.AbstractLibraryModule;
import com.facebook.inject.ApplicationScopeClassInit;
import com.facebook.inject.ApplicationScoped;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.Binder;
import com.facebook.inject.BundledAndroidModule;
import com.facebook.inject.InjectorLike;
import com.facebook.inject.InjectorModule;
import com.facebook.inject.Lazy;
import com.facebook.inject.ProviderMethod;
import com.facebook.inject.UltralightLazy;
import com.facebook.inject.UltralightProvider;
import com.facebook.mobileconfig.factory.MobileConfig;
import com.facebook.mobileconfig.interfaces.MobileConfigInitInterface;
import com.facebook.mobileconfig.interfaces.MobileConfigInterfacesModule;
import com.facebook.mobileconfig.interfaces.MobileConfigServiceHelperInterface;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import com.facebook.ultralight.UL;
import com.google.inject.Key;
import java.lang.annotation.Annotation;
import javax.inject.Provider;

@InjectorModule
@Nullsafe(Nullsafe.Mode.LOCAL)
public class MobileConfigFactoryModule extends AbstractLibraryModule {
    private static volatile MobileConfig _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_INSTANCE;
    private static final Object _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_LOCK = new Object();
    private static volatile MobileConfig _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_INSTANCE;
    private static final Object _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_LOCK = new Object();
    private static volatile MobileConfigInitInterface _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_INSTANCE;
    private static volatile MobileConfigServiceHelperInterface _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_INSTANCE;

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(MobileConfig.class)));
        public static final int _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(MobileConfig.class, (Class<? extends Annotation>) SessionlessMC.class)));
        public static final int _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(MobileConfigInitInterface.class)));
        public static final int _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(MobileConfigServiceHelperInterface.class)));
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_facebook_mobileconfig_factory_MobileConfig_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedBinder
    static class AutoGeneratedBindingsForMobileConfigFactoryModule {
        AutoGeneratedBindingsForMobileConfigFactoryModule() {
        }

        static void bind(Binder binder) {
            if (!UL.USE_STATIC_DI) {
                binder.require(BundledAndroidModule.class);
                binder.require(MobileConfigInterfacesModule.class);
                binder.bindDefault(MobileConfig.class).annotatedWith(SessionlessMC.class).toProvider(new MobileConfig_com_facebook_mobileconfig_factory_module_SessionlessMCMethodAutoProvider()).in(ApplicationScoped.class);
                binder.bindDefault(MobileConfig.class).toProvider(new MobileConfigMethodAutoProvider()).in(ApplicationScoped.class);
                binder.bindDefault(MobileConfigInitInterface.class).toProvider(new MobileConfigInitInterfaceMethodAutoProvider()).in(ApplicationScoped.class);
                binder.bindDefault(MobileConfigServiceHelperInterface.class).toProvider(new MobileConfigServiceHelperInterfaceMethodAutoProvider()).in(ApplicationScoped.class);
            }
        }
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_facebook_mobileconfig_factory_MobileConfig_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_facebook_mobileconfig_factory_MobileConfig_ULGT__ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final MobileConfig _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (MobileConfig) UL.factorymap.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final MobileConfig _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_INSTANCE == null) {
            synchronized (_UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_LOCK) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        injectorLike.getApplicationInjector();
                        _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_INSTANCE = provideMobileConfig();
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final MobileConfig _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (MobileConfig) UL.factorymap.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final MobileConfig _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_INSTANCE == null) {
            synchronized (_UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_LOCK) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        injectorLike.getApplicationInjector();
                        _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_INSTANCE = provideSessionlessMobileConfig();
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final MobileConfigInitInterface _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (MobileConfigInitInterface) UL.factorymap.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final MobileConfigInitInterface _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_INSTANCE == null) {
            synchronized (MobileConfigInitInterface.class) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        injectorLike.getApplicationInjector();
                        _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_INSTANCE = provideMobileConfigInitInterface();
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final MobileConfigServiceHelperInterface _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (MobileConfigServiceHelperInterface) UL.factorymap.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final MobileConfigServiceHelperInterface _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_INSTANCE == null) {
            synchronized (MobileConfigServiceHelperInterface.class) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        injectorLike.getApplicationInjector();
                        _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_INSTANCE = provideMobileConfigServiceHelperInterface();
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_facebook_mobileconfig_factory_MobileConfig_ULGT__ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_com_facebook_mobileconfig_factory_module_SessionlessMC_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigInitInterface_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_com_facebook_mobileconfig_interfaces_MobileConfigServiceHelperInterface_ULSEP_BINDING_ID, injectorLike);
    }

    @ApplicationScoped
    @ProviderMethod(asDefault = true)
    static MobileConfig provideMobileConfig() {
        return new MobileConfigEmptyImpl();
    }

    @SessionlessMC
    @ApplicationScoped
    @ProviderMethod(asDefault = true)
    static MobileConfig provideSessionlessMobileConfig() {
        return new MobileConfigEmptyImpl();
    }

    @ApplicationScoped
    @ProviderMethod(asDefault = true)
    static MobileConfigInitInterface provideMobileConfigInitInterface() {
        return new MobileConfigEmptyInitImpl();
    }

    @ApplicationScoped
    @ProviderMethod(asDefault = true)
    static MobileConfigServiceHelperInterface provideMobileConfigServiceHelperInterface() {
        return new MobileConfigEmptyServiceHelperImpl();
    }
}
