package com.oculus.alpenglow;

import X.AbstractC01750Lk;
import X.C02530aB;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import com.oculus.mobileconfig.init.MobileConfigInitOptions;

@InjectorModule
public class AlpenglowModule extends AbstractC01750Lk {
    public static volatile C02530aB _UL__ULSEP_com_fasterxml_jackson_databind_ObjectMapper_ULSEP_INSTANCE;
    public static volatile MobileConfigInitOptions _UL__ULSEP_com_oculus_mobileconfig_init_MobileConfigInitOptions_ULSEP_INSTANCE;

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForAlpenglowModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_fasterxml_jackson_databind_ObjectMapper_ULSEP_BINDING_ID = 62;
        public static final int _UL__ULSEP_com_oculus_mobileconfig_init_MobileConfigInitOptions_ULSEP_BINDING_ID = 126;
    }
}
