package com.oculus.util.constants;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;

public class PlatformPluginConstants {
    public static final List<String> ABUSE_CAPTURE_WHITELIST_PACKAGES = Arrays.asList("com.oculus.venues", DAIS_PACKAGE_NAME);
    public static final String COMPANION_SERVER_PACKAGE_NAME = "com.oculus.companion.server";
    public static final String DAIS_PACKAGE_NAME = "com.oculus.dais";
    public static final String EXPLORE_APP_ID = "2646830762095036";
    public static final String EXPLORE_PACKAGE_NAME = "com.oculus.explore";
    public static final String FB_HORIZON_DEMO_PACKAGE_NAME = "com.facebook.together.together.demo";
    public static final String FB_HORIZON_DEV_PACKAGE_NAME = "com.facebook.together.together.dev";
    public static final String FB_HORIZON_MAIN_LKG_PACKAGE_NAME = "com.facebook.together.together.main_lkg";
    public static final String FB_HORIZON_MAIN_NIGHTLY_PACKAGE_NAME = "com.facebook.together.together.main_nightly";
    public static final String FB_HORIZON_MAIN_STABLE_PACKAGE_NAME = "com.facebook.together.together.main_stable";
    public static final String FB_HORIZON_MAIN_TEST_PACKAGE_NAME = "com.facebook.together.together.main_test";
    public static final String FB_HORIZON_PACKAGE_NAME = "com.facebook.together.together";
    public static final String FB_HORIZON_PLAYTEST_PRIME_PACKAGE_NAME = "com.facebook.together.together.playtest_prime";
    public static final String FB_HORIZON_PLAYTEST_QA_PACKAGE_NAME = "com.facebook.together.together.playtest_qa";
    public static final String FB_HORIZON_RELEASE_LKG_PACKAGE_NAME = "com.facebook.together.together.release_lkg";
    public static final String FB_HORIZON_RELEASE_NIGHTLY_PACKAGE_NAME = "com.facebook.together.together.release_nightly";
    public static final String FB_HORIZON_RELEASE_PACKAGE_NAME = "com.facebook.horizon";
    public static final String FB_HORIZON_RELEASE_RC_PACKAGE_NAME = "com.facebook.together.together.release_rc";
    public static final String FB_HORIZON_STABLE_PACKAGE_NAME = "com.facebook.together.together.stable";
    public static final String FB_HORIZON_STAGING_PACKAGE_NAME = "com.facebook.together.together.staging";
    public static final String FIRST_TIME_NUX_APP_ID = "3331068290248074";
    public static final String FIRST_TIME_NUX_PACKAGE_NAME = "com.oculus.firsttimenux";
    public static final String HACKULUS_APP_ID = "882179625204268";
    public static final String HACKULUS_PACKAGE_NAME = "com.oculus.hackulus";
    public static final String HOME_APP_ID = "1102518876432898";
    public static final String HOME_PACKAGE_NAME = "com.oculus.home";
    public static final String HORIZON_APP_ID = "826037204154824";
    public static final String HORIZON_PACKAGE_NAME = "com.oculus.horizon";
    public static final String ROOMS_APP_ID = "1101959559889232";
    public static final String ROOMS_PACKAGE_NAME = "com.oculus.rooms";
    public static final String SHELLENV_APP_ID = "3057535150987422";
    public static final String SHELLENV_PACKAGE_NAME = "com.oculus.shellenv";
    public static final String SOCIAL_PLATFORM_APP_ID = "1953748974690454";
    public static final String SOCIAL_PLATFORM_PACKAGE_NAME = "com.oculus.socialplatform";
    public static final String SPATIAL_PERSISTENCE_SERVICE_APP_ID = "2837826999666071";
    public static final String SPATIAL_PERSISTENCE_SERVICE_PACKAGE_NAME = "com.facebook.spatial_persistence_service";
    public static final String SYSTEM_TELEMETRY_APP_ID = "1193470664101395";
    public static final String SYSTEM_TELEMETRY_PACKAGE_NAME = "com.oculus.telemetry";
    public static final String TV_PACKAGE_NAME = "com.oculus.tv";
    public static final String UNIVERSAL_MENU_APP_ID = "939044786184977";
    public static final String UNIVERSAL_MENU_PACKAGE_NAME = "com.oculus.systemactivities";
    public static final String UPDATER_APP_ID = "1556285957737177";
    public static final String UPDATER_PACKAGE_NAME = "com.oculus.updater";
    public static final String VENUES_PACKAGE_NAME = "com.oculus.venues";
    public static final String VRCAST_SERVICE_PACKAGE_NAME = "com.oculus.vrcast";
    public static final String VRSHELLHOME_APP_ID = "1481000308606657";
    public static final String VRSHELLHOME_CORE_APP_ID = "1880592348624904";
    public static final String VRSHELLHOME_PACKAGE_NAME = "com.oculus.vrshell.home";
    public static final String VRSHELL_APP_ID = "1031607236937163";
    public static final String VRSHELL_PACKAGE_NAME = "com.oculus.vrshell";
    public static final HashSet<String> WHITELIST_SYSTEM_VOIP_PACKAGES = new HashSet<>(Arrays.asList("com.oculus.home", "com.oculus.horizon", "com.oculus.rooms", "com.oculus.shellenv", "com.oculus.tv", "com.oculus.systemactivities", "com.oculus.systemactivities", "com.oculus.venues", "com.oculus.vrshell", "com.oculus.vrshell.home", "com.oculus.socialplatform", "com.oculus.hackulus", FB_HORIZON_PACKAGE_NAME, FB_HORIZON_DEV_PACKAGE_NAME, FB_HORIZON_STABLE_PACKAGE_NAME, FB_HORIZON_STAGING_PACKAGE_NAME, FB_HORIZON_MAIN_NIGHTLY_PACKAGE_NAME, FB_HORIZON_MAIN_STABLE_PACKAGE_NAME, FB_HORIZON_MAIN_LKG_PACKAGE_NAME, FB_HORIZON_MAIN_TEST_PACKAGE_NAME, FB_HORIZON_PLAYTEST_PRIME_PACKAGE_NAME, FB_HORIZON_PLAYTEST_QA_PACKAGE_NAME, FB_HORIZON_DEMO_PACKAGE_NAME, FB_HORIZON_RELEASE_NIGHTLY_PACKAGE_NAME, FB_HORIZON_RELEASE_LKG_PACKAGE_NAME, FB_HORIZON_RELEASE_RC_PACKAGE_NAME, FB_HORIZON_RELEASE_PACKAGE_NAME));
}
