package com.oculus.auth.service.passwordencryption;

import X.AbstractC06640p5;
import X.AnonymousClass0J2;
import X.AnonymousClass0QC;
import X.AnonymousClass0p1;
import X.AnonymousClass117;
import X.AnonymousClass1Dq;
import X.C003008y;
import X.C01020Iw;
import android.content.Context;
import android.content.SharedPreferences;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import javax.annotation.Nullable;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_BINDING_ID"})
public class OculusPasswordEncryptionKeyStore {
    public static final String KEY_EXPIRY_TIMESTAMP_MS = "expiry_timestamp_ms";
    public static final String KEY_KEY_ID = "key_id";
    public static final String KEY_PUBLIC_KEY = "public_key";
    public static final String KEY_STATE = "key_state";
    public static final String PREF_NAME = "password_encryption_key_store";
    public AnonymousClass0QC _UL_mInjectionContext;
    public final SharedPreferences mSharedPreferences;

    @AutoGeneratedAccessMethod
    public static final AnonymousClass0p1 _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_auth_service_passwordencryption_OculusPasswordEncryptionKeyStore_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C003008y(382, r2);
    }

    @AutoGeneratedAccessMethod
    public static final OculusPasswordEncryptionKeyStore _UL__ULSEP_com_oculus_auth_service_passwordencryption_OculusPasswordEncryptionKeyStore_ULSEP_ACCESS_METHOD(AbstractC06640p5 r1) {
        return (OculusPasswordEncryptionKeyStore) AnonymousClass117.A00(382, r1);
    }

    @AutoGeneratedFactoryMethod
    public static final OculusPasswordEncryptionKeyStore _UL__ULSEP_com_oculus_auth_service_passwordencryption_OculusPasswordEncryptionKeyStore_ULSEP_FACTORY_METHOD(AbstractC06640p5 r1) {
        return new OculusPasswordEncryptionKeyStore(r1);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_auth_service_passwordencryption_OculusPasswordEncryptionKeyStore_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C01020Iw(382, r2);
    }

    @Nullable
    public AnonymousClass1Dq getKey() {
        int i = this.mSharedPreferences.getInt("key_id", -1);
        String string = this.mSharedPreferences.getString("public_key", null);
        long j = this.mSharedPreferences.getLong(KEY_EXPIRY_TIMESTAMP_MS, -1);
        String string2 = this.mSharedPreferences.getString(KEY_STATE, null);
        if (i == -1 || string == null || j == -1 || string2 == null) {
            return null;
        }
        return new AnonymousClass1Dq(i, string, j, string2);
    }

    public void storeKey(@Nullable AnonymousClass1Dq r8) {
        String str;
        if (r8 != null && r8.A00()) {
            int i = r8.A00;
            String str2 = r8.A03;
            long j = r8.A01;
            if (1 - r8.A02.intValue() != 0) {
                str = "ENCRYPTION_WITH_TAGGING";
            } else {
                str = "PLAINTEXT_WITH_TAGGING";
            }
            this.mSharedPreferences.edit().putInt("key_id", i).putString("public_key", str2).putLong(KEY_EXPIRY_TIMESTAMP_MS, j).putString(KEY_STATE, str).apply();
        }
    }

    @Inject
    public OculusPasswordEncryptionKeyStore(AbstractC06640p5 r4) {
        AnonymousClass0QC r1 = new AnonymousClass0QC(1, r4);
        this._UL_mInjectionContext = r1;
        this.mSharedPreferences = ((Context) AnonymousClass0J2.A03(0, 80, r1)).getSharedPreferences(PREF_NAME, 0);
    }
}
