package com.oculus.horizon.sso;

import X.AnonymousClass0J5;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import com.oculus.horizon.abuse_prevention.AudioCapture;

@InjectorModule
public class SsoModule extends AnonymousClass0J5 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForSsoModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_horizon_sso_SsoManager_ULSEP_BINDING_ID = AudioCapture.AUDIO_RECORDER_INTERVAL_MS;
    }
}
