package com.oculus.common.sociallogger;

/* JADX INFO: Failed to restore enum class, 'enum' modifier removed */
public final class ClickEventButtonId extends Enum<ClickEventButtonId> {
    public static final /* synthetic */ ClickEventButtonId[] $VALUES;
    public static final ClickEventButtonId AUIV2_MESSENGER_COMPOSE_AUDIO_INPUT_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_COMPOSE_QUICK_REPLY_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_COMPOSE_SEND_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_COMPOSE_SEND_KEYBOARD_GO;
    public static final ClickEventButtonId AUIV2_MESSENGER_COMPOSE_TEXT_INPUT;
    public static final ClickEventButtonId AUIV2_MESSENGER_COMPOSE_TEXT_INPUT_CANCEL_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_DRAFT_THREAD_PARTICIPANT_DROPDOWN_ITEM;
    public static final ClickEventButtonId AUIV2_MESSENGER_DRAFT_THREAD_PARTICIPANT_REMOVE;
    public static final ClickEventButtonId AUIV2_MESSENGER_DRAFT_THREAD_PARTICIPANT_TEXT_INPUT;
    public static final ClickEventButtonId AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_CONTINUE_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_LEAVE_GROUP_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_MANAGE_BLOCKED_MEMBERS_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_MANAGE_BLOCK_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_LEAVE_CHAT_CONFIRMATION_CANCEL_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_LEAVE_CHAT_CONFIRMATION_LEAVE_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_ONE_ON_ONE_THREAD_BLOCKED_VIEW_REPORT_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_ONE_ON_ONE_THREAD_BLOCKED_VIEW_UNBLOCK_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_PROFILE_SWITCHER_BUTTON;
    public static final ClickEventButtonId AUIV2_MESSENGER_PROFILE_SWITCHER_FB_PROFILE;
    public static final ClickEventButtonId AUIV2_MESSENGER_PROFILE_SWITCHER_OC_PROFILE;
    public static final ClickEventButtonId AUIV2_MESSENGER_REACTIONS_DETAILS_CLOSE;
    public static final ClickEventButtonId AUIV2_MESSENGER_SIDE_NAV_CHAT_ICON;
    public static final ClickEventButtonId AUIV2_MESSENGER_SIDE_NAV_PEOPLE_ICON;
    public static final ClickEventButtonId AUIV2_MESSENGER_SIDE_NAV_SETTINGS_ICON;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_ADD_TO_PARTY;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_CONTEXT_MENU;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_CONTEXT_MENU_BLOCK;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_CONTEXT_MENU_REPORT;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_CONTEXT_MENU_UNBLOCK;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_CREATE;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_DRAFT_LIST_ITEM;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_LIST_ITEM;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_PROFILE_PICTURE_THEM;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_REACTIONS_PILL;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_START_PARTY;
    public static final ClickEventButtonId AUIV2_MESSENGER_THREAD_XMA_PARTY_INVITE;
    public static final ClickEventButtonId CREATE_VR_INVITE_APP_SELECT;
    public static final ClickEventButtonId CREATE_VR_INVITE_BACK;
    public static final ClickEventButtonId CREATE_VR_INVITE_CANCEL;
    public static final ClickEventButtonId CREATE_VR_INVITE_CHOOSE_LATER_SELECT;
    public static final ClickEventButtonId CREATE_VR_INVITE_CHOOSE_LATER_UNSELECT;
    public static final ClickEventButtonId CREATE_VR_INVITE_DESTINATION_SELECT;
    public static final ClickEventButtonId CREATE_VR_INVITE_DESTINATION_UPDATE;
    public static final ClickEventButtonId CREATE_VR_INVITE_PROFILE_CONFIRM;
    public static final ClickEventButtonId CREATE_VR_INVITE_PROFILE_REMINDER_TOGGLE;
    public static final ClickEventButtonId CREATE_VR_INVITE_SEND_INVITES;
    public static final ClickEventButtonId FACEBOOK_BLOCK_DIALOG_BACK;
    public static final ClickEventButtonId FACEBOOK_BLOCK_DIALOG_BLOCK;
    public static final ClickEventButtonId FACEBOOK_BLOCK_DIALOG_UNBLOCK;
    public static final ClickEventButtonId JOIN_PARTY_CANCEL;
    public static final ClickEventButtonId JOIN_PARTY_CONFIRM;
    public static final ClickEventButtonId JOIN_PARTY_OPEN;
    public static final ClickEventButtonId MESSENGER_INTEGRITY_DIALOG_BACK;
    public static final ClickEventButtonId MESSENGER_INTEGRITY_DIALOG_FACEBOOK_BLOCK;
    public static final ClickEventButtonId MESSENGER_INTEGRITY_DIALOG_FACEBOOK_UNBLOCK;
    public static final ClickEventButtonId MESSENGER_INTEGRITY_DIALOG_MESSENGER_BLOCK;
    public static final ClickEventButtonId MESSENGER_INTEGRITY_DIALOG_MESSENGER_UNBLOCK;
    public static final ClickEventButtonId MESSENGER_INTEGRITY_DIALOG_SELECTOR_BLOCK;
    public static final ClickEventButtonId MESSENGER_INTEGRITY_DIALOG_SELECTOR_REPORT;
    public static final ClickEventButtonId NO_BUTTON;
    public static final ClickEventButtonId PARTIES_PANEL_ADJUST_AUDIO_PLAYBACK_VOLUME;
    public static final ClickEventButtonId PARTIES_PANEL_BACK_BUTTON;
    public static final ClickEventButtonId PARTIES_PANEL_LEAVE_PARTY;
    public static final ClickEventButtonId PARTIES_PANEL_PARTY_PRIVACY;
    public static final ClickEventButtonId PARTIES_PANEL_USER_CARD_BLOCK;
    public static final ClickEventButtonId PARTIES_PANEL_USER_CARD_CANCEL_INVITE;
    public static final ClickEventButtonId PARTIES_PANEL_USER_CARD_KICK;
    public static final ClickEventButtonId PARTIES_TAB_FB_ADD_TO_PARTY_BUTTON;
    public static final ClickEventButtonId PARTIES_TAB_OC_ADD_TO_PARTY_BUTTON;
    public static final ClickEventButtonId PARTIES_TAB_OC_ADD_TO_PARTY_CANCEL_BUTTON;
    public static final ClickEventButtonId PARTIES_TAB_OC_ADD_TO_PARTY_INVITE_BUTTON;
    public static final ClickEventButtonId PARTY_PRIVACY_CLOSE;
    public static final ClickEventButtonId PARTY_PRIVACY_LINK_INVITE;
    public static final ClickEventButtonId PARTY_PRIVACY_PARTY_TYPE;
    public static final ClickEventButtonId PARTY_PRIVACY_SHARE;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_ACCEPT_RESPONSE;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_APP_LAUNCH_DIALOG_LEADER_VIEW_CANCEL;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_APP_LAUNCH_DIALOG_MEMBER_VIEW_CANCEL;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_CANCEL_RESPONSE;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_CREATE;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_LAUNCH;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_LAUNCH_SOLO;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_REJECT_RESPONSE;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_SELECT_NEW_DESTINATION;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_TRAVEL_TO_LAUNCH_APP;
    public static final ClickEventButtonId PARTY_TRAVEL_FOOTER_VIEW_APP_DETAILS;
    public static final ClickEventButtonId PEOPLE_TAB_ADD_FRIENDS;
    public static final ClickEventButtonId PEOPLE_TAB_ALL_CONNECTIONS_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_CONNECT_TO_WIFI;
    public static final ClickEventButtonId PEOPLE_TAB_FB_VR_FRIENDS_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_LOGIN_WITH_FACEBOOK;
    public static final ClickEventButtonId PEOPLE_TAB_OC_FRIENDS_ONLINE_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_OC_FRIEND_REQUEST_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_OC_NEARBY_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_OC_SUGGESTED_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_QUICK_MESSAGE_POPUP_OPEN_CHAT;
    public static final ClickEventButtonId PEOPLE_TAB_QUICK_MESSAGE_POPUP_QUICK_REPLY_SEND;
    public static final ClickEventButtonId PEOPLE_TAB_SEARCH_BACK_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_SEARCH_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_SEARCH_CLEAR_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_SEARCH_SUBMIT_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_SETTINGS_BUTTON;
    public static final ClickEventButtonId PEOPLE_TAB_UPSELL_ADD_FRIENDS;
    public static final ClickEventButtonId PEOPLE_TAB_UPSELL_ALL_FRIENDS;
    public static final ClickEventButtonId PEOPLE_TAB_UPSELL_CREATE_PARTY;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_ACCEPT_FRIEND_REQUEST;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_BLOCK;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_BLOCK_ON_MESSENGER;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_CANCEL_FRIEND_REQUEST;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_CHAT;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_CREATE_PARTY_WITH;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_DENY_FRIEND_REQUEST;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_HIDE_PYMK_USER;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_INVITE_TO_PARTY;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_JOIN_PARTY;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_PROFILE_PICTURE;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_REPORT;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_SEND_FRIEND_REQUEST;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_UNFRIEND;
    public static final ClickEventButtonId PEOPLE_TAB_USER_CARD_VIEW_PROFILE;
    public static final ClickEventButtonId PEOPLE_TAB_USER_OVERFLOW_MENU;
    public static final ClickEventButtonId REAUTH_NUX_DIALOG_CONTINUE;
    public static final ClickEventButtonId REAUTH_NUX_DIALOG_CONTINUE_REAUTH;
    public static final ClickEventButtonId REAUTH_NUX_DIALOG_DELAY_USING_MESSENGER;
    public static final ClickEventButtonId REAUTH_NUX_DIALOG_OPEN_MESSENGER;
    public static final ClickEventButtonId REAUTH_NUX_DIALOG_TOS_CLICK;
    public static final ClickEventButtonId SOCIAL_REAUTH_CONTINUE;
    public static final ClickEventButtonId SOCIAL_REAUTH_KEYBOARD_GO;
    public static final ClickEventButtonId SOCIAL_REAUTH_PASSWORD_VISIBILITY_TOGGLE;
    public static final ClickEventButtonId SOCIAL_SETTINGS_ACTIVE_STATUS_LEARN_MORE;
    public static final ClickEventButtonId SOCIAL_SETTINGS_ACTIVE_STATUS_TOGGLE;
    public static final ClickEventButtonId SOCIAL_SETTINGS_MESSENGER_SIGN_OUT;
    public static final ClickEventButtonId SOCIAL_SETTINGS_MESSENGER_SIGN_OUT_DIALOG_CANCEL;
    public static final ClickEventButtonId SOCIAL_SETTINGS_MESSENGER_SIGN_OUT_DIALOG_SIGN_OUT;
    public static final ClickEventButtonId SOCIAL_SETTINGS_PRIVACY_CONFIGURE_LOCK_PATTERN;
    public static final ClickEventButtonId START_MESSENGER_CALL_CANCEL;
    public static final ClickEventButtonId START_MESSENGER_CALL_CONFIRM;
    public final String mTelemetryButtonId;

    static {
        ClickEventButtonId clickEventButtonId = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_CREATE", 0, "auiv2_messenger_thread_create");
        AUIV2_MESSENGER_THREAD_CREATE = clickEventButtonId;
        ClickEventButtonId clickEventButtonId2 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_START_PARTY", 1, "auiv2_messenger_thread_start_party");
        AUIV2_MESSENGER_THREAD_START_PARTY = clickEventButtonId2;
        ClickEventButtonId clickEventButtonId3 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_ADD_TO_PARTY", 2, "auiv2_messenger_thread_add_to_party");
        AUIV2_MESSENGER_THREAD_ADD_TO_PARTY = clickEventButtonId3;
        ClickEventButtonId clickEventButtonId4 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_LIST_ITEM", 3, "auiv2_messenger_thread_list_item");
        AUIV2_MESSENGER_THREAD_LIST_ITEM = clickEventButtonId4;
        ClickEventButtonId clickEventButtonId5 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_DRAFT_LIST_ITEM", 4, "auiv2_messenger_thread_draft_list_item");
        AUIV2_MESSENGER_THREAD_DRAFT_LIST_ITEM = clickEventButtonId5;
        ClickEventButtonId clickEventButtonId6 = new ClickEventButtonId("AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_CONTINUE_BUTTON", 5, "auiv2_messenger_group_thread_containing_blocked_view_continue_button");
        AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_CONTINUE_BUTTON = clickEventButtonId6;
        ClickEventButtonId clickEventButtonId7 = new ClickEventButtonId("AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_LEAVE_GROUP_BUTTON", 6, "auiv2_messenger_group_thread_containing_blocked_view_leave_group_button");
        AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_LEAVE_GROUP_BUTTON = clickEventButtonId7;
        ClickEventButtonId clickEventButtonId8 = new ClickEventButtonId("AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_MANAGE_BLOCK_BUTTON", 7, "auiv2_messenger_group_thread_containing_blocked_view_manage_block_button");
        AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_MANAGE_BLOCK_BUTTON = clickEventButtonId8;
        ClickEventButtonId clickEventButtonId9 = new ClickEventButtonId("AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_MANAGE_BLOCKED_MEMBERS_BUTTON", 8, "auiv2_messenger_group_thread_containing_blocked_view_manage_blocked_members_button");
        AUIV2_MESSENGER_GROUP_THREAD_CONTAINING_BLOCKED_VIEW_MANAGE_BLOCKED_MEMBERS_BUTTON = clickEventButtonId9;
        ClickEventButtonId clickEventButtonId10 = new ClickEventButtonId("AUIV2_MESSENGER_LEAVE_CHAT_CONFIRMATION_CANCEL_BUTTON", 9, "auiv2_messenger_leave_chat_confirmation_cancel_button");
        AUIV2_MESSENGER_LEAVE_CHAT_CONFIRMATION_CANCEL_BUTTON = clickEventButtonId10;
        ClickEventButtonId clickEventButtonId11 = new ClickEventButtonId("AUIV2_MESSENGER_LEAVE_CHAT_CONFIRMATION_LEAVE_BUTTON", 10, "auiv2_messenger_leave_chat_confirmation_leave_button");
        AUIV2_MESSENGER_LEAVE_CHAT_CONFIRMATION_LEAVE_BUTTON = clickEventButtonId11;
        ClickEventButtonId clickEventButtonId12 = new ClickEventButtonId("AUIV2_MESSENGER_ONE_ON_ONE_THREAD_BLOCKED_VIEW_UNBLOCK_BUTTON", 11, "auiv2_messenger_one_on_one_thread_blocked_view_unblock_button");
        AUIV2_MESSENGER_ONE_ON_ONE_THREAD_BLOCKED_VIEW_UNBLOCK_BUTTON = clickEventButtonId12;
        ClickEventButtonId clickEventButtonId13 = new ClickEventButtonId("AUIV2_MESSENGER_ONE_ON_ONE_THREAD_BLOCKED_VIEW_REPORT_BUTTON", 12, "auiv2_messenger_one_on_one_thread_blocked_view_report_button");
        AUIV2_MESSENGER_ONE_ON_ONE_THREAD_BLOCKED_VIEW_REPORT_BUTTON = clickEventButtonId13;
        ClickEventButtonId clickEventButtonId14 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_CONTEXT_MENU", 13, "auiv2_messenger_thread_context_menu");
        AUIV2_MESSENGER_THREAD_CONTEXT_MENU = clickEventButtonId14;
        ClickEventButtonId clickEventButtonId15 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_CONTEXT_MENU_BLOCK", 14, "auiv2_messenger_thread_context_menu_block");
        AUIV2_MESSENGER_THREAD_CONTEXT_MENU_BLOCK = clickEventButtonId15;
        ClickEventButtonId clickEventButtonId16 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_CONTEXT_MENU_REPORT", 15, "auiv2_messenger_thread_context_menu_report");
        AUIV2_MESSENGER_THREAD_CONTEXT_MENU_REPORT = clickEventButtonId16;
        ClickEventButtonId clickEventButtonId17 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_CONTEXT_MENU_UNBLOCK", 16, "auiv2_messenger_thread_context_menu_unblock");
        AUIV2_MESSENGER_THREAD_CONTEXT_MENU_UNBLOCK = clickEventButtonId17;
        ClickEventButtonId clickEventButtonId18 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_PROFILE_PICTURE_THEM", 17, "auiv2_messenger_thread_profile_picture_them");
        AUIV2_MESSENGER_THREAD_PROFILE_PICTURE_THEM = clickEventButtonId18;
        ClickEventButtonId clickEventButtonId19 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_XMA_PARTY_INVITE", 18, "auiv2_messenger_thread_xma_party_invite");
        AUIV2_MESSENGER_THREAD_XMA_PARTY_INVITE = clickEventButtonId19;
        ClickEventButtonId clickEventButtonId20 = new ClickEventButtonId("AUIV2_MESSENGER_REACTIONS_DETAILS_CLOSE", 19, "auiv2_messenger_reactions_details_close");
        AUIV2_MESSENGER_REACTIONS_DETAILS_CLOSE = clickEventButtonId20;
        ClickEventButtonId clickEventButtonId21 = new ClickEventButtonId("AUIV2_MESSENGER_THREAD_REACTIONS_PILL", 20, "auiv2_messenger_thread_reactions_pill");
        AUIV2_MESSENGER_THREAD_REACTIONS_PILL = clickEventButtonId21;
        ClickEventButtonId clickEventButtonId22 = new ClickEventButtonId("AUIV2_MESSENGER_DRAFT_THREAD_PARTICIPANT_DROPDOWN_ITEM", 21, "auiv2_messenger_draft_thread_participant_dropdown_item");
        AUIV2_MESSENGER_DRAFT_THREAD_PARTICIPANT_DROPDOWN_ITEM = clickEventButtonId22;
        ClickEventButtonId clickEventButtonId23 = new ClickEventButtonId("AUIV2_MESSENGER_DRAFT_THREAD_PARTICIPANT_REMOVE", 22, "auiv2_messenger_draft_thread_participant_remove");
        AUIV2_MESSENGER_DRAFT_THREAD_PARTICIPANT_REMOVE = clickEventButtonId23;
        ClickEventButtonId clickEventButtonId24 = new ClickEventButtonId("AUIV2_MESSENGER_DRAFT_THREAD_PARTICIPANT_TEXT_INPUT", 23, "auiv2_messenger_draft_thread_participant_text_input");
        AUIV2_MESSENGER_DRAFT_THREAD_PARTICIPANT_TEXT_INPUT = clickEventButtonId24;
        ClickEventButtonId clickEventButtonId25 = new ClickEventButtonId("AUIV2_MESSENGER_COMPOSE_SEND_KEYBOARD_GO", 24, "auiv2_messenger_compose_send_go");
        AUIV2_MESSENGER_COMPOSE_SEND_KEYBOARD_GO = clickEventButtonId25;
        ClickEventButtonId clickEventButtonId26 = new ClickEventButtonId("AUIV2_MESSENGER_COMPOSE_SEND_BUTTON", 25, "auiv2_messenger_compose_send_button");
        AUIV2_MESSENGER_COMPOSE_SEND_BUTTON = clickEventButtonId26;
        ClickEventButtonId clickEventButtonId27 = new ClickEventButtonId("AUIV2_MESSENGER_COMPOSE_AUDIO_INPUT_BUTTON", 26, "auiv2_messenger_compose_audio_input_button");
        AUIV2_MESSENGER_COMPOSE_AUDIO_INPUT_BUTTON = clickEventButtonId27;
        ClickEventButtonId clickEventButtonId28 = new ClickEventButtonId("AUIV2_MESSENGER_COMPOSE_TEXT_INPUT", 27, "auiv2_messenger_compose_text_input");
        AUIV2_MESSENGER_COMPOSE_TEXT_INPUT = clickEventButtonId28;
        ClickEventButtonId clickEventButtonId29 = new ClickEventButtonId("AUIV2_MESSENGER_COMPOSE_TEXT_INPUT_CANCEL_BUTTON", 28, "auiv2_messenger_compose_text_input_cancel_button");
        AUIV2_MESSENGER_COMPOSE_TEXT_INPUT_CANCEL_BUTTON = clickEventButtonId29;
        ClickEventButtonId clickEventButtonId30 = new ClickEventButtonId("AUIV2_MESSENGER_COMPOSE_QUICK_REPLY_BUTTON", 29, "auiv2_messenger_compose_quick_reply_button");
        AUIV2_MESSENGER_COMPOSE_QUICK_REPLY_BUTTON = clickEventButtonId30;
        ClickEventButtonId clickEventButtonId31 = new ClickEventButtonId("AUIV2_MESSENGER_PROFILE_SWITCHER_BUTTON", 30, "auiv2_messenger_profile_switcher_button");
        AUIV2_MESSENGER_PROFILE_SWITCHER_BUTTON = clickEventButtonId31;
        ClickEventButtonId clickEventButtonId32 = new ClickEventButtonId("AUIV2_MESSENGER_PROFILE_SWITCHER_FB_PROFILE", 31, "auiv2_messenger_profile_switcher_fb_profile");
        AUIV2_MESSENGER_PROFILE_SWITCHER_FB_PROFILE = clickEventButtonId32;
        ClickEventButtonId clickEventButtonId33 = new ClickEventButtonId("AUIV2_MESSENGER_PROFILE_SWITCHER_OC_PROFILE", 32, "auiv2_messenger_profile_switcher_oc_profile");
        AUIV2_MESSENGER_PROFILE_SWITCHER_OC_PROFILE = clickEventButtonId33;
        ClickEventButtonId clickEventButtonId34 = new ClickEventButtonId("AUIV2_MESSENGER_SIDE_NAV_CHAT_ICON", 33, "auiv2_messenger_side_nav_chat_icon");
        AUIV2_MESSENGER_SIDE_NAV_CHAT_ICON = clickEventButtonId34;
        ClickEventButtonId clickEventButtonId35 = new ClickEventButtonId("AUIV2_MESSENGER_SIDE_NAV_PEOPLE_ICON", 34, "auiv2_messenger_side_nav_people_icon");
        AUIV2_MESSENGER_SIDE_NAV_PEOPLE_ICON = clickEventButtonId35;
        ClickEventButtonId clickEventButtonId36 = new ClickEventButtonId("AUIV2_MESSENGER_SIDE_NAV_SETTINGS_ICON", 35, "auiv2_messenger_side_nav_settings_icon");
        AUIV2_MESSENGER_SIDE_NAV_SETTINGS_ICON = clickEventButtonId36;
        ClickEventButtonId clickEventButtonId37 = new ClickEventButtonId("SOCIAL_REAUTH_CONTINUE", 36, "social_reauth_continue");
        SOCIAL_REAUTH_CONTINUE = clickEventButtonId37;
        ClickEventButtonId clickEventButtonId38 = new ClickEventButtonId("SOCIAL_REAUTH_KEYBOARD_GO", 37, "social_reauth_keyboard_go");
        SOCIAL_REAUTH_KEYBOARD_GO = clickEventButtonId38;
        ClickEventButtonId clickEventButtonId39 = new ClickEventButtonId("SOCIAL_REAUTH_PASSWORD_VISIBILITY_TOGGLE", 38, "social_reauth_password_visibility_toggle");
        SOCIAL_REAUTH_PASSWORD_VISIBILITY_TOGGLE = clickEventButtonId39;
        ClickEventButtonId clickEventButtonId40 = new ClickEventButtonId("SOCIAL_SETTINGS_ACTIVE_STATUS_LEARN_MORE", 39, "social_settings_active_status_learn_more");
        SOCIAL_SETTINGS_ACTIVE_STATUS_LEARN_MORE = clickEventButtonId40;
        ClickEventButtonId clickEventButtonId41 = new ClickEventButtonId("SOCIAL_SETTINGS_ACTIVE_STATUS_TOGGLE", 40, "social_settings_active_status_toggle");
        SOCIAL_SETTINGS_ACTIVE_STATUS_TOGGLE = clickEventButtonId41;
        ClickEventButtonId clickEventButtonId42 = new ClickEventButtonId("SOCIAL_SETTINGS_PRIVACY_CONFIGURE_LOCK_PATTERN", 41, "social_settings_privacy_configure_lock_pattern");
        SOCIAL_SETTINGS_PRIVACY_CONFIGURE_LOCK_PATTERN = clickEventButtonId42;
        ClickEventButtonId clickEventButtonId43 = new ClickEventButtonId("SOCIAL_SETTINGS_MESSENGER_SIGN_OUT", 42, "social_settings_messenger_sign_out");
        SOCIAL_SETTINGS_MESSENGER_SIGN_OUT = clickEventButtonId43;
        ClickEventButtonId clickEventButtonId44 = new ClickEventButtonId("SOCIAL_SETTINGS_MESSENGER_SIGN_OUT_DIALOG_CANCEL", 43, "social_settings_messenger_sign_out_dialog_cancel");
        SOCIAL_SETTINGS_MESSENGER_SIGN_OUT_DIALOG_CANCEL = clickEventButtonId44;
        ClickEventButtonId clickEventButtonId45 = new ClickEventButtonId("SOCIAL_SETTINGS_MESSENGER_SIGN_OUT_DIALOG_SIGN_OUT", 44, "social_settings_messenger_sign_out_dialog_sign_out");
        SOCIAL_SETTINGS_MESSENGER_SIGN_OUT_DIALOG_SIGN_OUT = clickEventButtonId45;
        ClickEventButtonId clickEventButtonId46 = new ClickEventButtonId("PARTIES_PANEL_ADJUST_AUDIO_PLAYBACK_VOLUME", 45, "parties_panel_adjust_audio_playback_volume");
        PARTIES_PANEL_ADJUST_AUDIO_PLAYBACK_VOLUME = clickEventButtonId46;
        ClickEventButtonId clickEventButtonId47 = new ClickEventButtonId("PARTIES_PANEL_BACK_BUTTON", 46, "parties_panel_back_button");
        PARTIES_PANEL_BACK_BUTTON = clickEventButtonId47;
        ClickEventButtonId clickEventButtonId48 = new ClickEventButtonId("PARTIES_PANEL_LEAVE_PARTY", 47, "parties_panel_leave_party");
        PARTIES_PANEL_LEAVE_PARTY = clickEventButtonId48;
        ClickEventButtonId clickEventButtonId49 = new ClickEventButtonId("PARTIES_PANEL_PARTY_PRIVACY", 48, "parties_panel_party_privacy");
        PARTIES_PANEL_PARTY_PRIVACY = clickEventButtonId49;
        ClickEventButtonId clickEventButtonId50 = new ClickEventButtonId("PARTIES_PANEL_USER_CARD_BLOCK", 49, "parties_panel_user_card_block");
        PARTIES_PANEL_USER_CARD_BLOCK = clickEventButtonId50;
        ClickEventButtonId clickEventButtonId51 = new ClickEventButtonId("PARTIES_PANEL_USER_CARD_CANCEL_INVITE", 50, "parties_panel_user_card_cancel_invite");
        PARTIES_PANEL_USER_CARD_CANCEL_INVITE = clickEventButtonId51;
        ClickEventButtonId clickEventButtonId52 = new ClickEventButtonId("PARTIES_PANEL_USER_CARD_KICK", 51, "parties_panel_user_card_kick");
        PARTIES_PANEL_USER_CARD_KICK = clickEventButtonId52;
        ClickEventButtonId clickEventButtonId53 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_VIEW_APP_DETAILS", 52, "party_travel_footer_group_launch_view_app_details");
        PARTY_TRAVEL_FOOTER_VIEW_APP_DETAILS = clickEventButtonId53;
        ClickEventButtonId clickEventButtonId54 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_CREATE", 53, "party_travel_footer_group_launch_create");
        PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_CREATE = clickEventButtonId54;
        ClickEventButtonId clickEventButtonId55 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_TRAVEL_TO_LAUNCH_APP", 54, "party_travel_footer_group_launch_travel_to_launch_app");
        PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_TRAVEL_TO_LAUNCH_APP = clickEventButtonId55;
        ClickEventButtonId clickEventButtonId56 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_LAUNCH_SOLO", 55, "party_travel_footer_group_launch_launch_solo");
        PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_LAUNCH_SOLO = clickEventButtonId56;
        ClickEventButtonId clickEventButtonId57 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_ACCEPT_RESPONSE", 56, "party_travel_footer_group_launch_accept_response");
        PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_ACCEPT_RESPONSE = clickEventButtonId57;
        ClickEventButtonId clickEventButtonId58 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_REJECT_RESPONSE", 57, "party_travel_footer_group_launch_reject_response");
        PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_REJECT_RESPONSE = clickEventButtonId58;
        ClickEventButtonId clickEventButtonId59 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_CANCEL_RESPONSE", 58, "party_travel_footer_group_launch_cancel_response");
        PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_CANCEL_RESPONSE = clickEventButtonId59;
        ClickEventButtonId clickEventButtonId60 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_LAUNCH", 59, "party_travel_footer_group_launch_launch");
        PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_LAUNCH = clickEventButtonId60;
        ClickEventButtonId clickEventButtonId61 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_APP_LAUNCH_DIALOG_LEADER_VIEW_CANCEL", 60, "party_travel_footer_app_lanch_dialog_leader_view_cancel");
        PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_APP_LAUNCH_DIALOG_LEADER_VIEW_CANCEL = clickEventButtonId61;
        ClickEventButtonId clickEventButtonId62 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_APP_LAUNCH_DIALOG_MEMBER_VIEW_CANCEL", 61, "party_travel_footer_app_lanch_dialog_member_view_cancel");
        PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_APP_LAUNCH_DIALOG_MEMBER_VIEW_CANCEL = clickEventButtonId62;
        ClickEventButtonId clickEventButtonId63 = new ClickEventButtonId("PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_SELECT_NEW_DESTINATION", 62, "party_travel_footer_group_launch_select_new_destination");
        PARTY_TRAVEL_FOOTER_GROUP_LAUNCH_SELECT_NEW_DESTINATION = clickEventButtonId63;
        ClickEventButtonId clickEventButtonId64 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_ACCEPT_FRIEND_REQUEST", 63, "people_tab_user_card_accept_friend_request");
        PEOPLE_TAB_USER_CARD_ACCEPT_FRIEND_REQUEST = clickEventButtonId64;
        ClickEventButtonId clickEventButtonId65 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_BLOCK", 64, "people_tab_user_card_block");
        PEOPLE_TAB_USER_CARD_BLOCK = clickEventButtonId65;
        ClickEventButtonId clickEventButtonId66 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_BLOCK_ON_MESSENGER", 65, "people_tab_user_card_block_on_messenger");
        PEOPLE_TAB_USER_CARD_BLOCK_ON_MESSENGER = clickEventButtonId66;
        ClickEventButtonId clickEventButtonId67 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_CANCEL_FRIEND_REQUEST", 66, "people_tab_user_card_cancel_friend_request");
        PEOPLE_TAB_USER_CARD_CANCEL_FRIEND_REQUEST = clickEventButtonId67;
        ClickEventButtonId clickEventButtonId68 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_CHAT", 67, "people_tab_user_card_chat");
        PEOPLE_TAB_USER_CARD_CHAT = clickEventButtonId68;
        ClickEventButtonId clickEventButtonId69 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_CREATE_PARTY_WITH", 68, "people_tab_user_card_create_party_with");
        PEOPLE_TAB_USER_CARD_CREATE_PARTY_WITH = clickEventButtonId69;
        ClickEventButtonId clickEventButtonId70 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_DENY_FRIEND_REQUEST", 69, "people_tab_user_card_deny_friend_request");
        PEOPLE_TAB_USER_CARD_DENY_FRIEND_REQUEST = clickEventButtonId70;
        ClickEventButtonId clickEventButtonId71 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_HIDE_PYMK_USER", 70, "people_tab_user_card_hide_pymk_user");
        PEOPLE_TAB_USER_CARD_HIDE_PYMK_USER = clickEventButtonId71;
        ClickEventButtonId clickEventButtonId72 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_INVITE_TO_PARTY", 71, "people_tab_user_card_invite_to_party");
        PEOPLE_TAB_USER_CARD_INVITE_TO_PARTY = clickEventButtonId72;
        ClickEventButtonId clickEventButtonId73 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_JOIN_PARTY", 72, "people_tab_user_card_join_party");
        PEOPLE_TAB_USER_CARD_JOIN_PARTY = clickEventButtonId73;
        ClickEventButtonId clickEventButtonId74 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_PROFILE_PICTURE", 73, "people_tab_user_card_profile_picture");
        PEOPLE_TAB_USER_CARD_PROFILE_PICTURE = clickEventButtonId74;
        ClickEventButtonId clickEventButtonId75 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_REPORT", 74, "people_tab_user_card_report");
        PEOPLE_TAB_USER_CARD_REPORT = clickEventButtonId75;
        ClickEventButtonId clickEventButtonId76 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_SEND_FRIEND_REQUEST", 75, "people_tab_user_card_send_friend_request");
        PEOPLE_TAB_USER_CARD_SEND_FRIEND_REQUEST = clickEventButtonId76;
        ClickEventButtonId clickEventButtonId77 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_UNFRIEND", 76, "people_tab_user_card_unfriend");
        PEOPLE_TAB_USER_CARD_UNFRIEND = clickEventButtonId77;
        ClickEventButtonId clickEventButtonId78 = new ClickEventButtonId("PEOPLE_TAB_USER_CARD_VIEW_PROFILE", 77, "people_tab_user_card_view_profile");
        PEOPLE_TAB_USER_CARD_VIEW_PROFILE = clickEventButtonId78;
        ClickEventButtonId clickEventButtonId79 = new ClickEventButtonId("PEOPLE_TAB_SEARCH_BUTTON", 78, "people_tab_search_button");
        PEOPLE_TAB_SEARCH_BUTTON = clickEventButtonId79;
        ClickEventButtonId clickEventButtonId80 = new ClickEventButtonId("PEOPLE_TAB_ALL_CONNECTIONS_BUTTON", 79, "people_tab_all_connections_button");
        PEOPLE_TAB_ALL_CONNECTIONS_BUTTON = clickEventButtonId80;
        ClickEventButtonId clickEventButtonId81 = new ClickEventButtonId("PEOPLE_TAB_SETTINGS_BUTTON", 80, "people_tab_settings_button");
        PEOPLE_TAB_SETTINGS_BUTTON = clickEventButtonId81;
        ClickEventButtonId clickEventButtonId82 = new ClickEventButtonId("PEOPLE_TAB_FB_VR_FRIENDS_BUTTON", 81, "people_tab_fb_vr_friends_button");
        PEOPLE_TAB_FB_VR_FRIENDS_BUTTON = clickEventButtonId82;
        ClickEventButtonId clickEventButtonId83 = new ClickEventButtonId("PEOPLE_TAB_OC_FRIENDS_ONLINE_BUTTON", 82, "people_tab_oc_friends_online_button");
        PEOPLE_TAB_OC_FRIENDS_ONLINE_BUTTON = clickEventButtonId83;
        ClickEventButtonId clickEventButtonId84 = new ClickEventButtonId("PEOPLE_TAB_OC_SUGGESTED_BUTTON", 83, "people_tab_oc_suggested_button");
        PEOPLE_TAB_OC_SUGGESTED_BUTTON = clickEventButtonId84;
        ClickEventButtonId clickEventButtonId85 = new ClickEventButtonId("PEOPLE_TAB_OC_FRIEND_REQUEST_BUTTON", 84, "people_tab_oc_friend_request_button");
        PEOPLE_TAB_OC_FRIEND_REQUEST_BUTTON = clickEventButtonId85;
        ClickEventButtonId clickEventButtonId86 = new ClickEventButtonId("PEOPLE_TAB_OC_NEARBY_BUTTON", 85, "people_tab_oc_nearby_button");
        PEOPLE_TAB_OC_NEARBY_BUTTON = clickEventButtonId86;
        ClickEventButtonId clickEventButtonId87 = new ClickEventButtonId("PEOPLE_TAB_SEARCH_CLEAR_BUTTON", 86, "people_tab_search_clear_button");
        PEOPLE_TAB_SEARCH_CLEAR_BUTTON = clickEventButtonId87;
        ClickEventButtonId clickEventButtonId88 = new ClickEventButtonId("PEOPLE_TAB_SEARCH_BACK_BUTTON", 87, "people_tab_search_back_button");
        PEOPLE_TAB_SEARCH_BACK_BUTTON = clickEventButtonId88;
        ClickEventButtonId clickEventButtonId89 = new ClickEventButtonId("PEOPLE_TAB_SEARCH_SUBMIT_BUTTON", 88, "people_tab_search_submit_button");
        PEOPLE_TAB_SEARCH_SUBMIT_BUTTON = clickEventButtonId89;
        ClickEventButtonId clickEventButtonId90 = new ClickEventButtonId("PEOPLE_TAB_LOGIN_WITH_FACEBOOK", 89, "people_tab_login_with_facebook");
        PEOPLE_TAB_LOGIN_WITH_FACEBOOK = clickEventButtonId90;
        ClickEventButtonId clickEventButtonId91 = new ClickEventButtonId("PEOPLE_TAB_CONNECT_TO_WIFI", 90, "people_tab_connect_to_wifi");
        PEOPLE_TAB_CONNECT_TO_WIFI = clickEventButtonId91;
        ClickEventButtonId clickEventButtonId92 = new ClickEventButtonId("PEOPLE_TAB_ADD_FRIENDS", 91, "people_tab_add_friends");
        PEOPLE_TAB_ADD_FRIENDS = clickEventButtonId92;
        ClickEventButtonId clickEventButtonId93 = new ClickEventButtonId("PEOPLE_TAB_UPSELL_CREATE_PARTY", 92, "people_tab_upsell_create_party");
        PEOPLE_TAB_UPSELL_CREATE_PARTY = clickEventButtonId93;
        ClickEventButtonId clickEventButtonId94 = new ClickEventButtonId("PEOPLE_TAB_UPSELL_ADD_FRIENDS", 93, "people_tab_upsell_add_friends");
        PEOPLE_TAB_UPSELL_ADD_FRIENDS = clickEventButtonId94;
        ClickEventButtonId clickEventButtonId95 = new ClickEventButtonId("PEOPLE_TAB_UPSELL_ALL_FRIENDS", 94, "people_tab_upsell_all_friends");
        PEOPLE_TAB_UPSELL_ALL_FRIENDS = clickEventButtonId95;
        ClickEventButtonId clickEventButtonId96 = new ClickEventButtonId("PEOPLE_TAB_USER_OVERFLOW_MENU", 95, "people_tab_user_overflow_menu");
        PEOPLE_TAB_USER_OVERFLOW_MENU = clickEventButtonId96;
        ClickEventButtonId clickEventButtonId97 = new ClickEventButtonId("PEOPLE_TAB_QUICK_MESSAGE_POPUP_QUICK_REPLY_SEND", 96, "people_tab_quick_message_popup_quick_reply_send");
        PEOPLE_TAB_QUICK_MESSAGE_POPUP_QUICK_REPLY_SEND = clickEventButtonId97;
        ClickEventButtonId clickEventButtonId98 = new ClickEventButtonId("PEOPLE_TAB_QUICK_MESSAGE_POPUP_OPEN_CHAT", 97, "people_tab_quick_message_popup_open_chat");
        PEOPLE_TAB_QUICK_MESSAGE_POPUP_OPEN_CHAT = clickEventButtonId98;
        ClickEventButtonId clickEventButtonId99 = new ClickEventButtonId("PARTIES_TAB_FB_ADD_TO_PARTY_BUTTON", 98, "parties_tab_fb_add_to_party_button");
        PARTIES_TAB_FB_ADD_TO_PARTY_BUTTON = clickEventButtonId99;
        ClickEventButtonId clickEventButtonId100 = new ClickEventButtonId("PARTIES_TAB_OC_ADD_TO_PARTY_BUTTON", 99, "parties_tab_oc_add_to_party_button");
        PARTIES_TAB_OC_ADD_TO_PARTY_BUTTON = clickEventButtonId100;
        ClickEventButtonId clickEventButtonId101 = new ClickEventButtonId("PARTIES_TAB_OC_ADD_TO_PARTY_CANCEL_BUTTON", 100, "parties_tab_oc_add_to_party_cancel_button");
        PARTIES_TAB_OC_ADD_TO_PARTY_CANCEL_BUTTON = clickEventButtonId101;
        ClickEventButtonId clickEventButtonId102 = new ClickEventButtonId("PARTIES_TAB_OC_ADD_TO_PARTY_INVITE_BUTTON", 101, "parties_tab_oc_add_to_party_invite_button");
        PARTIES_TAB_OC_ADD_TO_PARTY_INVITE_BUTTON = clickEventButtonId102;
        ClickEventButtonId clickEventButtonId103 = new ClickEventButtonId("FACEBOOK_BLOCK_DIALOG_BACK", 102, "facebook_block_dialog_back");
        FACEBOOK_BLOCK_DIALOG_BACK = clickEventButtonId103;
        ClickEventButtonId clickEventButtonId104 = new ClickEventButtonId("FACEBOOK_BLOCK_DIALOG_BLOCK", 103, "facebook_block_dialog_block");
        FACEBOOK_BLOCK_DIALOG_BLOCK = clickEventButtonId104;
        ClickEventButtonId clickEventButtonId105 = new ClickEventButtonId("FACEBOOK_BLOCK_DIALOG_UNBLOCK", 104, "facebook_block_dialog_unblock");
        FACEBOOK_BLOCK_DIALOG_UNBLOCK = clickEventButtonId105;
        ClickEventButtonId clickEventButtonId106 = new ClickEventButtonId("MESSENGER_INTEGRITY_DIALOG_BACK", 105, "messenger_integrity_dialog_back");
        MESSENGER_INTEGRITY_DIALOG_BACK = clickEventButtonId106;
        ClickEventButtonId clickEventButtonId107 = new ClickEventButtonId("MESSENGER_INTEGRITY_DIALOG_FACEBOOK_BLOCK", 106, "messenger_integrity_dialog_facebook_block");
        MESSENGER_INTEGRITY_DIALOG_FACEBOOK_BLOCK = clickEventButtonId107;
        ClickEventButtonId clickEventButtonId108 = new ClickEventButtonId("MESSENGER_INTEGRITY_DIALOG_FACEBOOK_UNBLOCK", 107, "messenger_integrity_dialog_facebook_unblock");
        MESSENGER_INTEGRITY_DIALOG_FACEBOOK_UNBLOCK = clickEventButtonId108;
        ClickEventButtonId clickEventButtonId109 = new ClickEventButtonId("MESSENGER_INTEGRITY_DIALOG_MESSENGER_BLOCK", 108, "messenger_integrity_dialog_messenger_block");
        MESSENGER_INTEGRITY_DIALOG_MESSENGER_BLOCK = clickEventButtonId109;
        ClickEventButtonId clickEventButtonId110 = new ClickEventButtonId("MESSENGER_INTEGRITY_DIALOG_MESSENGER_UNBLOCK", 109, "messenger_integrity_dialog_messenger_unblock");
        MESSENGER_INTEGRITY_DIALOG_MESSENGER_UNBLOCK = clickEventButtonId110;
        ClickEventButtonId clickEventButtonId111 = new ClickEventButtonId("MESSENGER_INTEGRITY_DIALOG_SELECTOR_BLOCK", 110, "messenger_integrity_dialog_selector_block");
        MESSENGER_INTEGRITY_DIALOG_SELECTOR_BLOCK = clickEventButtonId111;
        ClickEventButtonId clickEventButtonId112 = new ClickEventButtonId("MESSENGER_INTEGRITY_DIALOG_SELECTOR_REPORT", 111, "messenger_integrity_dialog_selector_report");
        MESSENGER_INTEGRITY_DIALOG_SELECTOR_REPORT = clickEventButtonId112;
        ClickEventButtonId clickEventButtonId113 = new ClickEventButtonId("CREATE_VR_INVITE_PROFILE_REMINDER_TOGGLE", 112, "create_vr_invite_profile_reminder_toggle");
        CREATE_VR_INVITE_PROFILE_REMINDER_TOGGLE = clickEventButtonId113;
        ClickEventButtonId clickEventButtonId114 = new ClickEventButtonId("CREATE_VR_INVITE_APP_SELECT", 113, "create_vr_invite_app_select");
        CREATE_VR_INVITE_APP_SELECT = clickEventButtonId114;
        ClickEventButtonId clickEventButtonId115 = new ClickEventButtonId("CREATE_VR_INVITE_BACK", 114, "create_vr_invite_back");
        CREATE_VR_INVITE_BACK = clickEventButtonId115;
        ClickEventButtonId clickEventButtonId116 = new ClickEventButtonId("CREATE_VR_INVITE_CANCEL", 115, "create_vr_invite_cancel");
        CREATE_VR_INVITE_CANCEL = clickEventButtonId116;
        ClickEventButtonId clickEventButtonId117 = new ClickEventButtonId("CREATE_VR_INVITE_CHOOSE_LATER_SELECT", 116, "create_vr_invite_app_select_select");
        CREATE_VR_INVITE_CHOOSE_LATER_SELECT = clickEventButtonId117;
        ClickEventButtonId clickEventButtonId118 = new ClickEventButtonId("CREATE_VR_INVITE_CHOOSE_LATER_UNSELECT", 117, "create_vr_invite_app_select_unselect");
        CREATE_VR_INVITE_CHOOSE_LATER_UNSELECT = clickEventButtonId118;
        ClickEventButtonId clickEventButtonId119 = new ClickEventButtonId("CREATE_VR_INVITE_DESTINATION_SELECT", 118, "create_vr_invite_destination_select");
        CREATE_VR_INVITE_DESTINATION_SELECT = clickEventButtonId119;
        ClickEventButtonId clickEventButtonId120 = new ClickEventButtonId("CREATE_VR_INVITE_DESTINATION_UPDATE", 119, "create_vr_invite_destination_update");
        CREATE_VR_INVITE_DESTINATION_UPDATE = clickEventButtonId120;
        ClickEventButtonId clickEventButtonId121 = new ClickEventButtonId("CREATE_VR_INVITE_PROFILE_CONFIRM", 120, "create_vr_invite_profile_confirm");
        CREATE_VR_INVITE_PROFILE_CONFIRM = clickEventButtonId121;
        ClickEventButtonId clickEventButtonId122 = new ClickEventButtonId("CREATE_VR_INVITE_SEND_INVITES", 121, "create_vr_invite_send_invites");
        CREATE_VR_INVITE_SEND_INVITES = clickEventButtonId122;
        ClickEventButtonId clickEventButtonId123 = new ClickEventButtonId("JOIN_PARTY_OPEN", 122, "join_party_open");
        JOIN_PARTY_OPEN = clickEventButtonId123;
        ClickEventButtonId clickEventButtonId124 = new ClickEventButtonId("JOIN_PARTY_CONFIRM", 123, "join_party_confirm");
        JOIN_PARTY_CONFIRM = clickEventButtonId124;
        ClickEventButtonId clickEventButtonId125 = new ClickEventButtonId("JOIN_PARTY_CANCEL", 124, "join_party_cancel");
        JOIN_PARTY_CANCEL = clickEventButtonId125;
        ClickEventButtonId clickEventButtonId126 = new ClickEventButtonId("PARTY_PRIVACY_CLOSE", 125, "PARTY_PRIVACY_CLOSE");
        PARTY_PRIVACY_CLOSE = clickEventButtonId126;
        ClickEventButtonId clickEventButtonId127 = new ClickEventButtonId("PARTY_PRIVACY_SHARE", 126, "PARTY_PRIVACY_SHARE");
        PARTY_PRIVACY_SHARE = clickEventButtonId127;
        ClickEventButtonId clickEventButtonId128 = new ClickEventButtonId("PARTY_PRIVACY_PARTY_TYPE", 127, "PARTY_PRIVACY_PARTY_TYPE");
        PARTY_PRIVACY_PARTY_TYPE = clickEventButtonId128;
        ClickEventButtonId clickEventButtonId129 = new ClickEventButtonId("PARTY_PRIVACY_LINK_INVITE", 128, "PARTY_PRIVACY_LINK_INVITE");
        PARTY_PRIVACY_LINK_INVITE = clickEventButtonId129;
        ClickEventButtonId clickEventButtonId130 = new ClickEventButtonId("REAUTH_NUX_DIALOG_DELAY_USING_MESSENGER", 129, "REAUTH_NUX_DIALOG_DELAY_USING_MESSENGER");
        REAUTH_NUX_DIALOG_DELAY_USING_MESSENGER = clickEventButtonId130;
        ClickEventButtonId clickEventButtonId131 = new ClickEventButtonId("REAUTH_NUX_DIALOG_CONTINUE_REAUTH", 130, "REAUTH_NUX_DIALOG_CONTINUE_REAUTH");
        REAUTH_NUX_DIALOG_CONTINUE_REAUTH = clickEventButtonId131;
        ClickEventButtonId clickEventButtonId132 = new ClickEventButtonId("REAUTH_NUX_DIALOG_OPEN_MESSENGER", 131, "REAUTH_NUX_DIALOG_OPEN_MESSENGER");
        REAUTH_NUX_DIALOG_OPEN_MESSENGER = clickEventButtonId132;
        ClickEventButtonId clickEventButtonId133 = new ClickEventButtonId("REAUTH_NUX_DIALOG_CONTINUE", 132, "REAUTH_NUX_DIALOG_CONTINUE");
        REAUTH_NUX_DIALOG_CONTINUE = clickEventButtonId133;
        ClickEventButtonId clickEventButtonId134 = new ClickEventButtonId("REAUTH_NUX_DIALOG_TOS_CLICK", 133, "REAUTH_NUX_DIALOG_TOS_CLICK");
        REAUTH_NUX_DIALOG_TOS_CLICK = clickEventButtonId134;
        ClickEventButtonId clickEventButtonId135 = new ClickEventButtonId("NO_BUTTON", 134, "NO_BUTTON");
        NO_BUTTON = clickEventButtonId135;
        ClickEventButtonId clickEventButtonId136 = new ClickEventButtonId("START_MESSENGER_CALL_CONFIRM", 135, "START_MESSENGER_CALL_CONFIRM");
        START_MESSENGER_CALL_CONFIRM = clickEventButtonId136;
        ClickEventButtonId clickEventButtonId137 = new ClickEventButtonId("START_MESSENGER_CALL_CANCEL", 136, "START_MESSENGER_CALL_CANCEL");
        START_MESSENGER_CALL_CANCEL = clickEventButtonId137;
        ClickEventButtonId[] clickEventButtonIdArr = new ClickEventButtonId[137];
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId, clickEventButtonId2, clickEventButtonId3, clickEventButtonId4, clickEventButtonId5, clickEventButtonId6, clickEventButtonId7, clickEventButtonId8, clickEventButtonId9, clickEventButtonId10, clickEventButtonId11, clickEventButtonId12, clickEventButtonId13, clickEventButtonId14, clickEventButtonId15, clickEventButtonId16, clickEventButtonId17, clickEventButtonId18, clickEventButtonId19, clickEventButtonId20, clickEventButtonId21, clickEventButtonId22, clickEventButtonId23, clickEventButtonId24, clickEventButtonId25, clickEventButtonId26, clickEventButtonId27}, 0, clickEventButtonIdArr, 0, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId28, clickEventButtonId29, clickEventButtonId30, clickEventButtonId31, clickEventButtonId32, clickEventButtonId33, clickEventButtonId34, clickEventButtonId35, clickEventButtonId36, clickEventButtonId37, clickEventButtonId38, clickEventButtonId39, clickEventButtonId40, clickEventButtonId41, clickEventButtonId42, clickEventButtonId43, clickEventButtonId44, clickEventButtonId45, clickEventButtonId46, clickEventButtonId47, clickEventButtonId48, clickEventButtonId49, clickEventButtonId50, clickEventButtonId51, clickEventButtonId52, clickEventButtonId53, clickEventButtonId54}, 0, clickEventButtonIdArr, 27, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId55, clickEventButtonId56, clickEventButtonId57, clickEventButtonId58, clickEventButtonId59, clickEventButtonId60, clickEventButtonId61, clickEventButtonId62, clickEventButtonId63, clickEventButtonId64, clickEventButtonId65, clickEventButtonId66, clickEventButtonId67, clickEventButtonId68, clickEventButtonId69, clickEventButtonId70, clickEventButtonId71, clickEventButtonId72, clickEventButtonId73, clickEventButtonId74, clickEventButtonId75, clickEventButtonId76, clickEventButtonId77, clickEventButtonId78, clickEventButtonId79, clickEventButtonId80, clickEventButtonId81}, 0, clickEventButtonIdArr, 54, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId82, clickEventButtonId83, clickEventButtonId84, clickEventButtonId85, clickEventButtonId86, clickEventButtonId87, clickEventButtonId88, clickEventButtonId89, clickEventButtonId90, clickEventButtonId91, clickEventButtonId92, clickEventButtonId93, clickEventButtonId94, clickEventButtonId95, clickEventButtonId96, clickEventButtonId97, clickEventButtonId98, clickEventButtonId99, clickEventButtonId100, clickEventButtonId101, clickEventButtonId102, clickEventButtonId103, clickEventButtonId104, clickEventButtonId105, clickEventButtonId106, clickEventButtonId107, clickEventButtonId108}, 0, clickEventButtonIdArr, 81, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId109, clickEventButtonId110, clickEventButtonId111, clickEventButtonId112, clickEventButtonId113, clickEventButtonId114, clickEventButtonId115, clickEventButtonId116, clickEventButtonId117, clickEventButtonId118, clickEventButtonId119, clickEventButtonId120, clickEventButtonId121, clickEventButtonId122, clickEventButtonId123, clickEventButtonId124, clickEventButtonId125, clickEventButtonId126, clickEventButtonId127, clickEventButtonId128, clickEventButtonId129, clickEventButtonId130, clickEventButtonId131, clickEventButtonId132, clickEventButtonId133, clickEventButtonId134, clickEventButtonId135}, 0, clickEventButtonIdArr, 108, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId136, clickEventButtonId137}, 0, clickEventButtonIdArr, 135, 2);
        $VALUES = clickEventButtonIdArr;
    }

    public static ClickEventButtonId valueOf(String str) {
        return (ClickEventButtonId) Enum.valueOf(ClickEventButtonId.class, str);
    }

    public static ClickEventButtonId[] values() {
        return (ClickEventButtonId[]) $VALUES.clone();
    }

    public String getTelemetryButtonId() {
        return this.mTelemetryButtonId;
    }

    public ClickEventButtonId(String str, int i, String str2) {
        this.mTelemetryButtonId = str2;
    }
}
