package com.oculus.tablet.logging;

import X.AnonymousClass006;
import com.oculus.vrshell.panels.telemetry.SourceConstants;

/* JADX INFO: Failed to restore enum class, 'enum' modifier removed */
public final class ClickEventButtonId extends Enum<ClickEventButtonId> {
    public static final /* synthetic */ ClickEventButtonId[] $VALUES;
    public static final ClickEventButtonId AUIV2_ACTIVE_CALL_BAR_ACTIVE_CALL_BUTTON;
    public static final ClickEventButtonId AUIV2_ACTIVE_CALL_BAR_CALL_VOLUME;
    public static final ClickEventButtonId AUIV2_ACTIVE_CALL_BAR_END_CALL;
    public static final ClickEventButtonId AUIV2_ACTIVE_CALL_BAR_MICROPHONE_APP_CHAT;
    public static final ClickEventButtonId AUIV2_ACTIVE_CALL_BAR_MICROPHONE_CONTROLS;
    public static final ClickEventButtonId AUIV2_ACTIVE_CALL_BAR_MICROPHONE_CONTROLS_BACK;
    public static final ClickEventButtonId AUIV2_ACTIVE_CALL_BAR_MICROPHONE_MUTE;
    public static final ClickEventButtonId AUIV2_ACTIVE_CALL_BAR_MICROPHONE_PARTY_CHAT;
    public static final ClickEventButtonId AUIV2_ACTIVE_CALL_BAR_VOLUME_ADJUSTMENT_BACK;
    public static final ClickEventButtonId AUIV2_APPS_APP_LAUNCH;
    public static final ClickEventButtonId AUIV2_APPS_BROWSER;
    public static final ClickEventButtonId AUIV2_APPS_EXPLORE;
    public static final ClickEventButtonId AUIV2_APPS_SOCIAL;
    public static final ClickEventButtonId AUIV2_APPS_STORE;
    public static final ClickEventButtonId AUIV2_APPS_TV;
    public static final ClickEventButtonId AUIV2_BAR_DEBUG_BUGREPORT;
    public static final ClickEventButtonId AUIV2_BAR_DEBUG_DOGFOODING;
    public static final ClickEventButtonId AUIV2_BAR_DEBUG_INTERNAL_SETTINGS;
    public static final ClickEventButtonId AUIV2_BAR_DESTINATION_UI;
    public static final ClickEventButtonId AUIV2_BAR_EXPLORE;
    public static final ClickEventButtonId AUIV2_BAR_LIBRARY;
    public static final ClickEventButtonId AUIV2_BAR_MESSENGER;
    public static final ClickEventButtonId AUIV2_BAR_NOTIFICATIONS;
    public static final ClickEventButtonId AUIV2_BAR_PROFILE;
    public static final ClickEventButtonId AUIV2_BAR_SETTINGS;
    public static final ClickEventButtonId AUIV2_BAR_SHARING;
    public static final ClickEventButtonId AUIV2_BAR_SOCIAL;
    public static final ClickEventButtonId AUIV2_BAR_STORE;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_CASTING;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_CASTING_STOP;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_INSTANT_REPLAY_SAVE;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_INVITE;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_LIVESTREAM;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_LIVESTREAM_STOP;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_QUIT;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_RECORD_ABUSE_VIDEO_STOP;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_RECORD_VIDEO;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_RECORD_VIDEO_STOP;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_REPORT;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_RESTART;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_RESUME;
    public static final ClickEventButtonId AUIV2_DESTINATION_UI_TAKE_SCREENSHOT;
    public static final ClickEventButtonId AUIV2_ENTERPRISE_PROFILE_ADMIN_KEYPAD_BACKSPACE;
    public static final ClickEventButtonId AUIV2_ENTERPRISE_PROFILE_ADMIN_KEYPAD_NUMBER;
    public static final ClickEventButtonId AUIV2_ENTERPRISE_PROFILE_CHECK_FOR_UPDATES;
    public static final ClickEventButtonId AUIV2_ENTERPRISE_PROFILE_EXIT_ADMIN;
    public static final ClickEventButtonId AUIV2_INTERNAL_SETTINGS_FILE_PICKER;
    public static final ClickEventButtonId AUIV2_INTERNAL_SETTINGS_FILE_PREVIEWER;
    public static final ClickEventButtonId AUIV2_INTERNAL_SETTINGS_LAUNCH_APPS_IN_TABLET_SPACE;
    public static final ClickEventButtonId AUIV2_INTERNAL_SETTINGS_LAUNCH_APPS_IN_TABLET_SPACE_SIZING_MODE_SELECTOR;
    public static final ClickEventButtonId AUIV2_INTERNAL_SETTINGS_PIN_DEBUG_BAR;
    public static final ClickEventButtonId AUIV2_INTERNAL_SETTINGS_SHELL_DEBUG;
    public static final ClickEventButtonId AUIV2_LIBRARY_APP_LAUNCH;
    public static final ClickEventButtonId AUIV2_LIBRARY_BROWSER;
    public static final ClickEventButtonId AUIV2_LIBRARY_CAMERA_ROLL;
    public static final ClickEventButtonId AUIV2_LIBRARY_HOME;
    public static final ClickEventButtonId AUIV2_LIBRARY_LAM_DISCLAIMER;
    public static final ClickEventButtonId AUIV2_LIBRARY_SOCIAL;
    public static final ClickEventButtonId AUIV2_LIBRARY_STORE;
    public static final ClickEventButtonId AUIV2_LIBRARY_STORE_GET_MORE_APPS;
    public static final ClickEventButtonId AUIV2_LIBRARY_TV;
    public static final ClickEventButtonId AUIV2_LIBRARY_UNKNOWN_SOURCES_CONTENT_GUIDELINES;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_ACCEPT_ACTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_ACCEPT_INVITE_ACTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_ALL_SECTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_APPS_SECTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_CANCEL_DOWNLOAD_ACTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_DEVICE_SECTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_DISMISS_ACTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_DOWNLOADS_SECTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_ITEM;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_LAUNCH_CAMERA_ROLL_ACTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_LAUNCH_CONTENT_ACTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_PHONE_EMPTY_CTA;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_PHONE_SECTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_RETRY_ACTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_SEE_MORE_ACTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_SOCIAL_SECTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_STORE_SECTION;
    public static final ClickEventButtonId AUIV2_NOTIFICATIONS_SYSTEM_SECTION;
    public static final ClickEventButtonId AUIV2_PROFILE_ACCEPT_FRIEND_REQUEST;
    public static final ClickEventButtonId AUIV2_PROFILE_ADD_FRIEND;
    public static final ClickEventButtonId AUIV2_PROFILE_AVATAR_EDITOR;
    public static final ClickEventButtonId AUIV2_PROFILE_BACK;
    public static final ClickEventButtonId AUIV2_PROFILE_BLOCK_FB_USER;
    public static final ClickEventButtonId AUIV2_PROFILE_BLOCK_VR_USER;
    public static final ClickEventButtonId AUIV2_PROFILE_CANCEL_FRIEND_REQUEST;
    public static final ClickEventButtonId AUIV2_PROFILE_CHAT_IN_MESSENGER;
    public static final ClickEventButtonId AUIV2_PROFILE_COMPLETE_PROFILE;
    public static final ClickEventButtonId AUIV2_PROFILE_CONFIRM_EDIT;
    public static final ClickEventButtonId AUIV2_PROFILE_CONFIRM_EDIT_BIO_CHANGED;
    public static final ClickEventButtonId AUIV2_PROFILE_CONFIRM_EDIT_FAIL_CANCEL;
    public static final ClickEventButtonId AUIV2_PROFILE_CONFIRM_EDIT_FAIL_RETRY;
    public static final ClickEventButtonId AUIV2_PROFILE_CREATE_PARTY;
    public static final ClickEventButtonId AUIV2_PROFILE_EDIT_PROFILE;
    public static final ClickEventButtonId AUIV2_PROFILE_FB_CREATE_PARTY;
    public static final ClickEventButtonId AUIV2_PROFILE_FB_INVITE_TO_PARTY;
    public static final ClickEventButtonId AUIV2_PROFILE_FB_JOIN_PARTY;
    public static final ClickEventButtonId AUIV2_PROFILE_OC_CHAT;
    public static final ClickEventButtonId AUIV2_PROFILE_OVERFLOW_MENU;
    public static final ClickEventButtonId AUIV2_PROFILE_PARTY_INVITE;
    public static final ClickEventButtonId AUIV2_PROFILE_PARTY_JOIN;
    public static final ClickEventButtonId AUIV2_PROFILE_PHOTO_EDITOR;
    public static final ClickEventButtonId AUIV2_PROFILE_PRIVACY_SETTINGS;
    public static final ClickEventButtonId AUIV2_PROFILE_REJECT_FRIEND_REQUEST;
    public static final ClickEventButtonId AUIV2_PROFILE_REPORT_FB_USER;
    public static final ClickEventButtonId AUIV2_PROFILE_REPORT_VR_USER;
    public static final ClickEventButtonId AUIV2_PROFILE_SHARE_PROFILE;
    public static final ClickEventButtonId AUIV2_PROFILE_UNBLOCK_VR_USER;
    public static final ClickEventButtonId AUIV2_PROFILE_UNFRIEND_USER;
    public static final ClickEventButtonId AUIV2_PROFILE_VIEW_PROFILE;
    public static final ClickEventButtonId AUIV2_QP_GUIDE_BAR_CTA;
    public static final ClickEventButtonId AUIV2_QP_GUIDE_BAR_DISMISS;
    public static final ClickEventButtonId AUIV2_QP_TOOLTIP_DISMISS;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_BRIGHTNESS;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_CHANGE_DATE_TIME;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_DO_NO_DISTURB;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_FULL_SETTINGS;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_GUARDIAN;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_HANDS;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_MICROPHONE;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_NIGHT_DISPLAY;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_REALITY_TUNER;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_RESET_VIEW;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_VOLUME;
    public static final ClickEventButtonId AUIV2_QUICK_SETTINGS_WIFI;
    public static final ClickEventButtonId AUIV2_SETTINGS_ASSISTANT;
    public static final ClickEventButtonId AUIV2_SETTINGS_BRIGHTNESS;
    public static final ClickEventButtonId AUIV2_SETTINGS_BUG_REPORT;
    public static final ClickEventButtonId AUIV2_SETTINGS_DO_NO_DISTURB;
    public static final ClickEventButtonId AUIV2_SETTINGS_GUARDIAN;
    public static final ClickEventButtonId AUIV2_SETTINGS_HANDS;
    public static final ClickEventButtonId AUIV2_SETTINGS_MICROPHONE;
    public static final ClickEventButtonId AUIV2_SETTINGS_NIGHT_DISPLAY;
    public static final ClickEventButtonId AUIV2_SETTINGS_OCULUS_LINK;
    public static final ClickEventButtonId AUIV2_SETTINGS_REALITY_TUNER;
    public static final ClickEventButtonId AUIV2_SETTINGS_RESET_VIEW;
    public static final ClickEventButtonId AUIV2_SETTINGS_VOLUME;
    public static final ClickEventButtonId AUIV2_SETTINGS_WIFI;
    public static final ClickEventButtonId AUIV2_SHARING_CAMERA_ROLL;
    public static final ClickEventButtonId AUIV2_SHARING_CASTING;
    public static final ClickEventButtonId AUIV2_SHARING_CASTING_STOP;
    public static final ClickEventButtonId AUIV2_SHARING_LIVESTREAM;
    public static final ClickEventButtonId AUIV2_SHARING_LIVESTREAM_STOP;
    public static final ClickEventButtonId AUIV2_SHARING_RECENT_TILE;
    public static final ClickEventButtonId AUIV2_SHARING_RECENT_TILE_1;
    public static final ClickEventButtonId AUIV2_SHARING_RECENT_TILE_2;
    public static final ClickEventButtonId AUIV2_SHARING_RECENT_TILE_3;
    public static final ClickEventButtonId AUIV2_SHARING_RECENT_TILE_4;
    public static final ClickEventButtonId AUIV2_SHARING_RECENT_TILE_5;
    public static final ClickEventButtonId AUIV2_SHARING_RECORD_ABUSE_VIDEO_STOP;
    public static final ClickEventButtonId AUIV2_SHARING_RECORD_VIDEO;
    public static final ClickEventButtonId AUIV2_SHARING_RECORD_VIDEO_STOP;
    public static final ClickEventButtonId AUIV2_SHARING_TAKE_SCREENSHOT;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_BLOCK_DIALOG_CANCEL;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_BLOCK_DIALOG_CONFIRM;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_BLOCK_DIALOG_OPEN;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_CARD_CHAT_START;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_CARD_PARTY_START;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_CARD_PROFILE_VIEW;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_CARD_REPORT;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_CARD_UNFRIEND;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_FRIEND_ADD;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_NAVIGATE_TO_PARTY;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_ROW_CHAT_START;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_ROW_PARTY_START;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_ROW_PROFILE_VIEW;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_ROW_REPORT;
    public static final ClickEventButtonId AUIV2_SOCIAL_FRIENDS_ROW_UNFRIEND;
    public static final ClickEventButtonId AUIV2_SOCIAL_GUIDED_ACTION_ADD_FRIEND;
    public static final ClickEventButtonId AUIV2_SOCIAL_GUIDED_ACTION_AVATAR;
    public static final ClickEventButtonId AUIV2_SOCIAL_GUIDED_ACTION_FB_LINK;
    public static final ClickEventButtonId AUIV2_SOCIAL_GUIDED_ACTION_FIND_EVENTS;
    public static final ClickEventButtonId AUIV2_SOCIAL_GUIDED_ACTION_SHARE_PROFILE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_ACCEPT_PARTY_INVITE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_CARD_FRIEND_INVITE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GOTO_USER_FROM_USER_CARD;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GOTO_USER_FROM_USER_VIEW;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_ACCEPT_RESPONSE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_APP_LAUNCH_DIALOG_LEADER_VIEW_CANCEL;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_APP_LAUNCH_DIALOG_MEMBER_VIEW_CANCEL;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_CANCEL;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_CANCEL_RESPONSE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_CREATE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_JOIN_LEADER;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_LAUNCH;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_LAUNCH_SOLO;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_LEAVE_PARTY;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_REJECT_RESPONSE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_SELECT_NEW_DESTINATION;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_TRAVEL_TO_LAUNCH_APP;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_VIEW_APP_DETAILS;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_INVITE_DIALOG_CANCEL;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_INVITE_DIALOG_OPEN;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_INVITE_DIALOG_SEND;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_JOIN_OPEN_PARTY;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_LEAVE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_MUTE_SELF;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_NAVIGATE_TO_FRIENDS;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_PARTY_INVITE_SUCCESS;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_PARTY_JOIN_SUCCESS;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_PARTY_KICK_START;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_PARTY_KICK_SUCCESS;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_PARTY_LEAVE_SUCCESS;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_PER_PERSON_MUTE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_PER_PERSON_UNMUTE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_PRIVACY_DIALOG_CANCEL;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_PRIVACY_DIALOG_OPEN;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_REPORT;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_ROW_FRIEND_INVITE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_START_DIALOG_CANCEL;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_START_DIALOG_CREATE;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_START_DIALOG_OPEN;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_START_PARTY_SUCCESS;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_UNMUTE_SELF;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_UPDATE_PRIVACY_CLOSED;
    public static final ClickEventButtonId AUIV2_SOCIAL_PARTIES_UPDATE_PRIVACY_OPEN;
    public static final ClickEventButtonId AUIV2_SOCIAL_PYMK_CARD_DISMISS;
    public static final ClickEventButtonId AUIV2_SOCIAL_PYMK_CARD_SEND_REQUEST;
    public static final ClickEventButtonId AUIV2_SOCIAL_PYMK_ROW_DISMISS;
    public static final ClickEventButtonId AUIV2_SOCIAL_PYMK_ROW_SEND_REQUEST;
    public static final ClickEventButtonId AUIV2_SOCIAL_REQUESTS_ACCEPT_FRIEND;
    public static final ClickEventButtonId AUIV2_SOCIAL_REQUESTS_REJECT_FRIEND;
    public static final ClickEventButtonId AUIV2_SOCIAL_SHARE_PARTY;
    public static final ClickEventButtonId AUIV2_SOCIAL_UPSELL_FB_LINK;
    public static final ClickEventButtonId AUIV2_SOCIAL_UPSELL_FRIEND;
    public static final ClickEventButtonId AUIV2_STATUS_TIME;
    public static final ClickEventButtonId AUIV2_STATUS_WIFI;
    public static final ClickEventButtonId AUIV2_SYSTEM_STATUS_NOTIFICATIONS;
    public static final ClickEventButtonId AUIV2_SYSTEM_STATUS_PROFILE;
    public static final ClickEventButtonId AUIV2_SYSTEM_STATUS_QUICK_SETTINGS;
    public static final ClickEventButtonId TRY_AUIV2;
    public final String mTelemetryButtonId;

    public static ClickEventButtonId valueOf(String str) {
        return (ClickEventButtonId) Enum.valueOf(ClickEventButtonId.class, str);
    }

    public static ClickEventButtonId[] values() {
        return (ClickEventButtonId[]) $VALUES.clone();
    }

    public String getTelemetryButtonId() {
        return this.mTelemetryButtonId;
    }

    public ClickEventButtonId(String str, int i, String str2) {
        this.mTelemetryButtonId = str2;
    }

    public ClickEventButtonId getSubButtonId(String str) {
        return valueOf(AnonymousClass006.A09(toString(), "_", str));
    }

    static {
        ClickEventButtonId clickEventButtonId = new ClickEventButtonId("AUIV2_ACTIVE_CALL_BAR_ACTIVE_CALL_BUTTON", 0, "auiv2_active_call_bar_full_active_call_button");
        AUIV2_ACTIVE_CALL_BAR_ACTIVE_CALL_BUTTON = clickEventButtonId;
        ClickEventButtonId clickEventButtonId2 = new ClickEventButtonId("AUIV2_ACTIVE_CALL_BAR_CALL_VOLUME", 1, "auiv2_active_call_bar_call_volume");
        AUIV2_ACTIVE_CALL_BAR_CALL_VOLUME = clickEventButtonId2;
        ClickEventButtonId clickEventButtonId3 = new ClickEventButtonId("AUIV2_ACTIVE_CALL_BAR_END_CALL", 2, "auiv2_active_call_bar_end_call");
        AUIV2_ACTIVE_CALL_BAR_END_CALL = clickEventButtonId3;
        ClickEventButtonId clickEventButtonId4 = new ClickEventButtonId("AUIV2_ACTIVE_CALL_BAR_MICROPHONE_APP_CHAT", 3, "auiv2_active_call_bar_microphone_app_chat");
        AUIV2_ACTIVE_CALL_BAR_MICROPHONE_APP_CHAT = clickEventButtonId4;
        ClickEventButtonId clickEventButtonId5 = new ClickEventButtonId("AUIV2_ACTIVE_CALL_BAR_MICROPHONE_CONTROLS", 4, "auiv2_active_call_bar_microphone_controls");
        AUIV2_ACTIVE_CALL_BAR_MICROPHONE_CONTROLS = clickEventButtonId5;
        ClickEventButtonId clickEventButtonId6 = new ClickEventButtonId("AUIV2_ACTIVE_CALL_BAR_MICROPHONE_CONTROLS_BACK", 5, "auiv2_active_call_bar_microphone_controls_back");
        AUIV2_ACTIVE_CALL_BAR_MICROPHONE_CONTROLS_BACK = clickEventButtonId6;
        ClickEventButtonId clickEventButtonId7 = new ClickEventButtonId("AUIV2_ACTIVE_CALL_BAR_MICROPHONE_PARTY_CHAT", 6, "auiv2_active_call_bar_microphone_party_chat");
        AUIV2_ACTIVE_CALL_BAR_MICROPHONE_PARTY_CHAT = clickEventButtonId7;
        ClickEventButtonId clickEventButtonId8 = new ClickEventButtonId("AUIV2_ACTIVE_CALL_BAR_MICROPHONE_MUTE", 7, "auiv2_active_call_bar_microphone_mute");
        AUIV2_ACTIVE_CALL_BAR_MICROPHONE_MUTE = clickEventButtonId8;
        ClickEventButtonId clickEventButtonId9 = new ClickEventButtonId("AUIV2_ACTIVE_CALL_BAR_VOLUME_ADJUSTMENT_BACK", 8, "auiv2_active_call_bar_volume_adjustment_back");
        AUIV2_ACTIVE_CALL_BAR_VOLUME_ADJUSTMENT_BACK = clickEventButtonId9;
        ClickEventButtonId clickEventButtonId10 = new ClickEventButtonId("AUIV2_APPS_APP_LAUNCH", 9, "auiv2_quick_start_app_launch");
        AUIV2_APPS_APP_LAUNCH = clickEventButtonId10;
        ClickEventButtonId clickEventButtonId11 = new ClickEventButtonId("AUIV2_APPS_BROWSER", 10, "auiv2_quick_start_browser");
        AUIV2_APPS_BROWSER = clickEventButtonId11;
        ClickEventButtonId clickEventButtonId12 = new ClickEventButtonId("AUIV2_APPS_EXPLORE", 11, "auiv2_quick_start_explore");
        AUIV2_APPS_EXPLORE = clickEventButtonId12;
        ClickEventButtonId clickEventButtonId13 = new ClickEventButtonId("AUIV2_APPS_SOCIAL", 12, "auiv2_quick_start_social");
        AUIV2_APPS_SOCIAL = clickEventButtonId13;
        ClickEventButtonId clickEventButtonId14 = new ClickEventButtonId("AUIV2_APPS_STORE", 13, "auiv2_quick_start_store");
        AUIV2_APPS_STORE = clickEventButtonId14;
        ClickEventButtonId clickEventButtonId15 = new ClickEventButtonId("AUIV2_APPS_TV", 14, "auiv2_quick_start_tv");
        AUIV2_APPS_TV = clickEventButtonId15;
        ClickEventButtonId clickEventButtonId16 = new ClickEventButtonId("AUIV2_BAR_DEBUG_BUGREPORT", 15, "auiv2_bar_debug_bugreport");
        AUIV2_BAR_DEBUG_BUGREPORT = clickEventButtonId16;
        ClickEventButtonId clickEventButtonId17 = new ClickEventButtonId("AUIV2_BAR_DEBUG_DOGFOODING", 16, "auiv2_bar_debug_dogfooding");
        AUIV2_BAR_DEBUG_DOGFOODING = clickEventButtonId17;
        ClickEventButtonId clickEventButtonId18 = new ClickEventButtonId("AUIV2_BAR_DEBUG_INTERNAL_SETTINGS", 17, "auiv2_bar_debug_internal_settings");
        AUIV2_BAR_DEBUG_INTERNAL_SETTINGS = clickEventButtonId18;
        ClickEventButtonId clickEventButtonId19 = new ClickEventButtonId("AUIV2_BAR_DESTINATION_UI", 18, "auiv2_bar_destination_ui");
        AUIV2_BAR_DESTINATION_UI = clickEventButtonId19;
        ClickEventButtonId clickEventButtonId20 = new ClickEventButtonId("AUIV2_BAR_EXPLORE", 19, "auiv2_bar_explore");
        AUIV2_BAR_EXPLORE = clickEventButtonId20;
        ClickEventButtonId clickEventButtonId21 = new ClickEventButtonId("AUIV2_BAR_LIBRARY", 20, "auiv2_bar_library");
        AUIV2_BAR_LIBRARY = clickEventButtonId21;
        ClickEventButtonId clickEventButtonId22 = new ClickEventButtonId("AUIV2_BAR_MESSENGER", 21, "auiv2_bar_messenger");
        AUIV2_BAR_MESSENGER = clickEventButtonId22;
        ClickEventButtonId clickEventButtonId23 = new ClickEventButtonId("AUIV2_BAR_NOTIFICATIONS", 22, "auiv2_bar_notifications");
        AUIV2_BAR_NOTIFICATIONS = clickEventButtonId23;
        ClickEventButtonId clickEventButtonId24 = new ClickEventButtonId("AUIV2_BAR_PROFILE", 23, "auiv2_bar_profile");
        AUIV2_BAR_PROFILE = clickEventButtonId24;
        ClickEventButtonId clickEventButtonId25 = new ClickEventButtonId("AUIV2_BAR_SETTINGS", 24, "auiv2_bar_settings");
        AUIV2_BAR_SETTINGS = clickEventButtonId25;
        ClickEventButtonId clickEventButtonId26 = new ClickEventButtonId("AUIV2_BAR_SHARING", 25, "auiv2_bar_sharing");
        AUIV2_BAR_SHARING = clickEventButtonId26;
        ClickEventButtonId clickEventButtonId27 = new ClickEventButtonId("AUIV2_BAR_SOCIAL", 26, "auiv2_bar_social");
        AUIV2_BAR_SOCIAL = clickEventButtonId27;
        ClickEventButtonId clickEventButtonId28 = new ClickEventButtonId("AUIV2_BAR_STORE", 27, "auiv2_bar_store");
        AUIV2_BAR_STORE = clickEventButtonId28;
        ClickEventButtonId clickEventButtonId29 = new ClickEventButtonId("AUIV2_ENTERPRISE_PROFILE_ADMIN_KEYPAD_BACKSPACE", 28, "auiv2_enterprise_profile_admin_keypad_backspace");
        AUIV2_ENTERPRISE_PROFILE_ADMIN_KEYPAD_BACKSPACE = clickEventButtonId29;
        ClickEventButtonId clickEventButtonId30 = new ClickEventButtonId("AUIV2_ENTERPRISE_PROFILE_ADMIN_KEYPAD_NUMBER", 29, "auiv2_enterprise_profile_admin_keypad_number");
        AUIV2_ENTERPRISE_PROFILE_ADMIN_KEYPAD_NUMBER = clickEventButtonId30;
        ClickEventButtonId clickEventButtonId31 = new ClickEventButtonId("AUIV2_ENTERPRISE_PROFILE_CHECK_FOR_UPDATES", 30, "auiv2_enterprise_profile_check_for_updates");
        AUIV2_ENTERPRISE_PROFILE_CHECK_FOR_UPDATES = clickEventButtonId31;
        ClickEventButtonId clickEventButtonId32 = new ClickEventButtonId("AUIV2_ENTERPRISE_PROFILE_EXIT_ADMIN", 31, "auiv2_enterprise_profile_exit_admin");
        AUIV2_ENTERPRISE_PROFILE_EXIT_ADMIN = clickEventButtonId32;
        ClickEventButtonId clickEventButtonId33 = new ClickEventButtonId("AUIV2_INTERNAL_SETTINGS_FILE_PICKER", 32, "auiv2_internal_settings_file_picker");
        AUIV2_INTERNAL_SETTINGS_FILE_PICKER = clickEventButtonId33;
        ClickEventButtonId clickEventButtonId34 = new ClickEventButtonId("AUIV2_INTERNAL_SETTINGS_FILE_PREVIEWER", 33, "auiv2_internal_settings_file_previewer");
        AUIV2_INTERNAL_SETTINGS_FILE_PREVIEWER = clickEventButtonId34;
        ClickEventButtonId clickEventButtonId35 = new ClickEventButtonId("AUIV2_INTERNAL_SETTINGS_LAUNCH_APPS_IN_TABLET_SPACE", 34, "auiv2_internal_settings_launch_apps_in_tablet_space");
        AUIV2_INTERNAL_SETTINGS_LAUNCH_APPS_IN_TABLET_SPACE = clickEventButtonId35;
        ClickEventButtonId clickEventButtonId36 = new ClickEventButtonId("AUIV2_INTERNAL_SETTINGS_LAUNCH_APPS_IN_TABLET_SPACE_SIZING_MODE_SELECTOR", 35, "auiv2_internal_settings_launch_apps_in_tablet_space_sizing_mode_selector");
        AUIV2_INTERNAL_SETTINGS_LAUNCH_APPS_IN_TABLET_SPACE_SIZING_MODE_SELECTOR = clickEventButtonId36;
        ClickEventButtonId clickEventButtonId37 = new ClickEventButtonId("AUIV2_INTERNAL_SETTINGS_PIN_DEBUG_BAR", 36, "auiv2_internal_settings_pin_debug_bar");
        AUIV2_INTERNAL_SETTINGS_PIN_DEBUG_BAR = clickEventButtonId37;
        ClickEventButtonId clickEventButtonId38 = new ClickEventButtonId("AUIV2_INTERNAL_SETTINGS_SHELL_DEBUG", 37, "auiv2_internal_settings_shell_debug");
        AUIV2_INTERNAL_SETTINGS_SHELL_DEBUG = clickEventButtonId38;
        ClickEventButtonId clickEventButtonId39 = new ClickEventButtonId("AUIV2_LIBRARY_APP_LAUNCH", 38, "auiv2_library_app_launch");
        AUIV2_LIBRARY_APP_LAUNCH = clickEventButtonId39;
        ClickEventButtonId clickEventButtonId40 = new ClickEventButtonId("AUIV2_LIBRARY_BROWSER", 39, "auiv2_library_browser");
        AUIV2_LIBRARY_BROWSER = clickEventButtonId40;
        ClickEventButtonId clickEventButtonId41 = new ClickEventButtonId("AUIV2_LIBRARY_HOME", 40, "auiv2_library_home");
        AUIV2_LIBRARY_HOME = clickEventButtonId41;
        ClickEventButtonId clickEventButtonId42 = new ClickEventButtonId("AUIV2_LIBRARY_SOCIAL", 41, "auiv2_library_social");
        AUIV2_LIBRARY_SOCIAL = clickEventButtonId42;
        ClickEventButtonId clickEventButtonId43 = new ClickEventButtonId("AUIV2_LIBRARY_STORE", 42, "auiv2_library_store");
        AUIV2_LIBRARY_STORE = clickEventButtonId43;
        ClickEventButtonId clickEventButtonId44 = new ClickEventButtonId("AUIV2_LIBRARY_STORE_GET_MORE_APPS", 43, "auiv2_library_store_get_more_apps");
        AUIV2_LIBRARY_STORE_GET_MORE_APPS = clickEventButtonId44;
        ClickEventButtonId clickEventButtonId45 = new ClickEventButtonId("AUIV2_LIBRARY_TV", 44, "auiv2_library_tv");
        AUIV2_LIBRARY_TV = clickEventButtonId45;
        ClickEventButtonId clickEventButtonId46 = new ClickEventButtonId("AUIV2_LIBRARY_CAMERA_ROLL", 45, "auiv2_library_camera_roll");
        AUIV2_LIBRARY_CAMERA_ROLL = clickEventButtonId46;
        ClickEventButtonId clickEventButtonId47 = new ClickEventButtonId("AUIV2_LIBRARY_UNKNOWN_SOURCES_CONTENT_GUIDELINES", 46, "auiv2_library_unknown_sources_content_guidelines");
        AUIV2_LIBRARY_UNKNOWN_SOURCES_CONTENT_GUIDELINES = clickEventButtonId47;
        ClickEventButtonId clickEventButtonId48 = new ClickEventButtonId("AUIV2_LIBRARY_LAM_DISCLAIMER", 47, "auiv2_library_lam_disclaimer");
        AUIV2_LIBRARY_LAM_DISCLAIMER = clickEventButtonId48;
        ClickEventButtonId clickEventButtonId49 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_ACCEPT_ACTION", 48, "auiv2_notifications_accept_action");
        AUIV2_NOTIFICATIONS_ACCEPT_ACTION = clickEventButtonId49;
        ClickEventButtonId clickEventButtonId50 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_ACCEPT_INVITE_ACTION", 49, "auiv2_notifications_accept_invite_action");
        AUIV2_NOTIFICATIONS_ACCEPT_INVITE_ACTION = clickEventButtonId50;
        ClickEventButtonId clickEventButtonId51 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_ALL_SECTION", 50, "auiv2_notifications_all_section");
        AUIV2_NOTIFICATIONS_ALL_SECTION = clickEventButtonId51;
        ClickEventButtonId clickEventButtonId52 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_APPS_SECTION", 51, "auiv2_notifications_apps_section");
        AUIV2_NOTIFICATIONS_APPS_SECTION = clickEventButtonId52;
        ClickEventButtonId clickEventButtonId53 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_CANCEL_DOWNLOAD_ACTION", 52, "auiv2_notifications_cancel_download_action");
        AUIV2_NOTIFICATIONS_CANCEL_DOWNLOAD_ACTION = clickEventButtonId53;
        ClickEventButtonId clickEventButtonId54 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_DEVICE_SECTION", 53, "auiv2_notifications_device_section");
        AUIV2_NOTIFICATIONS_DEVICE_SECTION = clickEventButtonId54;
        ClickEventButtonId clickEventButtonId55 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_DISMISS_ACTION", 54, "auiv2_notifications_dismiss_action");
        AUIV2_NOTIFICATIONS_DISMISS_ACTION = clickEventButtonId55;
        ClickEventButtonId clickEventButtonId56 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_DOWNLOADS_SECTION", 55, "auiv2_notifications_downloads_section");
        AUIV2_NOTIFICATIONS_DOWNLOADS_SECTION = clickEventButtonId56;
        ClickEventButtonId clickEventButtonId57 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_ITEM", 56, "auiv2_notifications_item");
        AUIV2_NOTIFICATIONS_ITEM = clickEventButtonId57;
        ClickEventButtonId clickEventButtonId58 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_LAUNCH_CAMERA_ROLL_ACTION", 57, "auiv2_notifications_launch_camera_roll_action");
        AUIV2_NOTIFICATIONS_LAUNCH_CAMERA_ROLL_ACTION = clickEventButtonId58;
        ClickEventButtonId clickEventButtonId59 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_LAUNCH_CONTENT_ACTION", 58, "auiv2_notifications_launch_content_action");
        AUIV2_NOTIFICATIONS_LAUNCH_CONTENT_ACTION = clickEventButtonId59;
        ClickEventButtonId clickEventButtonId60 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_PHONE_EMPTY_CTA", 59, "auiv2_notifications_phone_empty_cta");
        AUIV2_NOTIFICATIONS_PHONE_EMPTY_CTA = clickEventButtonId60;
        ClickEventButtonId clickEventButtonId61 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_PHONE_SECTION", 60, "auiv2_notifications_phone_action");
        AUIV2_NOTIFICATIONS_PHONE_SECTION = clickEventButtonId61;
        ClickEventButtonId clickEventButtonId62 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_RETRY_ACTION", 61, "auiv2_notifications_retry_action");
        AUIV2_NOTIFICATIONS_RETRY_ACTION = clickEventButtonId62;
        ClickEventButtonId clickEventButtonId63 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_SEE_MORE_ACTION", 62, "auiv2_notifications_see_more_action");
        AUIV2_NOTIFICATIONS_SEE_MORE_ACTION = clickEventButtonId63;
        ClickEventButtonId clickEventButtonId64 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_SOCIAL_SECTION", 63, "auiv2_notifications_social_section");
        AUIV2_NOTIFICATIONS_SOCIAL_SECTION = clickEventButtonId64;
        ClickEventButtonId clickEventButtonId65 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_STORE_SECTION", 64, "auiv2_notifications_store_section");
        AUIV2_NOTIFICATIONS_STORE_SECTION = clickEventButtonId65;
        ClickEventButtonId clickEventButtonId66 = new ClickEventButtonId("AUIV2_NOTIFICATIONS_SYSTEM_SECTION", 65, "auiv2_notifications_system_section");
        AUIV2_NOTIFICATIONS_SYSTEM_SECTION = clickEventButtonId66;
        ClickEventButtonId clickEventButtonId67 = new ClickEventButtonId("AUIV2_DESTINATION_UI_CASTING", 66, "auiv2_pause_casting");
        AUIV2_DESTINATION_UI_CASTING = clickEventButtonId67;
        ClickEventButtonId clickEventButtonId68 = new ClickEventButtonId("AUIV2_DESTINATION_UI_CASTING_STOP", 67, "auiv2_pause_casting_stop");
        AUIV2_DESTINATION_UI_CASTING_STOP = clickEventButtonId68;
        ClickEventButtonId clickEventButtonId69 = new ClickEventButtonId("AUIV2_DESTINATION_UI_INSTANT_REPLAY_SAVE", 68, "auiv2_pause_instant_replay_save");
        AUIV2_DESTINATION_UI_INSTANT_REPLAY_SAVE = clickEventButtonId69;
        ClickEventButtonId clickEventButtonId70 = new ClickEventButtonId("AUIV2_DESTINATION_UI_INVITE", 69, "auiv2_pause_invite");
        AUIV2_DESTINATION_UI_INVITE = clickEventButtonId70;
        ClickEventButtonId clickEventButtonId71 = new ClickEventButtonId("AUIV2_DESTINATION_UI_LIVESTREAM", 70, "auiv2_pause_livestream");
        AUIV2_DESTINATION_UI_LIVESTREAM = clickEventButtonId71;
        ClickEventButtonId clickEventButtonId72 = new ClickEventButtonId("AUIV2_DESTINATION_UI_LIVESTREAM_STOP", 71, "auiv2_pause_livestream_stop");
        AUIV2_DESTINATION_UI_LIVESTREAM_STOP = clickEventButtonId72;
        ClickEventButtonId clickEventButtonId73 = new ClickEventButtonId("AUIV2_DESTINATION_UI_QUIT", 72, "auiv2_pause_quit");
        AUIV2_DESTINATION_UI_QUIT = clickEventButtonId73;
        ClickEventButtonId clickEventButtonId74 = new ClickEventButtonId("AUIV2_DESTINATION_UI_RECORD_VIDEO", 73, "auiv2_pause_record_video");
        AUIV2_DESTINATION_UI_RECORD_VIDEO = clickEventButtonId74;
        ClickEventButtonId clickEventButtonId75 = new ClickEventButtonId("AUIV2_DESTINATION_UI_RECORD_VIDEO_STOP", 74, "auiv2_pause_record_video_stop");
        AUIV2_DESTINATION_UI_RECORD_VIDEO_STOP = clickEventButtonId75;
        ClickEventButtonId clickEventButtonId76 = new ClickEventButtonId("AUIV2_DESTINATION_UI_RECORD_ABUSE_VIDEO_STOP", 75, "auiv2_pause_record_abuse_video_stop");
        AUIV2_DESTINATION_UI_RECORD_ABUSE_VIDEO_STOP = clickEventButtonId76;
        ClickEventButtonId clickEventButtonId77 = new ClickEventButtonId("AUIV2_DESTINATION_UI_REPORT", 76, "auiv2_pause_report");
        AUIV2_DESTINATION_UI_REPORT = clickEventButtonId77;
        ClickEventButtonId clickEventButtonId78 = new ClickEventButtonId("AUIV2_DESTINATION_UI_RESTART", 77, "auiv2_pause_restart");
        AUIV2_DESTINATION_UI_RESTART = clickEventButtonId78;
        ClickEventButtonId clickEventButtonId79 = new ClickEventButtonId("AUIV2_DESTINATION_UI_RESUME", 78, "auiv2_pause_resume");
        AUIV2_DESTINATION_UI_RESUME = clickEventButtonId79;
        ClickEventButtonId clickEventButtonId80 = new ClickEventButtonId("AUIV2_DESTINATION_UI_TAKE_SCREENSHOT", 79, "auiv2_pause_screenshot");
        AUIV2_DESTINATION_UI_TAKE_SCREENSHOT = clickEventButtonId80;
        ClickEventButtonId clickEventButtonId81 = new ClickEventButtonId("AUIV2_PROFILE_ACCEPT_FRIEND_REQUEST", 80, "auiv2_profile_accept_friend_request");
        AUIV2_PROFILE_ACCEPT_FRIEND_REQUEST = clickEventButtonId81;
        ClickEventButtonId clickEventButtonId82 = new ClickEventButtonId("AUIV2_PROFILE_ADD_FRIEND", 81, "auiv2_profile_add_friend");
        AUIV2_PROFILE_ADD_FRIEND = clickEventButtonId82;
        ClickEventButtonId clickEventButtonId83 = new ClickEventButtonId("AUIV2_PROFILE_AVATAR_EDITOR", 82, "auiv2_profile_avatar_editor");
        AUIV2_PROFILE_AVATAR_EDITOR = clickEventButtonId83;
        ClickEventButtonId clickEventButtonId84 = new ClickEventButtonId("AUIV2_PROFILE_BACK", 83, "auiv2_profile_back");
        AUIV2_PROFILE_BACK = clickEventButtonId84;
        ClickEventButtonId clickEventButtonId85 = new ClickEventButtonId("AUIV2_PROFILE_BLOCK_FB_USER", 84, "auiv2_profile_block_fb_user");
        AUIV2_PROFILE_BLOCK_FB_USER = clickEventButtonId85;
        ClickEventButtonId clickEventButtonId86 = new ClickEventButtonId("AUIV2_PROFILE_BLOCK_VR_USER", 85, "auiv2_profile_block_vr_user");
        AUIV2_PROFILE_BLOCK_VR_USER = clickEventButtonId86;
        ClickEventButtonId clickEventButtonId87 = new ClickEventButtonId("AUIV2_PROFILE_CANCEL_FRIEND_REQUEST", 86, "auiv2_profile_cancel_friend_request");
        AUIV2_PROFILE_CANCEL_FRIEND_REQUEST = clickEventButtonId87;
        ClickEventButtonId clickEventButtonId88 = new ClickEventButtonId("AUIV2_PROFILE_CONFIRM_EDIT", 87, "auiv2_profile_confirm_edit");
        AUIV2_PROFILE_CONFIRM_EDIT = clickEventButtonId88;
        ClickEventButtonId clickEventButtonId89 = new ClickEventButtonId("AUIV2_PROFILE_CONFIRM_EDIT_BIO_CHANGED", 88, "auiv2_profile_confirm_edit_bio_changed");
        AUIV2_PROFILE_CONFIRM_EDIT_BIO_CHANGED = clickEventButtonId89;
        ClickEventButtonId clickEventButtonId90 = new ClickEventButtonId("AUIV2_PROFILE_CONFIRM_EDIT_FAIL_CANCEL", 89, "auiv2_profile_confirm_edit_fail_cancel");
        AUIV2_PROFILE_CONFIRM_EDIT_FAIL_CANCEL = clickEventButtonId90;
        ClickEventButtonId clickEventButtonId91 = new ClickEventButtonId("AUIV2_PROFILE_CONFIRM_EDIT_FAIL_RETRY", 90, "auiv2_profile_confirm_edit_fail_retry");
        AUIV2_PROFILE_CONFIRM_EDIT_FAIL_RETRY = clickEventButtonId91;
        ClickEventButtonId clickEventButtonId92 = new ClickEventButtonId("AUIV2_PROFILE_COMPLETE_PROFILE", 91, "auiv2_profile_complete_profile");
        AUIV2_PROFILE_COMPLETE_PROFILE = clickEventButtonId92;
        ClickEventButtonId clickEventButtonId93 = new ClickEventButtonId("AUIV2_PROFILE_CREATE_PARTY", 92, SourceConstants.AUI_PROFILE_CREATE_PARTY);
        AUIV2_PROFILE_CREATE_PARTY = clickEventButtonId93;
        ClickEventButtonId clickEventButtonId94 = new ClickEventButtonId("AUIV2_PROFILE_FB_CREATE_PARTY", 93, "auiv2_profile_fb_create_party");
        AUIV2_PROFILE_FB_CREATE_PARTY = clickEventButtonId94;
        ClickEventButtonId clickEventButtonId95 = new ClickEventButtonId("AUIV2_PROFILE_FB_INVITE_TO_PARTY", 94, "auiv2_profile_fb_invite_to_party");
        AUIV2_PROFILE_FB_INVITE_TO_PARTY = clickEventButtonId95;
        ClickEventButtonId clickEventButtonId96 = new ClickEventButtonId("AUIV2_PROFILE_FB_JOIN_PARTY", 95, "auiv2_profile_fb_join_party");
        AUIV2_PROFILE_FB_JOIN_PARTY = clickEventButtonId96;
        ClickEventButtonId clickEventButtonId97 = new ClickEventButtonId("AUIV2_PROFILE_EDIT_PROFILE", 96, "auiv2_profile_edit_profile");
        AUIV2_PROFILE_EDIT_PROFILE = clickEventButtonId97;
        ClickEventButtonId clickEventButtonId98 = new ClickEventButtonId("AUIV2_PROFILE_OC_CHAT", 97, "auiv2_profile_oc_chat");
        AUIV2_PROFILE_OC_CHAT = clickEventButtonId98;
        ClickEventButtonId clickEventButtonId99 = new ClickEventButtonId("AUIV2_PROFILE_OVERFLOW_MENU", 98, "auiv2_profile_overflow_menu");
        AUIV2_PROFILE_OVERFLOW_MENU = clickEventButtonId99;
        ClickEventButtonId clickEventButtonId100 = new ClickEventButtonId("AUIV2_PROFILE_PARTY_INVITE", 99, "auiv2_profile_party_invite");
        AUIV2_PROFILE_PARTY_INVITE = clickEventButtonId100;
        ClickEventButtonId clickEventButtonId101 = new ClickEventButtonId("AUIV2_PROFILE_PARTY_JOIN", 100, "auiv2_profile_party_join");
        AUIV2_PROFILE_PARTY_JOIN = clickEventButtonId101;
        ClickEventButtonId clickEventButtonId102 = new ClickEventButtonId("AUIV2_PROFILE_PHOTO_EDITOR", 101, "auiv2_profile_photo_editor");
        AUIV2_PROFILE_PHOTO_EDITOR = clickEventButtonId102;
        ClickEventButtonId clickEventButtonId103 = new ClickEventButtonId("AUIV2_PROFILE_PRIVACY_SETTINGS", 102, "auiv2_profile_privacy_settings");
        AUIV2_PROFILE_PRIVACY_SETTINGS = clickEventButtonId103;
        ClickEventButtonId clickEventButtonId104 = new ClickEventButtonId("AUIV2_PROFILE_REJECT_FRIEND_REQUEST", 103, "auiv2_profile_reject_friend_request");
        AUIV2_PROFILE_REJECT_FRIEND_REQUEST = clickEventButtonId104;
        ClickEventButtonId clickEventButtonId105 = new ClickEventButtonId("AUIV2_PROFILE_REPORT_FB_USER", 104, "auiv2_profile_report_fb_user");
        AUIV2_PROFILE_REPORT_FB_USER = clickEventButtonId105;
        ClickEventButtonId clickEventButtonId106 = new ClickEventButtonId("AUIV2_PROFILE_REPORT_VR_USER", 105, "auiv2_profile_report_vr_user");
        AUIV2_PROFILE_REPORT_VR_USER = clickEventButtonId106;
        ClickEventButtonId clickEventButtonId107 = new ClickEventButtonId("AUIV2_PROFILE_SHARE_PROFILE", 106, "auiv2_profile_share_profile");
        AUIV2_PROFILE_SHARE_PROFILE = clickEventButtonId107;
        ClickEventButtonId clickEventButtonId108 = new ClickEventButtonId("AUIV2_PROFILE_UNBLOCK_VR_USER", 107, "auiv2_profile_unblock_vr_user");
        AUIV2_PROFILE_UNBLOCK_VR_USER = clickEventButtonId108;
        ClickEventButtonId clickEventButtonId109 = new ClickEventButtonId("AUIV2_PROFILE_UNFRIEND_USER", 108, "auiv2_profile_unfriend_user");
        AUIV2_PROFILE_UNFRIEND_USER = clickEventButtonId109;
        ClickEventButtonId clickEventButtonId110 = new ClickEventButtonId("AUIV2_PROFILE_VIEW_PROFILE", 109, "auiv2_profile_view_profile");
        AUIV2_PROFILE_VIEW_PROFILE = clickEventButtonId110;
        ClickEventButtonId clickEventButtonId111 = new ClickEventButtonId("AUIV2_PROFILE_CHAT_IN_MESSENGER", 110, "auiv2_profile_chat_in_messenger");
        AUIV2_PROFILE_CHAT_IN_MESSENGER = clickEventButtonId111;
        ClickEventButtonId clickEventButtonId112 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_BRIGHTNESS", 111, "auiv2_quick_settings_brightness");
        AUIV2_QUICK_SETTINGS_BRIGHTNESS = clickEventButtonId112;
        ClickEventButtonId clickEventButtonId113 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_CHANGE_DATE_TIME", 112, "auiv2_quick_settings_change_date_time");
        AUIV2_QUICK_SETTINGS_CHANGE_DATE_TIME = clickEventButtonId113;
        ClickEventButtonId clickEventButtonId114 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_DO_NO_DISTURB", 113, "auiv2_quick_settings_do_not_disturb");
        AUIV2_QUICK_SETTINGS_DO_NO_DISTURB = clickEventButtonId114;
        ClickEventButtonId clickEventButtonId115 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_FULL_SETTINGS", 114, "auiv2_quick_settings_full_settings");
        AUIV2_QUICK_SETTINGS_FULL_SETTINGS = clickEventButtonId115;
        ClickEventButtonId clickEventButtonId116 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_GUARDIAN", 115, "auiv2_quick_settings_guardian");
        AUIV2_QUICK_SETTINGS_GUARDIAN = clickEventButtonId116;
        ClickEventButtonId clickEventButtonId117 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_HANDS", 116, "auiv2_quick_settings_hands");
        AUIV2_QUICK_SETTINGS_HANDS = clickEventButtonId117;
        ClickEventButtonId clickEventButtonId118 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_MICROPHONE", 117, "auiv2_quick_settings_microphone");
        AUIV2_QUICK_SETTINGS_MICROPHONE = clickEventButtonId118;
        ClickEventButtonId clickEventButtonId119 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_NIGHT_DISPLAY", 118, "auiv2_quick_settings_night_display");
        AUIV2_QUICK_SETTINGS_NIGHT_DISPLAY = clickEventButtonId119;
        ClickEventButtonId clickEventButtonId120 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_REALITY_TUNER", 119, "auiv2_quick_settings_reality_tuner");
        AUIV2_QUICK_SETTINGS_REALITY_TUNER = clickEventButtonId120;
        ClickEventButtonId clickEventButtonId121 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_RESET_VIEW", 120, "auiv2_quick_settings_reset_view");
        AUIV2_QUICK_SETTINGS_RESET_VIEW = clickEventButtonId121;
        ClickEventButtonId clickEventButtonId122 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_VOLUME", 121, "auiv2_quick_settings_volume");
        AUIV2_QUICK_SETTINGS_VOLUME = clickEventButtonId122;
        ClickEventButtonId clickEventButtonId123 = new ClickEventButtonId("AUIV2_QUICK_SETTINGS_WIFI", 122, "auiv2_quick_settings_wifi");
        AUIV2_QUICK_SETTINGS_WIFI = clickEventButtonId123;
        ClickEventButtonId clickEventButtonId124 = new ClickEventButtonId("AUIV2_SETTINGS_ASSISTANT", 123, "auiv2_quick_actions_assistant");
        AUIV2_SETTINGS_ASSISTANT = clickEventButtonId124;
        ClickEventButtonId clickEventButtonId125 = new ClickEventButtonId("AUIV2_SETTINGS_BRIGHTNESS", 124, "auiv2_quick_actions_brightness");
        AUIV2_SETTINGS_BRIGHTNESS = clickEventButtonId125;
        ClickEventButtonId clickEventButtonId126 = new ClickEventButtonId("AUIV2_SETTINGS_BUG_REPORT", 125, "auiv2_quick_actions_bug_report");
        AUIV2_SETTINGS_BUG_REPORT = clickEventButtonId126;
        ClickEventButtonId clickEventButtonId127 = new ClickEventButtonId("AUIV2_SETTINGS_DO_NO_DISTURB", 126, "auiv2_quick_actions_do_not_disturb");
        AUIV2_SETTINGS_DO_NO_DISTURB = clickEventButtonId127;
        ClickEventButtonId clickEventButtonId128 = new ClickEventButtonId("AUIV2_SETTINGS_GUARDIAN", 127, "auiv2_quick_actions_guardian");
        AUIV2_SETTINGS_GUARDIAN = clickEventButtonId128;
        ClickEventButtonId clickEventButtonId129 = new ClickEventButtonId("AUIV2_SETTINGS_HANDS", 128, "auiv2_quick_actions_hands");
        AUIV2_SETTINGS_HANDS = clickEventButtonId129;
        ClickEventButtonId clickEventButtonId130 = new ClickEventButtonId("AUIV2_SETTINGS_MICROPHONE", 129, "auiv2_quick_actions_microphone");
        AUIV2_SETTINGS_MICROPHONE = clickEventButtonId130;
        ClickEventButtonId clickEventButtonId131 = new ClickEventButtonId("AUIV2_SETTINGS_NIGHT_DISPLAY", 130, "auiv2_quick_actions_night_display");
        AUIV2_SETTINGS_NIGHT_DISPLAY = clickEventButtonId131;
        ClickEventButtonId clickEventButtonId132 = new ClickEventButtonId("AUIV2_SETTINGS_OCULUS_LINK", 131, "auiv2_quick_actions_oculus_link");
        AUIV2_SETTINGS_OCULUS_LINK = clickEventButtonId132;
        ClickEventButtonId clickEventButtonId133 = new ClickEventButtonId("AUIV2_SETTINGS_REALITY_TUNER", 132, "auiv2_quick_actions_reality_tuner");
        AUIV2_SETTINGS_REALITY_TUNER = clickEventButtonId133;
        ClickEventButtonId clickEventButtonId134 = new ClickEventButtonId("AUIV2_SETTINGS_RESET_VIEW", 133, "auiv2_quick_actions_reset_view");
        AUIV2_SETTINGS_RESET_VIEW = clickEventButtonId134;
        ClickEventButtonId clickEventButtonId135 = new ClickEventButtonId("AUIV2_SETTINGS_VOLUME", 134, "auiv2_quick_actions_volume");
        AUIV2_SETTINGS_VOLUME = clickEventButtonId135;
        ClickEventButtonId clickEventButtonId136 = new ClickEventButtonId("AUIV2_SETTINGS_WIFI", 135, "auiv2_quick_actions_wifi");
        AUIV2_SETTINGS_WIFI = clickEventButtonId136;
        ClickEventButtonId clickEventButtonId137 = new ClickEventButtonId("AUIV2_SHARING_CAMERA_ROLL", 136, "auiv2_sharing_camera_roll");
        AUIV2_SHARING_CAMERA_ROLL = clickEventButtonId137;
        ClickEventButtonId clickEventButtonId138 = new ClickEventButtonId("AUIV2_SHARING_CASTING", 137, "auiv2_sharing_casting");
        AUIV2_SHARING_CASTING = clickEventButtonId138;
        ClickEventButtonId clickEventButtonId139 = new ClickEventButtonId("AUIV2_SHARING_CASTING_STOP", 138, "auiv2_sharing_casting_stop");
        AUIV2_SHARING_CASTING_STOP = clickEventButtonId139;
        ClickEventButtonId clickEventButtonId140 = new ClickEventButtonId("AUIV2_SHARING_LIVESTREAM", 139, "auiv2_sharing_livestream");
        AUIV2_SHARING_LIVESTREAM = clickEventButtonId140;
        ClickEventButtonId clickEventButtonId141 = new ClickEventButtonId("AUIV2_SHARING_LIVESTREAM_STOP", 140, "auiv2_sharing_livestream_stop");
        AUIV2_SHARING_LIVESTREAM_STOP = clickEventButtonId141;
        ClickEventButtonId clickEventButtonId142 = new ClickEventButtonId("AUIV2_SOCIAL_SHARE_PARTY", 141, "auiv2_share_party");
        AUIV2_SOCIAL_SHARE_PARTY = clickEventButtonId142;
        ClickEventButtonId clickEventButtonId143 = new ClickEventButtonId("AUIV2_SHARING_RECORD_VIDEO", 142, "auiv2_sharing_record_video");
        AUIV2_SHARING_RECORD_VIDEO = clickEventButtonId143;
        ClickEventButtonId clickEventButtonId144 = new ClickEventButtonId("AUIV2_SHARING_RECORD_VIDEO_STOP", 143, "auiv2_sharing_record_video_stop");
        AUIV2_SHARING_RECORD_VIDEO_STOP = clickEventButtonId144;
        ClickEventButtonId clickEventButtonId145 = new ClickEventButtonId("AUIV2_SHARING_RECORD_ABUSE_VIDEO_STOP", 144, "auiv2_sharing_record_abuse_video_stop");
        AUIV2_SHARING_RECORD_ABUSE_VIDEO_STOP = clickEventButtonId145;
        ClickEventButtonId clickEventButtonId146 = new ClickEventButtonId("AUIV2_SHARING_RECENT_TILE", 145, "auiv2_sharing_recent_tile");
        AUIV2_SHARING_RECENT_TILE = clickEventButtonId146;
        ClickEventButtonId clickEventButtonId147 = new ClickEventButtonId("AUIV2_SHARING_RECENT_TILE_1", 146, "auiv2_sharing_recent_tile_1");
        AUIV2_SHARING_RECENT_TILE_1 = clickEventButtonId147;
        ClickEventButtonId clickEventButtonId148 = new ClickEventButtonId("AUIV2_SHARING_RECENT_TILE_2", 147, "auiv2_sharing_recent_tile_2");
        AUIV2_SHARING_RECENT_TILE_2 = clickEventButtonId148;
        ClickEventButtonId clickEventButtonId149 = new ClickEventButtonId("AUIV2_SHARING_RECENT_TILE_3", 148, "auiv2_sharing_recent_tile_3");
        AUIV2_SHARING_RECENT_TILE_3 = clickEventButtonId149;
        ClickEventButtonId clickEventButtonId150 = new ClickEventButtonId("AUIV2_SHARING_RECENT_TILE_4", 149, "auiv2_sharing_recent_tile_4");
        AUIV2_SHARING_RECENT_TILE_4 = clickEventButtonId150;
        ClickEventButtonId clickEventButtonId151 = new ClickEventButtonId("AUIV2_SHARING_RECENT_TILE_5", 150, "auiv2_sharing_recent_tile_5");
        AUIV2_SHARING_RECENT_TILE_5 = clickEventButtonId151;
        ClickEventButtonId clickEventButtonId152 = new ClickEventButtonId("AUIV2_SHARING_TAKE_SCREENSHOT", 151, "auiv2_sharing_screenshot");
        AUIV2_SHARING_TAKE_SCREENSHOT = clickEventButtonId152;
        ClickEventButtonId clickEventButtonId153 = new ClickEventButtonId("AUIV2_STATUS_TIME", 152, "auiv2_status_time");
        AUIV2_STATUS_TIME = clickEventButtonId153;
        ClickEventButtonId clickEventButtonId154 = new ClickEventButtonId("AUIV2_STATUS_WIFI", 153, "auiv2_status_wifi");
        AUIV2_STATUS_WIFI = clickEventButtonId154;
        ClickEventButtonId clickEventButtonId155 = new ClickEventButtonId("TRY_AUIV2", 154, "try_auiv2");
        TRY_AUIV2 = clickEventButtonId155;
        ClickEventButtonId clickEventButtonId156 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_BLOCK_DIALOG_CANCEL", 155, "auiv2_social_friends_block_dialog_cancel");
        AUIV2_SOCIAL_FRIENDS_BLOCK_DIALOG_CANCEL = clickEventButtonId156;
        ClickEventButtonId clickEventButtonId157 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_BLOCK_DIALOG_CONFIRM", 156, "auiv2_social_friends_block_confirm");
        AUIV2_SOCIAL_FRIENDS_BLOCK_DIALOG_CONFIRM = clickEventButtonId157;
        ClickEventButtonId clickEventButtonId158 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_BLOCK_DIALOG_OPEN", 157, "auiv2_social_friends_block_dialog_open");
        AUIV2_SOCIAL_FRIENDS_BLOCK_DIALOG_OPEN = clickEventButtonId158;
        ClickEventButtonId clickEventButtonId159 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_CARD_FRIEND_INVITE", 158, "auiv2_social_parties_card_friend_invite");
        AUIV2_SOCIAL_PARTIES_CARD_FRIEND_INVITE = clickEventButtonId159;
        ClickEventButtonId clickEventButtonId160 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_ROW_FRIEND_INVITE", 159, "auiv2_social_parties_row_friend_invite");
        AUIV2_SOCIAL_PARTIES_ROW_FRIEND_INVITE = clickEventButtonId160;
        ClickEventButtonId clickEventButtonId161 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_CARD_PROFILE_VIEW", 160, "auiv2_social_friends_card_profile_view");
        AUIV2_SOCIAL_FRIENDS_CARD_PROFILE_VIEW = clickEventButtonId161;
        ClickEventButtonId clickEventButtonId162 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_ROW_PROFILE_VIEW", 161, "auiv2_social_friends_row_profile_view");
        AUIV2_SOCIAL_FRIENDS_ROW_PROFILE_VIEW = clickEventButtonId162;
        ClickEventButtonId clickEventButtonId163 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_CARD_REPORT", 162, "auiv2_social_friends_card_report");
        AUIV2_SOCIAL_FRIENDS_CARD_REPORT = clickEventButtonId163;
        ClickEventButtonId clickEventButtonId164 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_ROW_REPORT", 163, "auiv2_social_friends_row_report");
        AUIV2_SOCIAL_FRIENDS_ROW_REPORT = clickEventButtonId164;
        ClickEventButtonId clickEventButtonId165 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_CARD_CHAT_START", 164, "auiv2_social_friends_card_chat_start");
        AUIV2_SOCIAL_FRIENDS_CARD_CHAT_START = clickEventButtonId165;
        ClickEventButtonId clickEventButtonId166 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_ROW_CHAT_START", 165, "auiv2_social_friends_row_chat_start");
        AUIV2_SOCIAL_FRIENDS_ROW_CHAT_START = clickEventButtonId166;
        ClickEventButtonId clickEventButtonId167 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_ROW_PARTY_START", 166, "auiv2_social_friends_row_party_start");
        AUIV2_SOCIAL_FRIENDS_ROW_PARTY_START = clickEventButtonId167;
        ClickEventButtonId clickEventButtonId168 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_CARD_PARTY_START", 167, "auiv2_social_friends_card_party_start");
        AUIV2_SOCIAL_FRIENDS_CARD_PARTY_START = clickEventButtonId168;
        ClickEventButtonId clickEventButtonId169 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_CARD_UNFRIEND", 168, "auiv2_social_friends_card_unfriend");
        AUIV2_SOCIAL_FRIENDS_CARD_UNFRIEND = clickEventButtonId169;
        ClickEventButtonId clickEventButtonId170 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_ROW_UNFRIEND", 169, "auiv2_social_friends_row_unfriend");
        AUIV2_SOCIAL_FRIENDS_ROW_UNFRIEND = clickEventButtonId170;
        ClickEventButtonId clickEventButtonId171 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_NAVIGATE_TO_PARTY", 170, "auiv2_social_friends_navigate_to_party");
        AUIV2_SOCIAL_FRIENDS_NAVIGATE_TO_PARTY = clickEventButtonId171;
        ClickEventButtonId clickEventButtonId172 = new ClickEventButtonId("AUIV2_SOCIAL_GUIDED_ACTION_AVATAR", 171, "auiv2_social_guided_action_avatar");
        AUIV2_SOCIAL_GUIDED_ACTION_AVATAR = clickEventButtonId172;
        ClickEventButtonId clickEventButtonId173 = new ClickEventButtonId("AUIV2_SOCIAL_GUIDED_ACTION_ADD_FRIEND", 172, "auiv2_social_guided_action_add_friend");
        AUIV2_SOCIAL_GUIDED_ACTION_ADD_FRIEND = clickEventButtonId173;
        ClickEventButtonId clickEventButtonId174 = new ClickEventButtonId("AUIV2_SOCIAL_GUIDED_ACTION_FB_LINK", 173, "auiv2_social_guided_action_fb_link");
        AUIV2_SOCIAL_GUIDED_ACTION_FB_LINK = clickEventButtonId174;
        ClickEventButtonId clickEventButtonId175 = new ClickEventButtonId("AUIV2_SOCIAL_GUIDED_ACTION_FIND_EVENTS", 174, "auiv2_social_guided_action_find_events");
        AUIV2_SOCIAL_GUIDED_ACTION_FIND_EVENTS = clickEventButtonId175;
        ClickEventButtonId clickEventButtonId176 = new ClickEventButtonId("AUIV2_SOCIAL_GUIDED_ACTION_SHARE_PROFILE", 175, "auiv2_social_guided_action_share_profile");
        AUIV2_SOCIAL_GUIDED_ACTION_SHARE_PROFILE = clickEventButtonId176;
        ClickEventButtonId clickEventButtonId177 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_ACCEPT_PARTY_INVITE", 176, "auiv2_social_parties_accept_party_invite");
        AUIV2_SOCIAL_PARTIES_ACCEPT_PARTY_INVITE = clickEventButtonId177;
        ClickEventButtonId clickEventButtonId178 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_INVITE_DIALOG_CANCEL", 177, "auiv2_social_parties_invite_dialog_cancel");
        AUIV2_SOCIAL_PARTIES_INVITE_DIALOG_CANCEL = clickEventButtonId178;
        ClickEventButtonId clickEventButtonId179 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_INVITE_DIALOG_OPEN", 178, "auiv2_social_parties_invite_dialog_open");
        AUIV2_SOCIAL_PARTIES_INVITE_DIALOG_OPEN = clickEventButtonId179;
        ClickEventButtonId clickEventButtonId180 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_INVITE_DIALOG_SEND", 179, "auiv2_social_parties_invite_dialog_send");
        AUIV2_SOCIAL_PARTIES_INVITE_DIALOG_SEND = clickEventButtonId180;
        ClickEventButtonId clickEventButtonId181 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_JOIN_OPEN_PARTY", 180, "auiv2_social_parties_join_open_party");
        AUIV2_SOCIAL_PARTIES_JOIN_OPEN_PARTY = clickEventButtonId181;
        ClickEventButtonId clickEventButtonId182 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_PARTY_JOIN_SUCCESS", 181, "auiv2_social_parties_party_join_success");
        AUIV2_SOCIAL_PARTIES_PARTY_JOIN_SUCCESS = clickEventButtonId182;
        ClickEventButtonId clickEventButtonId183 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_PER_PERSON_MUTE", 182, "auiv2_social_parties_per_person_mute");
        AUIV2_SOCIAL_PARTIES_PER_PERSON_MUTE = clickEventButtonId183;
        ClickEventButtonId clickEventButtonId184 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_PER_PERSON_UNMUTE", 183, "auiv2_social_parties_per_person_unmute");
        AUIV2_SOCIAL_PARTIES_PER_PERSON_UNMUTE = clickEventButtonId184;
        ClickEventButtonId clickEventButtonId185 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_MUTE_SELF", 184, "auiv2_social_parties_mute_self");
        AUIV2_SOCIAL_PARTIES_MUTE_SELF = clickEventButtonId185;
        ClickEventButtonId clickEventButtonId186 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_NAVIGATE_TO_FRIENDS", 185, "auiv2_social_parties_navigate_to_friends");
        AUIV2_SOCIAL_PARTIES_NAVIGATE_TO_FRIENDS = clickEventButtonId186;
        ClickEventButtonId clickEventButtonId187 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_PARTY_LEAVE_SUCCESS", 186, "auiv2_social_parties_party_leave_success");
        AUIV2_SOCIAL_PARTIES_PARTY_LEAVE_SUCCESS = clickEventButtonId187;
        ClickEventButtonId clickEventButtonId188 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_PARTY_INVITE_SUCCESS", 187, "auiv2_social_parties_party_invite_success");
        AUIV2_SOCIAL_PARTIES_PARTY_INVITE_SUCCESS = clickEventButtonId188;
        ClickEventButtonId clickEventButtonId189 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_PARTY_KICK_START", 188, "auiv2_social_parties_party_kick_start");
        AUIV2_SOCIAL_PARTIES_PARTY_KICK_START = clickEventButtonId189;
        ClickEventButtonId clickEventButtonId190 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_PARTY_KICK_SUCCESS", 189, "auiv2_social_parties_party_kick_success");
        AUIV2_SOCIAL_PARTIES_PARTY_KICK_SUCCESS = clickEventButtonId190;
        ClickEventButtonId clickEventButtonId191 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_PRIVACY_DIALOG_CANCEL", 190, "auiv2_social_parties_privacy_dialog_cancel");
        AUIV2_SOCIAL_PARTIES_PRIVACY_DIALOG_CANCEL = clickEventButtonId191;
        ClickEventButtonId clickEventButtonId192 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_PRIVACY_DIALOG_OPEN", 191, "auiv2_social_parties_privacy_dialog_open");
        AUIV2_SOCIAL_PARTIES_PRIVACY_DIALOG_OPEN = clickEventButtonId192;
        ClickEventButtonId clickEventButtonId193 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_START_DIALOG_CANCEL", 192, "auiv2_social_parties_start_dialog_cancel");
        AUIV2_SOCIAL_PARTIES_START_DIALOG_CANCEL = clickEventButtonId193;
        ClickEventButtonId clickEventButtonId194 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_START_DIALOG_CREATE", 193, "auiv2_social_parties_start_dialog_create");
        AUIV2_SOCIAL_PARTIES_START_DIALOG_CREATE = clickEventButtonId194;
        ClickEventButtonId clickEventButtonId195 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_START_DIALOG_OPEN", 194, "auiv2_social_parties_start_dialog_open");
        AUIV2_SOCIAL_PARTIES_START_DIALOG_OPEN = clickEventButtonId195;
        ClickEventButtonId clickEventButtonId196 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_START_PARTY_SUCCESS", 195, "auiv2_social_parties_start_party_success");
        AUIV2_SOCIAL_PARTIES_START_PARTY_SUCCESS = clickEventButtonId196;
        ClickEventButtonId clickEventButtonId197 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_UNMUTE_SELF", 196, "auiv2_social_parties_unmute_self");
        AUIV2_SOCIAL_PARTIES_UNMUTE_SELF = clickEventButtonId197;
        ClickEventButtonId clickEventButtonId198 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_UPDATE_PRIVACY_CLOSED", 197, "auiv2_social_parties_update_privacy_closed");
        AUIV2_SOCIAL_PARTIES_UPDATE_PRIVACY_CLOSED = clickEventButtonId198;
        ClickEventButtonId clickEventButtonId199 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_UPDATE_PRIVACY_OPEN", 198, "auiv2_social_parties_update_privacy_open");
        AUIV2_SOCIAL_PARTIES_UPDATE_PRIVACY_OPEN = clickEventButtonId199;
        ClickEventButtonId clickEventButtonId200 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GOTO_USER_FROM_USER_CARD", 199, "auiv2_social_parties_goto_user_from_user_card");
        AUIV2_SOCIAL_PARTIES_GOTO_USER_FROM_USER_CARD = clickEventButtonId200;
        ClickEventButtonId clickEventButtonId201 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GOTO_USER_FROM_USER_VIEW", 200, "auiv2_social_parties_goto_user_from_user_view");
        AUIV2_SOCIAL_PARTIES_GOTO_USER_FROM_USER_VIEW = clickEventButtonId201;
        ClickEventButtonId clickEventButtonId202 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_TRAVEL_TO_LAUNCH_APP", 201, "auiv2_social_parties_group_launch_travel_to_launch_app");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_TRAVEL_TO_LAUNCH_APP = clickEventButtonId202;
        ClickEventButtonId clickEventButtonId203 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_JOIN_LEADER", 202, "auiv2_social_parties_group_launch_join_leader");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_JOIN_LEADER = clickEventButtonId203;
        ClickEventButtonId clickEventButtonId204 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_CREATE", 203, "auiv2_social_parties_group_launch_create");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_CREATE = clickEventButtonId204;
        ClickEventButtonId clickEventButtonId205 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_CANCEL", 204, "auiv2_social_parties_group_launch_cancel");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_CANCEL = clickEventButtonId205;
        ClickEventButtonId clickEventButtonId206 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_LAUNCH", 205, "auiv2_social_parties_group_launch_launch");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_LAUNCH = clickEventButtonId206;
        ClickEventButtonId clickEventButtonId207 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_LAUNCH_SOLO", 206, "auiv2_social_parties_group_launch_launch_solo");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_LAUNCH_SOLO = clickEventButtonId207;
        ClickEventButtonId clickEventButtonId208 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_SELECT_NEW_DESTINATION", 207, "auiv2_social_parties_group_launch_select_new_destination");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_SELECT_NEW_DESTINATION = clickEventButtonId208;
        ClickEventButtonId clickEventButtonId209 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_ACCEPT_RESPONSE", 208, "auiv2_social_parties_group_launch_accept_response");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_ACCEPT_RESPONSE = clickEventButtonId209;
        ClickEventButtonId clickEventButtonId210 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_REJECT_RESPONSE", 209, "auiv2_social_parties_group_launch_reject_response");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_REJECT_RESPONSE = clickEventButtonId210;
        ClickEventButtonId clickEventButtonId211 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_CANCEL_RESPONSE", 210, "auiv2_social_parties_group_launch_cancel_response");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_CANCEL_RESPONSE = clickEventButtonId211;
        ClickEventButtonId clickEventButtonId212 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_VIEW_APP_DETAILS", 211, "auiv2_social_parties_group_launch_view_app_details");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_VIEW_APP_DETAILS = clickEventButtonId212;
        ClickEventButtonId clickEventButtonId213 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_LEAVE_PARTY", 212, "auiv2_social_parties_group_launch_leave_party");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_LEAVE_PARTY = clickEventButtonId213;
        ClickEventButtonId clickEventButtonId214 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_APP_LAUNCH_DIALOG_LEADER_VIEW_CANCEL", 213, "auiv2_social_parties_app_lanch_dialog_leader_view_cancel");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_APP_LAUNCH_DIALOG_LEADER_VIEW_CANCEL = clickEventButtonId214;
        ClickEventButtonId clickEventButtonId215 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_APP_LAUNCH_DIALOG_MEMBER_VIEW_CANCEL", 214, "auiv2_social_parties_app_lanch_dialog_member_view_cancel");
        AUIV2_SOCIAL_PARTIES_GROUP_LAUNCH_APP_LAUNCH_DIALOG_MEMBER_VIEW_CANCEL = clickEventButtonId215;
        ClickEventButtonId clickEventButtonId216 = new ClickEventButtonId("AUIV2_SOCIAL_PYMK_CARD_DISMISS", 215, "auiv2_social_pymk_card_dismiss");
        AUIV2_SOCIAL_PYMK_CARD_DISMISS = clickEventButtonId216;
        ClickEventButtonId clickEventButtonId217 = new ClickEventButtonId("AUIV2_SOCIAL_PYMK_ROW_DISMISS", 216, "auiv2_social_pymk_row_dismiss");
        AUIV2_SOCIAL_PYMK_ROW_DISMISS = clickEventButtonId217;
        ClickEventButtonId clickEventButtonId218 = new ClickEventButtonId("AUIV2_SOCIAL_PYMK_CARD_SEND_REQUEST", 217, "auiv2_social_pymk_card_send_request");
        AUIV2_SOCIAL_PYMK_CARD_SEND_REQUEST = clickEventButtonId218;
        ClickEventButtonId clickEventButtonId219 = new ClickEventButtonId("AUIV2_SOCIAL_PYMK_ROW_SEND_REQUEST", 218, "auiv2_social_pymk_row_send_request");
        AUIV2_SOCIAL_PYMK_ROW_SEND_REQUEST = clickEventButtonId219;
        ClickEventButtonId clickEventButtonId220 = new ClickEventButtonId("AUIV2_SOCIAL_REQUESTS_ACCEPT_FRIEND", 219, "auiv2_social_requests_accept_friend");
        AUIV2_SOCIAL_REQUESTS_ACCEPT_FRIEND = clickEventButtonId220;
        ClickEventButtonId clickEventButtonId221 = new ClickEventButtonId("AUIV2_SOCIAL_REQUESTS_REJECT_FRIEND", 220, "auiv2_social_requests_reject_friend");
        AUIV2_SOCIAL_REQUESTS_REJECT_FRIEND = clickEventButtonId221;
        ClickEventButtonId clickEventButtonId222 = new ClickEventButtonId("AUIV2_SOCIAL_FRIENDS_FRIEND_ADD", 221, "auiv2_social_friends_friend_add");
        AUIV2_SOCIAL_FRIENDS_FRIEND_ADD = clickEventButtonId222;
        ClickEventButtonId clickEventButtonId223 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_LEAVE", 222, "auiv2_social_parties_leave");
        AUIV2_SOCIAL_PARTIES_LEAVE = clickEventButtonId223;
        ClickEventButtonId clickEventButtonId224 = new ClickEventButtonId("AUIV2_SOCIAL_PARTIES_REPORT", 223, "auiv2_social_parties_report");
        AUIV2_SOCIAL_PARTIES_REPORT = clickEventButtonId224;
        ClickEventButtonId clickEventButtonId225 = new ClickEventButtonId("AUIV2_SOCIAL_UPSELL_FB_LINK", 224, "auiv2_social_upsell_fb_link");
        AUIV2_SOCIAL_UPSELL_FB_LINK = clickEventButtonId225;
        ClickEventButtonId clickEventButtonId226 = new ClickEventButtonId("AUIV2_SOCIAL_UPSELL_FRIEND", 225, "auiv2_social_upsell_friend");
        AUIV2_SOCIAL_UPSELL_FRIEND = clickEventButtonId226;
        ClickEventButtonId clickEventButtonId227 = new ClickEventButtonId("AUIV2_SYSTEM_STATUS_NOTIFICATIONS", 226, "auiv2_system_status_notifications");
        AUIV2_SYSTEM_STATUS_NOTIFICATIONS = clickEventButtonId227;
        ClickEventButtonId clickEventButtonId228 = new ClickEventButtonId("AUIV2_SYSTEM_STATUS_PROFILE", 227, "auiv2_system_status_profile");
        AUIV2_SYSTEM_STATUS_PROFILE = clickEventButtonId228;
        ClickEventButtonId clickEventButtonId229 = new ClickEventButtonId("AUIV2_SYSTEM_STATUS_QUICK_SETTINGS", 228, "auiv2_system_status_quick_settings");
        AUIV2_SYSTEM_STATUS_QUICK_SETTINGS = clickEventButtonId229;
        ClickEventButtonId clickEventButtonId230 = new ClickEventButtonId("AUIV2_QP_TOOLTIP_DISMISS", 229, "auiv2_qp_tooltip_dismiss");
        AUIV2_QP_TOOLTIP_DISMISS = clickEventButtonId230;
        ClickEventButtonId clickEventButtonId231 = new ClickEventButtonId("AUIV2_QP_GUIDE_BAR_DISMISS", 230, "auiv2_qp_guide_bar_dismiss");
        AUIV2_QP_GUIDE_BAR_DISMISS = clickEventButtonId231;
        ClickEventButtonId clickEventButtonId232 = new ClickEventButtonId("AUIV2_QP_GUIDE_BAR_CTA", 231, "auiv2_qp_guide_bar_cta");
        AUIV2_QP_GUIDE_BAR_CTA = clickEventButtonId232;
        ClickEventButtonId[] clickEventButtonIdArr = new ClickEventButtonId[232];
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId, clickEventButtonId2, clickEventButtonId3, clickEventButtonId4, clickEventButtonId5, clickEventButtonId6, clickEventButtonId7, clickEventButtonId8, clickEventButtonId9, clickEventButtonId10, clickEventButtonId11, clickEventButtonId12, clickEventButtonId13, clickEventButtonId14, clickEventButtonId15, clickEventButtonId16, clickEventButtonId17, clickEventButtonId18, clickEventButtonId19, clickEventButtonId20, clickEventButtonId21, clickEventButtonId22, clickEventButtonId23, clickEventButtonId24, clickEventButtonId25, clickEventButtonId26, clickEventButtonId27}, 0, clickEventButtonIdArr, 0, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId28, clickEventButtonId29, clickEventButtonId30, clickEventButtonId31, clickEventButtonId32, clickEventButtonId33, clickEventButtonId34, clickEventButtonId35, clickEventButtonId36, clickEventButtonId37, clickEventButtonId38, clickEventButtonId39, clickEventButtonId40, clickEventButtonId41, clickEventButtonId42, clickEventButtonId43, clickEventButtonId44, clickEventButtonId45, clickEventButtonId46, clickEventButtonId47, clickEventButtonId48, clickEventButtonId49, clickEventButtonId50, clickEventButtonId51, clickEventButtonId52, clickEventButtonId53, clickEventButtonId54}, 0, clickEventButtonIdArr, 27, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId55, clickEventButtonId56, clickEventButtonId57, clickEventButtonId58, clickEventButtonId59, clickEventButtonId60, clickEventButtonId61, clickEventButtonId62, clickEventButtonId63, clickEventButtonId64, clickEventButtonId65, clickEventButtonId66, clickEventButtonId67, clickEventButtonId68, clickEventButtonId69, clickEventButtonId70, clickEventButtonId71, clickEventButtonId72, clickEventButtonId73, clickEventButtonId74, clickEventButtonId75, clickEventButtonId76, clickEventButtonId77, clickEventButtonId78, clickEventButtonId79, clickEventButtonId80, clickEventButtonId81}, 0, clickEventButtonIdArr, 54, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId82, clickEventButtonId83, clickEventButtonId84, clickEventButtonId85, clickEventButtonId86, clickEventButtonId87, clickEventButtonId88, clickEventButtonId89, clickEventButtonId90, clickEventButtonId91, clickEventButtonId92, clickEventButtonId93, clickEventButtonId94, clickEventButtonId95, clickEventButtonId96, clickEventButtonId97, clickEventButtonId98, clickEventButtonId99, clickEventButtonId100, clickEventButtonId101, clickEventButtonId102, clickEventButtonId103, clickEventButtonId104, clickEventButtonId105, clickEventButtonId106, clickEventButtonId107, clickEventButtonId108}, 0, clickEventButtonIdArr, 81, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId109, clickEventButtonId110, clickEventButtonId111, clickEventButtonId112, clickEventButtonId113, clickEventButtonId114, clickEventButtonId115, clickEventButtonId116, clickEventButtonId117, clickEventButtonId118, clickEventButtonId119, clickEventButtonId120, clickEventButtonId121, clickEventButtonId122, clickEventButtonId123, clickEventButtonId124, clickEventButtonId125, clickEventButtonId126, clickEventButtonId127, clickEventButtonId128, clickEventButtonId129, clickEventButtonId130, clickEventButtonId131, clickEventButtonId132, clickEventButtonId133, clickEventButtonId134, clickEventButtonId135}, 0, clickEventButtonIdArr, 108, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId136, clickEventButtonId137, clickEventButtonId138, clickEventButtonId139, clickEventButtonId140, clickEventButtonId141, clickEventButtonId142, clickEventButtonId143, clickEventButtonId144, clickEventButtonId145, clickEventButtonId146, clickEventButtonId147, clickEventButtonId148, clickEventButtonId149, clickEventButtonId150, clickEventButtonId151, clickEventButtonId152, clickEventButtonId153, clickEventButtonId154, clickEventButtonId155, clickEventButtonId156, clickEventButtonId157, clickEventButtonId158, clickEventButtonId159, clickEventButtonId160, clickEventButtonId161, clickEventButtonId162}, 0, clickEventButtonIdArr, 135, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId163, clickEventButtonId164, clickEventButtonId165, clickEventButtonId166, clickEventButtonId167, clickEventButtonId168, clickEventButtonId169, clickEventButtonId170, clickEventButtonId171, clickEventButtonId172, clickEventButtonId173, clickEventButtonId174, clickEventButtonId175, clickEventButtonId176, clickEventButtonId177, clickEventButtonId178, clickEventButtonId179, clickEventButtonId180, clickEventButtonId181, clickEventButtonId182, clickEventButtonId183, clickEventButtonId184, clickEventButtonId185, clickEventButtonId186, clickEventButtonId187, clickEventButtonId188, clickEventButtonId189}, 0, clickEventButtonIdArr, 162, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId190, clickEventButtonId191, clickEventButtonId192, clickEventButtonId193, clickEventButtonId194, clickEventButtonId195, clickEventButtonId196, clickEventButtonId197, clickEventButtonId198, clickEventButtonId199, clickEventButtonId200, clickEventButtonId201, clickEventButtonId202, clickEventButtonId203, clickEventButtonId204, clickEventButtonId205, clickEventButtonId206, clickEventButtonId207, clickEventButtonId208, clickEventButtonId209, clickEventButtonId210, clickEventButtonId211, clickEventButtonId212, clickEventButtonId213, clickEventButtonId214, clickEventButtonId215, clickEventButtonId216}, 0, clickEventButtonIdArr, 189, 27);
        System.arraycopy(new ClickEventButtonId[]{clickEventButtonId217, clickEventButtonId218, clickEventButtonId219, clickEventButtonId220, clickEventButtonId221, clickEventButtonId222, clickEventButtonId223, clickEventButtonId224, clickEventButtonId225, clickEventButtonId226, clickEventButtonId227, clickEventButtonId228, clickEventButtonId229, clickEventButtonId230, clickEventButtonId231, clickEventButtonId232}, 0, clickEventButtonIdArr, 216, 16);
        $VALUES = clickEventButtonIdArr;
    }
}
