package com.oculus.executors;

import X.AbstractC0247Xu;
import X.C0515sp;
import X.I0;
import android.os.Handler;
import android.os.Looper;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class ExecutorsModule extends I0 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForExecutorsModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_android_os_Handler_ULSEP_com_oculus_executors_ForUiThread_ULSEP_BINDING_ID = 90;
        public static final int _UL__ULSEP_android_os_Looper_ULSEP_com_oculus_executors_ForUiThread_ULSEP_BINDING_ID = 75;
        public static final int _UL__ULSEP_com_oculus_executors_OculusThreadExecutor_ULSEP_BINDING_ID = 2067;
    }

    @AutoGeneratedAccessMethod
    public static final Looper A02(AbstractC0247Xu xu) {
        return (Looper) C0515sp.A00(75, xu);
    }

    @AutoGeneratedFactoryMethod
    public static final Handler A00(AbstractC0247Xu xu) {
        return new Handler(A02(xu));
    }

    @AutoGeneratedFactoryMethod
    public static final Looper A01() {
        return Looper.getMainLooper();
    }
}
