package com.oculus.auth.subscriber;

import X.AbstractC06640p5;
import X.AnonymousClass0J5;
import X.AnonymousClass0Pi;
import X.AnonymousClass0Pp;
import X.AnonymousClass0p1;
import X.AnonymousClass117;
import X.C003008y;
import X.C01020Iw;
import com.facebook.inject.ApplicationScoped;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.inject.ProviderMethod;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import com.oculus.auth.device.DeviceAuthTokenSubscriber;
import javax.inject.Provider;

@InjectorModule
public class LoginDeviceAuthTokenSubscriberModule extends AnonymousClass0J5 {
    public static volatile DeviceAuthTokenSubscriber _UL__ULSEP_com_oculus_auth_device_DeviceAuthTokenSubscriber_ULSEP_INSTANCE;

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_auth_device_DeviceAuthTokenSubscriber_ULSEP_BINDING_ID = 484;
        public static final int _UL__ULSEP_com_oculus_auth_subscriber_LoginDeviceAuthTokenSubscriber_ULSEP_BINDING_ID = 439;
    }

    @ApplicationScoped(enableScopeValidation = false)
    @ProviderMethod
    public static DeviceAuthTokenSubscriber providesDeviceAuthTokenSubscriber(LoginDeviceAuthTokenSubscriber loginDeviceAuthTokenSubscriber) {
        return loginDeviceAuthTokenSubscriber;
    }

    @AutoGeneratedAccessMethod
    public static final AnonymousClass0p1 _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_auth_device_DeviceAuthTokenSubscriber_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C003008y(484, r2);
    }

    @AutoGeneratedAccessMethod
    public static final DeviceAuthTokenSubscriber _UL__ULSEP_com_oculus_auth_device_DeviceAuthTokenSubscriber_ULSEP_ACCESS_METHOD(AbstractC06640p5 r1) {
        return (DeviceAuthTokenSubscriber) AnonymousClass117.A00(484, r1);
    }

    @AutoGeneratedFactoryMethod
    public static final DeviceAuthTokenSubscriber _UL__ULSEP_com_oculus_auth_device_DeviceAuthTokenSubscriber_ULSEP_FACTORY_METHOD(AbstractC06640p5 r3) {
        if (_UL__ULSEP_com_oculus_auth_device_DeviceAuthTokenSubscriber_ULSEP_INSTANCE == null) {
            synchronized (DeviceAuthTokenSubscriber.class) {
                AnonymousClass0Pi A00 = AnonymousClass0Pi.A00(_UL__ULSEP_com_oculus_auth_device_DeviceAuthTokenSubscriber_ULSEP_INSTANCE, r3);
                if (A00 != null) {
                    try {
                        _UL__ULSEP_com_oculus_auth_device_DeviceAuthTokenSubscriber_ULSEP_INSTANCE = LoginDeviceAuthTokenSubscriber._UL__ULSEP_com_oculus_auth_subscriber_LoginDeviceAuthTokenSubscriber_ULSEP_ACCESS_METHOD(r3.getApplicationInjector());
                    } finally {
                        A00.A01();
                    }
                }
            }
        }
        return _UL__ULSEP_com_oculus_auth_device_DeviceAuthTokenSubscriber_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_auth_device_DeviceAuthTokenSubscriber_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C01020Iw(484, r2);
    }

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForLoginDeviceAuthTokenSubscriberModule {
        public static void bind(AnonymousClass0Pp r0) {
        }
    }
}
