package com.oculus.alpenglow.http;

import X.AbstractC02990bJ;
import X.AbstractC05850lW;
import X.AnonymousClass0Lh;
import X.AnonymousClass0PX;
import X.AnonymousClass0R7;
import X.AnonymousClass13m;
import X.C05660kD;
import X.C05700ke;
import X.C05710kf;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.oculus.auth.device.DeviceAuthTokenStore;
import java.io.IOException;
import java.util.Locale;

@Dependencies({"_UL__ULSEP_com_oculus_auth_device_DeviceAuthTokenStore_ULSEP_BINDING_ID"})
public class DeviceAuthorizationInterceptor implements AbstractC05850lW {
    public static final String HEADER_AUTHORIZATION = "Authorization";
    public static final int HTTP_STATUS_UNAUTHORIZED = 401;
    public AnonymousClass0R7 _UL_mInjectionContext;

    @AutoGeneratedAccessMethod
    public static final DeviceAuthorizationInterceptor A00(AbstractC02990bJ r1) {
        return (DeviceAuthorizationInterceptor) AnonymousClass13m.A00(21, r1);
    }

    @AutoGeneratedFactoryMethod
    public static final DeviceAuthorizationInterceptor A01(AbstractC02990bJ r1) {
        return new DeviceAuthorizationInterceptor(r1);
    }

    @Override // X.AbstractC05850lW
    public final C05660kD A5K(AnonymousClass0PX r7) throws IOException {
        C05700ke r5 = r7.A01;
        String str = ((DeviceAuthTokenStore) AnonymousClass0Lh.A03(0, 112, this._UL_mInjectionContext)).mAuthToken;
        if (r5.A02.A00(HEADER_AUTHORIZATION) == null) {
            C05710kf r3 = new C05710kf(r5);
            r3.A02(HEADER_AUTHORIZATION, String.format(Locale.US, "Bearer %s", str));
            r5 = r3.A00();
        }
        C05660kD A00 = r7.A00(r5);
        if (A00.A01 == 401) {
            ((DeviceAuthTokenStore) AnonymousClass0Lh.A03(0, 112, this._UL_mInjectionContext)).fetchToken();
        }
        return A00;
    }

    @Inject
    public DeviceAuthorizationInterceptor(AbstractC02990bJ r3) {
        this._UL_mInjectionContext = new AnonymousClass0R7(1, r3);
    }
}
