package com.oculus.horizon.logging;

import X.AbstractC03180ld;
import X.AnonymousClass0Hr;
import X.AnonymousClass0RE;
import X.AnonymousClass0VC;
import X.AnonymousClass0VF;
import X.AnonymousClass0lg;
import X.AnonymousClass1TK;
import X.C00610Hs;
import android.content.Context;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import com.facebook.inject.ForAppContext;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.oculus.horizon.foreground.ApplicationForegroundListener;
import com.oculus.horizon.logging.contract.FunnelContract;
import com.oculus.logging.utils.EventManager;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_ForAppContext_ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_horizon_logging_OculusLogger_ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_logging_utils_EventManager_ULSEP_BINDING_ID"})
public class HorizonForegroundListener implements ApplicationForegroundListener {
    public AnonymousClass0RE _UL_mInjectionContext;
    public final OculusLogger mOculusLogger;
    public String mPackageName;
    public int mVersionCode = -1;
    public String mVersionName;

    @AutoGeneratedAccessMethod
    public static final AbstractC03180ld _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_horizon_logging_HorizonForegroundListener_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0Hr.A00(2078, r1);
    }

    @AutoGeneratedAccessMethod
    public static final HorizonForegroundListener _UL__ULSEP_com_oculus_horizon_logging_HorizonForegroundListener_ULSEP_ACCESS_METHOD(AnonymousClass0lg r2) {
        return (HorizonForegroundListener) AnonymousClass1TK.A00(2078, r2, null);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_horizon_logging_HorizonForegroundListener_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0VC.A00(2078, r1);
    }

    @Override // com.oculus.horizon.foreground.ApplicationForegroundListener
    public void onApplicationBackground(long j) {
        this.mOculusLogger.reportAppEnd2D(this.mPackageName, this.mVersionName, this.mVersionCode, j);
    }

    @Override // com.oculus.horizon.foreground.ApplicationForegroundListener
    public void onApplicationForeground() {
        ((EventManager) AnonymousClass0VF.A03(0, 92, this._UL_mInjectionContext)).startFunnel(FunnelContract.NAV_TO_VR_FUNNEL_NAME);
        this.mOculusLogger.reportAppStart2D(this.mPackageName, this.mVersionName, this.mVersionCode);
    }

    @Inject
    public HorizonForegroundListener(AnonymousClass0lg r4, @ForAppContext Context context, OculusLogger oculusLogger) {
        this._UL_mInjectionContext = new AnonymousClass0RE(1, r4);
        this.mOculusLogger = oculusLogger;
        this.mPackageName = context.getPackageName();
        try {
            PackageInfo packageInfo = context.getPackageManager().getPackageInfo(this.mPackageName, 0);
            this.mVersionName = packageInfo.versionName;
            this.mVersionCode = packageInfo.versionCode;
        } catch (PackageManager.NameNotFoundException unused) {
        }
    }

    @AutoGeneratedFactoryMethod
    public static final HorizonForegroundListener _UL__ULSEP_com_oculus_horizon_logging_HorizonForegroundListener_ULSEP_FACTORY_METHOD(AnonymousClass0lg r3, Object obj) {
        return new HorizonForegroundListener(r3, C00610Hs.A00(r3), OculusLogger._UL__ULSEP_com_oculus_horizon_logging_OculusLogger_ULSEP_ACCESS_METHOD(r3));
    }
}
