package com.oculus.horizon.logging;

import java.util.Locale;

public class TrackingViews {

    /* JADX INFO: Failed to restore enum class, 'enum' modifier removed */
    public static final class View extends Enum<View> {
        public static final /* synthetic */ View[] $VALUES;
        public static final View ACCOUNT_UNCONFIRMED;
        public static final View BLUETOOTH_CALIBRATION;
        public static final View BLUETOOTH_DEVICE;
        public static final View BLUETOOTH_DISCOVERY;
        public static final View BLUETOOTH_HANDEDNESS;
        public static final View BLUETOOTH_MALIBU;
        public static final View BLUETOOTH_UPDATE;
        public static final View CONCEPT_ROADBLOCK_CANCEL;
        public static final View CONCEPT_ROADBLOCK_CONTINUE;
        public static final View CONCEPT_ROADBLOCK_VIEW;
        public static final View DEVELOPER_INFO;
        public static final View EVENTS_EVENT_DETAILS;
        public static final View EVENTS_INDIVIDUAL_EVENTS;
        public static final View EVENTS_LANDING_PAGE;
        public static final View EVENTS_NOTIFICATION;
        public static final View EVENTS_SUBSCRIBED;
        public static final View FB_CONNECT_FIND_FACEBOOK_FRIENDS;
        public static final View FB_CONNECT_IMPORT_FACEBOOK_PICTURE;
        public static final View FB_CONNECT_REDIRECT;
        public static final View FB_LOGIN_ADD_EMAIL;
        public static final View FB_LOGIN_CONNECT_ACCOUNT;
        public static final View FB_LOGIN_CREATE_ACCOUNT;
        public static final View FB_LOGIN_EXISTING_ACCOUNT;
        public static final View FB_LOGIN_INTRO;
        public static final View FB_LOGIN_PIN;
        public static final View FB_LOGIN_VERIFICATION;
        public static final View FEED;
        public static final View GALLERY_ROADBLOCK_CANCEL;
        public static final View GALLERY_ROADBLOCK_CONTINUE;
        public static final View GALLERY_ROADBLOCK_VIEW;
        public static final View HELP;
        public static final View HSW_VIDEO;
        public static final View INSTALL_APPLICATIONS;
        public static final View INVALID;
        public static final View LANDING_SCREEN;
        public static final View LANGUAGE_PICKER;
        public static final View LIBRARY;
        public static final View LIBRARY_LOCAL_MEDIA;
        public static final View LIBRARY_LOCAL_MEDIA_PREVIEW;
        public static final View LIBRARY_MY_APPS;
        public static final View LIBRARY_SAVED;
        public static final View LIBRARY_SAVED_DIVE;
        public static final View LIBRARY_TAB;
        public static final View LIVE_STREAMING_SESSION;
        public static final View LOGIN;
        public static final View LOGIN_APPROVALS;
        public static final View LOGIN_APPROVALS_TERMINAL;
        public static final View NOTIFICATIONS_FEED;
        public static final View NOT_SET;
        public static final View NUX;
        public static final View PARTY_CALL_NUX;
        public static final View PRODUCT_DETAILS;
        public static final View REDEEM_CODE_ACTIVATED;
        public static final View REGISTRATION_EMAIL;
        public static final View REGISTRATION_FIRST_PARTY_APPS;
        public static final View REGISTRATION_NAME;
        public static final View REGISTRATION_PASSWORD;
        public static final View REGISTRATION_PIN;
        public static final View REGISTRATION_USERNAME;
        public static final View ROADBLOCK_ACTIVITY_PRIVACY_UPDATE;
        public static final View ROADBLOCK_ADD_PAYMENT_METHOD;
        public static final View ROADBLOCK_ADD_PAYMENT_METHOD_CANCEL_CONFIRMED;
        public static final View ROADBLOCK_ADD_PAYMENT_METHOD_DISPLAY_CANCEL_CONFIRM;
        public static final View ROADBLOCK_ADD_PAYMENT_METHOD_OBE_NUX;
        public static final View ROADBLOCK_CONFIRM_PASSWORD;
        public static final View ROADBLOCK_FIND_FRIENDS;
        public static final View ROADBLOCK_FORCE_UPGRADE;
        public static final View ROADBLOCK_FORGOT_PASSWORD;
        public static final View ROADBLOCK_INTRO;
        public static final View ROADBLOCK_PRIVACY_OVERVIEW;
        public static final View ROADBLOCK_PROFILE_INTRO;
        public static final View ROADBLOCK_PROFILE_PICTURE;
        public static final View ROADBLOCK_SET_PIN;
        public static final View SAMSUNG_ERROR_DIALOG;
        public static final View SETTINGS;
        public static final View SETTINGS_ADD_PAYMENT_METHOD;
        public static final View SETTINGS_ADVANCED;
        public static final View SETTINGS_CONFIRM_PASSWORD;
        public static final View SETTINGS_GATEKEEPERS;
        public static final View SETTINGS_INTERNAL;
        public static final View SETTINGS_LEGAL_NOTICES;
        public static final View SETTINGS_LINKED_ACCOUNTS;
        public static final View SETTINGS_MANAGE_PAYMENT_METHOD;
        public static final View SETTINGS_NOTIFICATIONS;
        public static final View SETTINGS_NUX_PREFERENCES;
        public static final View SETTINGS_OCULUS_OPEN_SOURCE;
        public static final View SETTINGS_OPEN_SOURCE;
        public static final View SETTINGS_ORDERS;
        public static final View SETTINGS_PARTY_CALL;
        public static final View SETTINGS_PASSWORD;
        public static final View SETTINGS_PLATFORM_ENDPOINT;
        public static final View SETTINGS_PRIVACY;
        public static final View SETTINGS_PRIVACY_NAME;
        public static final View SETTINGS_PRIVACY_SOCIAL_FRIENDS_LIST;
        public static final View SETTINGS_REDEEM_CODE;
        public static final View SETTINGS_REDEEM_CODE_ACTIVATED;
        public static final View SETTINGS_REQUEST_REFUND;
        public static final View SETTINGS_STORE_CREDIT;
        public static final View SETTINGS_TOS;
        public static final View SOCIAL_ACHIEVEMENTS;
        public static final View SOCIAL_AVATAR_SELECTION;
        public static final View SOCIAL_BLOCKED_USERS;
        public static final View SOCIAL_CAMERA;
        public static final View SOCIAL_FRIEND_REQUESTS;
        public static final View SOCIAL_FRIEND_REQUEST_FRIENDS_LIST;
        public static final View SOCIAL_GAME_INVITES;
        public static final View SOCIAL_LANDING_PAGE;
        public static final View SOCIAL_PARTY_INVITES;
        public static final View SOCIAL_PRIVACY_ACTIVITY;
        public static final View SOCIAL_PRIVACY_LANDING_PAGE;
        public static final View SOCIAL_PROFILE;
        public static final View SOCIAL_SPECIFIC_FRIENDS;
        public static final View SOCIAL_USER_SEARCH;
        public static final View STORE;
        public static final View STORE_BANNER;
        public static final View STORE_SEARCH;
        public static final View STORE_SECTION;
        public static final View TERMS_OF_SERVICE;
        public static final View TWO_FACTOR_METHODS;
        public static final View UNLOCK_STORE_WITH_PAYMENT;
        public static final View USER_REVIEWS_AUTHOR;
        public static final View USER_REVIEWS_COMMENT;
        public static final View USER_REVIEWS_SEE_ALL;
        public static final View USER_REVIEWS_UPDATE;
        public static final View VERSION_NOTES;
        public static final View YOU_ARE_READY;

        static {
            View view = new View("ACCOUNT_UNCONFIRMED", 0);
            ACCOUNT_UNCONFIRMED = view;
            View view2 = new View("BLUETOOTH_DISCOVERY", 1);
            BLUETOOTH_DISCOVERY = view2;
            View view3 = new View("BLUETOOTH_MALIBU", 2);
            BLUETOOTH_MALIBU = view3;
            View view4 = new View("BLUETOOTH_HANDEDNESS", 3);
            BLUETOOTH_HANDEDNESS = view4;
            View view5 = new View("BLUETOOTH_DEVICE", 4);
            BLUETOOTH_DEVICE = view5;
            View view6 = new View("BLUETOOTH_UPDATE", 5);
            BLUETOOTH_UPDATE = view6;
            View view7 = new View("BLUETOOTH_CALIBRATION", 6);
            BLUETOOTH_CALIBRATION = view7;
            View view8 = new View("CONCEPT_ROADBLOCK_CANCEL", 7);
            CONCEPT_ROADBLOCK_CANCEL = view8;
            View view9 = new View("CONCEPT_ROADBLOCK_CONTINUE", 8);
            CONCEPT_ROADBLOCK_CONTINUE = view9;
            View view10 = new View("CONCEPT_ROADBLOCK_VIEW", 9);
            CONCEPT_ROADBLOCK_VIEW = view10;
            View view11 = new View("DEVELOPER_INFO", 10);
            DEVELOPER_INFO = view11;
            View view12 = new View("EVENTS_EVENT_DETAILS", 11);
            EVENTS_EVENT_DETAILS = view12;
            View view13 = new View("EVENTS_LANDING_PAGE", 12);
            EVENTS_LANDING_PAGE = view13;
            View view14 = new View("EVENTS_INDIVIDUAL_EVENTS", 13);
            EVENTS_INDIVIDUAL_EVENTS = view14;
            View view15 = new View("EVENTS_NOTIFICATION", 14);
            EVENTS_NOTIFICATION = view15;
            View view16 = new View("EVENTS_SUBSCRIBED", 15);
            EVENTS_SUBSCRIBED = view16;
            View view17 = new View("FB_CONNECT_REDIRECT", 16);
            FB_CONNECT_REDIRECT = view17;
            View view18 = new View("FB_CONNECT_FIND_FACEBOOK_FRIENDS", 17);
            FB_CONNECT_FIND_FACEBOOK_FRIENDS = view18;
            View view19 = new View("FB_CONNECT_IMPORT_FACEBOOK_PICTURE", 18);
            FB_CONNECT_IMPORT_FACEBOOK_PICTURE = view19;
            View view20 = new View("FB_LOGIN_ADD_EMAIL", 19);
            FB_LOGIN_ADD_EMAIL = view20;
            View view21 = new View("FB_LOGIN_CONNECT_ACCOUNT", 20);
            FB_LOGIN_CONNECT_ACCOUNT = view21;
            View view22 = new View("FB_LOGIN_CREATE_ACCOUNT", 21);
            FB_LOGIN_CREATE_ACCOUNT = view22;
            View view23 = new View("FB_LOGIN_EXISTING_ACCOUNT", 22);
            FB_LOGIN_EXISTING_ACCOUNT = view23;
            View view24 = new View("FB_LOGIN_INTRO", 23);
            FB_LOGIN_INTRO = view24;
            View view25 = new View("FB_LOGIN_PIN", 24);
            FB_LOGIN_PIN = view25;
            View view26 = new View("FB_LOGIN_VERIFICATION", 25);
            FB_LOGIN_VERIFICATION = view26;
            View view27 = new View("FEED", 26);
            FEED = view27;
            View view28 = new View("GALLERY_ROADBLOCK_CANCEL", 27);
            GALLERY_ROADBLOCK_CANCEL = view28;
            View view29 = new View("GALLERY_ROADBLOCK_CONTINUE", 28);
            GALLERY_ROADBLOCK_CONTINUE = view29;
            View view30 = new View("GALLERY_ROADBLOCK_VIEW", 29);
            GALLERY_ROADBLOCK_VIEW = view30;
            View view31 = new View("HELP", 30);
            HELP = view31;
            View view32 = new View("HSW_VIDEO", 31);
            HSW_VIDEO = view32;
            View view33 = new View("INSTALL_APPLICATIONS", 32);
            INSTALL_APPLICATIONS = view33;
            View view34 = new View("INVALID", 33);
            INVALID = view34;
            View view35 = new View("LANDING_SCREEN", 34);
            LANDING_SCREEN = view35;
            View view36 = new View("LANGUAGE_PICKER", 35);
            LANGUAGE_PICKER = view36;
            View view37 = new View("LIBRARY_MY_APPS", 36);
            LIBRARY_MY_APPS = view37;
            View view38 = new View("LIVE_STREAMING_SESSION", 37);
            LIVE_STREAMING_SESSION = view38;
            View view39 = new View("LOGIN", 38);
            LOGIN = view39;
            View view40 = new View("LOGIN_APPROVALS", 39);
            LOGIN_APPROVALS = view40;
            View view41 = new View("LOGIN_APPROVALS_TERMINAL", 40);
            LOGIN_APPROVALS_TERMINAL = view41;
            View view42 = new View("NOTIFICATIONS_FEED", 41);
            NOTIFICATIONS_FEED = view42;
            View view43 = new View("NOT_SET", 42);
            NOT_SET = view43;
            View view44 = new View("NUX", 43);
            NUX = view44;
            View view45 = new View("PARTY_CALL_NUX", 44);
            PARTY_CALL_NUX = view45;
            View view46 = new View("PRODUCT_DETAILS", 45);
            PRODUCT_DETAILS = view46;
            View view47 = new View("REDEEM_CODE_ACTIVATED", 46);
            REDEEM_CODE_ACTIVATED = view47;
            View view48 = new View("REGISTRATION_EMAIL", 47);
            REGISTRATION_EMAIL = view48;
            View view49 = new View("REGISTRATION_FIRST_PARTY_APPS", 48);
            REGISTRATION_FIRST_PARTY_APPS = view49;
            View view50 = new View("REGISTRATION_NAME", 49);
            REGISTRATION_NAME = view50;
            View view51 = new View("REGISTRATION_PASSWORD", 50);
            REGISTRATION_PASSWORD = view51;
            View view52 = new View("REGISTRATION_PIN", 51);
            REGISTRATION_PIN = view52;
            View view53 = new View("REGISTRATION_USERNAME", 52);
            REGISTRATION_USERNAME = view53;
            View view54 = new View("ROADBLOCK_CONFIRM_PASSWORD", 53);
            ROADBLOCK_CONFIRM_PASSWORD = view54;
            View view55 = new View("ROADBLOCK_FORGOT_PASSWORD", 54);
            ROADBLOCK_FORGOT_PASSWORD = view55;
            View view56 = new View("ROADBLOCK_INTRO", 55);
            ROADBLOCK_INTRO = view56;
            View view57 = new View("ROADBLOCK_SET_PIN", 56);
            ROADBLOCK_SET_PIN = view57;
            View view58 = new View("ROADBLOCK_ADD_PAYMENT_METHOD", 57);
            ROADBLOCK_ADD_PAYMENT_METHOD = view58;
            View view59 = new View("ROADBLOCK_ADD_PAYMENT_METHOD_DISPLAY_CANCEL_CONFIRM", 58);
            ROADBLOCK_ADD_PAYMENT_METHOD_DISPLAY_CANCEL_CONFIRM = view59;
            View view60 = new View("ROADBLOCK_ADD_PAYMENT_METHOD_CANCEL_CONFIRMED", 59);
            ROADBLOCK_ADD_PAYMENT_METHOD_CANCEL_CONFIRMED = view60;
            View view61 = new View("ROADBLOCK_ADD_PAYMENT_METHOD_OBE_NUX", 60);
            ROADBLOCK_ADD_PAYMENT_METHOD_OBE_NUX = view61;
            View view62 = new View("ROADBLOCK_ACTIVITY_PRIVACY_UPDATE", 61);
            ROADBLOCK_ACTIVITY_PRIVACY_UPDATE = view62;
            View view63 = new View("ROADBLOCK_FIND_FRIENDS", 62);
            ROADBLOCK_FIND_FRIENDS = view63;
            View view64 = new View("ROADBLOCK_FORCE_UPGRADE", 63);
            ROADBLOCK_FORCE_UPGRADE = view64;
            View view65 = new View("ROADBLOCK_PRIVACY_OVERVIEW", 64);
            ROADBLOCK_PRIVACY_OVERVIEW = view65;
            View view66 = new View("ROADBLOCK_PROFILE_INTRO", 65);
            ROADBLOCK_PROFILE_INTRO = view66;
            View view67 = new View("ROADBLOCK_PROFILE_PICTURE", 66);
            ROADBLOCK_PROFILE_PICTURE = view67;
            View view68 = new View("YOU_ARE_READY", 67);
            YOU_ARE_READY = view68;
            View view69 = new View("SAMSUNG_ERROR_DIALOG", 68);
            SAMSUNG_ERROR_DIALOG = view69;
            View view70 = new View("SETTINGS", 69);
            SETTINGS = view70;
            View view71 = new View("SETTINGS_ADVANCED", 70);
            SETTINGS_ADVANCED = view71;
            View view72 = new View("SETTINGS_ADD_PAYMENT_METHOD", 71);
            SETTINGS_ADD_PAYMENT_METHOD = view72;
            View view73 = new View("SETTINGS_CONFIRM_PASSWORD", 72);
            SETTINGS_CONFIRM_PASSWORD = view73;
            View view74 = new View("SETTINGS_PRIVACY_SOCIAL_FRIENDS_LIST", 73);
            SETTINGS_PRIVACY_SOCIAL_FRIENDS_LIST = view74;
            View view75 = new View("SETTINGS_GATEKEEPERS", 74);
            SETTINGS_GATEKEEPERS = view75;
            View view76 = new View("SETTINGS_INTERNAL", 75);
            SETTINGS_INTERNAL = view76;
            View view77 = new View("SETTINGS_LEGAL_NOTICES", 76);
            SETTINGS_LEGAL_NOTICES = view77;
            View view78 = new View("SETTINGS_LINKED_ACCOUNTS", 77);
            SETTINGS_LINKED_ACCOUNTS = view78;
            View view79 = new View("SETTINGS_NOTIFICATIONS", 78);
            SETTINGS_NOTIFICATIONS = view79;
            View view80 = new View("SETTINGS_NUX_PREFERENCES", 79);
            SETTINGS_NUX_PREFERENCES = view80;
            View view81 = new View("SETTINGS_OCULUS_OPEN_SOURCE", 80);
            SETTINGS_OCULUS_OPEN_SOURCE = view81;
            View view82 = new View("SETTINGS_OPEN_SOURCE", 81);
            SETTINGS_OPEN_SOURCE = view82;
            View view83 = new View("SETTINGS_ORDERS", 82);
            SETTINGS_ORDERS = view83;
            View view84 = new View("SETTINGS_PASSWORD", 83);
            SETTINGS_PASSWORD = view84;
            View view85 = new View("SETTINGS_MANAGE_PAYMENT_METHOD", 84);
            SETTINGS_MANAGE_PAYMENT_METHOD = view85;
            View view86 = new View("SETTINGS_PLATFORM_ENDPOINT", 85);
            SETTINGS_PLATFORM_ENDPOINT = view86;
            View view87 = new View("SETTINGS_PRIVACY", 86);
            SETTINGS_PRIVACY = view87;
            View view88 = new View("SETTINGS_PRIVACY_NAME", 87);
            SETTINGS_PRIVACY_NAME = view88;
            View view89 = new View("SETTINGS_REDEEM_CODE", 88);
            SETTINGS_REDEEM_CODE = view89;
            View view90 = new View("SETTINGS_REDEEM_CODE_ACTIVATED", 89);
            SETTINGS_REDEEM_CODE_ACTIVATED = view90;
            View view91 = new View("SETTINGS_REQUEST_REFUND", 90);
            SETTINGS_REQUEST_REFUND = view91;
            View view92 = new View("SETTINGS_STORE_CREDIT", 91);
            SETTINGS_STORE_CREDIT = view92;
            View view93 = new View("SETTINGS_TOS", 92);
            SETTINGS_TOS = view93;
            View view94 = new View("SETTINGS_PARTY_CALL", 93);
            SETTINGS_PARTY_CALL = view94;
            View view95 = new View("SOCIAL_ACHIEVEMENTS", 94);
            SOCIAL_ACHIEVEMENTS = view95;
            View view96 = new View("SOCIAL_AVATAR_SELECTION", 95);
            SOCIAL_AVATAR_SELECTION = view96;
            View view97 = new View("SOCIAL_BLOCKED_USERS", 96);
            SOCIAL_BLOCKED_USERS = view97;
            View view98 = new View("SOCIAL_CAMERA", 97);
            SOCIAL_CAMERA = view98;
            View view99 = new View("SOCIAL_FRIEND_REQUESTS", 98);
            SOCIAL_FRIEND_REQUESTS = view99;
            View view100 = new View("SOCIAL_FRIEND_REQUEST_FRIENDS_LIST", 99);
            SOCIAL_FRIEND_REQUEST_FRIENDS_LIST = view100;
            View view101 = new View("SOCIAL_GAME_INVITES", 100);
            SOCIAL_GAME_INVITES = view101;
            View view102 = new View("SOCIAL_LANDING_PAGE", 101);
            SOCIAL_LANDING_PAGE = view102;
            View view103 = new View("SOCIAL_PARTY_INVITES", 102);
            SOCIAL_PARTY_INVITES = view103;
            View view104 = new View("SOCIAL_PRIVACY_ACTIVITY", 103);
            SOCIAL_PRIVACY_ACTIVITY = view104;
            View view105 = new View("SOCIAL_PRIVACY_LANDING_PAGE", 104);
            SOCIAL_PRIVACY_LANDING_PAGE = view105;
            View view106 = new View("SOCIAL_PROFILE", 105);
            SOCIAL_PROFILE = view106;
            View view107 = new View("SOCIAL_SPECIFIC_FRIENDS", 106);
            SOCIAL_SPECIFIC_FRIENDS = view107;
            View view108 = new View("SOCIAL_USER_SEARCH", 107);
            SOCIAL_USER_SEARCH = view108;
            View view109 = new View("STORE", 108);
            STORE = view109;
            View view110 = new View("STORE_BANNER", 109);
            STORE_BANNER = view110;
            View view111 = new View("STORE_SEARCH", 110);
            STORE_SEARCH = view111;
            View view112 = new View("STORE_SECTION", 111);
            STORE_SECTION = view112;
            View view113 = new View("TERMS_OF_SERVICE", 112);
            TERMS_OF_SERVICE = view113;
            View view114 = new View("TWO_FACTOR_METHODS", 113);
            TWO_FACTOR_METHODS = view114;
            View view115 = new View("LIBRARY", 114);
            LIBRARY = view115;
            View view116 = new View("LIBRARY_TAB", 115);
            LIBRARY_TAB = view116;
            View view117 = new View("LIBRARY_SAVED", 116);
            LIBRARY_SAVED = view117;
            View view118 = new View("LIBRARY_SAVED_DIVE", 117);
            LIBRARY_SAVED_DIVE = view118;
            View view119 = new View("LIBRARY_LOCAL_MEDIA", 118);
            LIBRARY_LOCAL_MEDIA = view119;
            View view120 = new View("LIBRARY_LOCAL_MEDIA_PREVIEW", 119);
            LIBRARY_LOCAL_MEDIA_PREVIEW = view120;
            View view121 = new View("UNLOCK_STORE_WITH_PAYMENT", 120);
            UNLOCK_STORE_WITH_PAYMENT = view121;
            View view122 = new View("USER_REVIEWS_SEE_ALL", 121);
            USER_REVIEWS_SEE_ALL = view122;
            View view123 = new View("USER_REVIEWS_UPDATE", 122);
            USER_REVIEWS_UPDATE = view123;
            View view124 = new View("USER_REVIEWS_AUTHOR", 123);
            USER_REVIEWS_AUTHOR = view124;
            View view125 = new View("USER_REVIEWS_COMMENT", 124);
            USER_REVIEWS_COMMENT = view125;
            View view126 = new View("VERSION_NOTES", 125);
            VERSION_NOTES = view126;
            View[] viewArr = new View[126];
            System.arraycopy(new View[]{view, view2, view3, view4, view5, view6, view7, view8, view9, view10, view11, view12, view13, view14, view15, view16, view17, view18, view19, view20, view21, view22, view23, view24, view25, view26, view27}, 0, viewArr, 0, 27);
            System.arraycopy(new View[]{view28, view29, view30, view31, view32, view33, view34, view35, view36, view37, view38, view39, view40, view41, view42, view43, view44, view45, view46, view47, view48, view49, view50, view51, view52, view53, view54}, 0, viewArr, 27, 27);
            System.arraycopy(new View[]{view55, view56, view57, view58, view59, view60, view61, view62, view63, view64, view65, view66, view67, view68, view69, view70, view71, view72, view73, view74, view75, view76, view77, view78, view79, view80, view81}, 0, viewArr, 54, 27);
            System.arraycopy(new View[]{view82, view83, view84, view85, view86, view87, view88, view89, view90, view91, view92, view93, view94, view95, view96, view97, view98, view99, view100, view101, view102, view103, view104, view105, view106, view107, view108}, 0, viewArr, 81, 27);
            System.arraycopy(new View[]{view109, view110, view111, view112, view113, view114, view115, view116, view117, view118, view119, view120, view121, view122, view123, view124, view125, view126}, 0, viewArr, 108, 18);
            $VALUES = viewArr;
        }

        public static View fromStringWithDefaults(String str) {
            if (str == null) {
                return NOT_SET;
            }
            try {
                return valueOf(str.toUpperCase(Locale.US));
            } catch (IllegalArgumentException unused) {
                return INVALID;
            }
        }

        public static View valueOf(String str) {
            return (View) Enum.valueOf(View.class, str);
        }

        public static View[] values() {
            return (View[]) $VALUES.clone();
        }

        public String toString() {
            return super.toString().toLowerCase(Locale.US);
        }

        public View(String str, int i) {
        }
    }
}
