package com.oculus.appmanager.info.schema;

import android.database.sqlite.SQLiteDatabase;
import com.facebook.inject.InjectorLike;
import com.facebook.inject.Lazy;
import com.facebook.inject.UltralightLazy;
import com.facebook.inject.UltralightProvider;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.UL;
import com.google.common.collect.ImmutableList;
import com.oculus.appmanager.info.ApkUpdateInfoContract;
import com.oculus.appmanager.info.InfoModule;
import com.oculus.database.supplier.TablesDbSchemaPart;
import javax.inject.Inject;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_com_oculus_appmanager_info_schema_ApkUpdateTable_ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_appmanager_info_schema_ApkUpdateExtrasTable_ULSEP_BINDING_ID"})
public class ApkUpdateSchemaPart extends TablesDbSchemaPart {
    private static final String PART_NAME = "apk_updates";
    private static final int VERSION = 9;
    private final ApkUpdateExtrasTable mApkUpdateExtrasTable;
    private final ApkUpdateTable mApkUpdateTable;

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_appmanager_info_schema_ApkUpdateSchemaPart_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(InfoModule.UL_id._UL__ULSEP_com_oculus_appmanager_info_schema_ApkUpdateSchemaPart_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_appmanager_info_schema_ApkUpdateSchemaPart_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(InfoModule.UL_id._UL__ULSEP_com_oculus_appmanager_info_schema_ApkUpdateSchemaPart_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final ApkUpdateSchemaPart _UL__ULSEP_com_oculus_appmanager_info_schema_ApkUpdateSchemaPart_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (ApkUpdateSchemaPart) UL.factorymap.get(InfoModule.UL_id._UL__ULSEP_com_oculus_appmanager_info_schema_ApkUpdateSchemaPart_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final ApkUpdateSchemaPart _UL__ULSEP_com_oculus_appmanager_info_schema_ApkUpdateSchemaPart_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return new ApkUpdateSchemaPart(ApkUpdateTable._UL__ULSEP_com_oculus_appmanager_info_schema_ApkUpdateTable_ULSEP_ACCESS_METHOD(injectorLike), ApkUpdateExtrasTable._UL__ULSEP_com_oculus_appmanager_info_schema_ApkUpdateExtrasTable_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @Inject
    public ApkUpdateSchemaPart(ApkUpdateTable apkUpdateTable, ApkUpdateExtrasTable apkUpdateExtrasTable) {
        super(PART_NAME, 9, ImmutableList.of(apkUpdateTable, apkUpdateExtrasTable));
        this.mApkUpdateTable = apkUpdateTable;
        this.mApkUpdateExtrasTable = apkUpdateExtrasTable;
    }

    /* access modifiers changed from: protected */
    @Override // com.oculus.database.supplier.SharedSQLiteSchemaPart, com.oculus.database.supplier.TablesDbSchemaPart
    public void onUpgrade(SQLiteDatabase sQLiteDatabase, int i, int i2) {
        boolean z;
        super.onUpgrade(sQLiteDatabase, i, i2);
        if (i < 2) {
            this.mApkUpdateTable.addColumn(ApkUpdateInfoContract.ApkUpdateTable.Columns.REQUEST_ORIGIN.name, "TEXT");
        }
        if (i < 3) {
            this.mApkUpdateTable.addColumn(ApkUpdateInfoContract.ApkUpdateTable.Columns.BASE_VERSION.name, "INTEGER");
            z = true;
        } else {
            z = false;
        }
        if (i < 4) {
            this.mApkUpdateTable.addColumn(ApkUpdateInfoContract.ApkUpdateTable.Columns.SIGNATURE.name, "STRING");
            z = true;
        }
        if (i < 5) {
            this.mApkUpdateTable.addColumn(ApkUpdateInfoContract.ApkUpdateTable.Columns.BINARY_ID.name, "TEXT");
            z = true;
        }
        if (i < 6) {
            this.mApkUpdateTable.addColumn(ApkUpdateInfoContract.ApkUpdateTable.Columns.EXTERNAL_SIGNATURES.name, "TEXT");
            z = true;
        }
        if (i < 7) {
            this.mApkUpdateTable.addColumn(ApkUpdateInfoContract.ApkUpdateTable.Columns.DOWNLOAD_CHECKSUM.name, "TEXT");
            z = true;
        }
        if (i < 8) {
            z = true;
        }
        if (i < 9) {
            this.mApkUpdateTable.addColumn(ApkUpdateInfoContract.ApkUpdateTable.Columns.REQUEST_HEADERS.name, "TEXT");
            this.mApkUpdateTable.addColumn(ApkUpdateInfoContract.ApkUpdateTable.Columns.DOWNLOAD_CHECKSUM_ALG.name, "TEXT");
            z = true;
        }
        if (z) {
            this.mApkUpdateTable.clear(sQLiteDatabase);
        }
    }
}
