package com.oculus.mobileconfig.init;

import X.AbstractC0096Hu;
import X.AbstractC0234Xa;
import X.AbstractC0247Xu;
import X.AnonymousClass06;
import X.C0088Gy;
import X.DB;
import X.GA;
import X.Gt;
import X.QC;
import X.RU;
import X.XX;
import X.eJ;
import com.facebook.mobileconfig.MobileConfigDependenciesInFBApps;
import com.facebook.mobileconfig.MobileConfigManagerHolderImpl;
import com.facebook.tigon.oktigon.OkTigonServiceHolder;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.oculus.auth.credentials.Credentials;
import com.oculus.auth.credentials.CredentialsModule;
import com.oculus.config.interfaces.Configuration;
import com.oculus.logging.utils.Event;
import com.oculus.logging.utils.EventManager;
import java.util.concurrent.Callable;

@Dependencies({"_UL__ULSEP_com_oculus_mobileconfig_init_MobileConfigInitOptions_ULSEP_BINDING_ID", "_UL__ULSEP_com_facebook_mobileconfig_impl_MobileConfigManagerSingletonHolder_ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_mobileconfig_init_MobileConfigInit_ULSEP_BINDING_ID", "_UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_logging_utils_EventManager_ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_auth_credentials_Credentials_ULSEP_BINDING_ID", "_UL__ULSEP_com_facebook_tigon_oktigon_OkTigonServiceHolder_ULSEP_BINDING_ID"})
public class MobileConfigConfiguration implements Configuration {
    public static final String EVENT_MOBILE_CONFIG_FETCH_RESULT = "oculus_mobile_config_fetch";
    public static final String EXTRA_FETCH_RESULT = "fetch_result";
    public static String TAG;
    public QC _UL_mInjectionContext;
    @Inject
    public final eJ<Credentials> mCredentialsProvider;
    @Inject
    public final eJ<AbstractC0234Xa> mMobileConfigFactoryProvider;
    @Inject
    public final eJ<XX> mMobileConfigManagerHolderProvider;
    @Inject
    public final eJ<OkTigonServiceHolder> mOkTigonServiceHolderProvider;

    /* JADX DEBUG: Type inference failed for r0v5. Raw type applied. Possible types: X.DB<?>, X.DB<java.lang.Void> */
    @Override // com.oculus.config.interfaces.Configuration
    public final DB<Void> fetchAsync() {
        final XX xx = this.mMobileConfigManagerHolderProvider.get();
        if (xx == null) {
            return DB.A08;
        }
        return DB.A00(new Callable<Void>() {
            /* class com.oculus.mobileconfig.init.MobileConfigConfiguration.AnonymousClass1 */

            /* Return type fixed from 'java.lang.Object' to match base method */
            @Override // java.util.concurrent.Callable
            public final Void call() throws Exception {
                MobileConfigConfiguration mobileConfigConfiguration = MobileConfigConfiguration.this;
                RU ru = xx;
                RU ru2 = ru;
                ((MobileConfigInit) AbstractC0096Hu.A03(0, 41, mobileConfigConfiguration._UL_mInjectionContext)).A02(mobileConfigConfiguration.mCredentialsProvider.get(), (GA) mobileConfigConfiguration.mMobileConfigFactoryProvider.get());
                if (ru instanceof XX) {
                    ru2 = ((XX) ru2).A00();
                }
                if (ru2 instanceof MobileConfigManagerHolderImpl) {
                    MobileConfigManagerHolderImpl mobileConfigManagerHolderImpl = (MobileConfigManagerHolderImpl) ru2;
                    if (!mobileConfigManagerHolderImpl.isNetworkServiceSet()) {
                        MobileConfigDependenciesInFBApps.setNetworkService(mobileConfigManagerHolderImpl, mobileConfigConfiguration.mOkTigonServiceHolderProvider.get(), true);
                    }
                }
                boolean updateConfigs = ru.updateConfigs();
                Event A1h = ((EventManager) AbstractC0096Hu.A03(1, 106, mobileConfigConfiguration._UL_mInjectionContext)).A1h(MobileConfigConfiguration.EVENT_MOBILE_CONFIG_FETCH_RESULT);
                A1h.A19(MobileConfigConfiguration.EXTRA_FETCH_RESULT, updateConfigs);
                A1h.A3Q();
                return null;
            }
        }, DB.A0C);
    }

    @Inject
    public MobileConfigConfiguration(AbstractC0247Xu xu, MobileConfigInitOptions mobileConfigInitOptions) {
        this._UL_mInjectionContext = new QC(2, xu);
        this.mMobileConfigManagerHolderProvider = new C0088Gy(64, xu);
        this.mMobileConfigFactoryProvider = new C0088Gy(115, xu);
        this.mCredentialsProvider = CredentialsModule._UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_auth_credentials_Credentials_ULGT__ULSEP_ACCESS_METHOD(xu);
        this.mOkTigonServiceHolderProvider = new Gt(113, xu);
        TAG = AnonymousClass06.A04(mobileConfigInitOptions.mTagPrefix, "MobileConfigConfiguration");
    }

    @AutoGeneratedFactoryMethod
    public static final MobileConfigConfiguration A00(AbstractC0247Xu xu) {
        return new MobileConfigConfiguration(xu, MobileConfigInitModule.A06(xu));
    }
}
