package com.oculus.android;

import X.AbstractC0031Bc;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class AndroidModule extends AbstractC0031Bc {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForAndroidModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_android_app_job_JobScheduler_ULSEP_BINDING_ID = 2066;
        public static final int _UL__ULSEP_android_bluetooth_BluetoothAdapter_ULSEP_BINDING_ID = 14;
        public static final int _UL__ULSEP_android_bluetooth_BluetoothManager_ULSEP_BINDING_ID = 2123;
        public static final int _UL__ULSEP_android_bluetooth_le_BluetoothLeScanner_ULSEP_BINDING_ID = 2059;
    }
}
