package com.oculus.horizon.vr;

import X.AnonymousClass0Qr;
import X.AnonymousClass0VI;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class VrModule extends AnonymousClass0VI {

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_horizon_vr_VRStateManager_ULSEP_BINDING_ID = 35;
    }

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForVrModule {
        public static void bind(AnonymousClass0Qr r0) {
        }
    }
}
