package com.oculus.security.basecomponent;

import X.AbstractC02630jR;
import X.AbstractC03180ld;
import X.AnonymousClass0Hr;
import X.AnonymousClass0RE;
import X.AnonymousClass0VC;
import X.AnonymousClass0VF;
import X.AnonymousClass0lg;
import X.AnonymousClass1TK;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.oculus.logging.utils.EventManager;
import com.oculus.security.basecomponent.MC;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_com_facebook_mobileconfig_factory_MobileConfig_ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_logging_utils_EventManager_ULSEP_BINDING_ID"})
public class OculusContentProviderLogger implements AbstractC02630jR {
    public static final String EVENT_NAME = "oculus_security_content_provider";
    public static final String KEY_CALLER_IDENTITY = "caller_identity";
    public static final String KEY_ENDPOINT_NAME = "endpoint_name";
    public static final String KEY_METHOD = "method";
    public AnonymousClass0RE _UL_mInjectionContext;

    @AutoGeneratedAccessMethod
    public static final AbstractC03180ld _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_security_basecomponent_OculusContentProviderLogger_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0Hr.A00(13, r1);
    }

    @AutoGeneratedAccessMethod
    public static final OculusContentProviderLogger _UL__ULSEP_com_oculus_security_basecomponent_OculusContentProviderLogger_ULSEP_ACCESS_METHOD(AnonymousClass0lg r2) {
        return (OculusContentProviderLogger) AnonymousClass1TK.A00(13, r2, null);
    }

    @AutoGeneratedFactoryMethod
    public static final OculusContentProviderLogger _UL__ULSEP_com_oculus_security_basecomponent_OculusContentProviderLogger_ULSEP_FACTORY_METHOD(AnonymousClass0lg r1, Object obj) {
        return new OculusContentProviderLogger(r1);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_security_basecomponent_OculusContentProviderLogger_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0VC.A00(13, r1);
    }

    @Inject
    public OculusContentProviderLogger(AnonymousClass0lg r3) {
        this._UL_mInjectionContext = new AnonymousClass0RE(2, r3);
    }

    @Override // X.AbstractC02630jR
    public void logUsage(String str, String str2) {
        AnonymousClass0RE r5 = this._UL_mInjectionContext;
        if (((MC.oculus_security_content_provider_logging.enabled >> 61) & 1) == 1) {
            ((EventManager) AnonymousClass0VF.A03(1, 92, r5)).createEvent(EVENT_NAME).addExtra("endpoint_name", str).addExtra("method", str2).logAndRelease();
        }
    }

    @Override // X.AbstractC02630jR
    public void logUsage(String str, String str2, String str3) {
        AnonymousClass0RE r5 = this._UL_mInjectionContext;
        if (((MC.oculus_security_content_provider_logging.enabled >> 61) & 1) == 1) {
            ((EventManager) AnonymousClass0VF.A03(1, 92, r5)).createEvent(EVENT_NAME).addExtra("endpoint_name", str).addExtra("caller_identity", str3).addExtra("method", str2).logAndRelease();
        }
    }
}
