package X;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

/* renamed from: X.1vF  reason: invalid class name */
public final class AnonymousClass1vF implements AbstractC08960z3 {
    public long A00 = 0;
    public long A01 = 0;
    public short A02 = 0;
    public boolean A03 = false;
    public byte[] A04;
    public byte A05;
    public int A06 = 0;
    public int A07;
    public int A08 = 0;
    public long A09 = 0;
    public AnonymousClass0XQ A0A;
    public AnonymousClass0XT A0B;
    public AnonymousClass0XU A0C;
    public AnonymousClass0XW A0D;
    public AnonymousClass0XX A0E;
    public AnonymousClass0XY A0F;
    public C01800Xn A0G;
    public AnonymousClass1mH A0H;
    public AnonymousClass1mE A0I;
    public AnonymousClass1nA A0J;
    public AnonymousClass1vI A0K;
    public AnonymousClass1v1 A0L;
    public AnonymousClass1ux A0M;
    public AnonymousClass1ur A0N;
    public C10771vc A0O;
    public InputStream A0P;
    public OutputStream A0Q;
    public String A0R;
    public String A0S;
    public String A0T;
    public List<C10871vm> A0U;
    public List<C10871vm> A0V;
    public List<AnonymousClass1v7> A0W;
    public Map<String, byte[]> A0X;
    public short A0Y = 0;
    public boolean A0Z = false;
    public boolean A0a = false;
    public boolean A0b;
    public boolean A0c;
    public boolean A0d = false;
    public boolean A0e;
    public boolean A0f;
    public boolean A0g = false;
    public boolean A0h;
    public byte[] A0i;
    public byte[] A0j;
    public byte[] A0k;
    public byte[] A0l;
    public byte[] A0m;
    public byte[] A0n;
}
