package X;

import android.annotation.SuppressLint;
import com.facebook.internal.NativeProtocol;
import com.oculus.common.build.BuildConstants;
import com.oculus.horizon.linkedaccounts.provider.verifier.LinkedAccountsCallerVerifier;
import com.oculus.userserver.api.OculusUserManager;
import com.oculus.util.constants.OculusConstants;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

@SuppressLint({"DirectOrcaPackageUse"})
/* renamed from: X.0bE  reason: invalid class name and case insensitive filesystem */
public final class C02710bE {
    public static final Set<String> A00 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.adsmanager", LinkedAccountsCallerVerifier.PACKAGE_NAME_FACEBOOK_AKIRA, "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.assistantplayground", "com.facebook.bishop", "com.facebook.creatorstudio", LinkedAccountsCallerVerifier.PACKAGE_NAME_FACEBOOK_DAYKIRA, "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.facebook.katana", NativeProtocol.MessengerAppInfo.MESSENGER_PACKAGE, "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.monza", "com.novi.wallet.validation", "com.novi.wallet.prodinternal", "com.novi.wallet", "com.oculus.alpenglow", "com.oculus.vrshell", "com.oculus.horizon", "com.oculus.horizon.dev", OculusConstants.PACKAGE_NAME_ARIANE_UPLOAD, "com.oculus.vrshell.home", "com.oculus.ocms", OculusConstants.PACKAGE_NAME_SYSTEM_UTILITIES, "com.oculus.twilight", OculusUserManager.SERVICE_IMPL_PKG, "com.oculus.updater", "com.facebook.pages.app", "com.facebook.bonfire", "com.facebook.study", "com.instagram.threadsapp", "com.facebook.wakizashi", "com.whatsapp", "com.whatsapp.w4b", "com.facebook.work", "com.facebook.workdev", "com.facebook.workchat")));
    public static final Set<String> A01 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.adsmanager", LinkedAccountsCallerVerifier.PACKAGE_NAME_FACEBOOK_AKIRA, "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.assistantplayground", "com.facebook.bishop", "com.facebook.creatorstudio", LinkedAccountsCallerVerifier.PACKAGE_NAME_FACEBOOK_DAYKIRA, "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.facebook.katana", NativeProtocol.MessengerAppInfo.MESSENGER_PACKAGE, "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.monza", "com.novi.wallet.validation", "com.novi.wallet.prodinternal", "com.novi.wallet", "com.oculus.alpenglow", "com.oculus.vrshell", "com.oculus.horizon", "com.oculus.horizon.dev", OculusConstants.PACKAGE_NAME_ARIANE_UPLOAD, "com.oculus.vrshell.home", "com.oculus.ocms", OculusConstants.PACKAGE_NAME_SYSTEM_UTILITIES, "com.oculus.twilight", OculusUserManager.SERVICE_IMPL_PKG, "com.oculus.updater", "com.facebook.pages.app", "com.facebook.bonfire", "com.facebook.study", "com.instagram.threadsapp", "com.facebook.wakizashi", "com.whatsapp", "com.whatsapp.w4b")));
    public static final Set<String> A02 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.adsmanager", LinkedAccountsCallerVerifier.PACKAGE_NAME_FACEBOOK_AKIRA, "com.facebook.appmanager", "com.facebook.appmanager.dev", "com.facebook.assistantplayground", "com.facebook.bishop", "com.facebook.creatorstudio", LinkedAccountsCallerVerifier.PACKAGE_NAME_FACEBOOK_DAYKIRA, "com.instagram.direct", "com.facebook.lite", "com.facebook.games", "com.facebook.phone", "com.facebook.home", "com.facebook.home.dev", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.facebook.katana", NativeProtocol.MessengerAppInfo.MESSENGER_PACKAGE, "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", "com.facebook.wearable.monza", "com.novi.wallet.validation", "com.novi.wallet.prodinternal", "com.novi.wallet", "com.oculus.alpenglow", "com.oculus.vrshell", "com.oculus.horizon", "com.oculus.horizon.dev", OculusConstants.PACKAGE_NAME_ARIANE_UPLOAD, "com.oculus.vrshell.home", "com.oculus.ocms", OculusConstants.PACKAGE_NAME_SYSTEM_UTILITIES, "com.oculus.twilight", OculusUserManager.SERVICE_IMPL_PKG, "com.oculus.updater", "com.facebook.pages.app", "com.facebook.bonfire", "com.facebook.study", "com.instagram.threadsapp", "com.facebook.wakizashi", "com.whatsapp", "com.whatsapp.w4b")));
    public static final Set<String> A03 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.globalsecurity", "com.facebook.viewpoints")));
    public static final Set<String> A04 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.instagram.direct", "com.instagram.android", "com.instagram.lite", "com.instagram.lite", "com.instagram.threadsapp")));
    public static final Set<String> A05 = Collections.unmodifiableSet(new HashSet(Arrays.asList(BuildConstants.PACKAGE_NAME_ASSISTANT, "com.oculus.companion.server", "com.oculus.alpenglow", "com.oculus.vrshell.home", "com.oculus.horizon", "com.oculus.horizon.dev", "com.oculus.nux.ota", "com.oculus.ocms", OculusConstants.PACKAGE_NAME_SYSTEM_UTILITIES, "com.oculus.twilight", OculusUserManager.SERVICE_IMPL_PKG, "com.oculus.updater")));
    public static final Set<String> A06 = Collections.unmodifiableSet(new HashSet(Arrays.asList("com.facebook.work", "com.facebook.workdev", "com.facebook.workchat")));
}
