package X;

import com.google.gson.internal.bind.TypeAdapters$26;
import com.google.gson.internal.bind.TypeAdapters$30;
import com.google.gson.internal.bind.TypeAdapters$32;
import com.google.gson.internal.bind.TypeAdapters$33;
import com.google.gson.internal.bind.TypeAdapters$34;
import com.google.gson.internal.bind.TypeAdapters$35;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

/* renamed from: X.0zN  reason: invalid class name and case insensitive filesystem */
public final class C09080zN {
    public static final AnonymousClass0yl<AtomicBoolean> A00;
    public static final AnonymousClass0yl<AtomicInteger> A01;
    public static final AnonymousClass0yl<AtomicIntegerArray> A02;
    public static final AnonymousClass0yl<BigDecimal> A03 = new AnonymousClass0V2();
    public static final AnonymousClass0yl<BigInteger> A04 = new AnonymousClass0V1();
    public static final AnonymousClass0yl<BitSet> A05;
    public static final AnonymousClass0yl<Boolean> A06;
    public static final AnonymousClass0yl<Boolean> A07 = new AnonymousClass0Ue();
    public static final AnonymousClass0yl<Number> A08;
    public static final AnonymousClass0yl<Calendar> A09;
    public static final AnonymousClass0yl<Character> A0A;
    public static final AnonymousClass0yl<Class> A0B;
    public static final AnonymousClass0yl<Currency> A0C;
    public static final AnonymousClass0yl<Number> A0D = new AnonymousClass0V6();
    public static final AnonymousClass0yl<Number> A0E = new AnonymousClass0V7();
    public static final AnonymousClass0yl<InetAddress> A0F;
    public static final AnonymousClass0yl<Number> A0G;
    public static final AnonymousClass0yl<AbstractC08820ye> A0H;
    public static final AnonymousClass0yl<Locale> A0I;
    public static final AnonymousClass0yl<Number> A0J = new AnonymousClass0V8();
    public static final AnonymousClass0yl<Number> A0K;
    public static final AnonymousClass0yl<Number> A0L;
    public static final AnonymousClass0yl<String> A0M;
    public static final AnonymousClass0yl<StringBuffer> A0N;
    public static final AnonymousClass0yl<StringBuilder> A0O;
    public static final AnonymousClass0yl<URI> A0P;
    public static final AnonymousClass0yl<URL> A0Q;
    public static final AnonymousClass0yl<UUID> A0R;
    public static final AbstractC08860ym A0S;
    public static final AbstractC08860ym A0T;
    public static final AbstractC08860ym A0U;
    public static final AbstractC08860ym A0V;
    public static final AbstractC08860ym A0W;
    public static final AbstractC08860ym A0X;
    public static final AbstractC08860ym A0Y;
    public static final AbstractC08860ym A0Z;
    public static final AbstractC08860ym A0a;
    public static final AbstractC08860ym A0b;
    public static final AbstractC08860ym A0c = new TypeAdapters$30();
    public static final AbstractC08860ym A0d;
    public static final AbstractC08860ym A0e;
    public static final AbstractC08860ym A0f;
    public static final AbstractC08860ym A0g;
    public static final AbstractC08860ym A0h;
    public static final AbstractC08860ym A0i;
    public static final AbstractC08860ym A0j;
    public static final AbstractC08860ym A0k;
    public static final AbstractC08860ym A0l;
    public static final AbstractC08860ym A0m = new TypeAdapters$26();
    public static final AbstractC08860ym A0n;
    public static final AbstractC08860ym A0o;
    public static final AbstractC08860ym A0p;

    static {
        AnonymousClass0c2 r2 = new AnonymousClass0c2(new C01470Uz());
        A0B = r2;
        A0a = new TypeAdapters$32(Class.class, r2);
        AnonymousClass0c2 r22 = new AnonymousClass0c2(new C01360Un());
        A05 = r22;
        A0V = new TypeAdapters$32(BitSet.class, r22);
        AnonymousClass0Uf r3 = new AnonymousClass0Uf();
        A06 = r3;
        A0W = new TypeAdapters$33(Boolean.TYPE, Boolean.class, r3);
        AnonymousClass0Ud r32 = new AnonymousClass0Ud();
        A08 = r32;
        A0X = new TypeAdapters$33(Byte.TYPE, Byte.class, r32);
        AnonymousClass0Uc r33 = new AnonymousClass0Uc();
        A0L = r33;
        A0i = new TypeAdapters$33(Short.TYPE, Short.class, r33);
        AnonymousClass0Ub r34 = new AnonymousClass0Ub();
        A0G = r34;
        A0e = new TypeAdapters$33(Integer.TYPE, Integer.class, r34);
        AnonymousClass0c2 r23 = new AnonymousClass0c2(new AnonymousClass0Ua());
        A01 = r23;
        A0U = new TypeAdapters$32(AtomicInteger.class, r23);
        AnonymousClass0c2 r24 = new AnonymousClass0c2(new AnonymousClass0UZ());
        A00 = r24;
        A0S = new TypeAdapters$32(AtomicBoolean.class, r24);
        AnonymousClass0c2 r25 = new AnonymousClass0c2(new AnonymousClass0V9());
        A02 = r25;
        A0T = new TypeAdapters$32(AtomicIntegerArray.class, r25);
        AnonymousClass0V5 r26 = new AnonymousClass0V5();
        A0K = r26;
        A0h = new TypeAdapters$32(Number.class, r26);
        AnonymousClass0V4 r35 = new AnonymousClass0V4();
        A0A = r35;
        A0Z = new TypeAdapters$33(Character.TYPE, Character.class, r35);
        AnonymousClass0V3 r27 = new AnonymousClass0V3();
        A0M = r27;
        A0l = new TypeAdapters$32(String.class, r27);
        AnonymousClass0V0 r28 = new AnonymousClass0V0();
        A0O = r28;
        A0k = new TypeAdapters$32(StringBuilder.class, r28);
        C01460Uy r29 = new C01460Uy();
        A0N = r29;
        A0j = new TypeAdapters$32(StringBuffer.class, r29);
        C01450Ux r210 = new C01450Ux();
        A0Q = r210;
        A0o = new TypeAdapters$32(URL.class, r210);
        C01440Uw r211 = new C01440Uw();
        A0P = r211;
        A0n = new TypeAdapters$32(URI.class, r211);
        C01430Uv r212 = new C01430Uv();
        A0F = r212;
        A0d = new TypeAdapters$35(InetAddress.class, r212);
        C01420Uu r213 = new C01420Uu();
        A0R = r213;
        A0p = new TypeAdapters$32(UUID.class, r213);
        AnonymousClass0c2 r214 = new AnonymousClass0c2(new C01410Ut());
        A0C = r214;
        A0b = new TypeAdapters$32(Currency.class, r214);
        C01390Uq r1 = new C01390Uq();
        A09 = r1;
        A0Y = new TypeAdapters$34(r1);
        C01380Up r215 = new C01380Up();
        A0I = r215;
        A0g = new TypeAdapters$32(Locale.class, r215);
        C01370Uo r216 = new C01370Uo();
        A0H = r216;
        A0f = new TypeAdapters$35(AbstractC08820ye.class, r216);
    }
}
