package com.oculus.horizon.auth;

import X.AnonymousClass0J5;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class HorizonAuthModule extends AnonymousClass0J5 {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForHorizonAuthModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_auth_receiver_BaseLoginHandler_ULSEP_BINDING_ID = 321;
        public static final int _UL__ULSEP_com_oculus_horizon_auth_HorizonLoginHandler_ULSEP_BINDING_ID = 51;
    }
}
