package com.oculus.logging.analytics2;

import X.C0219We;
import X.I0;
import X.SU;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public abstract class Analytics2LoggerModule extends I0 {
    public static volatile SU _UL__ULSEP_com_facebook_pigeon_common_protocol_DeviceIdProvider_ULSEP_INSTANCE;
    public static volatile C0219We _UL__ULSEP_com_fasterxml_jackson_databind_ObjectMapper_ULSEP_INSTANCE;

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForAnalytics2LoggerModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_facebook_analytics2_dumper_Analytics2DumperPlugin_ULSEP_BINDING_ID = 92;
        public static final int _UL__ULSEP_com_facebook_analytics2_logger_Analytics2Logger_ULSEP_BINDING_ID = 101;
        public static final int _UL__ULSEP_com_facebook_pigeon_common_protocol_DeviceIdProvider_ULSEP_BINDING_ID = 29;
        public static final int _UL__ULSEP_com_fasterxml_jackson_databind_ObjectMapper_ULSEP_BINDING_ID = 73;
        public static final int _UL__ULSEP_com_oculus_logging_analytics2_Analytics2LoggerProvider_ULSEP_BINDING_ID = 77;
        public static final int _UL__ULSEP_com_oculus_logging_analytics2_AppInfoProviderImpl_ULSEP_BINDING_ID = 130;
        public static final int _UL__ULSEP_com_oculus_logging_analytics2_EventBuilderConfig_ULSEP_BINDING_ID = 37;
        public static final int _UL__ULSEP_com_oculus_logging_analytics2_EventBuilderProvider_ULSEP_BINDING_ID = 53;
        public static final int _UL__ULSEP_com_oculus_logging_analytics2_EventCacheProvider_ULSEP_BINDING_ID = 28;
        public static final int _UL__ULSEP_com_oculus_logging_analytics2_EventFactoryWithAnalytics2SupportProvider_ULSEP_BINDING_ID = 26;
        public static final int _UL__ULSEP_com_oculus_logging_analytics2_FileOps_ULSEP_BINDING_ID = 18;
        public static final int _UL__ULSEP_com_oculus_logging_analytics2_RtcClock_ULSEP_BINDING_ID = 30;
        public static final int _UL__ULSEP_com_oculus_logging_analytics2_SessionManagerImpl_ULSEP_BINDING_ID = 137;
        public static final int _UL__ULSEP_java_util_Set_ULLT_com_facebook_analytics2_logger_EventListener_ULGT__ULSEP_com_oculus_logging_analytics2_HighPriEventListener_ULSEP_BINDING_ID = 71;
        public static final int _UL__ULSEP_java_util_Set_ULLT_com_facebook_analytics2_logger_EventListener_ULGT__ULSEP_com_oculus_logging_analytics2_NormalPriEventListener_ULSEP_BINDING_ID = 42;
    }
}
