package com.facebook.storage.attribution;

public enum Location {
    DATA_DIRECTORY,
    CACHE_DIRECTORY,
    FILES_DIRECTORY,
    ABSOLUTE_PATH_OVERRIDE,
    EXTERNAL_CACHE_DIRECTORY,
    EXTERNAL_FILES_DIRECTORY,
    EXTERNAL_MEDIA_DIRECTORY,
    DATABASE_DIRECTORY
}
