package com.oculus.util.device;

import X.AnonymousClass0Qr;
import X.AnonymousClass0VI;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class DeviceModule extends AnonymousClass0VI {

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_util_device_DeviceUtils_ULSEP_BINDING_ID = 21;
    }

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForDeviceModule {
        public static void bind(AnonymousClass0Qr r0) {
        }
    }
}
