package com.facebook.mobileconfig.ota;

import com.facebook.infer.annotation.Nullsafe;
import com.facebook.inject.AbstractLibraryModule;
import com.facebook.inject.InjectorLike;
import com.facebook.inject.InjectorModule;
import com.facebook.inject.ProviderMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import javax.annotation.Nullable;

@InjectorModule
@Nullsafe(Nullsafe.Mode.LOCAL)
public class MobileConfigOTAUtilModule extends AbstractLibraryModule {
    @ProviderMethod
    @Nullable
    static MobileConfigOTAUtil provideMobileConfigOTAUtil() {
        return null;
    }

    @AutoGeneratedFactoryMethod
    public static final MobileConfigOTAUtil _UL__ULSEP_com_facebook_mobileconfig_ota_MobileConfigOTAUtil_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideMobileConfigOTAUtil();
    }
}
