package com.oculus.common.sociallogger;

public enum ActionId {
    PARTY_CREATE("PARTY_CREATE"),
    PARTY_CREATE_TOGGLE_DISMISS_REMINDER("PARTY_CREATE_TOGGLE_DISMISS_REMINDER"),
    PARTY_JOIN("PARTY_JOIN"),
    PARTY_FETCH_GROUP_LAUNCH_APPS("PARTY_FETCH_GROUP_LAUNCH_APPS"),
    PARTY_FETCH_GROUP_LAUNCH_DESTINATIONS("PARTY_FETCH_GROUP_LAUNCH_DESTINATIONS"),
    PARTY_SEND_LINK_TO_THREAD("PARTY_SEND_LINK_TO_THREAD"),
    PARTY_SET_JOIN_TYPE_UNKNOWN("PARTY_SET_JOIN_TYPE_UNKNOWN"),
    PARTY_SET_JOIN_TYPE_INVITE_ONLY("PARTY_SET_JOIN_TYPE_INVITE_ONLY"),
    PARTY_SET_JOIN_TYPE_FRIENDS_OF_PARTICIPANTS("PARTY_SET_JOIN_TYPE_FRIENDS_OF_PARTICIPANTS"),
    PARTY_TOGGLE_LINK_INVITE_OFF("PARTY_TOGGLE_LINK_INVITE_OFF"),
    PARTY_TOGGLE_LINK_INVITE_ON("PARTY_TOGGLE_LINK_INVITE_ON"),
    PARTY_UPDATE_DESTINATION("PARTY_UPDATE_DESTINATION"),
    PARTY_LEAVE("PARTY_LEAVE"),
    PARTY_SEND_INVITE("PARTY_SEND_INVITE"),
    PARTY_CANCEL_INVITE("PARTY_CANCEL_INVITE"),
    PARTY_KICK_USER("PARTY_KICK_USER"),
    NAVIGATE_TO_SHARE_SHEET("NAVIGATE_TO_SHARE_SHEET"),
    BLOCK_USER("BLOCK_USER"),
    NAVIGATE_TO_DIALOG("NAVIGATE_TO_DIALOG"),
    PARTY_FOOTER_GO_TO_APP_LAUNCH("GO_TO_APP_LAUNCH"),
    PARTY_FOOTER_LAUNCH_SOLO("LAUNCH_SOLO"),
    PARTY_FOOTER_SET_USER_RESPONSE("SET_USER_RESPONSE"),
    PARTY_FOOTER_PREPARE_GROUP_LAUNCH("PREPARE_GROUP_LAUNCH"),
    PARTY_FOOTER_LAUNCH_GROUP_LAUNCH("LAUNCH_GROUP_LAUNCH"),
    MESSAGE_SEND("MESSAGE_SEND"),
    MESSAGE_THREAD_INITIAL_LOAD("MESSAGE_THREAD_INITIAL_LOAD"),
    FACEBOOK_BLOCK_DIALOG_BLOCK("FACEBOOK_BLOCK_DIALOG_BLOCK"),
    FACEBOOK_BLOCK_DIALOG_UNBLOCK("FACEBOOK_BLOCK_DIALOG_UNBLOCK"),
    MESSENGER_INTEGRITY_DIALOG_MESSENGER_BLOCK("MESSENGER_INTEGRITY_DIALOG_MESSENGER_BLOCK"),
    MESSENGER_INTEGRITY_DIALOG_MESSENGER_UNBLOCK("MESSENGER_INTEGRITY_DIALOG_MESSENGER_UNBLOCK"),
    MESSENGER_INTEGRITY_DIALOG_FACEBOOK_BLOCK("MESSENGER_INTEGRITY_DIALOG_FACEBOOK_BLOCK"),
    MESSENGER_INTEGRITY_DIALOG_FACEBOOK_UNBLOCK("MESSENGER_INTEGRITY_DIALOG_FACEBOOK_UNBLOCK"),
    ACCEPT_FRIEND_REQUEST("ACCEPT_FRIEND_REQUEST"),
    ADD_FRIEND("ADD_FRIEND"),
    CANCEL_FRIEND_REQUEST("CANCEL_FRIEND_REQUEST"),
    DENY_FRIEND_REQUEST("DENY_FRIEND_REQUEST"),
    HIDE_PYMK_USER("HIDE_PYMK_USER"),
    UNFRIEND("UNFRIEND"),
    FETCH_FB_FRIENDS("FETCH_FB_FRIENDS"),
    FETCH_OCULUS_VIEWER_PARTY_DATA("FETCH_OCULUS_VIEWER_PARTY_DATA"),
    FETCH_OCULUS_FRIEND_REQUESTS("FETCH_OCULUS_FRIEND_REQUESTS"),
    FETCH_OCULUS_FRIENDS("FETCH_OCULUS_FRIENDS"),
    FETCH_OCULUS_LINKED_ACCOUNTS("FETCH_OCULUS_LINKED_ACCOUNTS"),
    FETCH_OCULUS_PYMK("FETCH_OCULUS_PYMK"),
    FETCH_OCULUS_SEARCH_RESULTS("FETCH_OCULUS_SEARCH_RESULTS"),
    REAUTH_SKIP("REAUTH_SKIP"),
    REAUTH_VALIDATE_PASSWORD("REAUTH_VALIDATE_PASSWORD"),
    REAUTH_VALIDATE_PASSWORD_INCORRECT_PASSWORD("REAUTH_VALIDATE_PASSWORD_INCORRECT_PASSWORD"),
    REAUTH_VALIDATE_PASSWORD_TOO_MANY_ATTEMPTS("REAUTH_VALIDATE_PASSWORD_TOO_MANY_ATTEMPTS"),
    REAUTH_VALIDATE_PASSWORD_ERROR_UNKNOWN("REAUTH_VALIDATE_PASSWORD_ERROR_UNKNOWN"),
    SET_ACTIVE_STATUS_ACTIVE("SET_ACTIVE_STATUS_ACTIVE"),
    SET_ACTIVE_STATUS_INACTIVE("SET_ACTIVE_STATUS_INACTIVE"),
    SET_ACTIVE_STATUS_TOGGLE("SET_ACTIVE_STATUS_TOGGLE"),
    SOCIAL_SETTINGS_MESSENGER_SIGN_OUT("SOCIAL_SETTINGS_MESSENGER_SIGN_OUT"),
    CHECK_WHETHER_MESSENGER_IS_AUTHENTICATED("CHECK_WHETHER_MESSENGER_IS_AUTHENTICATED");
    
    private final String mActionId;

    private ActionId(String str) {
        this.mActionId = str;
    }

    public String getTelemetryActionId() {
        return this.mActionId;
    }
}
