package com.oculus.common.sociallogger;

public enum SurfaceType {
    APP_SELECT("APP_SELECT"),
    DESTINATION_SELECT("DESTINATION_SELECT"),
    PROFILE_CONFIRM("PROFILE_CONFIRM"),
    JOIN_PARTY("JOIN_PARTY"),
    FACEBOOK_BLOCK("FACEBOOK_BLOCK"),
    MESSENGER_INTEGRITY("MESSENGER_INTEGRITY"),
    DEEPLINKED_THREAD("DEEPLINKED_THREAD"),
    FB_MESSENGER_INITIALIZING("FB_MESSENGER_INITIALIZING"),
    FB_MESSENGER_INITIALIZED("FB_MESSENGER_INITIALIZED"),
    FB_MESSENGER_REACTIONS_SUMMARY("FB_MESSENGER_REACTIONS_SUMMARY"),
    FB_MESSENGER_REACTIONS_DETAILS("FB_MESSENGER_REACTIONS_DETAILS"),
    FB_MESSENGER_REACTIONS_PILL("FB_MESSENGER_REACTIONS_PILL"),
    MESSAGE_COMPOSE("MESSAGE_COMPOSE"),
    THREAD_LIST_ITEM("THREAD_LIST_ITEM"),
    THREAD_VIEW("THREAD_VIEW"),
    PARTY_INITIAL_LOAD("PARTY_INITIAL_LOAD"),
    PARTY_MEMBER_LIST("PARTY_MEMBER_LIST"),
    PARTIES_HEADER("PARTIES_HEADER"),
    PARTIES_FOOTER("PARTIES_FOOTER"),
    PARTY_PRIVACY("PARTY_PRIVACY"),
    PARTY_OC_ADD_TO_PARTY("PARTY_OC_ADD_TO_PARTY"),
    FB_PEOPLE_INITIALIZING("FB_PEOPLE_INITIALIZING"),
    FB_PEOPLE_INITIALIZED("FB_PEOPLE_INITIALIZED"),
    ALL_CONNECTIONS("ALL_CONNECTIONS"),
    ALL_NEARBY("ALL_NEARBY"),
    FRIENDS("FRIENDS"),
    REQUESTS("REQUESTS"),
    SEARCH("SEARCH"),
    SUGGESTIONS("SUGGESTIONS"),
    PEOPLE_NEARBY("PEOPLE_NEARBY"),
    BACKGROUND_FETCHER("BACKGROUND_FETCHER"),
    REAUTH_INITIALIZING("REAUTH_INITIALIZING"),
    REAUTH_INITIALIZED("REAUTH_INITIALIZED"),
    REAUTH_NUX_DIALOG("REAUTH_NUX_DIALOG"),
    REAUTH("REAUTH"),
    SETTINGS_INITIALIZING("SETTINGS_INITIALIZING"),
    SETTINGS_INITIALIZED("SETTINGS_INITIALIZED"),
    ACTIVE_STATUS("ACTIVE_STATUS"),
    PRIVACY("PRIVACY"),
    MESSENGER_ACCOUNT("MESSENGER_ACCOUNT"),
    MESSENGER_SIGN_OUT_DIALOG("MESSENGER_SIGN_OUT_DIALOG"),
    SIDE_NAV("SIDE_NAV");
    
    private final String mSurfaceType;

    private SurfaceType(String str) {
        this.mSurfaceType = str;
    }

    public String getTelemetrySurfaceType() {
        return this.mSurfaceType;
    }
}
