package com.oculus.http.common.graphql;

public class GraphQLQueryConstants {
    public static final String APP_ENTITLEMENT_CORE_ATTRIBUTES = "id,last_used,signed_token.machine_id(<machine_id>),";
    public static final String APP_ENTITLEMENT_CORE_ATTRIBUTES_OSS = "id, last_used, signed_token(machine_id: $machine_id),";
    public static final String BINARY_DOWNLOAD_ATTRIBUTES = " id, uri, size,";
    public static final String BINARY_DOWNLOAD_ATTRIBUTES_OSS = " id, uri, size,";
    public static final String EMPTY_BODY = "";
    public static final String GRAPHQL_ENDPOINT = "/graphql";
    public static final String GRAPHQL_OSS_QUERY_KEY = "doc";
    public static final String GRAPHQL_OSS_QUERY_PARAMS_KEY = "variables";
    public static final String GRAPHQL_QUERY_KEY = "q";
    public static final String GRAPHQL_QUERY_PARAMS_KEY = "query_params";
    public static final String HORIZON_STORE_FB_ID = "1659902747583923";
    public static final String ITEM_CORE_ATTRIBUTES = "  __typename,  id,  display_name,  category,  category_name,  grouping {     id,    cloud_file_is_enabled,    iap_items_2 {      nodes {        id,      },    },  },  latest_supported_binary {    id,    package_name,    version,    version_code,    target_android_sdk_version,    external_signatures,    size,    permissions,    user_quality_rating {id,author {  id,  alias,  name,  profile_photo.size(360x360) as avatar {    name,    uri,    width,    height,  },},date,score,rated_binary {  version,  id},author_timespent_pct,review_title,review_description,developer_response {  date,  body,},review_rank_by_viewer,review_helpful_count,    },    uri,    can_use_external_storage,    obb_binary {      id, id, uri, size,    },  },  cover_square_image       .size(360x360) {    name,    uri,  },  cover_landscape_image       .size(720x405) {    name,    uri,  },  cover_landscape_image       .size(180x101) as thumbnail {    name,    uri,  },  small_landscape_image       .size(360x120) {    name,    uri,  },  display_long_description,  display_short_description,  required_input_device {    tag,    name  },  supported_input_devices_list {    tag,    name  },  app_viewer_id,  is_viewer_entitled,  entitlement {id,last_used,signed_token.machine_id(<machine_id>),  },  internet_connection,  internet_connection_name,  user_interaction_modes,  user_interaction_mode_names,  supported_in_app_languages {    tag,    name,  },  comfort_rating,  quality_ratings_by_viewer {id,author {  id,  alias,  name,  profile_photo.size(360x360) as avatar {    name,    uri,    width,    height,  },},date,score,rated_binary {  version,  id},author_timespent_pct,review_title,review_description,developer_response {  date,  body,},review_rank_by_viewer,review_helpful_count,  },  developer_filtered_livestreaming_status,  livestreaming_audio_hooking_enabled,  chromecast_audio_enabled,  microphone_usage,  min_recommended_version_code,  min_required_version_code,  style_theme,  is_demo_of {    id,  },  supported_player_modes,  is_test,";
    public static final String ITEM_CORE_ATTRIBUTES_OSS = "__typename,id,display_name,... on Application {  category,  category_name,  environment_path,  grouping {    id,    cloud_file_is_enabled,    iap_items_2 {      nodes {        id      }    }  }  latest_supported_binary {    ... on AndroidBinary {      id,      package_name,      head_tracking,      version,      version_code,      target_android_sdk_version,      external_signatures,      size,      permissions,      user_quality_rating {id,author {  id,  alias,  name,  avatar : profile_photo(size: \"360x360\") {    name,    uri,    width,    height,  },},date,score,rated_binary {  version,  id,},author_timespent_pct,review_title,review_description,developer_response {  date,  body,},review_rank_by_viewer,review_helpful_count,      },      uri,      can_use_external_storage,      obb_binary {        ... on OBBBinary { id, uri, size,        },      },    },  },  cover_square_image(size: \"360x360\") {    name,    uri,  },  cover_landscape_image(size: \"720x405\") {    name,    uri,  },  thumbnail: cover_landscape_image(size: \"180x101\") {    name,    uri,  },  small_landscape_image(size: \"360x120\") {    name    uri  }  display_long_description,  display_short_description,  required_input_device {    tag,    name,  },  supported_input_devices_list {    tag,    name,  },  app_viewer_id,  is_viewer_entitled,  entitlement {id, last_used, signed_token(machine_id: $machine_id),  },  internet_connection,  internet_connection_name,  user_interaction_modes,  user_interaction_mode_names,  supported_in_app_languages {    tag,    name,  },  comfort_rating,  quality_ratings_by_viewer {id,author {  id,  alias,  name,  avatar : profile_photo(size: \"360x360\") {    name,    uri,    width,    height,  },},date,score,rated_binary {  version,  id,},author_timespent_pct,review_title,review_description,developer_response {  date,  body,},review_rank_by_viewer,review_helpful_count,  }  developer_filtered_livestreaming_status,  livestreaming_audio_hooking_enabled,  chromecast_audio_enabled,  microphone_usage,  min_recommended_version_code,  min_required_version_code,  style_theme,  is_demo_of {    id,  },  platform, share_capabilities,  supported_player_modes,  is_test,}";
    public static final String OCULUS_6DOF_STORE_ID = "215871315640047";
    public static final String QUALITY_RATING_CORE_ATTRIBUTES = "id,author {  id,  alias,  name,  profile_photo.size(360x360) as avatar {    name,    uri,    width,    height,  },},date,score,rated_binary {  version,  id},author_timespent_pct,review_title,review_description,developer_response {  date,  body,},review_rank_by_viewer,review_helpful_count,";
    public static final String QUALITY_RATING_CORE_ATTRIBUTES_OSS = "id,author {  id,  alias,  name,  avatar : profile_photo(size: \"360x360\") {    name,    uri,    width,    height,  },},date,score,rated_binary {  version,  id,},author_timespent_pct,review_title,review_description,developer_response {  date,  body,},review_rank_by_viewer,review_helpful_count,";
}
