package com.oculus.horizon.endpoint;

import X.AnonymousClass0J5;
import X.AnonymousClass0NO;
import android.content.Context;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.ForAppContext;
import com.facebook.inject.InjectorModule;
import com.facebook.inject.ProviderMethod;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import com.google.common.base.Throwables;
import com.oculus.http.core.annotations.OculusApiSharedPrefs;

@InjectorModule
public class HorizonEndpointModule extends AnonymousClass0J5 {
    public static final String KEY_CUSTOM_API_ENDPOINT = "key_custom_api_endpoint";
    public static final String SHARED_PREFS_API = "api_shared_preferences";
    public static final String TAG = "HorizonEndpointModule";

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForHorizonEndpointModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_android_content_SharedPreferences_ULSEP_com_oculus_http_core_annotations_OculusApiSharedPrefs_ULSEP_BINDING_ID = 34;
        public static final int _UL__ULSEP_java_lang_String_ULSEP_com_oculus_http_core_annotations_OculusApiEndpoint_ULSEP_BINDING_ID = 339;
    }

    @OculusApiSharedPrefs
    @ProviderMethod
    public static SharedPreferences A00(@ForAppContext Context context) {
        try {
            return context.createPackageContext("com.oculus.horizon", 1).getSharedPreferences(SHARED_PREFS_API, 4);
        } catch (PackageManager.NameNotFoundException e) {
            AnonymousClass0NO.A0B(TAG, "Failed to create Horizon Context", e);
            Throwables.propagate(e);
            throw new RuntimeException("Redex: Unreachable code after no-return invoke");
        }
    }
}
