package com.oculus.alpenglow.config;

import X.AbstractC01750Lk;
import com.facebook.infer.annotation.Nullsafe;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
@Nullsafe(Nullsafe.Mode.LOCAL)
public abstract class ConfigModule extends AbstractC01750Lk {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForConfigModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_alpenglow_config_BroadcastIntentHelper_ULSEP_BINDING_ID = 6;
        public static final int _UL__ULSEP_com_oculus_alpenglow_config_ConfigUnlockListener_ULSEP_BINDING_ID = 77;
        public static final int _UL__ULSEP_com_oculus_alpenglow_config_ConfigurationStore_ULSEP_BINDING_ID = 97;
        public static final int _UL__ULSEP_com_oculus_alpenglow_config_DeviceTypeAdapter_ULSEP_BINDING_ID = 90;
        public static final int _UL__ULSEP_com_oculus_alpenglow_config_FetchConfigurationAction_ULSEP_BINDING_ID = 50;
        public static final int _UL__ULSEP_com_oculus_alpenglow_config_ScheduleConfigSyncListener_ULSEP_BINDING_ID = 35;
        public static final int _UL__ULSEP_java_util_Set_ULLT_com_oculus_alpenglow_config_ConfigChangeListener_ULGT__ULSEP_BINDING_ID = 115;
    }
}
