package com.oculus.alpenglow.config;

import X.AbstractC02990bJ;
import X.AnonymousClass0Lh;
import X.AnonymousClass0NK;
import X.AnonymousClass0R7;
import com.facebook.infer.annotation.Nullsafe;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.oculus.alpenglow.logging.ConfigLogger;
import com.oculus.alpenglow.logging.LoggerConstants;

@Dependencies({"_UL__ULSEP_com_oculus_alpenglow_config_ConfigurationStore_ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_alpenglow_logging_ConfigLogger_ULSEP_BINDING_ID"})
@Nullsafe(Nullsafe.Mode.LOCAL)
public class FetchConfigurationAction {
    public static final String ACTION_FETCH_CONFIGURATION = "com.oculus.alpenglow.config.FETCH_CONFIGURATION";
    public static final String TAG = "EnterpriseServer.FetchConfigurationAction";
    public AnonymousClass0R7 _UL_mInjectionContext;

    @AutoGeneratedFactoryMethod
    public static final FetchConfigurationAction A00(AbstractC02990bJ r1) {
        return new FetchConfigurationAction(r1);
    }

    public final void A01() {
        AnonymousClass0NK.A01(TAG, "fetching configuration");
        ((ConfigurationStore) AnonymousClass0Lh.A03(0, 97, this._UL_mInjectionContext)).A03(((ConfigLogger) AnonymousClass0Lh.A03(1, 45, this._UL_mInjectionContext)).A01(LoggerConstants.CONFIGURATION_FETCH_REASON_BROADCAST, LoggerConstants.CONFIGURATION_FETCH_TYPE_NORMAL));
    }

    @Inject
    public FetchConfigurationAction(AbstractC02990bJ r3) {
        this._UL_mInjectionContext = new AnonymousClass0R7(2, r3);
    }
}
