package com.facebook.common.android;

import android.accounts.AccountManager;
import android.app.Activity;
import android.app.ActivityManager;
import android.app.AlarmManager;
import android.app.DownloadManager;
import android.app.KeyguardManager;
import android.app.NotificationManager;
import android.app.SearchManager;
import android.app.Service;
import android.app.admin.DevicePolicyManager;
import android.content.ClipboardManager;
import android.content.ContentResolver;
import android.content.Context;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.hardware.SensorManager;
import android.location.Geocoder;
import android.location.LocationManager;
import android.media.AudioManager;
import android.media.MediaPlayer;
import android.media.MediaRecorder;
import android.net.ConnectivityManager;
import android.net.NetworkInfo;
import android.net.wifi.WifiManager;
import android.os.Build;
import android.os.Handler;
import android.os.PowerManager;
import android.os.Vibrator;
import android.renderscript.RenderScript;
import android.telephony.TelephonyManager;
import android.view.LayoutInflater;
import android.view.WindowManager;
import android.view.accessibility.AccessibilityManager;
import android.view.inputmethod.InputMethodManager;
import androidx.core.app.NotificationCompat;
import androidx.fragment.app.FragmentActivity;
import androidx.localbroadcastmanager.content.LocalBroadcastManager;
import com.facebook.common.build.BuildConstants;
import com.facebook.common.util.context.ContextUtils;
import com.facebook.debug.log.BLog;
import com.facebook.inject.AbstractLibraryModule;
import com.facebook.inject.ApplicationScopeClassInit;
import com.facebook.inject.ApplicationScoped;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.Binder;
import com.facebook.inject.BundledAndroidModule;
import com.facebook.inject.InjectorLike;
import com.facebook.inject.InjectorModule;
import com.facebook.inject.Lazy;
import com.facebook.inject.ProviderMethod;
import com.facebook.inject.UltralightLazy;
import com.facebook.inject.UltralightProvider;
import com.facebook.inject.UltralightSingletonProvider;
import com.facebook.inject.UnsafeContextInjection;
import com.facebook.support.v4.net.ConnectivityManagerCompat;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import com.facebook.ultralight.UL;
import com.google.inject.Key;
import com.oculus.horizon.logging.LoggingKeys;
import java.lang.annotation.Annotation;
import java.util.Locale;
import javax.annotation.Nullable;
import javax.inject.Provider;

@InjectorModule
public class AndroidModule extends AbstractLibraryModule {
    private static volatile PackageInfo _UL__ULSEP_android_content_pm_PackageInfo_ULSEP_INSTANCE;
    private static final Object _UL__ULSEP_android_content_pm_PackageInfo_ULSEP_LOCK = new Object();
    private static volatile PackageManager _UL__ULSEP_android_content_pm_PackageManager_ULSEP_INSTANCE;
    private static final Object _UL__ULSEP_android_content_pm_PackageManager_ULSEP_LOCK = new Object();
    private static volatile Geocoder _UL__ULSEP_android_location_Geocoder_ULSEP_INSTANCE;
    private static final Object _UL__ULSEP_android_location_Geocoder_ULSEP_LOCK = new Object();
    private static volatile RenderScript _UL__ULSEP_android_renderscript_RenderScript_ULSEP_INSTANCE;
    private static final Object _UL__ULSEP_android_renderscript_RenderScript_ULSEP_LOCK = new Object();
    private static volatile LocalBroadcastManager _UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_INSTANCE;
    private static final Object _UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_LOCK = new Object();
    private static volatile FbLocalBroadcastManager _UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_INSTANCE;
    private static volatile ConnectivityManagerCompat _UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_INSTANCE;
    private static volatile String _UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_INSTANCE;
    private static final Object _UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_LOCK = new Object();

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_android_accounts_AccountManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_accounts_AccountManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(AccountManager.class)));
        public static final int _UL__ULSEP_android_app_ActivityManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_app_ActivityManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(ActivityManager.class)));
        public static final int _UL__ULSEP_android_app_Activity_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_app_Activity_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(Activity.class)));
        public static final int _UL__ULSEP_android_app_AlarmManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_app_AlarmManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(AlarmManager.class)));
        public static final int _UL__ULSEP_android_app_DownloadManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_app_DownloadManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(DownloadManager.class)));
        public static final int _UL__ULSEP_android_app_KeyguardManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_app_KeyguardManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(KeyguardManager.class)));
        public static final int _UL__ULSEP_android_app_NotificationManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_app_NotificationManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(NotificationManager.class)));
        public static final int _UL__ULSEP_android_app_SearchManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_app_SearchManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(SearchManager.class)));
        public static final int _UL__ULSEP_android_app_Service_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_app_Service_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(Service.class)));
        public static final int _UL__ULSEP_android_app_admin_DevicePolicyManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_app_admin_DevicePolicyManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(DevicePolicyManager.class)));
        public static final int _UL__ULSEP_android_content_ClipboardManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_content_ClipboardManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(ClipboardManager.class)));
        public static final int _UL__ULSEP_android_content_ContentResolver_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_content_ContentResolver_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(ContentResolver.class)));
        public static final int _UL__ULSEP_android_content_pm_ApplicationInfo_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_content_pm_ApplicationInfo_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(ApplicationInfo.class)));
        public static final int _UL__ULSEP_android_content_pm_PackageInfo_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_content_pm_PackageInfo_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(PackageInfo.class)));
        public static final int _UL__ULSEP_android_content_pm_PackageManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_content_pm_PackageManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(PackageManager.class)));
        public static final int _UL__ULSEP_android_hardware_SensorManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_hardware_SensorManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(SensorManager.class)));
        public static final int _UL__ULSEP_android_location_Geocoder_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_location_Geocoder_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(Geocoder.class)));
        public static final int _UL__ULSEP_android_location_LocationManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_location_LocationManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(LocationManager.class)));
        public static final int _UL__ULSEP_android_media_AudioManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_media_AudioManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(AudioManager.class)));
        public static final int _UL__ULSEP_android_media_MediaPlayer_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_media_MediaPlayer_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(MediaPlayer.class)));
        public static final int _UL__ULSEP_android_media_MediaRecorder_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_media_MediaRecorder_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(MediaRecorder.class)));
        public static final int _UL__ULSEP_android_net_ConnectivityManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_net_ConnectivityManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(ConnectivityManager.class)));
        public static final int _UL__ULSEP_android_net_NetworkInfo_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_net_NetworkInfo_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(NetworkInfo.class)));
        public static final int _UL__ULSEP_android_net_wifi_WifiManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_net_wifi_WifiManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(WifiManager.class)));
        public static final int _UL__ULSEP_android_os_Handler_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_os_Handler_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(Handler.class)));
        public static final int _UL__ULSEP_android_os_PowerManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_os_PowerManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(PowerManager.class)));
        public static final int _UL__ULSEP_android_os_Vibrator_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_os_Vibrator_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(Vibrator.class)));
        public static final int _UL__ULSEP_android_renderscript_RenderScript_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_renderscript_RenderScript_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(RenderScript.class)));
        public static final int _UL__ULSEP_android_telephony_TelephonyManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_telephony_TelephonyManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(TelephonyManager.class)));
        public static final int _UL__ULSEP_android_view_LayoutInflater_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_view_LayoutInflater_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(LayoutInflater.class)));
        public static final int _UL__ULSEP_android_view_WindowManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_view_WindowManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(WindowManager.class)));
        public static final int _UL__ULSEP_android_view_accessibility_AccessibilityManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_view_accessibility_AccessibilityManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(AccessibilityManager.class)));
        public static final int _UL__ULSEP_android_view_inputmethod_InputMethodManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_android_view_inputmethod_InputMethodManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(InputMethodManager.class)));
        public static final int _UL__ULSEP_androidx_fragment_app_FragmentActivity_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_androidx_fragment_app_FragmentActivity_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(FragmentActivity.class)));
        public static final int _UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(LocalBroadcastManager.class)));
        public static final int _UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(FbLocalBroadcastManager.class)));
        public static final int _UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(ConnectivityManagerCompat.class)));
        public static final int _UL__ULSEP_java_lang_Integer_ULSEP_com_facebook_common_android_AndroidSdkVersion_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_java_lang_Integer_ULSEP_com_facebook_common_android_AndroidSdkVersion_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(Integer.class, (Class<? extends Annotation>) AndroidSdkVersion.class)));
        public static final int _UL__ULSEP_java_lang_Object_ULSEP_com_facebook_common_android_WifiP2pManagerSystemService_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_java_lang_Object_ULSEP_com_facebook_common_android_WifiP2pManagerSystemService_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(Object.class, (Class<? extends Annotation>) WifiP2pManagerSystemService.class)));
        public static final int _UL__ULSEP_java_lang_Runtime_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_java_lang_Runtime_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(Runtime.class)));
        public static final int _UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(String.class, (Class<? extends Annotation>) PackageName.class)));
    }

    @AutoGeneratedBinder
    static class AutoGeneratedBindingsForAndroidModule {
        AutoGeneratedBindingsForAndroidModule() {
        }

        static void bind(Binder binder) {
            if (!UL.USE_STATIC_DI) {
                binder.require(BundledAndroidModule.class);
                binder.bindDefault(AccountManager.class).toProvider(new AccountManagerMethodAutoProvider());
                binder.bindDefault(Activity.class).toProvider(new ActivityMethodAutoProvider());
                binder.bindDefault(ActivityManager.class).toProvider(new ActivityManagerMethodAutoProvider());
                binder.bindDefault(AlarmManager.class).toProvider(new AlarmManagerMethodAutoProvider());
                binder.bindDefault(DownloadManager.class).toProvider(new DownloadManagerMethodAutoProvider());
                binder.bindDefault(KeyguardManager.class).toProvider(new KeyguardManagerMethodAutoProvider());
                binder.bindDefault(NotificationManager.class).toProvider(new NotificationManagerMethodAutoProvider());
                binder.bindDefault(SearchManager.class).toProvider(new SearchManagerMethodAutoProvider());
                binder.bind(Service.class).toProvider(new ServiceMethodAutoProvider());
                binder.bindDefault(DevicePolicyManager.class).toProvider(new DevicePolicyManagerMethodAutoProvider());
                binder.bind(ClipboardManager.class).toProvider(new ClipboardManagerMethodAutoProvider());
                binder.bindDefault(ContentResolver.class).toProvider(new ContentResolverMethodAutoProvider());
                binder.bindDefault(ApplicationInfo.class).toProvider(new ApplicationInfoMethodAutoProvider());
                binder.bindDefault(PackageInfo.class).toProvider(new PackageInfoMethodAutoProvider()).in(ApplicationScoped.class);
                binder.bindDefault(PackageManager.class).toProvider(new PackageManagerMethodAutoProvider()).in(ApplicationScoped.class);
                binder.bindDefault(SensorManager.class).toProvider(new SensorManagerMethodAutoProvider());
                binder.bind(Geocoder.class).toProvider(new GeocoderMethodAutoProvider()).in(ApplicationScoped.class);
                binder.bindDefault(LocationManager.class).toProvider(new LocationManagerMethodAutoProvider());
                binder.bindDefault(AudioManager.class).toProvider(new AudioManagerMethodAutoProvider());
                binder.bind(MediaPlayer.class).toProvider(new MediaPlayerMethodAutoProvider());
                binder.bind(MediaRecorder.class).toProvider(new MediaRecorderMethodAutoProvider());
                binder.bindDefault(ConnectivityManager.class).toProvider(new ConnectivityManagerMethodAutoProvider());
                binder.bindDefault(NetworkInfo.class).toProvider(new NetworkInfoMethodAutoProvider());
                binder.bindDefault(WifiManager.class).toProvider(new WifiManagerMethodAutoProvider());
                binder.bind(Handler.class).toProvider(new HandlerMethodAutoProvider());
                binder.bindDefault(PowerManager.class).toProvider(new PowerManagerMethodAutoProvider());
                binder.bindDefault(Vibrator.class).toProvider(new VibratorMethodAutoProvider());
                binder.bind(RenderScript.class).toProvider(new RenderScriptMethodAutoProvider()).in(ApplicationScoped.class);
                binder.bindDefault(TelephonyManager.class).toProvider(new TelephonyManagerMethodAutoProvider());
                binder.bindDefault(LayoutInflater.class).toProvider(new LayoutInflaterMethodAutoProvider());
                binder.bindDefault(WindowManager.class).toProvider(new WindowManagerMethodAutoProvider());
                binder.bindDefault(AccessibilityManager.class).toProvider(new AccessibilityManagerMethodAutoProvider());
                binder.bindDefault(InputMethodManager.class).toProvider(new InputMethodManagerMethodAutoProvider());
                binder.bind(FragmentActivity.class).toProvider(new FragmentActivityMethodAutoProvider());
                binder.bindDefault(LocalBroadcastManager.class).toProvider(new LocalBroadcastManagerMethodAutoProvider()).in(ApplicationScoped.class);
                binder.bind(FbLocalBroadcastManager.class).toProvider(new FbLocalBroadcastManagerMethodAutoProvider()).in(ApplicationScoped.class);
                binder.bind(ConnectivityManagerCompat.class).toProvider(new ConnectivityManagerCompatMethodAutoProvider()).in(ApplicationScoped.class);
                binder.bind(Integer.class).annotatedWith(AndroidSdkVersion.class).toProvider(new Integer_com_facebook_common_android_AndroidSdkVersionMethodAutoProvider());
                binder.bind(Object.class).annotatedWith(WifiP2pManagerSystemService.class).toProvider(new Object_com_facebook_common_android_WifiP2pManagerSystemServiceMethodAutoProvider());
                binder.bindDefault(Runtime.class).toProvider(new RuntimeMethodAutoProvider());
                binder.bind(String.class).annotatedWith(PackageName.class).toProvider(new String_com_facebook_common_android_PackageNameMethodAutoProvider()).in(ApplicationScoped.class);
            }
        }
    }

    @AutoGeneratedAccessMethod
    public static final AccountManager _UL__ULSEP_android_accounts_AccountManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (AccountManager) UL.factorymap.get(UL_id._UL__ULSEP_android_accounts_AccountManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final AccountManager _UL__ULSEP_android_accounts_AccountManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideAccountManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final ActivityManager _UL__ULSEP_android_app_ActivityManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (ActivityManager) UL.factorymap.get(UL_id._UL__ULSEP_android_app_ActivityManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final ActivityManager _UL__ULSEP_android_app_ActivityManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideActivityManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final Activity _UL__ULSEP_android_app_Activity_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (Activity) UL.factorymap.get(UL_id._UL__ULSEP_android_app_Activity_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final Activity _UL__ULSEP_android_app_Activity_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideActivity(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final AlarmManager _UL__ULSEP_android_app_AlarmManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (AlarmManager) UL.factorymap.get(UL_id._UL__ULSEP_android_app_AlarmManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final AlarmManager _UL__ULSEP_android_app_AlarmManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideAlarmManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final DownloadManager _UL__ULSEP_android_app_DownloadManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (DownloadManager) UL.factorymap.get(UL_id._UL__ULSEP_android_app_DownloadManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final DownloadManager _UL__ULSEP_android_app_DownloadManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideDownloadManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final KeyguardManager _UL__ULSEP_android_app_KeyguardManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (KeyguardManager) UL.factorymap.get(UL_id._UL__ULSEP_android_app_KeyguardManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final KeyguardManager _UL__ULSEP_android_app_KeyguardManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideKeyguardManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final NotificationManager _UL__ULSEP_android_app_NotificationManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (NotificationManager) UL.factorymap.get(UL_id._UL__ULSEP_android_app_NotificationManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final NotificationManager _UL__ULSEP_android_app_NotificationManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideNotificationManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final SearchManager _UL__ULSEP_android_app_SearchManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (SearchManager) UL.factorymap.get(UL_id._UL__ULSEP_android_app_SearchManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final SearchManager _UL__ULSEP_android_app_SearchManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideSearchManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final Service _UL__ULSEP_android_app_Service_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (Service) UL.factorymap.get(UL_id._UL__ULSEP_android_app_Service_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final Service _UL__ULSEP_android_app_Service_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideService(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final DevicePolicyManager _UL__ULSEP_android_app_admin_DevicePolicyManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (DevicePolicyManager) UL.factorymap.get(UL_id._UL__ULSEP_android_app_admin_DevicePolicyManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final DevicePolicyManager _UL__ULSEP_android_app_admin_DevicePolicyManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideDevicePolicyManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final ClipboardManager _UL__ULSEP_android_content_ClipboardManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (ClipboardManager) UL.factorymap.get(UL_id._UL__ULSEP_android_content_ClipboardManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final ClipboardManager _UL__ULSEP_android_content_ClipboardManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideClipboardManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final ContentResolver _UL__ULSEP_android_content_ContentResolver_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (ContentResolver) UL.factorymap.get(UL_id._UL__ULSEP_android_content_ContentResolver_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final ContentResolver _UL__ULSEP_android_content_ContentResolver_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideContentResolver(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final ApplicationInfo _UL__ULSEP_android_content_pm_ApplicationInfo_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (ApplicationInfo) UL.factorymap.get(UL_id._UL__ULSEP_android_content_pm_ApplicationInfo_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final ApplicationInfo _UL__ULSEP_android_content_pm_ApplicationInfo_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideApplicationInfo(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final PackageInfo _UL__ULSEP_android_content_pm_PackageInfo_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (PackageInfo) UL.factorymap.get(UL_id._UL__ULSEP_android_content_pm_PackageInfo_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final PackageInfo _UL__ULSEP_android_content_pm_PackageInfo_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_android_content_pm_PackageInfo_ULSEP_INSTANCE == null) {
            synchronized (_UL__ULSEP_android_content_pm_PackageInfo_ULSEP_LOCK) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_android_content_pm_PackageInfo_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        InjectorLike applicationInjector = injectorLike.getApplicationInjector();
                        _UL__ULSEP_android_content_pm_PackageInfo_ULSEP_INSTANCE = providePackageInfo(_UL__ULSEP_android_content_pm_PackageManager_ULSEP_ACCESS_METHOD(applicationInjector), BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(applicationInjector));
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_android_content_pm_PackageInfo_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final PackageManager _UL__ULSEP_android_content_pm_PackageManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (PackageManager) UL.factorymap.get(UL_id._UL__ULSEP_android_content_pm_PackageManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final PackageManager _UL__ULSEP_android_content_pm_PackageManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_android_content_pm_PackageManager_ULSEP_INSTANCE == null) {
            synchronized (_UL__ULSEP_android_content_pm_PackageManager_ULSEP_LOCK) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_android_content_pm_PackageManager_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        _UL__ULSEP_android_content_pm_PackageManager_ULSEP_INSTANCE = providePackageManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike.getApplicationInjector()));
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_android_content_pm_PackageManager_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final SensorManager _UL__ULSEP_android_hardware_SensorManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (SensorManager) UL.factorymap.get(UL_id._UL__ULSEP_android_hardware_SensorManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final SensorManager _UL__ULSEP_android_hardware_SensorManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideSensorManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final Geocoder _UL__ULSEP_android_location_Geocoder_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (Geocoder) UL.factorymap.get(UL_id._UL__ULSEP_android_location_Geocoder_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final Geocoder _UL__ULSEP_android_location_Geocoder_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_android_location_Geocoder_ULSEP_INSTANCE == null) {
            synchronized (_UL__ULSEP_android_location_Geocoder_ULSEP_LOCK) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_android_location_Geocoder_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        _UL__ULSEP_android_location_Geocoder_ULSEP_INSTANCE = provideGeocoder(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike.getApplicationInjector()));
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_android_location_Geocoder_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final LocationManager _UL__ULSEP_android_location_LocationManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (LocationManager) UL.factorymap.get(UL_id._UL__ULSEP_android_location_LocationManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final LocationManager _UL__ULSEP_android_location_LocationManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideLocationManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final AudioManager _UL__ULSEP_android_media_AudioManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (AudioManager) UL.factorymap.get(UL_id._UL__ULSEP_android_media_AudioManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final AudioManager _UL__ULSEP_android_media_AudioManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideAudioManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final MediaPlayer _UL__ULSEP_android_media_MediaPlayer_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (MediaPlayer) UL.factorymap.get(UL_id._UL__ULSEP_android_media_MediaPlayer_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final MediaPlayer _UL__ULSEP_android_media_MediaPlayer_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideMediaPlayer();
    }

    @AutoGeneratedAccessMethod
    public static final MediaRecorder _UL__ULSEP_android_media_MediaRecorder_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (MediaRecorder) UL.factorymap.get(UL_id._UL__ULSEP_android_media_MediaRecorder_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final MediaRecorder _UL__ULSEP_android_media_MediaRecorder_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideMediaRecorder();
    }

    @AutoGeneratedAccessMethod
    public static final ConnectivityManager _UL__ULSEP_android_net_ConnectivityManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (ConnectivityManager) UL.factorymap.get(UL_id._UL__ULSEP_android_net_ConnectivityManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final ConnectivityManager _UL__ULSEP_android_net_ConnectivityManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideConnectivityManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final NetworkInfo _UL__ULSEP_android_net_NetworkInfo_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (NetworkInfo) UL.factorymap.get(UL_id._UL__ULSEP_android_net_NetworkInfo_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final NetworkInfo _UL__ULSEP_android_net_NetworkInfo_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideActiveNetworkInfo(_UL__ULSEP_android_net_ConnectivityManager_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final WifiManager _UL__ULSEP_android_net_wifi_WifiManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (WifiManager) UL.factorymap.get(UL_id._UL__ULSEP_android_net_wifi_WifiManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final WifiManager _UL__ULSEP_android_net_wifi_WifiManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideWifiManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final Handler _UL__ULSEP_android_os_Handler_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (Handler) UL.factorymap.get(UL_id._UL__ULSEP_android_os_Handler_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final Handler _UL__ULSEP_android_os_Handler_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideHandler();
    }

    @AutoGeneratedAccessMethod
    public static final PowerManager _UL__ULSEP_android_os_PowerManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (PowerManager) UL.factorymap.get(UL_id._UL__ULSEP_android_os_PowerManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final PowerManager _UL__ULSEP_android_os_PowerManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return providePowerManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final Vibrator _UL__ULSEP_android_os_Vibrator_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (Vibrator) UL.factorymap.get(UL_id._UL__ULSEP_android_os_Vibrator_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final Vibrator _UL__ULSEP_android_os_Vibrator_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideVibrator(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final RenderScript _UL__ULSEP_android_renderscript_RenderScript_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (RenderScript) UL.factorymap.get(UL_id._UL__ULSEP_android_renderscript_RenderScript_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final RenderScript _UL__ULSEP_android_renderscript_RenderScript_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_android_renderscript_RenderScript_ULSEP_INSTANCE == null) {
            synchronized (_UL__ULSEP_android_renderscript_RenderScript_ULSEP_LOCK) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_android_renderscript_RenderScript_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        _UL__ULSEP_android_renderscript_RenderScript_ULSEP_INSTANCE = provideRenderScript(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike.getApplicationInjector()));
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_android_renderscript_RenderScript_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final TelephonyManager _UL__ULSEP_android_telephony_TelephonyManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (TelephonyManager) UL.factorymap.get(UL_id._UL__ULSEP_android_telephony_TelephonyManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final TelephonyManager _UL__ULSEP_android_telephony_TelephonyManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideTelephonyManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final LayoutInflater _UL__ULSEP_android_view_LayoutInflater_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (LayoutInflater) UL.factorymap.get(UL_id._UL__ULSEP_android_view_LayoutInflater_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final LayoutInflater _UL__ULSEP_android_view_LayoutInflater_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideLayoutInflater(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final WindowManager _UL__ULSEP_android_view_WindowManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (WindowManager) UL.factorymap.get(UL_id._UL__ULSEP_android_view_WindowManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final WindowManager _UL__ULSEP_android_view_WindowManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideWindowManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final AccessibilityManager _UL__ULSEP_android_view_accessibility_AccessibilityManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (AccessibilityManager) UL.factorymap.get(UL_id._UL__ULSEP_android_view_accessibility_AccessibilityManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final AccessibilityManager _UL__ULSEP_android_view_accessibility_AccessibilityManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideAccessibilityManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final InputMethodManager _UL__ULSEP_android_view_inputmethod_InputMethodManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (InputMethodManager) UL.factorymap.get(UL_id._UL__ULSEP_android_view_inputmethod_InputMethodManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final InputMethodManager _UL__ULSEP_android_view_inputmethod_InputMethodManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideInputMethodManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final FragmentActivity _UL__ULSEP_androidx_fragment_app_FragmentActivity_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (FragmentActivity) UL.factorymap.get(UL_id._UL__ULSEP_androidx_fragment_app_FragmentActivity_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final FragmentActivity _UL__ULSEP_androidx_fragment_app_FragmentActivity_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideFragmentActivity(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final LocalBroadcastManager _UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (LocalBroadcastManager) UL.factorymap.get(UL_id._UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final LocalBroadcastManager _UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_INSTANCE == null) {
            synchronized (_UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_LOCK) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        _UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_INSTANCE = provideLocalBroadcastManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike.getApplicationInjector()));
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final FbLocalBroadcastManager _UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (FbLocalBroadcastManager) UL.factorymap.get(UL_id._UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final FbLocalBroadcastManager _UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_INSTANCE == null) {
            synchronized (FbLocalBroadcastManager.class) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        _UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_INSTANCE = provideFbLocalBroadcastManager(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike.getApplicationInjector()));
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_accounts_AccountManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_accounts_AccountManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_app_ActivityManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_app_ActivityManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_app_Activity_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_app_Activity_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_app_AlarmManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_app_AlarmManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_app_DownloadManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_app_DownloadManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_app_KeyguardManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_app_KeyguardManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_app_NotificationManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_app_NotificationManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_app_SearchManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_app_SearchManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_app_Service_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_app_Service_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_app_admin_DevicePolicyManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_app_admin_DevicePolicyManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_content_ClipboardManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_content_ClipboardManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_content_ContentResolver_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_content_ContentResolver_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_content_pm_ApplicationInfo_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_content_pm_ApplicationInfo_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_content_pm_PackageInfo_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_content_pm_PackageInfo_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_content_pm_PackageManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_content_pm_PackageManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_hardware_SensorManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_hardware_SensorManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_location_Geocoder_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightSingletonProvider.get(UL_id._UL__ULSEP_android_location_Geocoder_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_location_LocationManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_location_LocationManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_media_AudioManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_media_AudioManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_media_MediaPlayer_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_media_MediaPlayer_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_media_MediaRecorder_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_media_MediaRecorder_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_net_ConnectivityManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_net_ConnectivityManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_net_NetworkInfo_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_net_NetworkInfo_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_net_wifi_WifiManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_net_wifi_WifiManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_os_Handler_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_os_Handler_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_os_PowerManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_os_PowerManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_os_Vibrator_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_os_Vibrator_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_renderscript_RenderScript_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightSingletonProvider.get(UL_id._UL__ULSEP_android_renderscript_RenderScript_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_telephony_TelephonyManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_telephony_TelephonyManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_view_LayoutInflater_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_view_LayoutInflater_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_view_WindowManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_view_WindowManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_view_accessibility_AccessibilityManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_view_accessibility_AccessibilityManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_android_view_inputmethod_InputMethodManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_android_view_inputmethod_InputMethodManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_androidx_fragment_app_FragmentActivity_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_androidx_fragment_app_FragmentActivity_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_facebook_common_android_FbLocalBroadcastManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightSingletonProvider.get(UL_id._UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_facebook_support_v4_net_ConnectivityManagerCompat_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightSingletonProvider.get(UL_id._UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_java_lang_Integer_ULGT__ULSEP_com_facebook_common_android_AndroidSdkVersion_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_java_lang_Integer_ULSEP_com_facebook_common_android_AndroidSdkVersion_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_java_lang_Object_ULGT__ULSEP_com_facebook_common_android_WifiP2pManagerSystemService_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_java_lang_Object_ULSEP_com_facebook_common_android_WifiP2pManagerSystemService_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_java_lang_Runtime_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(UL_id._UL__ULSEP_java_lang_Runtime_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_java_lang_String_ULGT__ULSEP_com_facebook_common_android_PackageName_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightSingletonProvider.get(UL_id._UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final ConnectivityManagerCompat _UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (ConnectivityManagerCompat) UL.factorymap.get(UL_id._UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final ConnectivityManagerCompat _UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_INSTANCE == null) {
            synchronized (ConnectivityManagerCompat.class) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        injectorLike.getApplicationInjector();
                        _UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_INSTANCE = provideConnectivityManagerCompat();
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final Integer _UL__ULSEP_java_lang_Integer_ULSEP_com_facebook_common_android_AndroidSdkVersion_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (Integer) UL.factorymap.get(UL_id._UL__ULSEP_java_lang_Integer_ULSEP_com_facebook_common_android_AndroidSdkVersion_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final Integer _UL__ULSEP_java_lang_Integer_ULSEP_com_facebook_common_android_AndroidSdkVersion_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideAndroidSdkVersion();
    }

    @AutoGeneratedAccessMethod
    public static final Object _UL__ULSEP_java_lang_Object_ULSEP_com_facebook_common_android_WifiP2pManagerSystemService_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UL.factorymap.get(UL_id._UL__ULSEP_java_lang_Object_ULSEP_com_facebook_common_android_WifiP2pManagerSystemService_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final Object _UL__ULSEP_java_lang_Object_ULSEP_com_facebook_common_android_WifiP2pManagerSystemService_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideWifiP2pManagerSystemService(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final Runtime _UL__ULSEP_java_lang_Runtime_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (Runtime) UL.factorymap.get(UL_id._UL__ULSEP_java_lang_Runtime_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final Runtime _UL__ULSEP_java_lang_Runtime_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideRuntime();
    }

    @AutoGeneratedAccessMethod
    public static final String _UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (String) UL.factorymap.get(UL_id._UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final String _UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        if (_UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_INSTANCE == null) {
            synchronized (_UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_LOCK) {
                ApplicationScopeClassInit start = ApplicationScopeClassInit.start(_UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_INSTANCE, injectorLike);
                if (start != null) {
                    try {
                        _UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_INSTANCE = providePackageName(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_UnsafeContextInjection_ULSEP_ACCESS_METHOD(injectorLike.getApplicationInjector()));
                    } finally {
                        start.finish();
                    }
                }
            }
        }
        return _UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_accounts_AccountManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_accounts_AccountManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_app_ActivityManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_app_ActivityManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_app_Activity_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_app_Activity_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_app_AlarmManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_app_AlarmManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_app_DownloadManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_app_DownloadManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_app_KeyguardManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_app_KeyguardManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_app_NotificationManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_app_NotificationManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_app_SearchManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_app_SearchManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_app_Service_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_app_Service_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_app_admin_DevicePolicyManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_app_admin_DevicePolicyManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_content_ClipboardManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_content_ClipboardManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_content_ContentResolver_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_content_ContentResolver_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_content_pm_ApplicationInfo_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_content_pm_ApplicationInfo_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_content_pm_PackageInfo_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_content_pm_PackageInfo_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_content_pm_PackageManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_content_pm_PackageManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_hardware_SensorManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_hardware_SensorManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_location_Geocoder_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightSingletonProvider.get(UL_id._UL__ULSEP_android_location_Geocoder_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_location_LocationManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_location_LocationManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_media_AudioManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_media_AudioManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_media_MediaPlayer_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_media_MediaPlayer_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_media_MediaRecorder_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_media_MediaRecorder_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_net_ConnectivityManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_net_ConnectivityManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_net_NetworkInfo_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_net_NetworkInfo_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_net_wifi_WifiManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_net_wifi_WifiManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_os_Handler_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_os_Handler_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_os_PowerManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_os_PowerManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_os_Vibrator_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_os_Vibrator_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_renderscript_RenderScript_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightSingletonProvider.get(UL_id._UL__ULSEP_android_renderscript_RenderScript_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_telephony_TelephonyManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_telephony_TelephonyManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_view_LayoutInflater_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_view_LayoutInflater_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_view_WindowManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_view_WindowManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_view_accessibility_AccessibilityManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_view_accessibility_AccessibilityManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_android_view_inputmethod_InputMethodManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_android_view_inputmethod_InputMethodManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_androidx_fragment_app_FragmentActivity_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_androidx_fragment_app_FragmentActivity_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_androidx_localbroadcastmanager_content_LocalBroadcastManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_facebook_common_android_FbLocalBroadcastManager_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightSingletonProvider.get(UL_id._UL__ULSEP_com_facebook_common_android_FbLocalBroadcastManager_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_facebook_support_v4_net_ConnectivityManagerCompat_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightSingletonProvider.get(UL_id._UL__ULSEP_com_facebook_support_v4_net_ConnectivityManagerCompat_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_java_lang_Integer_ULGT__ULSEP_com_facebook_common_android_AndroidSdkVersion_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_java_lang_Integer_ULSEP_com_facebook_common_android_AndroidSdkVersion_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_java_lang_Object_ULGT__ULSEP_com_facebook_common_android_WifiP2pManagerSystemService_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_java_lang_Object_ULSEP_com_facebook_common_android_WifiP2pManagerSystemService_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_java_lang_Runtime_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(UL_id._UL__ULSEP_java_lang_Runtime_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_java_lang_String_ULGT__ULSEP_com_facebook_common_android_PackageName_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightSingletonProvider.get(UL_id._UL__ULSEP_java_lang_String_ULSEP_com_facebook_common_android_PackageName_ULSEP_BINDING_ID, injectorLike);
    }

    @ProviderMethod(asDefault = true)
    static LocationManager provideLocationManager(@UnsafeContextInjection Context context) {
        return (LocationManager) context.getSystemService(LoggingKeys.NOTIFICATION_PREFERENCE_CHANGE_LOCATION);
    }

    @ProviderMethod(asDefault = true)
    static WindowManager provideWindowManager(@UnsafeContextInjection Context context) {
        return (WindowManager) context.getSystemService("window");
    }

    @ProviderMethod(asDefault = true)
    static LayoutInflater provideLayoutInflater(@UnsafeContextInjection Context context) {
        return (LayoutInflater) context.getSystemService("layout_inflater");
    }

    @ProviderMethod(asDefault = true)
    static ActivityManager provideActivityManager(@UnsafeContextInjection Context context) {
        return (ActivityManager) context.getSystemService("activity");
    }

    @ProviderMethod(asDefault = true)
    static PowerManager providePowerManager(@UnsafeContextInjection Context context) {
        return (PowerManager) context.getSystemService("power");
    }

    @ProviderMethod(asDefault = true)
    static DevicePolicyManager provideDevicePolicyManager(@UnsafeContextInjection Context context) {
        return (DevicePolicyManager) context.getSystemService("device_policy");
    }

    @ProviderMethod(asDefault = true)
    static AlarmManager provideAlarmManager(@UnsafeContextInjection Context context) {
        return (AlarmManager) context.getSystemService(NotificationCompat.CATEGORY_ALARM);
    }

    @ProviderMethod(asDefault = true)
    static NotificationManager provideNotificationManager(@UnsafeContextInjection Context context) {
        return (NotificationManager) context.getSystemService("notification");
    }

    @ProviderMethod(asDefault = true)
    static KeyguardManager provideKeyguardManager(@UnsafeContextInjection Context context) {
        return (KeyguardManager) context.getSystemService("keyguard");
    }

    @ProviderMethod(asDefault = true)
    static SearchManager provideSearchManager(@UnsafeContextInjection Context context) {
        return (SearchManager) context.getSystemService("search");
    }

    @ProviderMethod(asDefault = true)
    static Vibrator provideVibrator(@UnsafeContextInjection Context context) {
        return (Vibrator) context.getSystemService("vibrator");
    }

    @ProviderMethod(asDefault = true)
    @Nullable
    static ConnectivityManager provideConnectivityManager(@UnsafeContextInjection Context context) {
        try {
            return (ConnectivityManager) context.getSystemService("connectivity");
        } catch (Exception unused) {
            return null;
        }
    }

    @ProviderMethod(asDefault = true)
    @Nullable
    static NetworkInfo provideActiveNetworkInfo(@Nullable ConnectivityManager connectivityManager) {
        if (connectivityManager == null) {
            return null;
        }
        try {
            return connectivityManager.getActiveNetworkInfo();
        } catch (Exception unused) {
            return null;
        }
    }

    @ProviderMethod(asDefault = true)
    static WifiManager provideWifiManager(@UnsafeContextInjection Context context) {
        return (WifiManager) context.getApplicationContext().getSystemService("wifi");
    }

    @ProviderMethod(asDefault = true)
    static InputMethodManager provideInputMethodManager(@UnsafeContextInjection Context context) {
        return (InputMethodManager) context.getSystemService("input_method");
    }

    @ProviderMethod(asDefault = true)
    static SensorManager provideSensorManager(@UnsafeContextInjection Context context) {
        return (SensorManager) context.getSystemService("sensor");
    }

    @ProviderMethod
    static ClipboardManager provideClipboardManager(@UnsafeContextInjection Context context) {
        return (ClipboardManager) context.getSystemService("clipboard");
    }

    @ProviderMethod(asDefault = true)
    static TelephonyManager provideTelephonyManager(@UnsafeContextInjection Context context) {
        return (TelephonyManager) context.getSystemService("phone");
    }

    @ProviderMethod(asDefault = true)
    static AudioManager provideAudioManager(@UnsafeContextInjection Context context) {
        return (AudioManager) context.getSystemService("audio");
    }

    @ProviderMethod(asDefault = true)
    static AccountManager provideAccountManager(@UnsafeContextInjection Context context) {
        return (AccountManager) context.getSystemService("account");
    }

    @ProviderMethod(asDefault = true)
    static AccessibilityManager provideAccessibilityManager(@UnsafeContextInjection Context context) {
        return (AccessibilityManager) context.getSystemService("accessibility");
    }

    @ProviderMethod(asDefault = true)
    static DownloadManager provideDownloadManager(@UnsafeContextInjection Context context) {
        return (DownloadManager) context.getSystemService("download");
    }

    @WifiP2pManagerSystemService
    @ProviderMethod
    static Object provideWifiP2pManagerSystemService(@UnsafeContextInjection Context context) {
        return context.getSystemService("wifip2p");
    }

    @ApplicationScoped(enableScopeValidation = false)
    @ProviderMethod(asDefault = true)
    static PackageManager providePackageManager(@UnsafeContextInjection Context context) {
        return context.getApplicationContext().getPackageManager();
    }

    @ApplicationScoped(enableScopeValidation = false)
    @ProviderMethod(asDefault = true)
    static PackageInfo providePackageInfo(PackageManager packageManager, @UnsafeContextInjection Context context) {
        try {
            PackageInfo packageInfo = packageManager.getPackageInfo(context.getPackageName(), 0);
            int aPKVersionCode = BuildConstants.getAPKVersionCode();
            if (packageInfo.versionCode != aPKVersionCode) {
                BLog.wtf("AndroidModule", String.format(Locale.US, "Android PackageManager returned version code: %d, apk version code is: %d", Integer.valueOf(packageInfo.versionCode), Integer.valueOf(aPKVersionCode)));
            }
            return packageInfo;
        } catch (PackageManager.NameNotFoundException e) {
            throw new RuntimeException(e);
        }
    }

    @ApplicationScoped(enableScopeValidation = false)
    @ProviderMethod(asDefault = true)
    static LocalBroadcastManager provideLocalBroadcastManager(@UnsafeContextInjection Context context) {
        return LocalBroadcastManager.getInstance(context.getApplicationContext());
    }

    @ProviderMethod(asDefault = true)
    static ContentResolver provideContentResolver(@UnsafeContextInjection Context context) {
        return context.getContentResolver();
    }

    @ApplicationScoped(enableScopeValidation = false)
    @ProviderMethod
    static Geocoder provideGeocoder(@UnsafeContextInjection Context context) {
        return new Geocoder(context.getApplicationContext());
    }

    @ProviderMethod
    static MediaRecorder provideMediaRecorder() {
        return new MediaRecorder();
    }

    @ProviderMethod
    static MediaPlayer provideMediaPlayer() {
        return new MediaPlayer();
    }

    @ApplicationScoped(enableScopeValidation = false)
    @ProviderMethod
    static ConnectivityManagerCompat provideConnectivityManagerCompat() {
        return new ConnectivityManagerCompat();
    }

    @ProviderMethod(asDefault = true)
    static Activity provideActivity(@UnsafeContextInjection Context context) {
        return (Activity) ContextUtils.findContextOfType(context, Activity.class);
    }

    @ProviderMethod
    static FragmentActivity provideFragmentActivity(@UnsafeContextInjection Context context) {
        return (FragmentActivity) ContextUtils.findContextOfType(context, FragmentActivity.class);
    }

    @ProviderMethod
    @Nullable
    static Service provideService(@UnsafeContextInjection Context context) {
        if (context instanceof Service) {
            return (Service) context;
        }
        return null;
    }

    @PackageName
    @ApplicationScoped
    @ProviderMethod
    static String providePackageName(@UnsafeContextInjection Context context) {
        return context.getPackageName();
    }

    @ProviderMethod(asDefault = true)
    static ApplicationInfo provideApplicationInfo(@UnsafeContextInjection Context context) {
        return context.getApplicationInfo();
    }

    @ProviderMethod(asDefault = true)
    static Runtime provideRuntime() {
        return Runtime.getRuntime();
    }

    @ProviderMethod
    @AndroidSdkVersion
    static Integer provideAndroidSdkVersion() {
        return Integer.valueOf(Build.VERSION.SDK_INT);
    }

    @ApplicationScoped(enableScopeValidation = false)
    @ProviderMethod
    static FbLocalBroadcastManager provideFbLocalBroadcastManager(@UnsafeContextInjection Context context) {
        return FbLocalBroadcastManager.getInstance(context);
    }

    @ProviderMethod
    static Handler provideHandler() {
        return new Handler();
    }

    @ApplicationScoped(enableScopeValidation = false)
    @ProviderMethod
    static RenderScript provideRenderScript(@UnsafeContextInjection Context context) {
        return RenderScript.create(context.getApplicationContext());
    }
}
