package X;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

public final class hA {
    public static final hh<AtomicBoolean> A00;
    public static final hh<AtomicInteger> A01;
    public static final hh<AtomicIntegerArray> A02;
    public static final hh<BigDecimal> A03 = new L5();
    public static final hh<BigInteger> A04 = new L4();
    public static final hh<BitSet> A05;
    public static final hh<Boolean> A06;
    public static final hh<Boolean> A07 = new KR();
    public static final hh<Number> A08;
    public static final hh<Calendar> A09;
    public static final hh<Character> A0A;
    public static final hh<Class> A0B;
    public static final hh<Currency> A0C;
    public static final hh<Number> A0D = new L9();
    public static final hh<Number> A0E = new LA();
    public static final hh<InetAddress> A0F;
    public static final hh<Number> A0G;
    public static final hh<AbstractC0241hm> A0H;
    public static final hh<Locale> A0I;
    public static final hh<Number> A0J = new LB();
    public static final hh<Number> A0K;
    public static final hh<Number> A0L;
    public static final hh<String> A0M;
    public static final hh<StringBuffer> A0N;
    public static final hh<StringBuilder> A0O;
    public static final hh<URI> A0P;
    public static final hh<URL> A0Q;
    public static final hh<UUID> A0R;
    public static final AbstractC0237hg A0S;
    public static final AbstractC0237hg A0T;
    public static final AbstractC0237hg A0U;
    public static final AbstractC0237hg A0V;
    public static final AbstractC0237hg A0W;
    public static final AbstractC0237hg A0X;
    public static final AbstractC0237hg A0Y;
    public static final AbstractC0237hg A0Z;
    public static final AbstractC0237hg A0a;
    public static final AbstractC0237hg A0b;
    public static final AbstractC0237hg A0c = new C0067Kg();
    public static final AbstractC0237hg A0d;
    public static final AbstractC0237hg A0e;
    public static final AbstractC0237hg A0f;
    public static final AbstractC0237hg A0g;
    public static final AbstractC0237hg A0h;
    public static final AbstractC0237hg A0i;
    public static final AbstractC0237hg A0j;
    public static final AbstractC0237hg A0k;
    public static final AbstractC0237hg A0l;
    public static final AbstractC0237hg A0m = new C0074Ku();
    public static final AbstractC0237hg A0n;
    public static final AbstractC0237hg A0o;
    public static final AbstractC0237hg A0p;

    static {
        C0099Lv lv = new C0099Lv(new L2());
        A0B = lv;
        A0a = new C0064Kd(Class.class, lv);
        C0099Lv lv2 = new C0099Lv(new Kl());
        A05 = lv2;
        A0V = new C0064Kd(BitSet.class, lv2);
        KS ks = new KS();
        A06 = ks;
        A0W = new C0063Kc(Boolean.TYPE, Boolean.class, ks);
        KQ kq = new KQ();
        A08 = kq;
        A0X = new C0063Kc(Byte.TYPE, Byte.class, kq);
        KK kk = new KK();
        A0L = kk;
        A0i = new C0063Kc(Short.TYPE, Short.class, kk);
        KJ kj = new KJ();
        A0G = kj;
        A0e = new C0063Kc(Integer.TYPE, Integer.class, kj);
        C0099Lv lv3 = new C0099Lv(new KI());
        A01 = lv3;
        A0U = new C0064Kd(AtomicInteger.class, lv3);
        C0099Lv lv4 = new C0099Lv(new KH());
        A00 = lv4;
        A0S = new C0064Kd(AtomicBoolean.class, lv4);
        C0099Lv lv5 = new C0099Lv(new LC());
        A02 = lv5;
        A0T = new C0064Kd(AtomicIntegerArray.class, lv5);
        L8 l8 = new L8();
        A0K = l8;
        A0h = new C0064Kd(Number.class, l8);
        L7 l7 = new L7();
        A0A = l7;
        A0Z = new C0063Kc(Character.TYPE, Character.class, l7);
        L6 l6 = new L6();
        A0M = l6;
        A0l = new C0064Kd(String.class, l6);
        L3 l3 = new L3();
        A0O = l3;
        A0k = new C0064Kd(StringBuilder.class, l3);
        L1 l1 = new L1();
        A0N = l1;
        A0j = new C0064Kd(StringBuffer.class, l1);
        L0 l0 = new L0();
        A0Q = l0;
        A0o = new C0064Kd(URL.class, l0);
        C0078Kz kz = new C0078Kz();
        A0P = kz;
        A0n = new C0064Kd(URI.class, kz);
        Ky ky = new Ky();
        A0F = ky;
        A0d = new KZ(InetAddress.class, ky);
        C0077Kx kx = new C0077Kx();
        A0R = kx;
        A0p = new C0064Kd(UUID.class, kx);
        C0099Lv lv6 = new C0099Lv(new C0076Kw());
        A0C = lv6;
        A0b = new C0064Kd(Currency.class, lv6);
        C0073Ko ko = new C0073Ko();
        A09 = ko;
        A0Y = new C0062Kb(ko);
        C0072Kn kn = new C0072Kn();
        A0I = kn;
        A0g = new C0064Kd(Locale.class, kn);
        C0071Km km = new C0071Km();
        A0H = km;
        A0f = new KZ(AbstractC0241hm.class, km);
    }
}
