package com.oculus.ocms.defaultapps;

import android.content.Context;
import android.content.SharedPreferences;
import com.facebook.inject.BundledAndroidModule;
import com.facebook.inject.ForAppContext;
import com.facebook.inject.InjectorLike;
import com.facebook.inject.Lazy;
import com.facebook.inject.UltralightLazy;
import com.facebook.inject.UltralightProvider;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.facebook.ultralight.UL;
import com.oculus.ocms.defaultapps.DefaultAppsModule;
import java.util.Collections;
import java.util.Set;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_ForAppContext_ULSEP_BINDING_ID"})
public class DefaultAppsPrefs {
    private static final String HIGH_PRIORITY_APPS_RESCHEDULE_ATTEMPT = "high_pri_apps_reschedule_attempt";
    private static final String HIGH_PRIORITY_APPS_SETUP_COMPLETE = "high_pri_apps_setup_complete";
    private static final String SETUP_COMPLETED_PACKAGES = "completed_packages";
    private static final String SHARED_PREFS_PACIFIC = "prefs_horizon_pacific";
    private final SharedPreferences mPrefs;

    @AutoGeneratedAccessMethod
    public static final DefaultAppsPrefs _UL__ULSEP_com_oculus_ocms_defaultapps_DefaultAppsPrefs_ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return (DefaultAppsPrefs) UL.factorymap.get(DefaultAppsModule.UL_id._UL__ULSEP_com_oculus_ocms_defaultapps_DefaultAppsPrefs_ULSEP_BINDING_ID, injectorLike);
    }

    @AutoGeneratedFactoryMethod
    public static final DefaultAppsPrefs _UL__ULSEP_com_oculus_ocms_defaultapps_DefaultAppsPrefs_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return new DefaultAppsPrefs(BundledAndroidModule._UL__ULSEP_android_content_Context_ULSEP_com_facebook_inject_ForAppContext_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_ocms_defaultapps_DefaultAppsPrefs_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightProvider.get(DefaultAppsModule.UL_id._UL__ULSEP_com_oculus_ocms_defaultapps_DefaultAppsPrefs_ULSEP_BINDING_ID, injectorLike);
    }

    @Inject
    public DefaultAppsPrefs(@ForAppContext Context context) {
        this.mPrefs = context.getSharedPreferences(SHARED_PREFS_PACIFIC, 0);
    }

    @AutoGeneratedAccessMethod
    public static final Lazy _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_ocms_defaultapps_DefaultAppsPrefs_ULGT__ULSEP_ACCESS_METHOD(InjectorLike injectorLike) {
        return UltralightLazy.get(DefaultAppsModule.UL_id._UL__ULSEP_com_oculus_ocms_defaultapps_DefaultAppsPrefs_ULSEP_BINDING_ID, injectorLike);
    }

    public boolean isHighPriAppsSetupComplete() {
        return this.mPrefs.getBoolean(HIGH_PRIORITY_APPS_SETUP_COMPLETE, false);
    }

    public void setHighPriAppsSetupComplete(boolean z) {
        this.mPrefs.edit().putBoolean(HIGH_PRIORITY_APPS_SETUP_COMPLETE, z).apply();
    }

    public int getHighPriAppsRescheduleAttempts() {
        return this.mPrefs.getInt(HIGH_PRIORITY_APPS_RESCHEDULE_ATTEMPT, 0);
    }

    public void setHighPriAppsRescheduleAttempts(int i) {
        this.mPrefs.edit().putInt(HIGH_PRIORITY_APPS_RESCHEDULE_ATTEMPT, i).apply();
    }

    public Set<String> getCompletedSetupInstalls() {
        return this.mPrefs.getStringSet(SETUP_COMPLETED_PACKAGES, Collections.EMPTY_SET);
    }

    public void setCompletedSetupInstalls(Set<String> set) {
        this.mPrefs.edit().putStringSet(SETUP_COMPLETED_PACKAGES, set).apply();
    }
}
