package com.oculus.multiuser;

import com.facebook.inject.AbstractLibraryModule;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.Binder;
import com.facebook.inject.BundledAndroidModule;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import com.facebook.ultralight.UL;
import com.google.inject.Key;
import com.oculus.android.os.internal.inject.InternalModule;

@InjectorModule
public class MultiuserModule extends AbstractLibraryModule {

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_multiuser_UserClassifier_ULSEP_BINDING_ID = (UL.USE_STATIC_DI ? UL.id._UL__ULSEP_com_oculus_multiuser_UserClassifier_ULSEP_BINDING_ID : UL.id.dynamicId(Key.get(UserClassifier.class)));
    }

    @AutoGeneratedBinder
    static class AutoGeneratedBindingsForMultiuserModule {
        AutoGeneratedBindingsForMultiuserModule() {
        }

        static void bind(Binder binder) {
            if (!UL.USE_STATIC_DI) {
                binder.require(BundledAndroidModule.class);
                binder.require(InternalModule.class);
                binder.bind(UserClassifier.class).toProvider(new UserClassifierAutoProvider());
            }
        }
    }
}
