package com.oculus.alpenglow.induction;

import X.AbstractC01750Lk;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public abstract class InductionModule extends AbstractC01750Lk {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForInductionModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_alpenglow_induction_InductionBootListener_ULSEP_BINDING_ID = 117;
        public static final int _UL__ULSEP_com_oculus_alpenglow_induction_Induction_ULSEP_BINDING_ID = 129;
        public static final int _UL__ULSEP_com_oculus_alpenglow_induction_WifiProvisioning_ULSEP_BINDING_ID = 87;
    }
}
