package com.oculus.oktigon;

import com.facebook.http.annotations.UserAgentString;
import com.facebook.inject.AbstractLibraryModule;
import com.facebook.inject.InjectorLike;
import com.facebook.inject.InjectorModule;
import com.facebook.inject.ProviderMethod;
import com.facebook.tigon.oktigon.OkTigonClient;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.oculus.http.defaultclient.DefaultClientModule;
import com.oculus.http.defaultclient.DefaultHttpClient;
import com.oculus.http.useragent.UserAgentModule;
import okhttp3.OkHttpClient;

@InjectorModule
public class OculusOkTigonModule extends AbstractLibraryModule {
    @OkTigonClient
    @ProviderMethod
    static OkHttpClient getOkHttpClient(@DefaultHttpClient OkHttpClient okHttpClient) {
        return okHttpClient;
    }

    @UserAgentString
    @ProviderMethod
    static String provideUserAgentString(@com.oculus.http.useragent.UserAgentString String str) {
        return str;
    }

    @AutoGeneratedFactoryMethod
    public static final String _UL__ULSEP_java_lang_String_ULSEP_com_facebook_http_annotations_UserAgentString_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return provideUserAgentString(UserAgentModule._UL__ULSEP_java_lang_String_ULSEP_com_oculus_http_useragent_UserAgentString_ULSEP_ACCESS_METHOD(injectorLike));
    }

    @AutoGeneratedFactoryMethod
    public static final OkHttpClient _UL__ULSEP_okhttp3_OkHttpClient_ULSEP_com_facebook_tigon_oktigon_OkTigonClient_ULSEP_FACTORY_METHOD(InjectorLike injectorLike) {
        return getOkHttpClient(DefaultClientModule._UL__ULSEP_okhttp3_OkHttpClient_ULSEP_com_oculus_http_defaultclient_DefaultHttpClient_ULSEP_ACCESS_METHOD(injectorLike));
    }
}
