package com.oculus.util.task;

import X.AbstractC0247Xu;
import X.C0515sp;
import X.D3;
import X.DB;
import X.DC;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;

@Dependencies({})
public class TaskDelayFactory {

    /* renamed from: com.oculus.util.task.TaskDelayFactory$1  reason: invalid class name */
    public class AnonymousClass1 implements D3<DB<Void>, DB<Void>> {
        public final /* synthetic */ TaskDelayFactory this$0;
        public final /* synthetic */ DC val$completionSource;
    }

    @AutoGeneratedFactoryMethod
    public static final TaskDelayFactory A00() {
        return new TaskDelayFactory();
    }

    @AutoGeneratedAccessMethod
    public static final TaskDelayFactory A01(AbstractC0247Xu xu) {
        return (TaskDelayFactory) C0515sp.A00(10, xu);
    }
}
