package android.app.settings;

import com.google.protobuf.Internal;

public enum Action implements Internal.EnumLite {
    ACTION_UNKNOWN(0),
    PAGE_VISIBLE(1),
    PAGE_HIDE(2),
    ACTION_WIFI_CONNECT(135),
    ACTION_WIFI_FORGET(137),
    ACTION_WIFI_OFF(138),
    ACTION_WIFI_ON(139),
    ACTION_BLUETOOTH_RENAME(161),
    ACTION_BLUETOOTH_FILES(162),
    ACTION_ZEN_ALLOW_REMINDERS(167),
    ACTION_ZEN_ALLOW_EVENTS(168),
    ACTION_ZEN_ALLOW_MESSAGES(169),
    ACTION_ZEN_ALLOW_CALLS(170),
    ACTION_ZEN_ALLOW_REPEAT_CALLS(171),
    ACTION_ZEN_DELETE_RULE_OK(175),
    ACTION_AIRPLANE_TOGGLE(177),
    ACTION_CELL_DATA_TOGGLE(178),
    ACTION_ROTATION_LOCK(203),
    ACTION_SEARCH_RESULTS(ACTION_SEARCH_RESULTS_VALUE),
    ACTION_FINGERPRINT_DELETE(253),
    ACTION_FINGERPRINT_RENAME(254),
    ACTION_BUGREPORT_FROM_SETTINGS_INTERACTIVE(ACTION_BUGREPORT_FROM_SETTINGS_INTERACTIVE_VALUE),
    ACTION_BUGREPORT_FROM_SETTINGS_FULL(ACTION_BUGREPORT_FROM_SETTINGS_FULL_VALUE),
    ACTION_SETTINGS_CONDITION_EXPAND(ACTION_SETTINGS_CONDITION_EXPAND_VALUE),
    ACTION_SETTINGS_CONDITION_CLICK(ACTION_SETTINGS_CONDITION_CLICK_VALUE),
    ACTION_SETTINGS_CONDITION_BUTTON(ACTION_SETTINGS_CONDITION_BUTTON_VALUE),
    ACTION_DATA_SAVER_MODE(ACTION_DATA_SAVER_MODE_VALUE),
    ACTION_DATA_SAVER_WHITELIST(ACTION_DATA_SAVER_WHITELIST_VALUE),
    ACTION_DATA_SAVER_BLACKLIST(ACTION_DATA_SAVER_BLACKLIST_VALUE),
    ACTION_TOGGLE_STORAGE_MANAGER(ACTION_TOGGLE_STORAGE_MANAGER_VALUE),
    ACTION_AMBIENT_DISPLAY(ACTION_AMBIENT_DISPLAY_VALUE),
    APP_SPECIAL_PERMISSION_BATTERY_ALLOW(APP_SPECIAL_PERMISSION_BATTERY_ALLOW_VALUE),
    APP_SPECIAL_PERMISSION_BATTERY_DENY(APP_SPECIAL_PERMISSION_BATTERY_DENY_VALUE),
    APP_SPECIAL_PERMISSION_ADMIN_ALLOW(APP_SPECIAL_PERMISSION_ADMIN_ALLOW_VALUE),
    APP_SPECIAL_PERMISSION_ADMIN_DENY(APP_SPECIAL_PERMISSION_ADMIN_DENY_VALUE),
    APP_SPECIAL_PERMISSION_DND_ALLOW(APP_SPECIAL_PERMISSION_DND_ALLOW_VALUE),
    APP_SPECIAL_PERMISSION_DND_DENY(APP_SPECIAL_PERMISSION_DND_DENY_VALUE),
    APP_SPECIAL_PERMISSION_APPDRAW_ALLOW(APP_SPECIAL_PERMISSION_APPDRAW_ALLOW_VALUE),
    APP_SPECIAL_PERMISSION_APPDRAW_DENY(APP_SPECIAL_PERMISSION_APPDRAW_DENY_VALUE),
    APP_SPECIAL_PERMISSION_VRHELPER_ALLOW(APP_SPECIAL_PERMISSION_VRHELPER_ALLOW_VALUE),
    APP_SPECIAL_PERMISSION_VRHELPER_DENY(APP_SPECIAL_PERMISSION_VRHELPER_DENY_VALUE),
    APP_SPECIAL_PERMISSION_SETTINGS_CHANGE_ALLOW(APP_SPECIAL_PERMISSION_SETTINGS_CHANGE_ALLOW_VALUE),
    APP_SPECIAL_PERMISSION_SETTINGS_CHANGE_DENY(APP_SPECIAL_PERMISSION_SETTINGS_CHANGE_DENY_VALUE),
    APP_SPECIAL_PERMISSION_NOTIVIEW_ALLOW(APP_SPECIAL_PERMISSION_NOTIVIEW_ALLOW_VALUE),
    APP_SPECIAL_PERMISSION_NOTIVIEW_DENY(APP_SPECIAL_PERMISSION_NOTIVIEW_DENY_VALUE),
    APP_SPECIAL_PERMISSION_PREMIUM_SMS_ASK(APP_SPECIAL_PERMISSION_PREMIUM_SMS_ASK_VALUE),
    APP_SPECIAL_PERMISSION_PREMIUM_SMS_DENY(APP_SPECIAL_PERMISSION_PREMIUM_SMS_DENY_VALUE),
    APP_SPECIAL_PERMISSION_PREMIUM_SMS_ALWAYS_ALLOW(APP_SPECIAL_PERMISSION_PREMIUM_SMS_ALWAYS_ALLOW_VALUE),
    APP_SPECIAL_PERMISSION_UNL_DATA_ALLOW(APP_SPECIAL_PERMISSION_UNL_DATA_ALLOW_VALUE),
    APP_SPECIAL_PERMISSION_UNL_DATA_DENY(APP_SPECIAL_PERMISSION_UNL_DATA_DENY_VALUE),
    APP_SPECIAL_PERMISSION_USAGE_VIEW_ALLOW(APP_SPECIAL_PERMISSION_USAGE_VIEW_ALLOW_VALUE),
    APP_SPECIAL_PERMISSION_USAGE_VIEW_DENY(APP_SPECIAL_PERMISSION_USAGE_VIEW_DENY_VALUE),
    ACTION_APP_FORCE_STOP(ACTION_APP_FORCE_STOP_VALUE),
    APP_PICTURE_IN_PICTURE_ALLOW(APP_PICTURE_IN_PICTURE_ALLOW_VALUE),
    ACTION_SETTINGS_CREATE_SHORTCUT(ACTION_SETTINGS_CREATE_SHORTCUT_VALUE),
    ACTION_SETTINGS_ADVANCED_BUTTON_EXPAND(ACTION_SETTINGS_ADVANCED_BUTTON_EXPAND_VALUE),
    APP_PICTURE_IN_PICTURE_DENY(APP_PICTURE_IN_PICTURE_DENY_VALUE),
    ACTION_THEME(ACTION_THEME_VALUE),
    ACTION_SETTINGS_BUILD_NUMBER_PREF(ACTION_SETTINGS_BUILD_NUMBER_PREF_VALUE),
    ACTION_SETTINGS_MENU_BATTERY_OPTIMIZATION(ACTION_SETTINGS_MENU_BATTERY_OPTIMIZATION_VALUE),
    ACTION_SETTINGS_MENU_BATTERY_APPS_TOGGLE(ACTION_SETTINGS_MENU_BATTERY_APPS_TOGGLE_VALUE),
    ACTION_SETTINGS_PREFERENCE_CHANGE(ACTION_SETTINGS_PREFERENCE_CHANGE_VALUE),
    ACTION_SETTINGS_BLUETOOTH_PAIR(ACTION_SETTINGS_BLUETOOTH_PAIR_VALUE),
    ACTION_SETTINGS_BLUETOOTH_CONNECT(ACTION_SETTINGS_BLUETOOTH_CONNECT_VALUE),
    ACTION_SETTINGS_BLUETOOTH_DISCONNECT(ACTION_SETTINGS_BLUETOOTH_DISCONNECT_VALUE),
    ACTION_SETTINGS_BLUETOOTH_CONNECT_ERROR(ACTION_SETTINGS_BLUETOOTH_CONNECT_ERROR_VALUE),
    ACTION_SETTINGS_MASTER_SWITCH_BLUETOOTH_TOGGLE(ACTION_SETTINGS_MASTER_SWITCH_BLUETOOTH_TOGGLE_VALUE),
    ACTION_SETTINGS_UNINSTALL_APP(ACTION_SETTINGS_UNINSTALL_APP_VALUE),
    ACTION_SETTINGS_UNINSTALL_DEVICE_ADMIN(ACTION_SETTINGS_UNINSTALL_DEVICE_ADMIN_VALUE),
    ACTION_SETTINGS_DISABLE_APP(ACTION_SETTINGS_DISABLE_APP_VALUE),
    ACTION_SETTINGS_ENABLE_APP(ACTION_SETTINGS_ENABLE_APP_VALUE),
    ACTION_SETTINGS_CLEAR_APP_DATA(ACTION_SETTINGS_CLEAR_APP_DATA_VALUE),
    ACTION_SETTINGS_CLEAR_APP_CACHE(ACTION_SETTINGS_CLEAR_APP_CACHE_VALUE),
    ACTION_SETTINGS_CLEAR_INSTANT_APP(ACTION_SETTINGS_CLEAR_INSTANT_APP_VALUE),
    SETTINGS_ASSIST_GESTURE_TRAINING_INTRO(SETTINGS_ASSIST_GESTURE_TRAINING_INTRO_VALUE),
    SETTINGS_ASSIST_GESTURE_TRAINING_ENROLLING(SETTINGS_ASSIST_GESTURE_TRAINING_ENROLLING_VALUE),
    SETTINGS_ASSIST_GESTURE_TRAINING_FINISHED(SETTINGS_ASSIST_GESTURE_TRAINING_FINISHED_VALUE),
    ACTION_SETTINGS_UPDATE_DEFAULT_APP(1000),
    ACTION_WIFI_SIGNIN(1008),
    ACTION_OPEN_APP_NOTIFICATION_SETTING(1016),
    ACTION_OPEN_APP_SETTING(1017),
    ACTION_PSD_LOADER(1019),
    TRAMPOLINE_SETTINGS_EVENT(1033),
    ACTION_SETTINGS_BLUETOOTH_PAIR_DEVICES_WITHOUT_NAMES(ACTION_SETTINGS_BLUETOOTH_PAIR_DEVICES_WITHOUT_NAMES_VALUE),
    ACTION_MOBILE_NETWORK_MANUAL_SELECT_NETWORK(ACTION_MOBILE_NETWORK_MANUAL_SELECT_NETWORK_VALUE),
    ACTION_ZEN_ALLOW_ALARMS(ACTION_ZEN_ALLOW_ALARMS_VALUE),
    ACTION_ZEN_ALLOW_MEDIA(ACTION_ZEN_ALLOW_MEDIA_VALUE),
    ACTION_PRIVATE_DNS_MODE(ACTION_PRIVATE_DNS_MODE_VALUE),
    ACTION_ZEN_MODE_RULE_NAME_CHANGE_OK(ACTION_ZEN_MODE_RULE_NAME_CHANGE_OK_VALUE),
    ACTION_ZEN_TOGGLE_DND_BUTTON(ACTION_ZEN_TOGGLE_DND_BUTTON_VALUE),
    ACTION_ZEN_BLOCK_FULL_SCREEN_INTENTS(ACTION_ZEN_BLOCK_FULL_SCREEN_INTENTS_VALUE),
    ACTION_ZEN_BLOCK_LIGHT(ACTION_ZEN_BLOCK_LIGHT_VALUE),
    ACTION_ZEN_BLOCK_PEEK(ACTION_ZEN_BLOCK_PEEK_VALUE),
    ACTION_ZEN_BLOCK_STATUS(ACTION_ZEN_BLOCK_STATUS_VALUE),
    ACTION_ZEN_BLOCK_BADGE(ACTION_ZEN_BLOCK_BADGE_VALUE),
    ACTION_ZEN_BLOCK_AMBIENT(ACTION_ZEN_BLOCK_AMBIENT_VALUE),
    ACTION_ZEN_BLOCK_NOTIFICATION_LIST(ACTION_ZEN_BLOCK_NOTIFICATION_LIST_VALUE),
    ACTION_ZEN_ALLOW_SYSTEM(ACTION_ZEN_ALLOW_SYSTEM_VALUE),
    ACTION_APP_RESTRICTION_TIP(ACTION_APP_RESTRICTION_TIP_VALUE),
    ACTION_HIGH_USAGE_TIP(ACTION_HIGH_USAGE_TIP_VALUE),
    ACTION_SUMMARY_TIP(ACTION_SUMMARY_TIP_VALUE),
    ACTION_SMART_BATTERY_TIP(ACTION_SMART_BATTERY_TIP_VALUE),
    ACTION_EARLY_WARNING_TIP(ACTION_EARLY_WARNING_TIP_VALUE),
    ACTION_LOW_BATTERY_TIP(ACTION_LOW_BATTERY_TIP_VALUE),
    ACTION_APP_RESTRICTION_TIP_LIST(ACTION_APP_RESTRICTION_TIP_LIST_VALUE),
    ACTION_HIGH_USAGE_TIP_LIST(ACTION_HIGH_USAGE_TIP_LIST_VALUE),
    ACTION_TIP_OPEN_APP_RESTRICTION_PAGE(ACTION_TIP_OPEN_APP_RESTRICTION_PAGE_VALUE),
    ACTION_TIP_RESTRICT_APP(ACTION_TIP_RESTRICT_APP_VALUE),
    ACTION_TIP_UNRESTRICT_APP(ACTION_TIP_UNRESTRICT_APP_VALUE),
    ACTION_TIP_OPEN_SMART_BATTERY(ACTION_TIP_OPEN_SMART_BATTERY_VALUE),
    ACTION_TIP_TURN_ON_BATTERY_SAVER(ACTION_TIP_TURN_ON_BATTERY_SAVER_VALUE),
    ACTION_ANOMALY_TRIGGERED(ACTION_ANOMALY_TRIGGERED_VALUE),
    ACTION_SETTINGS_SLICE_REQUESTED(ACTION_SETTINGS_SLICE_REQUESTED_VALUE),
    ACTION_SETTINGS_SLICE_CHANGED(ACTION_SETTINGS_SLICE_CHANGED_VALUE),
    ACTION_ZEN_ONBOARDING_OK(ACTION_ZEN_ONBOARDING_OK_VALUE),
    ACTION_ZEN_ONBOARDING_SETTINGS(ACTION_ZEN_ONBOARDING_SETTINGS_VALUE),
    ACTION_ANOMALY_IGNORED(ACTION_ANOMALY_IGNORED_VALUE),
    ACTION_TIP_OPEN_BATTERY_SAVER_PAGE(ACTION_TIP_OPEN_BATTERY_SAVER_PAGE_VALUE),
    ACTION_ZEN_SOUND_ONLY(ACTION_ZEN_SOUND_ONLY_VALUE),
    ACTION_ZEN_SOUND_AND_VIS_EFFECTS(ACTION_ZEN_SOUND_AND_VIS_EFFECTS_VALUE),
    ACTION_ZEN_SHOW_CUSTOM(ACTION_ZEN_SHOW_CUSTOM_VALUE),
    ACTION_ZEN_CUSTOM(ACTION_ZEN_CUSTOM_VALUE),
    ACTION_ZEN_ONBOARDING_KEEP_CURRENT_SETTINGS(ACTION_ZEN_ONBOARDING_KEEP_CURRENT_SETTINGS_VALUE),
    ACTION_STORAGE_INIT_EXTERNAL(ACTION_STORAGE_INIT_EXTERNAL_VALUE),
    ACTION_STORAGE_INIT_INTERNAL(ACTION_STORAGE_INIT_INTERNAL_VALUE),
    ACTION_STORAGE_BENCHMARK_FAST_CONTINUE(ACTION_STORAGE_BENCHMARK_FAST_CONTINUE_VALUE),
    ACTION_STORAGE_BENCHMARK_SLOW_CONTINUE(ACTION_STORAGE_BENCHMARK_SLOW_CONTINUE_VALUE),
    ACTION_STORAGE_BENCHMARK_SLOW_ABORT(ACTION_STORAGE_BENCHMARK_SLOW_ABORT_VALUE),
    ACTION_STORAGE_MIGRATE_NOW(ACTION_STORAGE_MIGRATE_NOW_VALUE),
    ACTION_STORAGE_MIGRATE_LATER(ACTION_STORAGE_MIGRATE_LATER_VALUE),
    DIALOG_SWITCH_A2DP_DEVICES(DIALOG_SWITCH_A2DP_DEVICES_VALUE),
    DIALOG_SWITCH_HFP_DEVICES(DIALOG_SWITCH_HFP_DEVICES_VALUE),
    QS_SENSOR_PRIVACY(QS_SENSOR_PRIVACY_VALUE),
    ACTION_NFC_PAYMENT_FOREGROUND_SETTING(ACTION_NFC_PAYMENT_FOREGROUND_SETTING_VALUE),
    ACTION_NFC_PAYMENT_ALWAYS_SETTING(ACTION_NFC_PAYMENT_ALWAYS_SETTING_VALUE),
    CLICK_ACCOUNT_AVATAR(CLICK_ACCOUNT_AVATAR_VALUE),
    ACTION_SET_NEW_PASSWORD(ACTION_SET_NEW_PASSWORD_VALUE),
    ACTION_SET_NEW_PARENT_PROFILE_PASSWORD(ACTION_SET_NEW_PARENT_PROFILE_PASSWORD_VALUE),
    ACTION_PANEL_INTERACTION(ACTION_PANEL_INTERACTION_VALUE),
    ACTION_CONTEXTUAL_HOME_SHOW(ACTION_CONTEXTUAL_HOME_SHOW_VALUE),
    ACTION_CONTEXTUAL_CARD_SHOW(ACTION_CONTEXTUAL_CARD_SHOW_VALUE),
    ACTION_CONTEXTUAL_CARD_NOT_SHOW(ACTION_CONTEXTUAL_CARD_NOT_SHOW_VALUE),
    ACTION_CONTEXTUAL_CARD_DISMISS(ACTION_CONTEXTUAL_CARD_DISMISS_VALUE),
    ACTION_CONTEXTUAL_CARD_CLICK(ACTION_CONTEXTUAL_CARD_CLICK_VALUE),
    ACTION_ATSG(ACTION_ATSG_VALUE),
    ACTION_ATPG(ACTION_ATPG_VALUE),
    ACTION_ATCLPB(ACTION_ATCLPB_VALUE),
    ACTION_ATCGIB(ACTION_ATCGIB_VALUE),
    ACTION_ATCPAB(ACTION_ATCPAB_VALUE),
    ACTION_ATCSAUC(ACTION_ATCSAUC_VALUE),
    ACTION_ATCSCUC(ACTION_ATCSCUC_VALUE),
    ACTION_ATCHNUC(ACTION_ATCHNUC_VALUE),
    ACTION_CONTEXTUAL_CARD_LOAD(ACTION_CONTEXTUAL_CARD_LOAD_VALUE),
    ACTION_CONTEXTUAL_CARD_LOAD_TIMEOUT(ACTION_CONTEXTUAL_CARD_LOAD_TIMEOUT_VALUE),
    ACTION_CONTEXTUAL_CARD_ELIGIBILITY(ACTION_CONTEXTUAL_CARD_ELIGIBILITY_VALUE),
    ACTION_DISPLAY_WHITE_BALANCE_SETTING_CHANGED(ACTION_DISPLAY_WHITE_BALANCE_SETTING_CHANGED_VALUE),
    ACTION_SETTINGS_SHARE_WIFI_QR_CODE(ACTION_SETTINGS_SHARE_WIFI_QR_CODE_VALUE),
    ACTION_SETTINGS_ENROLL_WIFI_QR_CODE(ACTION_SETTINGS_ENROLL_WIFI_QR_CODE_VALUE),
    ACTION_SETTINGS_SHARE_WIFI_HOTSPOT_QR_CODE(ACTION_SETTINGS_SHARE_WIFI_HOTSPOT_QR_CODE_VALUE),
    ACTION_VERIFY_SLICE_ERROR_INVALID_DATA(ACTION_VERIFY_SLICE_ERROR_INVALID_DATA_VALUE),
    ACTION_VERIFY_SLICE_PARSING_ERROR(ACTION_VERIFY_SLICE_PARSING_ERROR_VALUE),
    ACTION_VERIFY_SLICE_OTHER_EXCEPTION(ACTION_VERIFY_SLICE_OTHER_EXCEPTION_VALUE);
    
    public static final int ACTION_AIRPLANE_TOGGLE_VALUE = 177;
    public static final int ACTION_AMBIENT_DISPLAY_VALUE = 495;
    public static final int ACTION_ANOMALY_IGNORED_VALUE = 1387;
    public static final int ACTION_ANOMALY_TRIGGERED_VALUE = 1367;
    public static final int ACTION_APP_FORCE_STOP_VALUE = 807;
    public static final int ACTION_APP_RESTRICTION_TIP_LIST_VALUE = 1353;
    public static final int ACTION_APP_RESTRICTION_TIP_VALUE = 1347;
    public static final int ACTION_ATCGIB_VALUE = 1677;
    public static final int ACTION_ATCHNUC_VALUE = 1681;
    public static final int ACTION_ATCLPB_VALUE = 1676;
    public static final int ACTION_ATCPAB_VALUE = 1678;
    public static final int ACTION_ATCSAUC_VALUE = 1679;
    public static final int ACTION_ATCSCUC_VALUE = 1680;
    public static final int ACTION_ATPG_VALUE = 1675;
    public static final int ACTION_ATSG_VALUE = 1674;
    public static final int ACTION_BLUETOOTH_FILES_VALUE = 162;
    public static final int ACTION_BLUETOOTH_RENAME_VALUE = 161;
    public static final int ACTION_BUGREPORT_FROM_SETTINGS_FULL_VALUE = 295;
    public static final int ACTION_BUGREPORT_FROM_SETTINGS_INTERACTIVE_VALUE = 294;
    public static final int ACTION_CELL_DATA_TOGGLE_VALUE = 178;
    public static final int ACTION_CONTEXTUAL_CARD_CLICK_VALUE = 1666;
    public static final int ACTION_CONTEXTUAL_CARD_DISMISS_VALUE = 1665;
    public static final int ACTION_CONTEXTUAL_CARD_ELIGIBILITY_VALUE = 1686;
    public static final int ACTION_CONTEXTUAL_CARD_LOAD_TIMEOUT_VALUE = 1685;
    public static final int ACTION_CONTEXTUAL_CARD_LOAD_VALUE = 1684;
    public static final int ACTION_CONTEXTUAL_CARD_NOT_SHOW_VALUE = 1664;
    public static final int ACTION_CONTEXTUAL_CARD_SHOW_VALUE = 1663;
    public static final int ACTION_CONTEXTUAL_HOME_SHOW_VALUE = 1662;
    public static final int ACTION_DATA_SAVER_BLACKLIST_VALUE = 396;
    public static final int ACTION_DATA_SAVER_MODE_VALUE = 394;
    public static final int ACTION_DATA_SAVER_WHITELIST_VALUE = 395;
    public static final int ACTION_DISPLAY_WHITE_BALANCE_SETTING_CHANGED_VALUE = 1703;
    public static final int ACTION_EARLY_WARNING_TIP_VALUE = 1351;
    public static final int ACTION_FINGERPRINT_DELETE_VALUE = 253;
    public static final int ACTION_FINGERPRINT_RENAME_VALUE = 254;
    public static final int ACTION_HIGH_USAGE_TIP_LIST_VALUE = 1354;
    public static final int ACTION_HIGH_USAGE_TIP_VALUE = 1348;
    public static final int ACTION_LOW_BATTERY_TIP_VALUE = 1352;
    public static final int ACTION_MOBILE_NETWORK_MANUAL_SELECT_NETWORK_VALUE = 1210;
    public static final int ACTION_NFC_PAYMENT_ALWAYS_SETTING_VALUE = 1623;
    public static final int ACTION_NFC_PAYMENT_FOREGROUND_SETTING_VALUE = 1622;
    public static final int ACTION_OPEN_APP_NOTIFICATION_SETTING_VALUE = 1016;
    public static final int ACTION_OPEN_APP_SETTING_VALUE = 1017;
    public static final int ACTION_PANEL_INTERACTION_VALUE = 1658;
    public static final int ACTION_PRIVATE_DNS_MODE_VALUE = 1249;
    public static final int ACTION_PSD_LOADER_VALUE = 1019;
    public static final int ACTION_ROTATION_LOCK_VALUE = 203;
    public static final int ACTION_SEARCH_RESULTS_VALUE = 226;
    public static final int ACTION_SETTINGS_ADVANCED_BUTTON_EXPAND_VALUE = 834;
    public static final int ACTION_SETTINGS_BLUETOOTH_CONNECT_ERROR_VALUE = 869;
    public static final int ACTION_SETTINGS_BLUETOOTH_CONNECT_VALUE = 867;
    public static final int ACTION_SETTINGS_BLUETOOTH_DISCONNECT_VALUE = 868;
    public static final int ACTION_SETTINGS_BLUETOOTH_PAIR_DEVICES_WITHOUT_NAMES_VALUE = 1096;
    public static final int ACTION_SETTINGS_BLUETOOTH_PAIR_VALUE = 866;
    public static final int ACTION_SETTINGS_BUILD_NUMBER_PREF_VALUE = 847;
    public static final int ACTION_SETTINGS_CLEAR_APP_CACHE_VALUE = 877;
    public static final int ACTION_SETTINGS_CLEAR_APP_DATA_VALUE = 876;
    public static final int ACTION_SETTINGS_CLEAR_INSTANT_APP_VALUE = 923;
    public static final int ACTION_SETTINGS_CONDITION_BUTTON_VALUE = 376;
    public static final int ACTION_SETTINGS_CONDITION_CLICK_VALUE = 375;
    public static final int ACTION_SETTINGS_CONDITION_EXPAND_VALUE = 373;
    public static final int ACTION_SETTINGS_CREATE_SHORTCUT_VALUE = 829;
    public static final int ACTION_SETTINGS_DISABLE_APP_VALUE = 874;
    public static final int ACTION_SETTINGS_ENABLE_APP_VALUE = 875;
    public static final int ACTION_SETTINGS_ENROLL_WIFI_QR_CODE_VALUE = 1711;
    public static final int ACTION_SETTINGS_MASTER_SWITCH_BLUETOOTH_TOGGLE_VALUE = 870;
    public static final int ACTION_SETTINGS_MENU_BATTERY_APPS_TOGGLE_VALUE = 852;
    public static final int ACTION_SETTINGS_MENU_BATTERY_OPTIMIZATION_VALUE = 851;
    public static final int ACTION_SETTINGS_PREFERENCE_CHANGE_VALUE = 853;
    public static final int ACTION_SETTINGS_SHARE_WIFI_HOTSPOT_QR_CODE_VALUE = 1712;
    public static final int ACTION_SETTINGS_SHARE_WIFI_QR_CODE_VALUE = 1710;
    public static final int ACTION_SETTINGS_SLICE_CHANGED_VALUE = 1372;
    public static final int ACTION_SETTINGS_SLICE_REQUESTED_VALUE = 1371;
    public static final int ACTION_SETTINGS_UNINSTALL_APP_VALUE = 872;
    public static final int ACTION_SETTINGS_UNINSTALL_DEVICE_ADMIN_VALUE = 873;
    public static final int ACTION_SETTINGS_UPDATE_DEFAULT_APP_VALUE = 1000;
    public static final int ACTION_SET_NEW_PARENT_PROFILE_PASSWORD_VALUE = 1646;
    public static final int ACTION_SET_NEW_PASSWORD_VALUE = 1645;
    public static final int ACTION_SMART_BATTERY_TIP_VALUE = 1350;
    public static final int ACTION_STORAGE_BENCHMARK_FAST_CONTINUE_VALUE = 1409;
    public static final int ACTION_STORAGE_BENCHMARK_SLOW_ABORT_VALUE = 1411;
    public static final int ACTION_STORAGE_BENCHMARK_SLOW_CONTINUE_VALUE = 1410;
    public static final int ACTION_STORAGE_INIT_EXTERNAL_VALUE = 1407;
    public static final int ACTION_STORAGE_INIT_INTERNAL_VALUE = 1408;
    public static final int ACTION_STORAGE_MIGRATE_LATER_VALUE = 1413;
    public static final int ACTION_STORAGE_MIGRATE_NOW_VALUE = 1412;
    public static final int ACTION_SUMMARY_TIP_VALUE = 1349;
    public static final int ACTION_THEME_VALUE = 816;
    public static final int ACTION_TIP_OPEN_APP_RESTRICTION_PAGE_VALUE = 1361;
    public static final int ACTION_TIP_OPEN_BATTERY_SAVER_PAGE_VALUE = 1388;
    public static final int ACTION_TIP_OPEN_SMART_BATTERY_VALUE = 1364;
    public static final int ACTION_TIP_RESTRICT_APP_VALUE = 1362;
    public static final int ACTION_TIP_TURN_ON_BATTERY_SAVER_VALUE = 1365;
    public static final int ACTION_TIP_UNRESTRICT_APP_VALUE = 1363;
    public static final int ACTION_TOGGLE_STORAGE_MANAGER_VALUE = 489;
    public static final int ACTION_UNKNOWN_VALUE = 0;
    public static final int ACTION_VERIFY_SLICE_ERROR_INVALID_DATA_VALUE = 1725;
    public static final int ACTION_VERIFY_SLICE_OTHER_EXCEPTION_VALUE = 1727;
    public static final int ACTION_VERIFY_SLICE_PARSING_ERROR_VALUE = 1726;
    public static final int ACTION_WIFI_CONNECT_VALUE = 135;
    public static final int ACTION_WIFI_FORGET_VALUE = 137;
    public static final int ACTION_WIFI_OFF_VALUE = 138;
    public static final int ACTION_WIFI_ON_VALUE = 139;
    public static final int ACTION_WIFI_SIGNIN_VALUE = 1008;
    public static final int ACTION_ZEN_ALLOW_ALARMS_VALUE = 1226;
    public static final int ACTION_ZEN_ALLOW_CALLS_VALUE = 170;
    public static final int ACTION_ZEN_ALLOW_EVENTS_VALUE = 168;
    public static final int ACTION_ZEN_ALLOW_MEDIA_VALUE = 1227;
    public static final int ACTION_ZEN_ALLOW_MESSAGES_VALUE = 169;
    public static final int ACTION_ZEN_ALLOW_REMINDERS_VALUE = 167;
    public static final int ACTION_ZEN_ALLOW_REPEAT_CALLS_VALUE = 171;
    public static final int ACTION_ZEN_ALLOW_SYSTEM_VALUE = 1340;
    public static final int ACTION_ZEN_BLOCK_AMBIENT_VALUE = 1337;
    public static final int ACTION_ZEN_BLOCK_BADGE_VALUE = 1336;
    public static final int ACTION_ZEN_BLOCK_FULL_SCREEN_INTENTS_VALUE = 1332;
    public static final int ACTION_ZEN_BLOCK_LIGHT_VALUE = 1333;
    public static final int ACTION_ZEN_BLOCK_NOTIFICATION_LIST_VALUE = 1338;
    public static final int ACTION_ZEN_BLOCK_PEEK_VALUE = 1334;
    public static final int ACTION_ZEN_BLOCK_STATUS_VALUE = 1335;
    public static final int ACTION_ZEN_CUSTOM_VALUE = 1399;
    public static final int ACTION_ZEN_DELETE_RULE_OK_VALUE = 175;
    public static final int ACTION_ZEN_MODE_RULE_NAME_CHANGE_OK_VALUE = 1267;
    public static final int ACTION_ZEN_ONBOARDING_KEEP_CURRENT_SETTINGS_VALUE = 1406;
    public static final int ACTION_ZEN_ONBOARDING_OK_VALUE = 1378;
    public static final int ACTION_ZEN_ONBOARDING_SETTINGS_VALUE = 1379;
    public static final int ACTION_ZEN_SHOW_CUSTOM_VALUE = 1398;
    public static final int ACTION_ZEN_SOUND_AND_VIS_EFFECTS_VALUE = 1397;
    public static final int ACTION_ZEN_SOUND_ONLY_VALUE = 1396;
    public static final int ACTION_ZEN_TOGGLE_DND_BUTTON_VALUE = 1268;
    public static final int APP_PICTURE_IN_PICTURE_ALLOW_VALUE = 813;
    public static final int APP_PICTURE_IN_PICTURE_DENY_VALUE = 814;
    public static final int APP_SPECIAL_PERMISSION_ADMIN_ALLOW_VALUE = 766;
    public static final int APP_SPECIAL_PERMISSION_ADMIN_DENY_VALUE = 767;
    public static final int APP_SPECIAL_PERMISSION_APPDRAW_ALLOW_VALUE = 770;
    public static final int APP_SPECIAL_PERMISSION_APPDRAW_DENY_VALUE = 771;
    public static final int APP_SPECIAL_PERMISSION_BATTERY_ALLOW_VALUE = 764;
    public static final int APP_SPECIAL_PERMISSION_BATTERY_DENY_VALUE = 765;
    public static final int APP_SPECIAL_PERMISSION_DND_ALLOW_VALUE = 768;
    public static final int APP_SPECIAL_PERMISSION_DND_DENY_VALUE = 769;
    public static final int APP_SPECIAL_PERMISSION_NOTIVIEW_ALLOW_VALUE = 776;
    public static final int APP_SPECIAL_PERMISSION_NOTIVIEW_DENY_VALUE = 777;
    public static final int APP_SPECIAL_PERMISSION_PREMIUM_SMS_ALWAYS_ALLOW_VALUE = 780;
    public static final int APP_SPECIAL_PERMISSION_PREMIUM_SMS_ASK_VALUE = 778;
    public static final int APP_SPECIAL_PERMISSION_PREMIUM_SMS_DENY_VALUE = 779;
    public static final int APP_SPECIAL_PERMISSION_SETTINGS_CHANGE_ALLOW_VALUE = 774;
    public static final int APP_SPECIAL_PERMISSION_SETTINGS_CHANGE_DENY_VALUE = 775;
    public static final int APP_SPECIAL_PERMISSION_UNL_DATA_ALLOW_VALUE = 781;
    public static final int APP_SPECIAL_PERMISSION_UNL_DATA_DENY_VALUE = 782;
    public static final int APP_SPECIAL_PERMISSION_USAGE_VIEW_ALLOW_VALUE = 783;
    public static final int APP_SPECIAL_PERMISSION_USAGE_VIEW_DENY_VALUE = 784;
    public static final int APP_SPECIAL_PERMISSION_VRHELPER_ALLOW_VALUE = 772;
    public static final int APP_SPECIAL_PERMISSION_VRHELPER_DENY_VALUE = 773;
    public static final int CLICK_ACCOUNT_AVATAR_VALUE = 1643;
    public static final int DIALOG_SWITCH_A2DP_DEVICES_VALUE = 1415;
    public static final int DIALOG_SWITCH_HFP_DEVICES_VALUE = 1416;
    public static final int PAGE_HIDE_VALUE = 2;
    public static final int PAGE_VISIBLE_VALUE = 1;
    public static final int QS_SENSOR_PRIVACY_VALUE = 1598;
    public static final int SETTINGS_ASSIST_GESTURE_TRAINING_ENROLLING_VALUE = 992;
    public static final int SETTINGS_ASSIST_GESTURE_TRAINING_FINISHED_VALUE = 993;
    public static final int SETTINGS_ASSIST_GESTURE_TRAINING_INTRO_VALUE = 991;
    public static final int TRAMPOLINE_SETTINGS_EVENT_VALUE = 1033;
    private static final Internal.EnumLiteMap<Action> internalValueMap = new Internal.EnumLiteMap<Action>() {
        /* class android.app.settings.Action.AnonymousClass1 */

        @Override // com.google.protobuf.Internal.EnumLiteMap
        public Action findValueByNumber(int number) {
            return Action.forNumber(number);
        }
    };
    private final int value;

    @Override // com.google.protobuf.Internal.EnumLite
    public final int getNumber() {
        return this.value;
    }

    @Deprecated
    public static Action valueOf(int value2) {
        return forNumber(value2);
    }

    public static Action forNumber(int value2) {
        if (value2 == 0) {
            return ACTION_UNKNOWN;
        }
        if (value2 == 1) {
            return PAGE_VISIBLE;
        }
        if (value2 == 2) {
            return PAGE_HIDE;
        }
        if (value2 == 161) {
            return ACTION_BLUETOOTH_RENAME;
        }
        if (value2 == 162) {
            return ACTION_BLUETOOTH_FILES;
        }
        if (value2 == 177) {
            return ACTION_AIRPLANE_TOGGLE;
        }
        if (value2 == 178) {
            return ACTION_CELL_DATA_TOGGLE;
        }
        if (value2 == 253) {
            return ACTION_FINGERPRINT_DELETE;
        }
        if (value2 == 254) {
            return ACTION_FINGERPRINT_RENAME;
        }
        if (value2 == 294) {
            return ACTION_BUGREPORT_FROM_SETTINGS_INTERACTIVE;
        }
        if (value2 == 295) {
            return ACTION_BUGREPORT_FROM_SETTINGS_FULL;
        }
        if (value2 == 375) {
            return ACTION_SETTINGS_CONDITION_CLICK;
        }
        if (value2 == 376) {
            return ACTION_SETTINGS_CONDITION_BUTTON;
        }
        switch (value2) {
            case 135:
                return ACTION_WIFI_CONNECT;
            case 175:
                return ACTION_ZEN_DELETE_RULE_OK;
            case 203:
                return ACTION_ROTATION_LOCK;
            case ACTION_SEARCH_RESULTS_VALUE:
                return ACTION_SEARCH_RESULTS;
            case ACTION_SETTINGS_CONDITION_EXPAND_VALUE:
                return ACTION_SETTINGS_CONDITION_EXPAND;
            case ACTION_TOGGLE_STORAGE_MANAGER_VALUE:
                return ACTION_TOGGLE_STORAGE_MANAGER;
            case ACTION_AMBIENT_DISPLAY_VALUE:
                return ACTION_AMBIENT_DISPLAY;
            case APP_SPECIAL_PERMISSION_BATTERY_ALLOW_VALUE:
                return APP_SPECIAL_PERMISSION_BATTERY_ALLOW;
            case APP_SPECIAL_PERMISSION_BATTERY_DENY_VALUE:
                return APP_SPECIAL_PERMISSION_BATTERY_DENY;
            case APP_SPECIAL_PERMISSION_ADMIN_ALLOW_VALUE:
                return APP_SPECIAL_PERMISSION_ADMIN_ALLOW;
            case APP_SPECIAL_PERMISSION_ADMIN_DENY_VALUE:
                return APP_SPECIAL_PERMISSION_ADMIN_DENY;
            case APP_SPECIAL_PERMISSION_DND_ALLOW_VALUE:
                return APP_SPECIAL_PERMISSION_DND_ALLOW;
            case APP_SPECIAL_PERMISSION_DND_DENY_VALUE:
                return APP_SPECIAL_PERMISSION_DND_DENY;
            case APP_SPECIAL_PERMISSION_APPDRAW_ALLOW_VALUE:
                return APP_SPECIAL_PERMISSION_APPDRAW_ALLOW;
            case APP_SPECIAL_PERMISSION_APPDRAW_DENY_VALUE:
                return APP_SPECIAL_PERMISSION_APPDRAW_DENY;
            case APP_SPECIAL_PERMISSION_VRHELPER_ALLOW_VALUE:
                return APP_SPECIAL_PERMISSION_VRHELPER_ALLOW;
            case APP_SPECIAL_PERMISSION_VRHELPER_DENY_VALUE:
                return APP_SPECIAL_PERMISSION_VRHELPER_DENY;
            case APP_SPECIAL_PERMISSION_SETTINGS_CHANGE_ALLOW_VALUE:
                return APP_SPECIAL_PERMISSION_SETTINGS_CHANGE_ALLOW;
            case APP_SPECIAL_PERMISSION_SETTINGS_CHANGE_DENY_VALUE:
                return APP_SPECIAL_PERMISSION_SETTINGS_CHANGE_DENY;
            case APP_SPECIAL_PERMISSION_NOTIVIEW_ALLOW_VALUE:
                return APP_SPECIAL_PERMISSION_NOTIVIEW_ALLOW;
            case APP_SPECIAL_PERMISSION_NOTIVIEW_DENY_VALUE:
                return APP_SPECIAL_PERMISSION_NOTIVIEW_DENY;
            case APP_SPECIAL_PERMISSION_PREMIUM_SMS_ASK_VALUE:
                return APP_SPECIAL_PERMISSION_PREMIUM_SMS_ASK;
            case APP_SPECIAL_PERMISSION_PREMIUM_SMS_DENY_VALUE:
                return APP_SPECIAL_PERMISSION_PREMIUM_SMS_DENY;
            case APP_SPECIAL_PERMISSION_PREMIUM_SMS_ALWAYS_ALLOW_VALUE:
                return APP_SPECIAL_PERMISSION_PREMIUM_SMS_ALWAYS_ALLOW;
            case APP_SPECIAL_PERMISSION_UNL_DATA_ALLOW_VALUE:
                return APP_SPECIAL_PERMISSION_UNL_DATA_ALLOW;
            case APP_SPECIAL_PERMISSION_UNL_DATA_DENY_VALUE:
                return APP_SPECIAL_PERMISSION_UNL_DATA_DENY;
            case APP_SPECIAL_PERMISSION_USAGE_VIEW_ALLOW_VALUE:
                return APP_SPECIAL_PERMISSION_USAGE_VIEW_ALLOW;
            case APP_SPECIAL_PERMISSION_USAGE_VIEW_DENY_VALUE:
                return APP_SPECIAL_PERMISSION_USAGE_VIEW_DENY;
            case ACTION_APP_FORCE_STOP_VALUE:
                return ACTION_APP_FORCE_STOP;
            case APP_PICTURE_IN_PICTURE_ALLOW_VALUE:
                return APP_PICTURE_IN_PICTURE_ALLOW;
            case APP_PICTURE_IN_PICTURE_DENY_VALUE:
                return APP_PICTURE_IN_PICTURE_DENY;
            case ACTION_THEME_VALUE:
                return ACTION_THEME;
            case ACTION_SETTINGS_CREATE_SHORTCUT_VALUE:
                return ACTION_SETTINGS_CREATE_SHORTCUT;
            case ACTION_SETTINGS_ADVANCED_BUTTON_EXPAND_VALUE:
                return ACTION_SETTINGS_ADVANCED_BUTTON_EXPAND;
            case ACTION_SETTINGS_BUILD_NUMBER_PREF_VALUE:
                return ACTION_SETTINGS_BUILD_NUMBER_PREF;
            case ACTION_SETTINGS_MENU_BATTERY_OPTIMIZATION_VALUE:
                return ACTION_SETTINGS_MENU_BATTERY_OPTIMIZATION;
            case ACTION_SETTINGS_MENU_BATTERY_APPS_TOGGLE_VALUE:
                return ACTION_SETTINGS_MENU_BATTERY_APPS_TOGGLE;
            case ACTION_SETTINGS_PREFERENCE_CHANGE_VALUE:
                return ACTION_SETTINGS_PREFERENCE_CHANGE;
            case ACTION_SETTINGS_BLUETOOTH_PAIR_VALUE:
                return ACTION_SETTINGS_BLUETOOTH_PAIR;
            case ACTION_SETTINGS_BLUETOOTH_CONNECT_VALUE:
                return ACTION_SETTINGS_BLUETOOTH_CONNECT;
            case ACTION_SETTINGS_BLUETOOTH_DISCONNECT_VALUE:
                return ACTION_SETTINGS_BLUETOOTH_DISCONNECT;
            case ACTION_SETTINGS_BLUETOOTH_CONNECT_ERROR_VALUE:
                return ACTION_SETTINGS_BLUETOOTH_CONNECT_ERROR;
            case ACTION_SETTINGS_MASTER_SWITCH_BLUETOOTH_TOGGLE_VALUE:
                return ACTION_SETTINGS_MASTER_SWITCH_BLUETOOTH_TOGGLE;
            case ACTION_SETTINGS_UNINSTALL_APP_VALUE:
                return ACTION_SETTINGS_UNINSTALL_APP;
            case ACTION_SETTINGS_UNINSTALL_DEVICE_ADMIN_VALUE:
                return ACTION_SETTINGS_UNINSTALL_DEVICE_ADMIN;
            case ACTION_SETTINGS_DISABLE_APP_VALUE:
                return ACTION_SETTINGS_DISABLE_APP;
            case ACTION_SETTINGS_ENABLE_APP_VALUE:
                return ACTION_SETTINGS_ENABLE_APP;
            case ACTION_SETTINGS_CLEAR_APP_DATA_VALUE:
                return ACTION_SETTINGS_CLEAR_APP_DATA;
            case ACTION_SETTINGS_CLEAR_APP_CACHE_VALUE:
                return ACTION_SETTINGS_CLEAR_APP_CACHE;
            case ACTION_SETTINGS_CLEAR_INSTANT_APP_VALUE:
                return ACTION_SETTINGS_CLEAR_INSTANT_APP;
            case SETTINGS_ASSIST_GESTURE_TRAINING_INTRO_VALUE:
                return SETTINGS_ASSIST_GESTURE_TRAINING_INTRO;
            case SETTINGS_ASSIST_GESTURE_TRAINING_ENROLLING_VALUE:
                return SETTINGS_ASSIST_GESTURE_TRAINING_ENROLLING;
            case SETTINGS_ASSIST_GESTURE_TRAINING_FINISHED_VALUE:
                return SETTINGS_ASSIST_GESTURE_TRAINING_FINISHED;
            case 1000:
                return ACTION_SETTINGS_UPDATE_DEFAULT_APP;
            case 1008:
                return ACTION_WIFI_SIGNIN;
            case 1016:
                return ACTION_OPEN_APP_NOTIFICATION_SETTING;
            case 1017:
                return ACTION_OPEN_APP_SETTING;
            case 1019:
                return ACTION_PSD_LOADER;
            case 1033:
                return TRAMPOLINE_SETTINGS_EVENT;
            case ACTION_SETTINGS_BLUETOOTH_PAIR_DEVICES_WITHOUT_NAMES_VALUE:
                return ACTION_SETTINGS_BLUETOOTH_PAIR_DEVICES_WITHOUT_NAMES;
            case ACTION_MOBILE_NETWORK_MANUAL_SELECT_NETWORK_VALUE:
                return ACTION_MOBILE_NETWORK_MANUAL_SELECT_NETWORK;
            case ACTION_ZEN_ALLOW_ALARMS_VALUE:
                return ACTION_ZEN_ALLOW_ALARMS;
            case ACTION_ZEN_ALLOW_MEDIA_VALUE:
                return ACTION_ZEN_ALLOW_MEDIA;
            case ACTION_PRIVATE_DNS_MODE_VALUE:
                return ACTION_PRIVATE_DNS_MODE;
            case ACTION_ZEN_MODE_RULE_NAME_CHANGE_OK_VALUE:
                return ACTION_ZEN_MODE_RULE_NAME_CHANGE_OK;
            case ACTION_ZEN_TOGGLE_DND_BUTTON_VALUE:
                return ACTION_ZEN_TOGGLE_DND_BUTTON;
            case ACTION_ZEN_BLOCK_FULL_SCREEN_INTENTS_VALUE:
                return ACTION_ZEN_BLOCK_FULL_SCREEN_INTENTS;
            case ACTION_ZEN_BLOCK_LIGHT_VALUE:
                return ACTION_ZEN_BLOCK_LIGHT;
            case ACTION_ZEN_BLOCK_PEEK_VALUE:
                return ACTION_ZEN_BLOCK_PEEK;
            case ACTION_ZEN_BLOCK_STATUS_VALUE:
                return ACTION_ZEN_BLOCK_STATUS;
            case ACTION_ZEN_BLOCK_BADGE_VALUE:
                return ACTION_ZEN_BLOCK_BADGE;
            case ACTION_ZEN_BLOCK_AMBIENT_VALUE:
                return ACTION_ZEN_BLOCK_AMBIENT;
            case ACTION_ZEN_BLOCK_NOTIFICATION_LIST_VALUE:
                return ACTION_ZEN_BLOCK_NOTIFICATION_LIST;
            case ACTION_ZEN_ALLOW_SYSTEM_VALUE:
                return ACTION_ZEN_ALLOW_SYSTEM;
            case ACTION_APP_RESTRICTION_TIP_VALUE:
                return ACTION_APP_RESTRICTION_TIP;
            case ACTION_HIGH_USAGE_TIP_VALUE:
                return ACTION_HIGH_USAGE_TIP;
            case ACTION_SUMMARY_TIP_VALUE:
                return ACTION_SUMMARY_TIP;
            case ACTION_SMART_BATTERY_TIP_VALUE:
                return ACTION_SMART_BATTERY_TIP;
            case ACTION_EARLY_WARNING_TIP_VALUE:
                return ACTION_EARLY_WARNING_TIP;
            case ACTION_LOW_BATTERY_TIP_VALUE:
                return ACTION_LOW_BATTERY_TIP;
            case ACTION_APP_RESTRICTION_TIP_LIST_VALUE:
                return ACTION_APP_RESTRICTION_TIP_LIST;
            case ACTION_HIGH_USAGE_TIP_LIST_VALUE:
                return ACTION_HIGH_USAGE_TIP_LIST;
            case ACTION_TIP_OPEN_APP_RESTRICTION_PAGE_VALUE:
                return ACTION_TIP_OPEN_APP_RESTRICTION_PAGE;
            case ACTION_TIP_RESTRICT_APP_VALUE:
                return ACTION_TIP_RESTRICT_APP;
            case ACTION_TIP_UNRESTRICT_APP_VALUE:
                return ACTION_TIP_UNRESTRICT_APP;
            case ACTION_TIP_OPEN_SMART_BATTERY_VALUE:
                return ACTION_TIP_OPEN_SMART_BATTERY;
            case ACTION_TIP_TURN_ON_BATTERY_SAVER_VALUE:
                return ACTION_TIP_TURN_ON_BATTERY_SAVER;
            case ACTION_ANOMALY_TRIGGERED_VALUE:
                return ACTION_ANOMALY_TRIGGERED;
            case ACTION_SETTINGS_SLICE_REQUESTED_VALUE:
                return ACTION_SETTINGS_SLICE_REQUESTED;
            case ACTION_SETTINGS_SLICE_CHANGED_VALUE:
                return ACTION_SETTINGS_SLICE_CHANGED;
            case ACTION_ZEN_ONBOARDING_OK_VALUE:
                return ACTION_ZEN_ONBOARDING_OK;
            case ACTION_ZEN_ONBOARDING_SETTINGS_VALUE:
                return ACTION_ZEN_ONBOARDING_SETTINGS;
            case ACTION_ANOMALY_IGNORED_VALUE:
                return ACTION_ANOMALY_IGNORED;
            case ACTION_TIP_OPEN_BATTERY_SAVER_PAGE_VALUE:
                return ACTION_TIP_OPEN_BATTERY_SAVER_PAGE;
            case ACTION_ZEN_SOUND_ONLY_VALUE:
                return ACTION_ZEN_SOUND_ONLY;
            case ACTION_ZEN_SOUND_AND_VIS_EFFECTS_VALUE:
                return ACTION_ZEN_SOUND_AND_VIS_EFFECTS;
            case ACTION_ZEN_SHOW_CUSTOM_VALUE:
                return ACTION_ZEN_SHOW_CUSTOM;
            case ACTION_ZEN_CUSTOM_VALUE:
                return ACTION_ZEN_CUSTOM;
            case ACTION_ZEN_ONBOARDING_KEEP_CURRENT_SETTINGS_VALUE:
                return ACTION_ZEN_ONBOARDING_KEEP_CURRENT_SETTINGS;
            case ACTION_STORAGE_INIT_EXTERNAL_VALUE:
                return ACTION_STORAGE_INIT_EXTERNAL;
            case ACTION_STORAGE_INIT_INTERNAL_VALUE:
                return ACTION_STORAGE_INIT_INTERNAL;
            case ACTION_STORAGE_BENCHMARK_FAST_CONTINUE_VALUE:
                return ACTION_STORAGE_BENCHMARK_FAST_CONTINUE;
            case ACTION_STORAGE_BENCHMARK_SLOW_CONTINUE_VALUE:
                return ACTION_STORAGE_BENCHMARK_SLOW_CONTINUE;
            case ACTION_STORAGE_BENCHMARK_SLOW_ABORT_VALUE:
                return ACTION_STORAGE_BENCHMARK_SLOW_ABORT;
            case ACTION_STORAGE_MIGRATE_NOW_VALUE:
                return ACTION_STORAGE_MIGRATE_NOW;
            case ACTION_STORAGE_MIGRATE_LATER_VALUE:
                return ACTION_STORAGE_MIGRATE_LATER;
            case DIALOG_SWITCH_A2DP_DEVICES_VALUE:
                return DIALOG_SWITCH_A2DP_DEVICES;
            case DIALOG_SWITCH_HFP_DEVICES_VALUE:
                return DIALOG_SWITCH_HFP_DEVICES;
            case QS_SENSOR_PRIVACY_VALUE:
                return QS_SENSOR_PRIVACY;
            case ACTION_NFC_PAYMENT_FOREGROUND_SETTING_VALUE:
                return ACTION_NFC_PAYMENT_FOREGROUND_SETTING;
            case ACTION_NFC_PAYMENT_ALWAYS_SETTING_VALUE:
                return ACTION_NFC_PAYMENT_ALWAYS_SETTING;
            case CLICK_ACCOUNT_AVATAR_VALUE:
                return CLICK_ACCOUNT_AVATAR;
            case ACTION_SET_NEW_PASSWORD_VALUE:
                return ACTION_SET_NEW_PASSWORD;
            case ACTION_SET_NEW_PARENT_PROFILE_PASSWORD_VALUE:
                return ACTION_SET_NEW_PARENT_PROFILE_PASSWORD;
            case ACTION_PANEL_INTERACTION_VALUE:
                return ACTION_PANEL_INTERACTION;
            case ACTION_CONTEXTUAL_HOME_SHOW_VALUE:
                return ACTION_CONTEXTUAL_HOME_SHOW;
            case ACTION_CONTEXTUAL_CARD_SHOW_VALUE:
                return ACTION_CONTEXTUAL_CARD_SHOW;
            case ACTION_CONTEXTUAL_CARD_NOT_SHOW_VALUE:
                return ACTION_CONTEXTUAL_CARD_NOT_SHOW;
            case ACTION_CONTEXTUAL_CARD_DISMISS_VALUE:
                return ACTION_CONTEXTUAL_CARD_DISMISS;
            case ACTION_CONTEXTUAL_CARD_CLICK_VALUE:
                return ACTION_CONTEXTUAL_CARD_CLICK;
            case ACTION_ATSG_VALUE:
                return ACTION_ATSG;
            case ACTION_ATPG_VALUE:
                return ACTION_ATPG;
            case ACTION_ATCLPB_VALUE:
                return ACTION_ATCLPB;
            case ACTION_ATCGIB_VALUE:
                return ACTION_ATCGIB;
            case ACTION_ATCPAB_VALUE:
                return ACTION_ATCPAB;
            case ACTION_ATCSAUC_VALUE:
                return ACTION_ATCSAUC;
            case ACTION_ATCSCUC_VALUE:
                return ACTION_ATCSCUC;
            case ACTION_ATCHNUC_VALUE:
                return ACTION_ATCHNUC;
            case ACTION_CONTEXTUAL_CARD_LOAD_VALUE:
                return ACTION_CONTEXTUAL_CARD_LOAD;
            case ACTION_CONTEXTUAL_CARD_LOAD_TIMEOUT_VALUE:
                return ACTION_CONTEXTUAL_CARD_LOAD_TIMEOUT;
            case ACTION_CONTEXTUAL_CARD_ELIGIBILITY_VALUE:
                return ACTION_CONTEXTUAL_CARD_ELIGIBILITY;
            case ACTION_DISPLAY_WHITE_BALANCE_SETTING_CHANGED_VALUE:
                return ACTION_DISPLAY_WHITE_BALANCE_SETTING_CHANGED;
            case ACTION_SETTINGS_SHARE_WIFI_QR_CODE_VALUE:
                return ACTION_SETTINGS_SHARE_WIFI_QR_CODE;
            case ACTION_SETTINGS_ENROLL_WIFI_QR_CODE_VALUE:
                return ACTION_SETTINGS_ENROLL_WIFI_QR_CODE;
            case ACTION_SETTINGS_SHARE_WIFI_HOTSPOT_QR_CODE_VALUE:
                return ACTION_SETTINGS_SHARE_WIFI_HOTSPOT_QR_CODE;
            case ACTION_VERIFY_SLICE_ERROR_INVALID_DATA_VALUE:
                return ACTION_VERIFY_SLICE_ERROR_INVALID_DATA;
            case ACTION_VERIFY_SLICE_PARSING_ERROR_VALUE:
                return ACTION_VERIFY_SLICE_PARSING_ERROR;
            case ACTION_VERIFY_SLICE_OTHER_EXCEPTION_VALUE:
                return ACTION_VERIFY_SLICE_OTHER_EXCEPTION;
            default:
                switch (value2) {
                    case 137:
                        return ACTION_WIFI_FORGET;
                    case 138:
                        return ACTION_WIFI_OFF;
                    case 139:
                        return ACTION_WIFI_ON;
                    default:
                        switch (value2) {
                            case 167:
                                return ACTION_ZEN_ALLOW_REMINDERS;
                            case 168:
                                return ACTION_ZEN_ALLOW_EVENTS;
                            case 169:
                                return ACTION_ZEN_ALLOW_MESSAGES;
                            case 170:
                                return ACTION_ZEN_ALLOW_CALLS;
                            case 171:
                                return ACTION_ZEN_ALLOW_REPEAT_CALLS;
                            default:
                                switch (value2) {
                                    case ACTION_DATA_SAVER_MODE_VALUE:
                                        return ACTION_DATA_SAVER_MODE;
                                    case ACTION_DATA_SAVER_WHITELIST_VALUE:
                                        return ACTION_DATA_SAVER_WHITELIST;
                                    case ACTION_DATA_SAVER_BLACKLIST_VALUE:
                                        return ACTION_DATA_SAVER_BLACKLIST;
                                    default:
                                        return null;
                                }
                        }
                }
        }
    }

    public static Internal.EnumLiteMap<Action> internalGetValueMap() {
        return internalValueMap;
    }

    private Action(int value2) {
        this.value = value2;
    }
}
