package android.app.settings;

import com.google.protobuf.Internal;

public enum PageId implements Internal.EnumLite {
    PAGE_UNKNOWN(0),
    ACCESSIBILITY(2),
    ACCESSIBILITY_CAPTION_PROPERTIES(3),
    ACCESSIBILITY_SERVICE(4),
    ACCESSIBILITY_TOGGLE_DALTONIZER(5),
    ACCESSIBILITY_TOGGLE_GLOBAL_GESTURE(6),
    ACCESSIBILITY_TOGGLE_SCREEN_MAGNIFICATION(7),
    ACCOUNT(8),
    ACCOUNTS_ACCOUNT_SYNC(9),
    ACCOUNTS_CHOOSE_ACCOUNT_ACTIVITY(10),
    APN(12),
    APN_EDITOR(13),
    APPLICATIONS_APP_LAUNCH(17),
    APPLICATIONS_APP_STORAGE(19),
    APPLICATIONS_INSTALLED_APP_DETAILS(20),
    APPLICATIONS_PROCESS_STATS_DETAIL(21),
    APPLICATIONS_PROCESS_STATS_UI(23),
    BLUETOOTH_DEVICE_PICKER(25),
    CHOOSE_LOCK_GENERIC(27),
    CHOOSE_LOCK_PASSWORD(28),
    CHOOSE_LOCK_PATTERN(29),
    CONFIRM_LOCK_PASSWORD(30),
    CONFIRM_LOCK_PATTERN(31),
    CRYPT_KEEPER(32),
    CRYPT_KEEPER_CONFIRM(33),
    DASHBOARD_SUMMARY(35),
    DATA_USAGE_SUMMARY(37),
    DATE_TIME(38),
    DEVELOPMENT(39),
    DEVICEINFO(40),
    DEVICEINFO_STORAGE(42),
    DISPLAY(46),
    DREAM(47),
    ENCRYPTION(48),
    FINGERPRINT(49),
    FUELGAUGE_BATTERY_HISTORY_DETAIL(51),
    FUELGAUGE_BATTERY_SAVER(52),
    FUELGAUGE_POWER_USAGE_DETAIL(53),
    ICC_LOCK(56),
    INPUTMETHOD_KEYBOARD(58),
    INPUTMETHOD_SPELL_CHECKERS(59),
    INPUTMETHOD_SUBTYPE_ENABLER(60),
    INPUTMETHOD_USER_DICTIONARY(61),
    INPUTMETHOD_USER_DICTIONARY_ADD_WORD(62),
    LOCATION(63),
    MANAGE_APPLICATIONS(65),
    MASTER_CLEAR(66),
    MASTER_CLEAR_CONFIRM(67),
    NFC_BEAM(69),
    NFC_PAYMENT(70),
    NOTIFICATION_APP_NOTIFICATION(72),
    NOTIFICATION_REDACTION(74),
    NOTIFICATION_STATION(75),
    NOTIFICATION_ZEN_MODE(76),
    PRINT_JOB_SETTINGS(78),
    PRINT_SERVICE_SETTINGS(79),
    PRINT_SETTINGS(80),
    PRIVACY(81),
    PROXY_SELECTOR(82),
    RESET_NETWORK(83),
    RESET_NETWORK_CONFIRM(84),
    RUNNING_SERVICE_DETAILS(85),
    SCREEN_PINNING(86),
    SECURITY(87),
    SIM(88),
    TESTING(89),
    TETHER(90),
    TRUST_AGENT(91),
    TRUSTED_CREDENTIALS(92),
    TTS_ENGINE_SETTINGS(93),
    TTS_TEXT_TO_SPEECH(94),
    USAGE_ACCESS(95),
    USER(96),
    USERS_APP_RESTRICTIONS(97),
    USER_DETAILS(98),
    VPN(100),
    WALLPAPER_TYPE(101),
    WFD_WIFI_DISPLAY(102),
    WIFI(103),
    WIFI_CALLING(105),
    WIFI_SAVED_ACCESS_POINTS(106),
    WIFI_P2P(109),
    APPLICATIONS_ADVANCED(130),
    LOCATION_SCANNING(131),
    MANAGE_APPLICATIONS_NOTIFICATIONS(133),
    NOTIFICATION_ZEN_MODE_PRIORITY(141),
    NOTIFICATION_ZEN_MODE_AUTOMATION(142),
    NOTIFICATION_ZEN_MODE_SCHEDULE_RULE(144),
    MANAGE_DOMAIN_URLS(143),
    NOTIFICATION_ZEN_MODE_EVENT_RULE(146),
    NOTIFICATION_ACCESS(179),
    NOTIFICATION_ZEN_MODE_ACCESS(180),
    APPLICATIONS_STORAGE_APPS(182),
    APPLICATIONS_USAGE_ACCESS_DETAIL(183),
    APPLICATIONS_HIGH_POWER_APPS(184),
    APPLICATIONS_MANAGE_ASSIST(201),
    PROCESS_STATS_SUMMARY(PROCESS_STATS_SUMMARY_VALUE),
    SYSTEM_ALERT_WINDOW_APPS(SYSTEM_ALERT_WINDOW_APPS_VALUE),
    ABOUT_LEGAL_SETTINGS(ABOUT_LEGAL_SETTINGS_VALUE),
    FUELGAUGE_INACTIVE_APPS(FUELGAUGE_INACTIVE_APPS_VALUE),
    FINGERPRINT_ENROLLING(FINGERPRINT_ENROLLING_VALUE),
    FINGERPRINT_FIND_SENSOR(FINGERPRINT_FIND_SENSOR_VALUE),
    FINGERPRINT_ENROLL_FINISH(FINGERPRINT_ENROLL_FINISH_VALUE),
    FINGERPRINT_ENROLL_INTRO(FINGERPRINT_ENROLL_INTRO_VALUE),
    FINGERPRINT_ENROLL_SIDECAR(FINGERPRINT_ENROLL_SIDECAR_VALUE),
    FINGERPRINT_ENROLLING_SETUP(FINGERPRINT_ENROLLING_SETUP_VALUE),
    FINGERPRINT_FIND_SENSOR_SETUP(FINGERPRINT_FIND_SENSOR_SETUP_VALUE),
    FINGERPRINT_ENROLL_FINISH_SETUP(FINGERPRINT_ENROLL_FINISH_SETUP_VALUE),
    FINGERPRINT_ENROLL_INTRO_SETUP(249),
    BACKGROUND_CHECK_SUMMARY(BACKGROUND_CHECK_SUMMARY_VALUE),
    NOTIFICATION_TOPIC_NOTIFICATION(NOTIFICATION_TOPIC_NOTIFICATION_VALUE),
    USER_CREDENTIALS(USER_CREDENTIALS_VALUE),
    VR_MANAGE_LISTENERS(VR_MANAGE_LISTENERS_VALUE),
    ACCESSIBILITY_TOGGLE_AUTOCLICK(ACCESSIBILITY_TOGGLE_AUTOCLICK_VALUE),
    SOUND(SOUND_VALUE),
    CONFIGURE_NOTIFICATION(CONFIGURE_NOTIFICATION_VALUE),
    CONFIGURE_WIFI(CONFIGURE_WIFI_VALUE),
    DISPLAY_SCREEN_ZOOM(DISPLAY_SCREEN_ZOOM_VALUE),
    ACCESSIBILITY_FONT_SIZE(ACCESSIBILITY_FONT_SIZE_VALUE),
    DATA_USAGE_LIST(DATA_USAGE_LIST_VALUE),
    BILLING_CYCLE(BILLING_CYCLE_VALUE),
    APP_DATA_USAGE(APP_DATA_USAGE_VALUE),
    USER_LOCALE_LIST(USER_LOCALE_LIST_VALUE),
    VIRTUAL_KEYBOARDS(VIRTUAL_KEYBOARDS_VALUE),
    PHYSICAL_KEYBOARDS(PHYSICAL_KEYBOARDS_VALUE),
    ENABLE_VIRTUAL_KEYBOARDS(ENABLE_VIRTUAL_KEYBOARDS_VALUE),
    DATA_SAVER_SUMMARY(DATA_SAVER_SUMMARY_VALUE),
    DATA_USAGE_UNRESTRICTED_ACCESS(DATA_USAGE_UNRESTRICTED_ACCESS_VALUE),
    SPECIAL_ACCESS(SPECIAL_ACCESS_VALUE),
    SUW_ACCESSIBILITY(SUW_ACCESSIBILITY_VALUE),
    SUW_ACCESSIBILITY_TOGGLE_SCREEN_MAGNIFICATION(SUW_ACCESSIBILITY_TOGGLE_SCREEN_MAGNIFICATION_VALUE),
    SUW_ACCESSIBILITY_FONT_SIZE(SUW_ACCESSIBILITY_FONT_SIZE_VALUE),
    SUW_ACCESSIBILITY_DISPLAY_SIZE(SUW_ACCESSIBILITY_DISPLAY_SIZE_VALUE),
    SUW_ACCESSIBILITY_TOGGLE_SCREEN_READER(SUW_ACCESSIBILITY_TOGGLE_SCREEN_READER_VALUE),
    SETTINGS_CONDITION_AIRPLANE_MODE(SETTINGS_CONDITION_AIRPLANE_MODE_VALUE),
    SETTINGS_CONDITION_BACKGROUND_DATA(SETTINGS_CONDITION_BACKGROUND_DATA_VALUE),
    SETTINGS_CONDITION_BATTERY_SAVER(SETTINGS_CONDITION_BATTERY_SAVER_VALUE),
    SETTINGS_CONDITION_CELLULAR_DATA(SETTINGS_CONDITION_CELLULAR_DATA_VALUE),
    SETTINGS_CONDITION_DND(SETTINGS_CONDITION_DND_VALUE),
    SETTINGS_CONDITION_HOTSPOT(SETTINGS_CONDITION_HOTSPOT_VALUE),
    SETTINGS_CONDITION_WORK_MODE(SETTINGS_CONDITION_WORK_MODE_VALUE),
    PREMIUM_SMS_ACCESS(PREMIUM_SMS_ACCESS_VALUE),
    ACCOUNTS_WORK_PROFILE_SETTINGS(ACCOUNTS_WORK_PROFILE_SETTINGS_VALUE),
    CONVERT_FBE(CONVERT_FBE_VALUE),
    CONVERT_FBE_CONFIRM(CONVERT_FBE_CONFIRM_VALUE),
    RUNNING_SERVICES(RUNNING_SERVICES_VALUE),
    WEBVIEW_IMPLEMENTATION(WEBVIEW_IMPLEMENTATION_VALUE),
    STORAGE_MANAGER_SETTINGS(STORAGE_MANAGER_SETTINGS_VALUE),
    SETTINGS_GESTURES(SETTINGS_GESTURES_VALUE),
    NIGHT_DISPLAY_SETTINGS(NIGHT_DISPLAY_SETTINGS_VALUE),
    SETTINGS_CONDITION_NIGHT_DISPLAY(SETTINGS_CONDITION_NIGHT_DISPLAY_VALUE),
    USER_DICTIONARY_SETTINGS(USER_DICTIONARY_SETTINGS_VALUE),
    ZONE_PICKER(ZONE_PICKER_VALUE),
    DEVICE_ADMIN_SETTINGS(DEVICE_ADMIN_SETTINGS_VALUE),
    DIALOG_FRP(DIALOG_FRP_VALUE),
    DIALOG_CUSTOM_LIST_CONFIRMATION(DIALOG_CUSTOM_LIST_CONFIRMATION_VALUE),
    DIALOG_APN_EDITOR_ERROR(DIALOG_APN_EDITOR_ERROR_VALUE),
    DIALOG_OWNER_INFO_SETTINGS(DIALOG_OWNER_INFO_SETTINGS_VALUE),
    DIALOG_UNIFICATION_CONFIRMATION(DIALOG_UNIFICATION_CONFIRMATION_VALUE),
    DIALOG_USER_CREDENTIAL(DIALOG_USER_CREDENTIAL_VALUE),
    DIALOG_REMOVE_USER(DIALOG_REMOVE_USER_VALUE),
    DIALOG_CONFIRM_AUTO_SYNC_CHANGE(DIALOG_CONFIRM_AUTO_SYNC_CHANGE_VALUE),
    DIALOG_RUNNIGN_SERVICE(DIALOG_RUNNIGN_SERVICE_VALUE),
    DIALOG_BLUETOOTH_RENAME(DIALOG_BLUETOOTH_RENAME_VALUE),
    DIALOG_HIGH_POWER_DETAILS(DIALOG_HIGH_POWER_DETAILS_VALUE),
    DIALOG_KEYBOARD_LAYOUT(DIALOG_KEYBOARD_LAYOUT_VALUE),
    DIALOG_WIFI_SCAN_MODE(DIALOG_WIFI_SCAN_MODE_VALUE),
    DIALOG_LEGACY_VPN_CONFIG(DIALOG_LEGACY_VPN_CONFIG_VALUE),
    DIALOG_VPN_APP_CONFIG(DIALOG_VPN_APP_CONFIG_VALUE),
    DIALOG_VPN_CANNOT_CONNECT(DIALOG_VPN_CANNOT_CONNECT_VALUE),
    DIALOG_VPN_REPLACE_EXISTING(DIALOG_VPN_REPLACE_EXISTING_VALUE),
    DIALOG_BILLING_CYCLE(DIALOG_BILLING_CYCLE_VALUE),
    DIALOG_BILLING_BYTE_LIMIT(DIALOG_BILLING_BYTE_LIMIT_VALUE),
    DIALOG_BILLING_CONFIRM_LIMIT(DIALOG_BILLING_CONFIRM_LIMIT_VALUE),
    DIALOG_DISABLE_NOTIFICATION_ACCESS(DIALOG_DISABLE_NOTIFICATION_ACCESS_VALUE),
    DIALOG_UNIFY_SOUND_SETTINGS(DIALOG_UNIFY_SOUND_SETTINGS_VALUE),
    DIALOG_ZEN_ACCESS_GRANT(DIALOG_ZEN_ACCESS_GRANT_VALUE),
    DIALOG_ZEN_ACCESS_REVOKE(DIALOG_ZEN_ACCESS_REVOKE_VALUE),
    DIALOG_ZEN_TIMEPICKER(DIALOG_ZEN_TIMEPICKER_VALUE),
    DIALOG_SERVICE_ACCESS_WARNING(DIALOG_SERVICE_ACCESS_WARNING_VALUE),
    DIALOG_APP_INFO_ACTION(DIALOG_APP_INFO_ACTION_VALUE),
    DIALOG_VOLUME_FORGET(DIALOG_VOLUME_FORGET_VALUE),
    DIALOG_VOLUME_INIT(DIALOG_VOLUME_INIT_VALUE),
    DIALOG_VOLUME_UNMOUNT(DIALOG_VOLUME_UNMOUNT_VALUE),
    DIALOG_VOLUME_RENAME(DIALOG_VOLUME_RENAME_VALUE),
    DIALOG_STORAGE_CLEAR_CACHE(DIALOG_STORAGE_CLEAR_CACHE_VALUE),
    DIALOG_STORAGE_SYSTEM_INFO(DIALOG_STORAGE_SYSTEM_INFO_VALUE),
    DIALOG_STORAGE_OTHER_INFO(DIALOG_STORAGE_OTHER_INFO_VALUE),
    DIALOG_STORAGE_USER_INFO(DIALOG_STORAGE_USER_INFO_VALUE),
    DIALOG_FINGERPRINT_ICON_TOUCH(DIALOG_FINGERPRINT_ICON_TOUCH_VALUE),
    DIALOG_FINGERPINT_ERROR(DIALOG_FINGERPINT_ERROR_VALUE),
    DIALOG_FINGERPINT_EDIT(DIALOG_FINGERPINT_EDIT_VALUE),
    DIALOG_FINGERPINT_DELETE_LAST(DIALOG_FINGERPINT_DELETE_LAST_VALUE),
    DIALOG_FINGERPRINT_SKIP_SETUP(DIALOG_FINGERPRINT_SKIP_SETUP_VALUE),
    DIALOG_PROXY_SELECTOR_ERROR(DIALOG_PROXY_SELECTOR_ERROR_VALUE),
    DIALOG_WIFI_P2P_DISCONNECT(DIALOG_WIFI_P2P_DISCONNECT_VALUE),
    DIALOG_WIFI_P2P_CANCEL_CONNECT(DIALOG_WIFI_P2P_CANCEL_CONNECT_VALUE),
    DIALOG_WIFI_P2P_RENAME(DIALOG_WIFI_P2P_RENAME_VALUE),
    DIALOG_WIFI_P2P_DELETE_GROUP(DIALOG_WIFI_P2P_DELETE_GROUP_VALUE),
    DIALOG_APN_RESTORE_DEFAULT(DIALOG_APN_RESTORE_DEFAULT_VALUE),
    DIALOG_ENCRYPTION_INTERSTITIAL_ACCESSIBILITY(DIALOG_ENCRYPTION_INTERSTITIAL_ACCESSIBILITY_VALUE),
    DIALOG_ACCESSIBILITY_SERVICE_ENABLE(DIALOG_ACCESSIBILITY_SERVICE_ENABLE_VALUE),
    DIALOG_ACCESSIBILITY_SERVICE_DISABLE(DIALOG_ACCESSIBILITY_SERVICE_DISABLE_VALUE),
    DIALOG_ACCOUNT_SYNC_REMOVE(DIALOG_ACCOUNT_SYNC_REMOVE_VALUE),
    DIALOG_ACCOUNT_SYNC_FAILED_REMOVAL(DIALOG_ACCOUNT_SYNC_FAILED_REMOVAL_VALUE),
    DIALOG_ACCOUNT_SYNC_CANNOT_ONETIME_SYNC(DIALOG_ACCOUNT_SYNC_CANNOT_ONETIME_SYNC_VALUE),
    DIALOG_NIGHT_DISPLAY_SET_START_TIME(DIALOG_NIGHT_DISPLAY_SET_START_TIME_VALUE),
    DIALOG_NIGHT_DISPLAY_SET_END_TIME(DIALOG_NIGHT_DISPLAY_SET_END_TIME_VALUE),
    DIALOG_USER_EDIT(DIALOG_USER_EDIT_VALUE),
    DIALOG_USER_REMOVE(DIALOG_USER_REMOVE_VALUE),
    DIALOG_USER_ENABLE_CALLING(DIALOG_USER_ENABLE_CALLING_VALUE),
    DIALOG_USER_ENABLE_CALLING_AND_SMS(DIALOG_USER_ENABLE_CALLING_AND_SMS_VALUE),
    DIALOG_USER_CANNOT_MANAGE(DIALOG_USER_CANNOT_MANAGE_VALUE),
    DIALOG_USER_ADD(DIALOG_USER_ADD_VALUE),
    DIALOG_USER_SETUP(DIALOG_USER_SETUP_VALUE),
    DIALOG_USER_SETUP_PROFILE(DIALOG_USER_SETUP_PROFILE_VALUE),
    DIALOG_USER_CHOOSE_TYPE(DIALOG_USER_CHOOSE_TYPE_VALUE),
    DIALOG_USER_NEED_LOCKSCREEN(DIALOG_USER_NEED_LOCKSCREEN_VALUE),
    DIALOG_USER_CONFIRM_EXIT_GUEST(DIALOG_USER_CONFIRM_EXIT_GUEST_VALUE),
    DIALOG_USER_EDIT_PROFILE(DIALOG_USER_EDIT_PROFILE_VALUE),
    DIALOG_WIFI_SAVED_AP_EDIT(DIALOG_WIFI_SAVED_AP_EDIT_VALUE),
    DIALOG_WIFI_AP_EDIT(DIALOG_WIFI_AP_EDIT_VALUE),
    DIALOG_WIFI_WRITE_NFC(DIALOG_WIFI_WRITE_NFC_VALUE),
    DIALOG_DATE_PICKER(DIALOG_DATE_PICKER_VALUE),
    DIALOG_TIME_PICKER(DIALOG_TIME_PICKER_VALUE),
    DIALOG_MANAGE_MOBILE_PLAN(DIALOG_MANAGE_MOBILE_PLAN_VALUE),
    BLUETOOTH_DIALOG_FRAGMENT(BLUETOOTH_DIALOG_FRAGMENT_VALUE),
    ENTERPRISE_PRIVACY_SETTINGS(ENTERPRISE_PRIVACY_SETTINGS_VALUE),
    SETTINGS_SYSTEM_CATEGORY(SETTINGS_SYSTEM_CATEGORY_VALUE),
    SETTINGS_STORAGE_CATEGORY(SETTINGS_STORAGE_CATEGORY_VALUE),
    SETTINGS_NETWORK_CATEGORY(SETTINGS_NETWORK_CATEGORY_VALUE),
    SETTINGS_CONNECTED_DEVICE_CATEGORY(SETTINGS_CONNECTED_DEVICE_CATEGORY_VALUE),
    SETTINGS_APP_NOTIF_CATEGORY(SETTINGS_APP_NOTIF_CATEGORY_VALUE),
    SETTINGS_LANGUAGE_CATEGORY(SETTINGS_LANGUAGE_CATEGORY_VALUE),
    SETTINGS_GESTURE_SWIPE_TO_NOTIFICATION(SETTINGS_GESTURE_SWIPE_TO_NOTIFICATION_VALUE),
    SETTINGS_GESTURE_DOUBLE_TAP_POWER(SETTINGS_GESTURE_DOUBLE_TAP_POWER_VALUE),
    SETTINGS_GESTURE_PICKUP(SETTINGS_GESTURE_PICKUP_VALUE),
    SETTINGS_GESTURE_DOUBLE_TAP_SCREEN(SETTINGS_GESTURE_DOUBLE_TAP_SCREEN_VALUE),
    SETTINGS_GESTURE_DOUBLE_TWIST(SETTINGS_GESTURE_DOUBLE_TWIST_VALUE),
    DEFAULT_BROWSER_PICKER(DEFAULT_BROWSER_PICKER_VALUE),
    DEFAULT_EMERGENCY_APP_PICKER(DEFAULT_EMERGENCY_APP_PICKER_VALUE),
    DEFAULT_HOME_PICKER(DEFAULT_HOME_PICKER_VALUE),
    DEFAULT_PHONE_PICKER(DEFAULT_PHONE_PICKER_VALUE),
    DEFAULT_SMS_PICKER(DEFAULT_SMS_PICKER_VALUE),
    DEFAULT_NOTIFICATION_ASSISTANT(DEFAULT_NOTIFICATION_ASSISTANT_VALUE),
    DEFAULT_APP_PICKER_CONFIRMATION_DIALOG(DEFAULT_APP_PICKER_CONFIRMATION_DIALOG_VALUE),
    DEFAULT_AUTOFILL_PICKER(DEFAULT_AUTOFILL_PICKER_VALUE),
    MANAGE_EXTERNAL_SOURCES(MANAGE_EXTERNAL_SOURCES_VALUE),
    SETTINGS_MANAGE_PICTURE_IN_PICTURE(SETTINGS_MANAGE_PICTURE_IN_PICTURE_VALUE),
    SUW_ACCESSIBILITY_TOGGLE_SELECT_TO_SPEAK(SUW_ACCESSIBILITY_TOGGLE_SELECT_TO_SPEAK_VALUE),
    BACKUP_SETTINGS(BACKUP_SETTINGS_VALUE),
    APPLICATIONS_STORAGE_GAMES(APPLICATIONS_STORAGE_GAMES_VALUE),
    APPLICATIONS_STORAGE_MUSIC(APPLICATIONS_STORAGE_MUSIC_VALUE),
    STORAGE_FREE_UP_SPACE_NOW(STORAGE_FREE_UP_SPACE_NOW_VALUE),
    STORAGE_FILES(STORAGE_FILES_VALUE),
    DEFAULT_ASSIST_PICKER(DEFAULT_ASSIST_PICKER_VALUE),
    DEFAULT_VOICE_INPUT_PICKER(DEFAULT_VOICE_INPUT_PICKER_VALUE),
    SETTINGS_STORAGE_PROFILE(SETTINGS_STORAGE_PROFILE_VALUE),
    ENCRYPTION_AND_CREDENTIAL(ENCRYPTION_AND_CREDENTIAL_VALUE),
    WIFI_NETWORK_DETAILS(WIFI_NETWORK_DETAILS_VALUE),
    SETTINGS_NETWORK_SCORER(SETTINGS_NETWORK_SCORER_VALUE),
    DIALOG_SETTINGS_HARDWARE_INFO(DIALOG_SETTINGS_HARDWARE_INFO_VALUE),
    SETTINGS_LOCK_SCREEN_PREFERENCES(SETTINGS_LOCK_SCREEN_PREFERENCES_VALUE),
    VR_DISPLAY_PREFERENCE(VR_DISPLAY_PREFERENCE_VALUE),
    ACCESSIBILITY_SCREEN_MAGNIFICATION_SETTINGS(ACCESSIBILITY_SCREEN_MAGNIFICATION_SETTINGS_VALUE),
    RESET_DASHBOARD(RESET_DASHBOARD_VALUE),
    FINGERPRINT_REMOVE_SIDECAR(FINGERPRINT_REMOVE_SIDECAR_VALUE),
    APPLICATIONS_STORAGE_MOVIES(APPLICATIONS_STORAGE_MOVIES_VALUE),
    ENTERPRISE_PRIVACY_INSTALLED_APPS(ENTERPRISE_PRIVACY_INSTALLED_APPS_VALUE),
    ENTERPRISE_PRIVACY_PERMISSIONS(ENTERPRISE_PRIVACY_PERMISSIONS_VALUE),
    ENTERPRISE_PRIVACY_DEFAULT_APPS(ENTERPRISE_PRIVACY_DEFAULT_APPS_VALUE),
    SETTINGS_CHOOSE_LOCK_DIALOG(SETTINGS_CHOOSE_LOCK_DIALOG_VALUE),
    SETTINGS_ASSIST_GESTURE(SETTINGS_ASSIST_GESTURE_VALUE),
    BLUETOOTH_DEVICE_DETAILS(1009),
    CONFIGURE_KEYGUARD_DIALOG(1010),
    WIFI_TETHER_SETTINGS(1014),
    DIALOG_BLUETOOTH_PAIRED_DEVICE_RENAME(1015),
    BLUETOOTH_PAIRING(1018),
    DIALOG_BLUETOOTH_PAIRED_DEVICE_FORGET(1031),
    APPLICATIONS_STORAGE_PHOTOS(1092),
    COLOR_MODE_SETTINGS(COLOR_MODE_SETTINGS_VALUE),
    SETTINGS_FEATURE_FLAGS_DASHBOARD(SETTINGS_FEATURE_FLAGS_DASHBOARD_VALUE),
    NOTIFICATION_CHANNEL_GROUP(NOTIFICATION_CHANNEL_GROUP_VALUE),
    DIALOG_ENABLE_DEVELOPMENT_OPTIONS(DIALOG_ENABLE_DEVELOPMENT_OPTIONS_VALUE),
    DIALOG_ENABLE_OEM_UNLOCKING(DIALOG_ENABLE_OEM_UNLOCKING_VALUE),
    DIALOG_ENABLE_ADB(DIALOG_ENABLE_ADB_VALUE),
    FINGERPRINT_AUTHENTICATE_SIDECAR(FINGERPRINT_AUTHENTICATE_SIDECAR_VALUE),
    DIALOG_CLEAR_ADB_KEYS(DIALOG_CLEAR_ADB_KEYS_VALUE),
    DEVELOPMENT_QS_TILE_CONFIG(DEVELOPMENT_QS_TILE_CONFIG_VALUE),
    DIALOG_LOG_PERSIST(DIALOG_LOG_PERSIST_VALUE),
    WIFI_CALLING_FOR_SUB(WIFI_CALLING_FOR_SUB_VALUE),
    DIALOG_OEM_LOCK_INFO(DIALOG_OEM_LOCK_INFO_VALUE),
    DIALOG_IMEI_INFO(DIALOG_IMEI_INFO_VALUE),
    DIALOG_SIM_STATUS(DIALOG_SIM_STATUS_VALUE),
    DIALOG_FIRMWARE_VERSION(DIALOG_FIRMWARE_VERSION_VALUE),
    FUELGAUGE_POWER_USAGE_SUMMARY_V2(FUELGAUGE_POWER_USAGE_SUMMARY_V2_VALUE),
    CONNECTION_DEVICE_ADVANCED(CONNECTION_DEVICE_ADVANCED_VALUE),
    SCREEN_LOCK_SETTINGS(SCREEN_LOCK_SETTINGS_VALUE),
    NOTIFICATION_ZEN_MODE_DELETE_RULE_DIALOG(NOTIFICATION_ZEN_MODE_DELETE_RULE_DIALOG_VALUE),
    NOTIFICATION_ZEN_MODE_RULE_NAME_DIALOG(NOTIFICATION_ZEN_MODE_RULE_NAME_DIALOG_VALUE),
    NOTIFICATION_ZEN_MODE_RULE_SELECTION_DIALOG(NOTIFICATION_ZEN_MODE_RULE_SELECTION_DIALOG_VALUE),
    FUELGAUGE_SMART_BATTERY(FUELGAUGE_SMART_BATTERY_VALUE),
    FUELGAUGE_RESTRICTED_APP_DETAILS(FUELGAUGE_RESTRICTED_APP_DETAILS_VALUE),
    NOTIFICATION_ZEN_MODE_ENABLE_DIALOG(NOTIFICATION_ZEN_MODE_ENABLE_DIALOG_VALUE),
    USB_DEVICE_DETAILS(USB_DEVICE_DETAILS_VALUE),
    ACCESSIBILITY_VIBRATION(ACCESSIBILITY_VIBRATION_VALUE),
    ACCESSIBILITY_VIBRATION_NOTIFICATION(ACCESSIBILITY_VIBRATION_NOTIFICATION_VALUE),
    ACCESSIBILITY_VIBRATION_TOUCH(ACCESSIBILITY_VIBRATION_TOUCH_VALUE),
    USB_DEFAULT(USB_DEFAULT_VALUE),
    FUELGAUGE_BATTERY_TIP_DIALOG(FUELGAUGE_BATTERY_TIP_DIALOG_VALUE),
    ZEN_WHAT_TO_BLOCK(ZEN_WHAT_TO_BLOCK_VALUE),
    NOTIFICATION_ZEN_MODE_DURATION_DIALOG(NOTIFICATION_ZEN_MODE_DURATION_DIALOG_VALUE),
    SETTINGS_ZONE_PICKER_REGION(SETTINGS_ZONE_PICKER_REGION_VALUE),
    SETTINGS_ZONE_PICKER_TIME_ZONE(SETTINGS_ZONE_PICKER_TIME_ZONE_VALUE),
    SETTINGS_ZONE_PICKER_FIXED_OFFSET(SETTINGS_ZONE_PICKER_FIXED_OFFSET_VALUE),
    SETTINGS_PREVENT_RINGING(SETTINGS_PREVENT_RINGING_VALUE),
    SETTINGS_CONDITION_DEVICE_MUTED(SETTINGS_CONDITION_DEVICE_MUTED_VALUE),
    SETTINGS_CONDITION_DEVICE_VIBRATE(SETTINGS_CONDITION_DEVICE_VIBRATE_VALUE),
    PREVIOUSLY_CONNECTED_DEVICES(PREVIOUSLY_CONNECTED_DEVICES_VALUE),
    WIFI_SCANNING_NEEDED_DIALOG(WIFI_SCANNING_NEEDED_DIALOG_VALUE),
    SETTINGS_GESTURE_SWIPE_UP(SETTINGS_GESTURE_SWIPE_UP_VALUE),
    DIALOG_VOLUME_FORMAT(DIALOG_VOLUME_FORMAT_VALUE),
    SETTINGS_ZEN_ONBOARDING(SETTINGS_ZEN_ONBOARDING_VALUE),
    SETTINGS_AUTO_BRIGHTNESS(SETTINGS_AUTO_BRIGHTNESS_VALUE),
    BLUETOOTH_FRAGMENT(BLUETOOTH_FRAGMENT_VALUE),
    SETTINGS_ZEN_NOTIFICATIONS(SETTINGS_ZEN_NOTIFICATIONS_VALUE),
    SLICE(SLICE_VALUE),
    DIALOG_BLUETOOTH_DISABLE_A2DP_HW_OFFLOAD(DIALOG_BLUETOOTH_DISABLE_A2DP_HW_OFFLOAD_VALUE),
    SETTINGS_HOMEPAGE(SETTINGS_HOMEPAGE_VALUE),
    SETTINGS_CREATE_SHORTCUT(SETTINGS_CREATE_SHORTCUT_VALUE),
    FACE_ENROLL_INTRO(FACE_ENROLL_INTRO_VALUE),
    FACE_ENROLL_ENROLLING(FACE_ENROLL_ENROLLING_VALUE),
    FACE_ENROLL_FINISHED(FACE_ENROLL_FINISHED_VALUE),
    FACE_ENROLL_SIDECAR(FACE_ENROLL_SIDECAR_VALUE),
    DIALOG_FACE_ERROR(DIALOG_FACE_ERROR_VALUE),
    FACE(FACE_VALUE),
    DIALOG_ACCESSIBILITY_HEARINGAID(DIALOG_ACCESSIBILITY_HEARINGAID_VALUE),
    FACE_ENROLL_PREVIEW(FACE_ENROLL_PREVIEW_VALUE),
    SETTINGS_WIFI_ADD_NETWORK(SETTINGS_WIFI_ADD_NETWORK_VALUE),
    SETTINGS_GESTURE_WAKE_LOCK_SCREEN(SETTINGS_GESTURE_WAKE_LOCK_SCREEN_VALUE),
    SETTINGS_GESTURE_WAKE_SCREEN(SETTINGS_GESTURE_WAKE_SCREEN_VALUE),
    MOBILE_NETWORK(MOBILE_NETWORK_VALUE),
    MOBILE_NETWORK_SELECT(MOBILE_NETWORK_SELECT_VALUE),
    MOBILE_DATA_DIALOG(MOBILE_DATA_DIALOG_VALUE),
    MOBILE_ROAMING_DIALOG(MOBILE_ROAMING_DIALOG_VALUE),
    LOCK_SCREEN_NOTIFICATION_CONTENT(LOCK_SCREEN_NOTIFICATION_CONTENT_VALUE),
    BIOMETRIC_FRAGMENT(BIOMETRIC_FRAGMENT_VALUE),
    BIOMETRIC_ENROLL_ACTIVITY(BIOMETRIC_ENROLL_ACTIVITY_VALUE),
    TOP_LEVEL_PRIVACY(TOP_LEVEL_PRIVACY_VALUE),
    NOTIFICATION_ZEN_MODE_OVERRIDING_APPS(NOTIFICATION_ZEN_MODE_OVERRIDING_APPS_VALUE),
    NOTIFICATION_ZEN_MODE_OVERRIDING_APP(NOTIFICATION_ZEN_MODE_OVERRIDING_APP_VALUE),
    DIALOG_DISABLE_DEVELOPMENT_OPTIONS(DIALOG_DISABLE_DEVELOPMENT_OPTIONS_VALUE),
    SETTINGS_WIFI_DPP_CONFIGURATOR(SETTINGS_WIFI_DPP_CONFIGURATOR_VALUE),
    SETTINGS_WIFI_DPP_ENROLLEE(SETTINGS_WIFI_DPP_ENROLLEE_VALUE),
    SETTINGS_FINANCIAL_APPS_SMS_ACCESS(SETTINGS_FINANCIAL_APPS_SMS_ACCESS_VALUE),
    ZEN_CUSTOM_RULE_SETTINGS(ZEN_CUSTOM_RULE_SETTINGS_VALUE),
    ZEN_CUSTOM_RULE_SOUND_SETTINGS(ZEN_CUSTOM_RULE_SOUND_SETTINGS_VALUE),
    ZEN_CUSTOM_RULE_DEFAULT_SETTINGS(ZEN_CUSTOM_RULE_DEFAULT_SETTINGS_VALUE),
    ZEN_CUSTOM_RULE_NOTIFICATION_RESTRICTIONS(ZEN_CUSTOM_RULE_NOTIFICATION_RESTRICTIONS_VALUE),
    ZEN_CUSTOM_RULE_VIS_EFFECTS(ZEN_CUSTOM_RULE_VIS_EFFECTS_VALUE),
    ZEN_CUSTOM_RULE_MESSAGES(ZEN_CUSTOM_RULE_MESSAGES_VALUE),
    ZEN_CUSTOM_RULE_CALLS(ZEN_CUSTOM_RULE_CALLS_VALUE),
    ZEN_CUSTOM_SETTINGS_DIALOG(ZEN_CUSTOM_SETTINGS_DIALOG_VALUE),
    SETTINGS_GAME_DRIVER_DASHBOARD(SETTINGS_GAME_DRIVER_DASHBOARD_VALUE),
    ACCESSIBILITY_VIBRATION_RING(ACCESSIBILITY_VIBRATION_RING_VALUE),
    SETTINGS_GESTURE_SKIP(SETTINGS_GESTURE_SKIP_VALUE),
    SETTINGS_GESTURE_SILENCE(SETTINGS_GESTURE_SILENCE_VALUE),
    SETTINGS_GESTURE_TAP_SCREEN(SETTINGS_GESTURE_TAP_SCREEN_VALUE),
    MOBILE_NETWORK_LIST(MOBILE_NETWORK_LIST_VALUE),
    SETTINGS_ADAPTIVE_SLEEP(SETTINGS_ADAPTIVE_SLEEP_VALUE),
    SETTINGS_AWARE(SETTINGS_AWARE_VALUE),
    DIALOG_AWARE_DISABLE(DIALOG_AWARE_DISABLE_VALUE),
    MOBILE_NETWORK_RENAME_DIALOG(MOBILE_NETWORK_RENAME_DIALOG_VALUE),
    SET_NEW_PASSWORD_ACTIVITY(SET_NEW_PASSWORD_ACTIVITY_VALUE),
    PANEL_INTERNET_CONNECTIVITY(PANEL_INTERNET_CONNECTIVITY_VALUE),
    PANEL_VOLUME(PANEL_VOLUME_VALUE),
    PANEL_NFC(PANEL_NFC_VALUE),
    PANEL_MEDIA_OUTPUT(PANEL_MEDIA_OUTPUT_VALUE),
    PAGE_ATSSI(PAGE_ATSSI_VALUE),
    PAGE_ATSII(PAGE_ATSII_VALUE),
    PAGE_ATUS(PAGE_ATUS_VALUE),
    PAGE_ATSSP(PAGE_ATSSP_VALUE),
    PAGE_ATSAP(PAGE_ATSAP_VALUE),
    PAGE_ATSCP(PAGE_ATSCP_VALUE),
    PAGE_ATHNP(PAGE_ATHNP_VALUE),
    ACCESSIBILITY_DETAILS_SETTINGS(ACCESSIBILITY_DETAILS_SETTINGS_VALUE),
    SETTINGS_CONDITION_GRAYSCALE_MODE(SETTINGS_CONDITION_GRAYSCALE_MODE_VALUE),
    PANEL_WIFI(PANEL_WIFI_VALUE),
    ZEN_ACCESS_DETAIL(ZEN_ACCESS_DETAIL_VALUE),
    DIALOG_FACE_REMOVE(DIALOG_FACE_REMOVE_VALUE),
    DARK_UI_SETTINGS(DARK_UI_SETTINGS_VALUE),
    BUBBLE_SETTINGS(BUBBLE_SETTINGS_VALUE),
    APP_BUBBLE_SETTINGS(APP_BUBBLE_SETTINGS_VALUE),
    DIALOG_AWARE_STATUS(DIALOG_AWARE_STATUS_VALUE),
    DIALOG_APP_BUBBLE_SETTINGS(DIALOG_APP_BUBBLE_SETTINGS_VALUE),
    DIALOG_SIM_LIST(DIALOG_SIM_LIST_VALUE),
    DIALOG_CALL_SIM_LIST(DIALOG_CALL_SIM_LIST_VALUE),
    DIALOG_PREFERRED_SIM_PICKER(DIALOG_PREFERRED_SIM_PICKER_VALUE),
    DIALOG_DELETE_SIM_CONFIRMATION(DIALOG_DELETE_SIM_CONFIRMATION_VALUE),
    DIALOG_DELETE_SIM_PROGRESS(DIALOG_DELETE_SIM_PROGRESS_VALUE),
    GENTLE_NOTIFICATIONS_SCREEN(GENTLE_NOTIFICATIONS_SCREEN_VALUE),
    GLOBAL_ACTIONS_PANEL_SETTINGS(GLOBAL_ACTIONS_PANEL_SETTINGS_VALUE),
    DIALOG_DARK_UI_INFO(DIALOG_DARK_UI_INFO_VALUE),
    MODULE_LICENSES_DASHBOARD(MODULE_LICENSES_DASHBOARD_VALUE),
    SETTINGS_GESTURE_NAV_NOT_AVAILABLE_DLG(SETTINGS_GESTURE_NAV_NOT_AVAILABLE_DLG_VALUE),
    SETTINGS_GESTURE_NAV_BACK_SENSITIVITY_DLG(SETTINGS_GESTURE_NAV_BACK_SENSITIVITY_DLG_VALUE),
    SETTINGS_AWARE_DISPLAY(SETTINGS_AWARE_DISPLAY_VALUE),
    SETTINGS_GESTURE_TAP(SETTINGS_GESTURE_TAP_VALUE);
    
    public static final int ABOUT_LEGAL_SETTINGS_VALUE = 225;
    public static final int ACCESSIBILITY_CAPTION_PROPERTIES_VALUE = 3;
    public static final int ACCESSIBILITY_DETAILS_SETTINGS_VALUE = 1682;
    public static final int ACCESSIBILITY_FONT_SIZE_VALUE = 340;
    public static final int ACCESSIBILITY_SCREEN_MAGNIFICATION_SETTINGS_VALUE = 922;
    public static final int ACCESSIBILITY_SERVICE_VALUE = 4;
    public static final int ACCESSIBILITY_TOGGLE_AUTOCLICK_VALUE = 335;
    public static final int ACCESSIBILITY_TOGGLE_DALTONIZER_VALUE = 5;
    public static final int ACCESSIBILITY_TOGGLE_GLOBAL_GESTURE_VALUE = 6;
    public static final int ACCESSIBILITY_TOGGLE_SCREEN_MAGNIFICATION_VALUE = 7;
    public static final int ACCESSIBILITY_VALUE = 2;
    public static final int ACCESSIBILITY_VIBRATION_NOTIFICATION_VALUE = 1293;
    public static final int ACCESSIBILITY_VIBRATION_RING_VALUE = 1620;
    public static final int ACCESSIBILITY_VIBRATION_TOUCH_VALUE = 1294;
    public static final int ACCESSIBILITY_VIBRATION_VALUE = 1292;
    public static final int ACCOUNTS_ACCOUNT_SYNC_VALUE = 9;
    public static final int ACCOUNTS_CHOOSE_ACCOUNT_ACTIVITY_VALUE = 10;
    public static final int ACCOUNTS_WORK_PROFILE_SETTINGS_VALUE = 401;
    public static final int ACCOUNT_VALUE = 8;
    public static final int APN_EDITOR_VALUE = 13;
    public static final int APN_VALUE = 12;
    public static final int APPLICATIONS_ADVANCED_VALUE = 130;
    public static final int APPLICATIONS_APP_LAUNCH_VALUE = 17;
    public static final int APPLICATIONS_APP_STORAGE_VALUE = 19;
    public static final int APPLICATIONS_HIGH_POWER_APPS_VALUE = 184;
    public static final int APPLICATIONS_INSTALLED_APP_DETAILS_VALUE = 20;
    public static final int APPLICATIONS_MANAGE_ASSIST_VALUE = 201;
    public static final int APPLICATIONS_PROCESS_STATS_DETAIL_VALUE = 21;
    public static final int APPLICATIONS_PROCESS_STATS_UI_VALUE = 23;
    public static final int APPLICATIONS_STORAGE_APPS_VALUE = 182;
    public static final int APPLICATIONS_STORAGE_GAMES_VALUE = 838;
    public static final int APPLICATIONS_STORAGE_MOVIES_VALUE = 935;
    public static final int APPLICATIONS_STORAGE_MUSIC_VALUE = 839;
    public static final int APPLICATIONS_STORAGE_PHOTOS_VALUE = 1092;
    public static final int APPLICATIONS_USAGE_ACCESS_DETAIL_VALUE = 183;
    public static final int APP_BUBBLE_SETTINGS_VALUE = 1700;
    public static final int APP_DATA_USAGE_VALUE = 343;
    public static final int BACKGROUND_CHECK_SUMMARY_VALUE = 258;
    public static final int BACKUP_SETTINGS_VALUE = 818;
    public static final int BILLING_CYCLE_VALUE = 342;
    public static final int BIOMETRIC_ENROLL_ACTIVITY_VALUE = 1586;
    public static final int BIOMETRIC_FRAGMENT_VALUE = 1585;
    public static final int BLUETOOTH_DEVICE_DETAILS_VALUE = 1009;
    public static final int BLUETOOTH_DEVICE_PICKER_VALUE = 25;
    public static final int BLUETOOTH_DIALOG_FRAGMENT_VALUE = 613;
    public static final int BLUETOOTH_FRAGMENT_VALUE = 1390;
    public static final int BLUETOOTH_PAIRING_VALUE = 1018;
    public static final int BUBBLE_SETTINGS_VALUE = 1699;
    public static final int CHOOSE_LOCK_GENERIC_VALUE = 27;
    public static final int CHOOSE_LOCK_PASSWORD_VALUE = 28;
    public static final int CHOOSE_LOCK_PATTERN_VALUE = 29;
    public static final int COLOR_MODE_SETTINGS_VALUE = 1143;
    public static final int CONFIGURE_KEYGUARD_DIALOG_VALUE = 1010;
    public static final int CONFIGURE_NOTIFICATION_VALUE = 337;
    public static final int CONFIGURE_WIFI_VALUE = 338;
    public static final int CONFIRM_LOCK_PASSWORD_VALUE = 30;
    public static final int CONFIRM_LOCK_PATTERN_VALUE = 31;
    public static final int CONNECTION_DEVICE_ADVANCED_VALUE = 1264;
    public static final int CONVERT_FBE_CONFIRM_VALUE = 403;
    public static final int CONVERT_FBE_VALUE = 402;
    public static final int CRYPT_KEEPER_CONFIRM_VALUE = 33;
    public static final int CRYPT_KEEPER_VALUE = 32;
    public static final int DARK_UI_SETTINGS_VALUE = 1698;
    public static final int DASHBOARD_SUMMARY_VALUE = 35;
    public static final int DATA_SAVER_SUMMARY_VALUE = 348;
    public static final int DATA_USAGE_LIST_VALUE = 341;
    public static final int DATA_USAGE_SUMMARY_VALUE = 37;
    public static final int DATA_USAGE_UNRESTRICTED_ACCESS_VALUE = 349;
    public static final int DATE_TIME_VALUE = 38;
    public static final int DEFAULT_APP_PICKER_CONFIRMATION_DIALOG_VALUE = 791;
    public static final int DEFAULT_ASSIST_PICKER_VALUE = 843;
    public static final int DEFAULT_AUTOFILL_PICKER_VALUE = 792;
    public static final int DEFAULT_BROWSER_PICKER_VALUE = 785;
    public static final int DEFAULT_EMERGENCY_APP_PICKER_VALUE = 786;
    public static final int DEFAULT_HOME_PICKER_VALUE = 787;
    public static final int DEFAULT_NOTIFICATION_ASSISTANT_VALUE = 790;
    public static final int DEFAULT_PHONE_PICKER_VALUE = 788;
    public static final int DEFAULT_SMS_PICKER_VALUE = 789;
    public static final int DEFAULT_VOICE_INPUT_PICKER_VALUE = 844;
    public static final int DEVELOPMENT_QS_TILE_CONFIG_VALUE = 1224;
    public static final int DEVELOPMENT_VALUE = 39;
    public static final int DEVICEINFO_STORAGE_VALUE = 42;
    public static final int DEVICEINFO_VALUE = 40;
    public static final int DEVICE_ADMIN_SETTINGS_VALUE = 516;
    public static final int DIALOG_ACCESSIBILITY_HEARINGAID_VALUE = 1512;
    public static final int DIALOG_ACCESSIBILITY_SERVICE_DISABLE_VALUE = 584;
    public static final int DIALOG_ACCESSIBILITY_SERVICE_ENABLE_VALUE = 583;
    public static final int DIALOG_ACCOUNT_SYNC_CANNOT_ONETIME_SYNC_VALUE = 587;
    public static final int DIALOG_ACCOUNT_SYNC_FAILED_REMOVAL_VALUE = 586;
    public static final int DIALOG_ACCOUNT_SYNC_REMOVE_VALUE = 585;
    public static final int DIALOG_APN_EDITOR_ERROR_VALUE = 530;
    public static final int DIALOG_APN_RESTORE_DEFAULT_VALUE = 579;
    public static final int DIALOG_APP_BUBBLE_SETTINGS_VALUE = 1702;
    public static final int DIALOG_APP_INFO_ACTION_VALUE = 558;
    public static final int DIALOG_AWARE_DISABLE_VALUE = 1633;
    public static final int DIALOG_AWARE_STATUS_VALUE = 1701;
    public static final int DIALOG_BILLING_BYTE_LIMIT_VALUE = 550;
    public static final int DIALOG_BILLING_CONFIRM_LIMIT_VALUE = 551;
    public static final int DIALOG_BILLING_CYCLE_VALUE = 549;
    public static final int DIALOG_BLUETOOTH_DISABLE_A2DP_HW_OFFLOAD_VALUE = 1441;
    public static final int DIALOG_BLUETOOTH_PAIRED_DEVICE_FORGET_VALUE = 1031;
    public static final int DIALOG_BLUETOOTH_PAIRED_DEVICE_RENAME_VALUE = 1015;
    public static final int DIALOG_BLUETOOTH_RENAME_VALUE = 538;
    public static final int DIALOG_CALL_SIM_LIST_VALUE = 1708;
    public static final int DIALOG_CLEAR_ADB_KEYS_VALUE = 1223;
    public static final int DIALOG_CONFIRM_AUTO_SYNC_CHANGE_VALUE = 535;
    public static final int DIALOG_CUSTOM_LIST_CONFIRMATION_VALUE = 529;
    public static final int DIALOG_DARK_UI_INFO_VALUE = 1740;
    public static final int DIALOG_DATE_PICKER_VALUE = 607;
    public static final int DIALOG_DELETE_SIM_CONFIRMATION_VALUE = 1713;
    public static final int DIALOG_DELETE_SIM_PROGRESS_VALUE = 1714;
    public static final int DIALOG_DISABLE_DEVELOPMENT_OPTIONS_VALUE = 1591;
    public static final int DIALOG_DISABLE_NOTIFICATION_ACCESS_VALUE = 552;
    public static final int DIALOG_ENABLE_ADB_VALUE = 1222;
    public static final int DIALOG_ENABLE_DEVELOPMENT_OPTIONS_VALUE = 1219;
    public static final int DIALOG_ENABLE_OEM_UNLOCKING_VALUE = 1220;
    public static final int DIALOG_ENCRYPTION_INTERSTITIAL_ACCESSIBILITY_VALUE = 581;
    public static final int DIALOG_FACE_ERROR_VALUE = 1510;
    public static final int DIALOG_FACE_REMOVE_VALUE = 1693;
    public static final int DIALOG_FINGERPINT_DELETE_LAST_VALUE = 571;
    public static final int DIALOG_FINGERPINT_EDIT_VALUE = 570;
    public static final int DIALOG_FINGERPINT_ERROR_VALUE = 569;
    public static final int DIALOG_FINGERPRINT_ICON_TOUCH_VALUE = 568;
    public static final int DIALOG_FINGERPRINT_SKIP_SETUP_VALUE = 573;
    public static final int DIALOG_FIRMWARE_VERSION_VALUE = 1247;
    public static final int DIALOG_FRP_VALUE = 528;
    public static final int DIALOG_HIGH_POWER_DETAILS_VALUE = 540;
    public static final int DIALOG_IMEI_INFO_VALUE = 1240;
    public static final int DIALOG_KEYBOARD_LAYOUT_VALUE = 541;
    public static final int DIALOG_LEGACY_VPN_CONFIG_VALUE = 545;
    public static final int DIALOG_LOG_PERSIST_VALUE = 1225;
    public static final int DIALOG_MANAGE_MOBILE_PLAN_VALUE = 609;
    public static final int DIALOG_NIGHT_DISPLAY_SET_END_TIME_VALUE = 589;
    public static final int DIALOG_NIGHT_DISPLAY_SET_START_TIME_VALUE = 588;
    public static final int DIALOG_OEM_LOCK_INFO_VALUE = 1238;
    public static final int DIALOG_OWNER_INFO_SETTINGS_VALUE = 531;
    public static final int DIALOG_PREFERRED_SIM_PICKER_VALUE = 1709;
    public static final int DIALOG_PROXY_SELECTOR_ERROR_VALUE = 574;
    public static final int DIALOG_REMOVE_USER_VALUE = 534;
    public static final int DIALOG_RUNNIGN_SERVICE_VALUE = 536;
    public static final int DIALOG_SERVICE_ACCESS_WARNING_VALUE = 557;
    public static final int DIALOG_SETTINGS_HARDWARE_INFO_VALUE = 862;
    public static final int DIALOG_SIM_LIST_VALUE = 1707;
    public static final int DIALOG_SIM_STATUS_VALUE = 1246;
    public static final int DIALOG_STORAGE_CLEAR_CACHE_VALUE = 564;
    public static final int DIALOG_STORAGE_OTHER_INFO_VALUE = 566;
    public static final int DIALOG_STORAGE_SYSTEM_INFO_VALUE = 565;
    public static final int DIALOG_STORAGE_USER_INFO_VALUE = 567;
    public static final int DIALOG_TIME_PICKER_VALUE = 608;
    public static final int DIALOG_UNIFICATION_CONFIRMATION_VALUE = 532;
    public static final int DIALOG_UNIFY_SOUND_SETTINGS_VALUE = 553;
    public static final int DIALOG_USER_ADD_VALUE = 595;
    public static final int DIALOG_USER_CANNOT_MANAGE_VALUE = 594;
    public static final int DIALOG_USER_CHOOSE_TYPE_VALUE = 598;
    public static final int DIALOG_USER_CONFIRM_EXIT_GUEST_VALUE = 600;
    public static final int DIALOG_USER_CREDENTIAL_VALUE = 533;
    public static final int DIALOG_USER_EDIT_PROFILE_VALUE = 601;
    public static final int DIALOG_USER_EDIT_VALUE = 590;
    public static final int DIALOG_USER_ENABLE_CALLING_AND_SMS_VALUE = 593;
    public static final int DIALOG_USER_ENABLE_CALLING_VALUE = 592;
    public static final int DIALOG_USER_NEED_LOCKSCREEN_VALUE = 599;
    public static final int DIALOG_USER_REMOVE_VALUE = 591;
    public static final int DIALOG_USER_SETUP_PROFILE_VALUE = 597;
    public static final int DIALOG_USER_SETUP_VALUE = 596;
    public static final int DIALOG_VOLUME_FORGET_VALUE = 559;
    public static final int DIALOG_VOLUME_FORMAT_VALUE = 1375;
    public static final int DIALOG_VOLUME_INIT_VALUE = 561;
    public static final int DIALOG_VOLUME_RENAME_VALUE = 563;
    public static final int DIALOG_VOLUME_UNMOUNT_VALUE = 562;
    public static final int DIALOG_VPN_APP_CONFIG_VALUE = 546;
    public static final int DIALOG_VPN_CANNOT_CONNECT_VALUE = 547;
    public static final int DIALOG_VPN_REPLACE_EXISTING_VALUE = 548;
    public static final int DIALOG_WIFI_AP_EDIT_VALUE = 603;
    public static final int DIALOG_WIFI_P2P_CANCEL_CONNECT_VALUE = 576;
    public static final int DIALOG_WIFI_P2P_DELETE_GROUP_VALUE = 578;
    public static final int DIALOG_WIFI_P2P_DISCONNECT_VALUE = 575;
    public static final int DIALOG_WIFI_P2P_RENAME_VALUE = 577;
    public static final int DIALOG_WIFI_SAVED_AP_EDIT_VALUE = 602;
    public static final int DIALOG_WIFI_SCAN_MODE_VALUE = 543;
    public static final int DIALOG_WIFI_WRITE_NFC_VALUE = 606;
    public static final int DIALOG_ZEN_ACCESS_GRANT_VALUE = 554;
    public static final int DIALOG_ZEN_ACCESS_REVOKE_VALUE = 555;
    public static final int DIALOG_ZEN_TIMEPICKER_VALUE = 556;
    public static final int DISPLAY_SCREEN_ZOOM_VALUE = 339;
    public static final int DISPLAY_VALUE = 46;
    public static final int DREAM_VALUE = 47;
    public static final int ENABLE_VIRTUAL_KEYBOARDS_VALUE = 347;
    public static final int ENCRYPTION_AND_CREDENTIAL_VALUE = 846;
    public static final int ENCRYPTION_VALUE = 48;
    public static final int ENTERPRISE_PRIVACY_DEFAULT_APPS_VALUE = 940;
    public static final int ENTERPRISE_PRIVACY_INSTALLED_APPS_VALUE = 938;
    public static final int ENTERPRISE_PRIVACY_PERMISSIONS_VALUE = 939;
    public static final int ENTERPRISE_PRIVACY_SETTINGS_VALUE = 628;
    public static final int FACE_ENROLL_ENROLLING_VALUE = 1507;
    public static final int FACE_ENROLL_FINISHED_VALUE = 1508;
    public static final int FACE_ENROLL_INTRO_VALUE = 1506;
    public static final int FACE_ENROLL_PREVIEW_VALUE = 1554;
    public static final int FACE_ENROLL_SIDECAR_VALUE = 1509;
    public static final int FACE_VALUE = 1511;
    public static final int FINGERPRINT_AUTHENTICATE_SIDECAR_VALUE = 1221;
    public static final int FINGERPRINT_ENROLLING_SETUP_VALUE = 246;
    public static final int FINGERPRINT_ENROLLING_VALUE = 240;
    public static final int FINGERPRINT_ENROLL_FINISH_SETUP_VALUE = 248;
    public static final int FINGERPRINT_ENROLL_FINISH_VALUE = 242;
    public static final int FINGERPRINT_ENROLL_INTRO_SETUP_VALUE = 249;
    public static final int FINGERPRINT_ENROLL_INTRO_VALUE = 243;
    public static final int FINGERPRINT_ENROLL_SIDECAR_VALUE = 245;
    public static final int FINGERPRINT_FIND_SENSOR_SETUP_VALUE = 247;
    public static final int FINGERPRINT_FIND_SENSOR_VALUE = 241;
    public static final int FINGERPRINT_REMOVE_SIDECAR_VALUE = 934;
    public static final int FINGERPRINT_VALUE = 49;
    public static final int FUELGAUGE_BATTERY_HISTORY_DETAIL_VALUE = 51;
    public static final int FUELGAUGE_BATTERY_SAVER_VALUE = 52;
    public static final int FUELGAUGE_BATTERY_TIP_DIALOG_VALUE = 1323;
    public static final int FUELGAUGE_INACTIVE_APPS_VALUE = 238;
    public static final int FUELGAUGE_POWER_USAGE_DETAIL_VALUE = 53;
    public static final int FUELGAUGE_POWER_USAGE_SUMMARY_V2_VALUE = 1263;
    public static final int FUELGAUGE_RESTRICTED_APP_DETAILS_VALUE = 1285;
    public static final int FUELGAUGE_SMART_BATTERY_VALUE = 1281;
    public static final int GENTLE_NOTIFICATIONS_SCREEN_VALUE = 1715;
    public static final int GLOBAL_ACTIONS_PANEL_SETTINGS_VALUE = 1728;
    public static final int ICC_LOCK_VALUE = 56;
    public static final int INPUTMETHOD_KEYBOARD_VALUE = 58;
    public static final int INPUTMETHOD_SPELL_CHECKERS_VALUE = 59;
    public static final int INPUTMETHOD_SUBTYPE_ENABLER_VALUE = 60;
    public static final int INPUTMETHOD_USER_DICTIONARY_ADD_WORD_VALUE = 62;
    public static final int INPUTMETHOD_USER_DICTIONARY_VALUE = 61;
    public static final int LOCATION_SCANNING_VALUE = 131;
    public static final int LOCATION_VALUE = 63;
    public static final int LOCK_SCREEN_NOTIFICATION_CONTENT_VALUE = 1584;
    public static final int MANAGE_APPLICATIONS_NOTIFICATIONS_VALUE = 133;
    public static final int MANAGE_APPLICATIONS_VALUE = 65;
    public static final int MANAGE_DOMAIN_URLS_VALUE = 143;
    public static final int MANAGE_EXTERNAL_SOURCES_VALUE = 808;
    public static final int MASTER_CLEAR_CONFIRM_VALUE = 67;
    public static final int MASTER_CLEAR_VALUE = 66;
    public static final int MOBILE_DATA_DIALOG_VALUE = 1582;
    public static final int MOBILE_NETWORK_LIST_VALUE = 1627;
    public static final int MOBILE_NETWORK_RENAME_DIALOG_VALUE = 1642;
    public static final int MOBILE_NETWORK_SELECT_VALUE = 1581;
    public static final int MOBILE_NETWORK_VALUE = 1571;
    public static final int MOBILE_ROAMING_DIALOG_VALUE = 1583;
    public static final int MODULE_LICENSES_DASHBOARD_VALUE = 1746;
    public static final int NFC_BEAM_VALUE = 69;
    public static final int NFC_PAYMENT_VALUE = 70;
    public static final int NIGHT_DISPLAY_SETTINGS_VALUE = 488;
    public static final int NOTIFICATION_ACCESS_VALUE = 179;
    public static final int NOTIFICATION_APP_NOTIFICATION_VALUE = 72;
    public static final int NOTIFICATION_CHANNEL_GROUP_VALUE = 1218;
    public static final int NOTIFICATION_REDACTION_VALUE = 74;
    public static final int NOTIFICATION_STATION_VALUE = 75;
    public static final int NOTIFICATION_TOPIC_NOTIFICATION_VALUE = 265;
    public static final int NOTIFICATION_ZEN_MODE_ACCESS_VALUE = 180;
    public static final int NOTIFICATION_ZEN_MODE_AUTOMATION_VALUE = 142;
    public static final int NOTIFICATION_ZEN_MODE_DELETE_RULE_DIALOG_VALUE = 1266;
    public static final int NOTIFICATION_ZEN_MODE_DURATION_DIALOG_VALUE = 1341;
    public static final int NOTIFICATION_ZEN_MODE_ENABLE_DIALOG_VALUE = 1286;
    public static final int NOTIFICATION_ZEN_MODE_EVENT_RULE_VALUE = 146;
    public static final int NOTIFICATION_ZEN_MODE_OVERRIDING_APPS_VALUE = 1588;
    public static final int NOTIFICATION_ZEN_MODE_OVERRIDING_APP_VALUE = 1589;
    public static final int NOTIFICATION_ZEN_MODE_PRIORITY_VALUE = 141;
    public static final int NOTIFICATION_ZEN_MODE_RULE_NAME_DIALOG_VALUE = 1269;
    public static final int NOTIFICATION_ZEN_MODE_RULE_SELECTION_DIALOG_VALUE = 1270;
    public static final int NOTIFICATION_ZEN_MODE_SCHEDULE_RULE_VALUE = 144;
    public static final int NOTIFICATION_ZEN_MODE_VALUE = 76;
    public static final int PAGE_ATHNP_VALUE = 1673;
    public static final int PAGE_ATSAP_VALUE = 1671;
    public static final int PAGE_ATSCP_VALUE = 1672;
    public static final int PAGE_ATSII_VALUE = 1668;
    public static final int PAGE_ATSSI_VALUE = 1667;
    public static final int PAGE_ATSSP_VALUE = 1670;
    public static final int PAGE_ATUS_VALUE = 1669;
    public static final int PAGE_UNKNOWN_VALUE = 0;
    public static final int PANEL_INTERNET_CONNECTIVITY_VALUE = 1654;
    public static final int PANEL_MEDIA_OUTPUT_VALUE = 1657;
    public static final int PANEL_NFC_VALUE = 1656;
    public static final int PANEL_VOLUME_VALUE = 1655;
    public static final int PANEL_WIFI_VALUE = 1687;
    public static final int PHYSICAL_KEYBOARDS_VALUE = 346;
    public static final int PREMIUM_SMS_ACCESS_VALUE = 388;
    public static final int PREVIOUSLY_CONNECTED_DEVICES_VALUE = 1370;
    public static final int PRINT_JOB_SETTINGS_VALUE = 78;
    public static final int PRINT_SERVICE_SETTINGS_VALUE = 79;
    public static final int PRINT_SETTINGS_VALUE = 80;
    public static final int PRIVACY_VALUE = 81;
    public static final int PROCESS_STATS_SUMMARY_VALUE = 202;
    public static final int PROXY_SELECTOR_VALUE = 82;
    public static final int RESET_DASHBOARD_VALUE = 924;
    public static final int RESET_NETWORK_CONFIRM_VALUE = 84;
    public static final int RESET_NETWORK_VALUE = 83;
    public static final int RUNNING_SERVICES_VALUE = 404;
    public static final int RUNNING_SERVICE_DETAILS_VALUE = 85;
    public static final int SCREEN_LOCK_SETTINGS_VALUE = 1265;
    public static final int SCREEN_PINNING_VALUE = 86;
    public static final int SECURITY_VALUE = 87;
    public static final int SETTINGS_ADAPTIVE_SLEEP_VALUE = 1628;
    public static final int SETTINGS_APP_NOTIF_CATEGORY_VALUE = 748;
    public static final int SETTINGS_ASSIST_GESTURE_VALUE = 996;
    public static final int SETTINGS_AUTO_BRIGHTNESS_VALUE = 1381;
    public static final int SETTINGS_AWARE_DISPLAY_VALUE = 1750;
    public static final int SETTINGS_AWARE_VALUE = 1632;
    public static final int SETTINGS_CHOOSE_LOCK_DIALOG_VALUE = 990;
    public static final int SETTINGS_CONDITION_AIRPLANE_MODE_VALUE = 377;
    public static final int SETTINGS_CONDITION_BACKGROUND_DATA_VALUE = 378;
    public static final int SETTINGS_CONDITION_BATTERY_SAVER_VALUE = 379;
    public static final int SETTINGS_CONDITION_CELLULAR_DATA_VALUE = 380;
    public static final int SETTINGS_CONDITION_DEVICE_MUTED_VALUE = 1368;
    public static final int SETTINGS_CONDITION_DEVICE_VIBRATE_VALUE = 1369;
    public static final int SETTINGS_CONDITION_DND_VALUE = 381;
    public static final int SETTINGS_CONDITION_GRAYSCALE_MODE_VALUE = 1683;
    public static final int SETTINGS_CONDITION_HOTSPOT_VALUE = 382;
    public static final int SETTINGS_CONDITION_NIGHT_DISPLAY_VALUE = 492;
    public static final int SETTINGS_CONDITION_WORK_MODE_VALUE = 383;
    public static final int SETTINGS_CONNECTED_DEVICE_CATEGORY_VALUE = 747;
    public static final int SETTINGS_CREATE_SHORTCUT_VALUE = 1503;
    public static final int SETTINGS_FEATURE_FLAGS_DASHBOARD_VALUE = 1217;
    public static final int SETTINGS_FINANCIAL_APPS_SMS_ACCESS_VALUE = 1597;
    public static final int SETTINGS_GAME_DRIVER_DASHBOARD_VALUE = 1613;
    public static final int SETTINGS_GESTURES_VALUE = 459;
    public static final int SETTINGS_GESTURE_DOUBLE_TAP_POWER_VALUE = 752;
    public static final int SETTINGS_GESTURE_DOUBLE_TAP_SCREEN_VALUE = 754;
    public static final int SETTINGS_GESTURE_DOUBLE_TWIST_VALUE = 755;
    public static final int SETTINGS_GESTURE_NAV_BACK_SENSITIVITY_DLG_VALUE = 1748;
    public static final int SETTINGS_GESTURE_NAV_NOT_AVAILABLE_DLG_VALUE = 1747;
    public static final int SETTINGS_GESTURE_PICKUP_VALUE = 753;
    public static final int SETTINGS_GESTURE_SILENCE_VALUE = 1625;
    public static final int SETTINGS_GESTURE_SKIP_VALUE = 1624;
    public static final int SETTINGS_GESTURE_SWIPE_TO_NOTIFICATION_VALUE = 751;
    public static final int SETTINGS_GESTURE_SWIPE_UP_VALUE = 1374;
    public static final int SETTINGS_GESTURE_TAP_SCREEN_VALUE = 1626;
    public static final int SETTINGS_GESTURE_TAP_VALUE = 1751;
    public static final int SETTINGS_GESTURE_WAKE_LOCK_SCREEN_VALUE = 1557;
    public static final int SETTINGS_GESTURE_WAKE_SCREEN_VALUE = 1570;
    public static final int SETTINGS_HOMEPAGE_VALUE = 1502;
    public static final int SETTINGS_LANGUAGE_CATEGORY_VALUE = 750;
    public static final int SETTINGS_LOCK_SCREEN_PREFERENCES_VALUE = 882;
    public static final int SETTINGS_MANAGE_PICTURE_IN_PICTURE_VALUE = 812;
    public static final int SETTINGS_NETWORK_CATEGORY_VALUE = 746;
    public static final int SETTINGS_NETWORK_SCORER_VALUE = 861;
    public static final int SETTINGS_PREVENT_RINGING_VALUE = 1360;
    public static final int SETTINGS_STORAGE_CATEGORY_VALUE = 745;
    public static final int SETTINGS_STORAGE_PROFILE_VALUE = 845;
    public static final int SETTINGS_SYSTEM_CATEGORY_VALUE = 744;
    public static final int SETTINGS_WIFI_ADD_NETWORK_VALUE = 1556;
    public static final int SETTINGS_WIFI_DPP_CONFIGURATOR_VALUE = 1595;
    public static final int SETTINGS_WIFI_DPP_ENROLLEE_VALUE = 1596;
    public static final int SETTINGS_ZEN_NOTIFICATIONS_VALUE = 1400;
    public static final int SETTINGS_ZEN_ONBOARDING_VALUE = 1380;
    public static final int SETTINGS_ZONE_PICKER_FIXED_OFFSET_VALUE = 1357;
    public static final int SETTINGS_ZONE_PICKER_REGION_VALUE = 1355;
    public static final int SETTINGS_ZONE_PICKER_TIME_ZONE_VALUE = 1356;
    public static final int SET_NEW_PASSWORD_ACTIVITY_VALUE = 1644;
    public static final int SIM_VALUE = 88;
    public static final int SLICE_VALUE = 1401;
    public static final int SOUND_VALUE = 336;
    public static final int SPECIAL_ACCESS_VALUE = 351;
    public static final int STORAGE_FILES_VALUE = 841;
    public static final int STORAGE_FREE_UP_SPACE_NOW_VALUE = 840;
    public static final int STORAGE_MANAGER_SETTINGS_VALUE = 458;
    public static final int SUW_ACCESSIBILITY_DISPLAY_SIZE_VALUE = 370;
    public static final int SUW_ACCESSIBILITY_FONT_SIZE_VALUE = 369;
    public static final int SUW_ACCESSIBILITY_TOGGLE_SCREEN_MAGNIFICATION_VALUE = 368;
    public static final int SUW_ACCESSIBILITY_TOGGLE_SCREEN_READER_VALUE = 371;
    public static final int SUW_ACCESSIBILITY_TOGGLE_SELECT_TO_SPEAK_VALUE = 817;
    public static final int SUW_ACCESSIBILITY_VALUE = 367;
    public static final int SYSTEM_ALERT_WINDOW_APPS_VALUE = 221;
    public static final int TESTING_VALUE = 89;
    public static final int TETHER_VALUE = 90;
    public static final int TOP_LEVEL_PRIVACY_VALUE = 1587;
    public static final int TRUSTED_CREDENTIALS_VALUE = 92;
    public static final int TRUST_AGENT_VALUE = 91;
    public static final int TTS_ENGINE_SETTINGS_VALUE = 93;
    public static final int TTS_TEXT_TO_SPEECH_VALUE = 94;
    public static final int USAGE_ACCESS_VALUE = 95;
    public static final int USB_DEFAULT_VALUE = 1312;
    public static final int USB_DEVICE_DETAILS_VALUE = 1291;
    public static final int USERS_APP_RESTRICTIONS_VALUE = 97;
    public static final int USER_CREDENTIALS_VALUE = 285;
    public static final int USER_DETAILS_VALUE = 98;
    public static final int USER_DICTIONARY_SETTINGS_VALUE = 514;
    public static final int USER_LOCALE_LIST_VALUE = 344;
    public static final int USER_VALUE = 96;
    public static final int VIRTUAL_KEYBOARDS_VALUE = 345;
    public static final int VPN_VALUE = 100;
    public static final int VR_DISPLAY_PREFERENCE_VALUE = 921;
    public static final int VR_MANAGE_LISTENERS_VALUE = 334;
    public static final int WALLPAPER_TYPE_VALUE = 101;
    public static final int WEBVIEW_IMPLEMENTATION_VALUE = 405;
    public static final int WFD_WIFI_DISPLAY_VALUE = 102;
    public static final int WIFI_CALLING_FOR_SUB_VALUE = 1230;
    public static final int WIFI_CALLING_VALUE = 105;
    public static final int WIFI_NETWORK_DETAILS_VALUE = 849;
    public static final int WIFI_P2P_VALUE = 109;
    public static final int WIFI_SAVED_ACCESS_POINTS_VALUE = 106;
    public static final int WIFI_SCANNING_NEEDED_DIALOG_VALUE = 1373;
    public static final int WIFI_TETHER_SETTINGS_VALUE = 1014;
    public static final int WIFI_VALUE = 103;
    public static final int ZEN_ACCESS_DETAIL_VALUE = 1692;
    public static final int ZEN_CUSTOM_RULE_CALLS_VALUE = 1611;
    public static final int ZEN_CUSTOM_RULE_DEFAULT_SETTINGS_VALUE = 1606;
    public static final int ZEN_CUSTOM_RULE_MESSAGES_VALUE = 1610;
    public static final int ZEN_CUSTOM_RULE_NOTIFICATION_RESTRICTIONS_VALUE = 1608;
    public static final int ZEN_CUSTOM_RULE_SETTINGS_VALUE = 1604;
    public static final int ZEN_CUSTOM_RULE_SOUND_SETTINGS_VALUE = 1605;
    public static final int ZEN_CUSTOM_RULE_VIS_EFFECTS_VALUE = 1609;
    public static final int ZEN_CUSTOM_SETTINGS_DIALOG_VALUE = 1612;
    public static final int ZEN_WHAT_TO_BLOCK_VALUE = 1339;
    public static final int ZONE_PICKER_VALUE = 515;
    private static final Internal.EnumLiteMap<PageId> internalValueMap = new Internal.EnumLiteMap<PageId>() {
        /* class android.app.settings.PageId.AnonymousClass1 */

        @Override // com.google.protobuf.Internal.EnumLiteMap
        public PageId findValueByNumber(int number) {
            return PageId.forNumber(number);
        }
    };
    private final int value;

    @Override // com.google.protobuf.Internal.EnumLite
    public final int getNumber() {
        return this.value;
    }

    @Deprecated
    public static PageId valueOf(int value2) {
        return forNumber(value2);
    }

    public static PageId forNumber(int value2) {
        if (value2 == 0) {
            return PAGE_UNKNOWN;
        }
        if (value2 == 2) {
            return ACCESSIBILITY;
        }
        if (value2 == 3) {
            return ACCESSIBILITY_CAPTION_PROPERTIES;
        }
        if (value2 == 4) {
            return ACCESSIBILITY_SERVICE;
        }
        if (value2 == 5) {
            return ACCESSIBILITY_TOGGLE_DALTONIZER;
        }
        if (value2 == 6) {
            return ACCESSIBILITY_TOGGLE_GLOBAL_GESTURE;
        }
        if (value2 != 7) {
            if (value2 == 12) {
                return APN;
            }
            if (value2 == 13) {
                return APN_EDITOR;
            }
            if (value2 == 69) {
                return NFC_BEAM;
            }
            if (value2 == 70) {
                return NFC_PAYMENT;
            }
            switch (value2) {
                case 7:
                    break;
                case 8:
                    return ACCOUNT;
                case 9:
                    return ACCOUNTS_ACCOUNT_SYNC;
                case 10:
                    return ACCOUNTS_CHOOSE_ACCOUNT_ACTIVITY;
                case 17:
                    return APPLICATIONS_APP_LAUNCH;
                case 23:
                    return APPLICATIONS_PROCESS_STATS_UI;
                case 25:
                    return BLUETOOTH_DEVICE_PICKER;
                case 35:
                    return DASHBOARD_SUMMARY;
                case 42:
                    return DEVICEINFO_STORAGE;
                case 56:
                    return ICC_LOCK;
                case 72:
                    return NOTIFICATION_APP_NOTIFICATION;
                case 74:
                    return NOTIFICATION_REDACTION;
                case 75:
                    return NOTIFICATION_STATION;
                case 76:
                    return NOTIFICATION_ZEN_MODE;
                case 78:
                    return PRINT_JOB_SETTINGS;
                case 79:
                    return PRINT_SERVICE_SETTINGS;
                case 80:
                    return PRINT_SETTINGS;
                case 81:
                    return PRIVACY;
                case 82:
                    return PROXY_SELECTOR;
                case 83:
                    return RESET_NETWORK;
                case 84:
                    return RESET_NETWORK_CONFIRM;
                case 85:
                    return RUNNING_SERVICE_DETAILS;
                case 86:
                    return SCREEN_PINNING;
                case 87:
                    return SECURITY;
                case 88:
                    return SIM;
                case 89:
                    return TESTING;
                case 90:
                    return TETHER;
                case 91:
                    return TRUST_AGENT;
                case 92:
                    return TRUSTED_CREDENTIALS;
                case 93:
                    return TTS_ENGINE_SETTINGS;
                case 94:
                    return TTS_TEXT_TO_SPEECH;
                case 95:
                    return USAGE_ACCESS;
                case 96:
                    return USER;
                case 97:
                    return USERS_APP_RESTRICTIONS;
                case 98:
                    return USER_DETAILS;
                case 100:
                    return VPN;
                case 101:
                    return WALLPAPER_TYPE;
                case 102:
                    return WFD_WIFI_DISPLAY;
                case 103:
                    return WIFI;
                case 105:
                    return WIFI_CALLING;
                case 106:
                    return WIFI_SAVED_ACCESS_POINTS;
                case 109:
                    return WIFI_P2P;
                case 130:
                    return APPLICATIONS_ADVANCED;
                case 131:
                    return LOCATION_SCANNING;
                case 133:
                    return MANAGE_APPLICATIONS_NOTIFICATIONS;
                case 141:
                    return NOTIFICATION_ZEN_MODE_PRIORITY;
                case 142:
                    return NOTIFICATION_ZEN_MODE_AUTOMATION;
                case 143:
                    return MANAGE_DOMAIN_URLS;
                case 144:
                    return NOTIFICATION_ZEN_MODE_SCHEDULE_RULE;
                case 146:
                    return NOTIFICATION_ZEN_MODE_EVENT_RULE;
                case 179:
                    return NOTIFICATION_ACCESS;
                case 180:
                    return NOTIFICATION_ZEN_MODE_ACCESS;
                case 182:
                    return APPLICATIONS_STORAGE_APPS;
                case 183:
                    return APPLICATIONS_USAGE_ACCESS_DETAIL;
                case 184:
                    return APPLICATIONS_HIGH_POWER_APPS;
                case 201:
                    return APPLICATIONS_MANAGE_ASSIST;
                case PROCESS_STATS_SUMMARY_VALUE:
                    return PROCESS_STATS_SUMMARY;
                case SYSTEM_ALERT_WINDOW_APPS_VALUE:
                    return SYSTEM_ALERT_WINDOW_APPS;
                case ABOUT_LEGAL_SETTINGS_VALUE:
                    return ABOUT_LEGAL_SETTINGS;
                case FUELGAUGE_INACTIVE_APPS_VALUE:
                    return FUELGAUGE_INACTIVE_APPS;
                case FINGERPRINT_ENROLLING_VALUE:
                    return FINGERPRINT_ENROLLING;
                case FINGERPRINT_FIND_SENSOR_VALUE:
                    return FINGERPRINT_FIND_SENSOR;
                case FINGERPRINT_ENROLL_FINISH_VALUE:
                    return FINGERPRINT_ENROLL_FINISH;
                case FINGERPRINT_ENROLL_INTRO_VALUE:
                    return FINGERPRINT_ENROLL_INTRO;
                case FINGERPRINT_ENROLL_SIDECAR_VALUE:
                    return FINGERPRINT_ENROLL_SIDECAR;
                case FINGERPRINT_ENROLLING_SETUP_VALUE:
                    return FINGERPRINT_ENROLLING_SETUP;
                case FINGERPRINT_FIND_SENSOR_SETUP_VALUE:
                    return FINGERPRINT_FIND_SENSOR_SETUP;
                case FINGERPRINT_ENROLL_FINISH_SETUP_VALUE:
                    return FINGERPRINT_ENROLL_FINISH_SETUP;
                case 249:
                    return FINGERPRINT_ENROLL_INTRO_SETUP;
                case BACKGROUND_CHECK_SUMMARY_VALUE:
                    return BACKGROUND_CHECK_SUMMARY;
                case NOTIFICATION_TOPIC_NOTIFICATION_VALUE:
                    return NOTIFICATION_TOPIC_NOTIFICATION;
                case USER_CREDENTIALS_VALUE:
                    return USER_CREDENTIALS;
                case VR_MANAGE_LISTENERS_VALUE:
                    return VR_MANAGE_LISTENERS;
                case ACCESSIBILITY_TOGGLE_AUTOCLICK_VALUE:
                    return ACCESSIBILITY_TOGGLE_AUTOCLICK;
                case SOUND_VALUE:
                    return SOUND;
                case CONFIGURE_NOTIFICATION_VALUE:
                    return CONFIGURE_NOTIFICATION;
                case CONFIGURE_WIFI_VALUE:
                    return CONFIGURE_WIFI;
                case DISPLAY_SCREEN_ZOOM_VALUE:
                    return DISPLAY_SCREEN_ZOOM;
                case ACCESSIBILITY_FONT_SIZE_VALUE:
                    return ACCESSIBILITY_FONT_SIZE;
                case DATA_USAGE_LIST_VALUE:
                    return DATA_USAGE_LIST;
                case BILLING_CYCLE_VALUE:
                    return BILLING_CYCLE;
                case APP_DATA_USAGE_VALUE:
                    return APP_DATA_USAGE;
                case USER_LOCALE_LIST_VALUE:
                    return USER_LOCALE_LIST;
                case VIRTUAL_KEYBOARDS_VALUE:
                    return VIRTUAL_KEYBOARDS;
                case PHYSICAL_KEYBOARDS_VALUE:
                    return PHYSICAL_KEYBOARDS;
                case ENABLE_VIRTUAL_KEYBOARDS_VALUE:
                    return ENABLE_VIRTUAL_KEYBOARDS;
                case DATA_SAVER_SUMMARY_VALUE:
                    return DATA_SAVER_SUMMARY;
                case DATA_USAGE_UNRESTRICTED_ACCESS_VALUE:
                    return DATA_USAGE_UNRESTRICTED_ACCESS;
                case SPECIAL_ACCESS_VALUE:
                    return SPECIAL_ACCESS;
                case SUW_ACCESSIBILITY_VALUE:
                    return SUW_ACCESSIBILITY;
                case SUW_ACCESSIBILITY_TOGGLE_SCREEN_MAGNIFICATION_VALUE:
                    return SUW_ACCESSIBILITY_TOGGLE_SCREEN_MAGNIFICATION;
                case SUW_ACCESSIBILITY_FONT_SIZE_VALUE:
                    return SUW_ACCESSIBILITY_FONT_SIZE;
                case SUW_ACCESSIBILITY_DISPLAY_SIZE_VALUE:
                    return SUW_ACCESSIBILITY_DISPLAY_SIZE;
                case SUW_ACCESSIBILITY_TOGGLE_SCREEN_READER_VALUE:
                    return SUW_ACCESSIBILITY_TOGGLE_SCREEN_READER;
                case SETTINGS_CONDITION_AIRPLANE_MODE_VALUE:
                    return SETTINGS_CONDITION_AIRPLANE_MODE;
                case SETTINGS_CONDITION_BACKGROUND_DATA_VALUE:
                    return SETTINGS_CONDITION_BACKGROUND_DATA;
                case SETTINGS_CONDITION_BATTERY_SAVER_VALUE:
                    return SETTINGS_CONDITION_BATTERY_SAVER;
                case SETTINGS_CONDITION_CELLULAR_DATA_VALUE:
                    return SETTINGS_CONDITION_CELLULAR_DATA;
                case SETTINGS_CONDITION_DND_VALUE:
                    return SETTINGS_CONDITION_DND;
                case SETTINGS_CONDITION_HOTSPOT_VALUE:
                    return SETTINGS_CONDITION_HOTSPOT;
                case SETTINGS_CONDITION_WORK_MODE_VALUE:
                    return SETTINGS_CONDITION_WORK_MODE;
                case PREMIUM_SMS_ACCESS_VALUE:
                    return PREMIUM_SMS_ACCESS;
                case ACCOUNTS_WORK_PROFILE_SETTINGS_VALUE:
                    return ACCOUNTS_WORK_PROFILE_SETTINGS;
                case CONVERT_FBE_VALUE:
                    return CONVERT_FBE;
                case CONVERT_FBE_CONFIRM_VALUE:
                    return CONVERT_FBE_CONFIRM;
                case RUNNING_SERVICES_VALUE:
                    return RUNNING_SERVICES;
                case WEBVIEW_IMPLEMENTATION_VALUE:
                    return WEBVIEW_IMPLEMENTATION;
                case STORAGE_MANAGER_SETTINGS_VALUE:
                    return STORAGE_MANAGER_SETTINGS;
                case SETTINGS_GESTURES_VALUE:
                    return SETTINGS_GESTURES;
                case NIGHT_DISPLAY_SETTINGS_VALUE:
                    return NIGHT_DISPLAY_SETTINGS;
                case SETTINGS_CONDITION_NIGHT_DISPLAY_VALUE:
                    return SETTINGS_CONDITION_NIGHT_DISPLAY;
                case USER_DICTIONARY_SETTINGS_VALUE:
                    return USER_DICTIONARY_SETTINGS;
                case ZONE_PICKER_VALUE:
                    return ZONE_PICKER;
                case DEVICE_ADMIN_SETTINGS_VALUE:
                    return DEVICE_ADMIN_SETTINGS;
                case DIALOG_FRP_VALUE:
                    return DIALOG_FRP;
                case DIALOG_CUSTOM_LIST_CONFIRMATION_VALUE:
                    return DIALOG_CUSTOM_LIST_CONFIRMATION;
                case DIALOG_APN_EDITOR_ERROR_VALUE:
                    return DIALOG_APN_EDITOR_ERROR;
                case DIALOG_OWNER_INFO_SETTINGS_VALUE:
                    return DIALOG_OWNER_INFO_SETTINGS;
                case DIALOG_UNIFICATION_CONFIRMATION_VALUE:
                    return DIALOG_UNIFICATION_CONFIRMATION;
                case DIALOG_USER_CREDENTIAL_VALUE:
                    return DIALOG_USER_CREDENTIAL;
                case DIALOG_REMOVE_USER_VALUE:
                    return DIALOG_REMOVE_USER;
                case DIALOG_CONFIRM_AUTO_SYNC_CHANGE_VALUE:
                    return DIALOG_CONFIRM_AUTO_SYNC_CHANGE;
                case DIALOG_RUNNIGN_SERVICE_VALUE:
                    return DIALOG_RUNNIGN_SERVICE;
                case DIALOG_BLUETOOTH_RENAME_VALUE:
                    return DIALOG_BLUETOOTH_RENAME;
                case DIALOG_HIGH_POWER_DETAILS_VALUE:
                    return DIALOG_HIGH_POWER_DETAILS;
                case DIALOG_KEYBOARD_LAYOUT_VALUE:
                    return DIALOG_KEYBOARD_LAYOUT;
                case DIALOG_WIFI_SCAN_MODE_VALUE:
                    return DIALOG_WIFI_SCAN_MODE;
                case DIALOG_LEGACY_VPN_CONFIG_VALUE:
                    return DIALOG_LEGACY_VPN_CONFIG;
                case DIALOG_VPN_APP_CONFIG_VALUE:
                    return DIALOG_VPN_APP_CONFIG;
                case DIALOG_VPN_CANNOT_CONNECT_VALUE:
                    return DIALOG_VPN_CANNOT_CONNECT;
                case DIALOG_VPN_REPLACE_EXISTING_VALUE:
                    return DIALOG_VPN_REPLACE_EXISTING;
                case DIALOG_BILLING_CYCLE_VALUE:
                    return DIALOG_BILLING_CYCLE;
                case DIALOG_BILLING_BYTE_LIMIT_VALUE:
                    return DIALOG_BILLING_BYTE_LIMIT;
                case DIALOG_BILLING_CONFIRM_LIMIT_VALUE:
                    return DIALOG_BILLING_CONFIRM_LIMIT;
                case DIALOG_DISABLE_NOTIFICATION_ACCESS_VALUE:
                    return DIALOG_DISABLE_NOTIFICATION_ACCESS;
                case DIALOG_UNIFY_SOUND_SETTINGS_VALUE:
                    return DIALOG_UNIFY_SOUND_SETTINGS;
                case DIALOG_ZEN_ACCESS_GRANT_VALUE:
                    return DIALOG_ZEN_ACCESS_GRANT;
                case DIALOG_ZEN_ACCESS_REVOKE_VALUE:
                    return DIALOG_ZEN_ACCESS_REVOKE;
                case DIALOG_ZEN_TIMEPICKER_VALUE:
                    return DIALOG_ZEN_TIMEPICKER;
                case DIALOG_SERVICE_ACCESS_WARNING_VALUE:
                    return DIALOG_SERVICE_ACCESS_WARNING;
                case DIALOG_APP_INFO_ACTION_VALUE:
                    return DIALOG_APP_INFO_ACTION;
                case DIALOG_VOLUME_FORGET_VALUE:
                    return DIALOG_VOLUME_FORGET;
                case DIALOG_VOLUME_INIT_VALUE:
                    return DIALOG_VOLUME_INIT;
                case DIALOG_VOLUME_UNMOUNT_VALUE:
                    return DIALOG_VOLUME_UNMOUNT;
                case DIALOG_VOLUME_RENAME_VALUE:
                    return DIALOG_VOLUME_RENAME;
                case DIALOG_STORAGE_CLEAR_CACHE_VALUE:
                    return DIALOG_STORAGE_CLEAR_CACHE;
                case DIALOG_STORAGE_SYSTEM_INFO_VALUE:
                    return DIALOG_STORAGE_SYSTEM_INFO;
                case DIALOG_STORAGE_OTHER_INFO_VALUE:
                    return DIALOG_STORAGE_OTHER_INFO;
                case DIALOG_STORAGE_USER_INFO_VALUE:
                    return DIALOG_STORAGE_USER_INFO;
                case DIALOG_FINGERPRINT_ICON_TOUCH_VALUE:
                    return DIALOG_FINGERPRINT_ICON_TOUCH;
                case DIALOG_FINGERPINT_ERROR_VALUE:
                    return DIALOG_FINGERPINT_ERROR;
                case DIALOG_FINGERPINT_EDIT_VALUE:
                    return DIALOG_FINGERPINT_EDIT;
                case DIALOG_FINGERPINT_DELETE_LAST_VALUE:
                    return DIALOG_FINGERPINT_DELETE_LAST;
                case DIALOG_FINGERPRINT_SKIP_SETUP_VALUE:
                    return DIALOG_FINGERPRINT_SKIP_SETUP;
                case DIALOG_PROXY_SELECTOR_ERROR_VALUE:
                    return DIALOG_PROXY_SELECTOR_ERROR;
                case DIALOG_WIFI_P2P_DISCONNECT_VALUE:
                    return DIALOG_WIFI_P2P_DISCONNECT;
                case DIALOG_WIFI_P2P_CANCEL_CONNECT_VALUE:
                    return DIALOG_WIFI_P2P_CANCEL_CONNECT;
                case DIALOG_WIFI_P2P_RENAME_VALUE:
                    return DIALOG_WIFI_P2P_RENAME;
                case DIALOG_WIFI_P2P_DELETE_GROUP_VALUE:
                    return DIALOG_WIFI_P2P_DELETE_GROUP;
                case DIALOG_APN_RESTORE_DEFAULT_VALUE:
                    return DIALOG_APN_RESTORE_DEFAULT;
                case DIALOG_ENCRYPTION_INTERSTITIAL_ACCESSIBILITY_VALUE:
                    return DIALOG_ENCRYPTION_INTERSTITIAL_ACCESSIBILITY;
                case DIALOG_ACCESSIBILITY_SERVICE_ENABLE_VALUE:
                    return DIALOG_ACCESSIBILITY_SERVICE_ENABLE;
                case DIALOG_ACCESSIBILITY_SERVICE_DISABLE_VALUE:
                    return DIALOG_ACCESSIBILITY_SERVICE_DISABLE;
                case DIALOG_ACCOUNT_SYNC_REMOVE_VALUE:
                    return DIALOG_ACCOUNT_SYNC_REMOVE;
                case DIALOG_ACCOUNT_SYNC_FAILED_REMOVAL_VALUE:
                    return DIALOG_ACCOUNT_SYNC_FAILED_REMOVAL;
                case DIALOG_ACCOUNT_SYNC_CANNOT_ONETIME_SYNC_VALUE:
                    return DIALOG_ACCOUNT_SYNC_CANNOT_ONETIME_SYNC;
                case DIALOG_NIGHT_DISPLAY_SET_START_TIME_VALUE:
                    return DIALOG_NIGHT_DISPLAY_SET_START_TIME;
                case DIALOG_NIGHT_DISPLAY_SET_END_TIME_VALUE:
                    return DIALOG_NIGHT_DISPLAY_SET_END_TIME;
                case DIALOG_USER_EDIT_VALUE:
                    return DIALOG_USER_EDIT;
                case DIALOG_USER_REMOVE_VALUE:
                    return DIALOG_USER_REMOVE;
                case DIALOG_USER_ENABLE_CALLING_VALUE:
                    return DIALOG_USER_ENABLE_CALLING;
                case DIALOG_USER_ENABLE_CALLING_AND_SMS_VALUE:
                    return DIALOG_USER_ENABLE_CALLING_AND_SMS;
                case DIALOG_USER_CANNOT_MANAGE_VALUE:
                    return DIALOG_USER_CANNOT_MANAGE;
                case DIALOG_USER_ADD_VALUE:
                    return DIALOG_USER_ADD;
                case DIALOG_USER_SETUP_VALUE:
                    return DIALOG_USER_SETUP;
                case DIALOG_USER_SETUP_PROFILE_VALUE:
                    return DIALOG_USER_SETUP_PROFILE;
                case DIALOG_USER_CHOOSE_TYPE_VALUE:
                    return DIALOG_USER_CHOOSE_TYPE;
                case DIALOG_USER_NEED_LOCKSCREEN_VALUE:
                    return DIALOG_USER_NEED_LOCKSCREEN;
                case DIALOG_USER_CONFIRM_EXIT_GUEST_VALUE:
                    return DIALOG_USER_CONFIRM_EXIT_GUEST;
                case DIALOG_USER_EDIT_PROFILE_VALUE:
                    return DIALOG_USER_EDIT_PROFILE;
                case DIALOG_WIFI_SAVED_AP_EDIT_VALUE:
                    return DIALOG_WIFI_SAVED_AP_EDIT;
                case DIALOG_WIFI_AP_EDIT_VALUE:
                    return DIALOG_WIFI_AP_EDIT;
                case DIALOG_WIFI_WRITE_NFC_VALUE:
                    return DIALOG_WIFI_WRITE_NFC;
                case DIALOG_DATE_PICKER_VALUE:
                    return DIALOG_DATE_PICKER;
                case DIALOG_TIME_PICKER_VALUE:
                    return DIALOG_TIME_PICKER;
                case DIALOG_MANAGE_MOBILE_PLAN_VALUE:
                    return DIALOG_MANAGE_MOBILE_PLAN;
                case BLUETOOTH_DIALOG_FRAGMENT_VALUE:
                    return BLUETOOTH_DIALOG_FRAGMENT;
                case ENTERPRISE_PRIVACY_SETTINGS_VALUE:
                    return ENTERPRISE_PRIVACY_SETTINGS;
                case SETTINGS_SYSTEM_CATEGORY_VALUE:
                    return SETTINGS_SYSTEM_CATEGORY;
                case SETTINGS_STORAGE_CATEGORY_VALUE:
                    return SETTINGS_STORAGE_CATEGORY;
                case SETTINGS_NETWORK_CATEGORY_VALUE:
                    return SETTINGS_NETWORK_CATEGORY;
                case SETTINGS_CONNECTED_DEVICE_CATEGORY_VALUE:
                    return SETTINGS_CONNECTED_DEVICE_CATEGORY;
                case SETTINGS_APP_NOTIF_CATEGORY_VALUE:
                    return SETTINGS_APP_NOTIF_CATEGORY;
                case SETTINGS_LANGUAGE_CATEGORY_VALUE:
                    return SETTINGS_LANGUAGE_CATEGORY;
                case SETTINGS_GESTURE_SWIPE_TO_NOTIFICATION_VALUE:
                    return SETTINGS_GESTURE_SWIPE_TO_NOTIFICATION;
                case SETTINGS_GESTURE_DOUBLE_TAP_POWER_VALUE:
                    return SETTINGS_GESTURE_DOUBLE_TAP_POWER;
                case SETTINGS_GESTURE_PICKUP_VALUE:
                    return SETTINGS_GESTURE_PICKUP;
                case SETTINGS_GESTURE_DOUBLE_TAP_SCREEN_VALUE:
                    return SETTINGS_GESTURE_DOUBLE_TAP_SCREEN;
                case SETTINGS_GESTURE_DOUBLE_TWIST_VALUE:
                    return SETTINGS_GESTURE_DOUBLE_TWIST;
                case DEFAULT_BROWSER_PICKER_VALUE:
                    return DEFAULT_BROWSER_PICKER;
                case DEFAULT_EMERGENCY_APP_PICKER_VALUE:
                    return DEFAULT_EMERGENCY_APP_PICKER;
                case DEFAULT_HOME_PICKER_VALUE:
                    return DEFAULT_HOME_PICKER;
                case DEFAULT_PHONE_PICKER_VALUE:
                    return DEFAULT_PHONE_PICKER;
                case DEFAULT_SMS_PICKER_VALUE:
                    return DEFAULT_SMS_PICKER;
                case DEFAULT_NOTIFICATION_ASSISTANT_VALUE:
                    return DEFAULT_NOTIFICATION_ASSISTANT;
                case DEFAULT_APP_PICKER_CONFIRMATION_DIALOG_VALUE:
                    return DEFAULT_APP_PICKER_CONFIRMATION_DIALOG;
                case DEFAULT_AUTOFILL_PICKER_VALUE:
                    return DEFAULT_AUTOFILL_PICKER;
                case MANAGE_EXTERNAL_SOURCES_VALUE:
                    return MANAGE_EXTERNAL_SOURCES;
                case SETTINGS_MANAGE_PICTURE_IN_PICTURE_VALUE:
                    return SETTINGS_MANAGE_PICTURE_IN_PICTURE;
                case SUW_ACCESSIBILITY_TOGGLE_SELECT_TO_SPEAK_VALUE:
                    return SUW_ACCESSIBILITY_TOGGLE_SELECT_TO_SPEAK;
                case BACKUP_SETTINGS_VALUE:
                    return BACKUP_SETTINGS;
                case APPLICATIONS_STORAGE_GAMES_VALUE:
                    return APPLICATIONS_STORAGE_GAMES;
                case APPLICATIONS_STORAGE_MUSIC_VALUE:
                    return APPLICATIONS_STORAGE_MUSIC;
                case STORAGE_FREE_UP_SPACE_NOW_VALUE:
                    return STORAGE_FREE_UP_SPACE_NOW;
                case STORAGE_FILES_VALUE:
                    return STORAGE_FILES;
                case DEFAULT_ASSIST_PICKER_VALUE:
                    return DEFAULT_ASSIST_PICKER;
                case DEFAULT_VOICE_INPUT_PICKER_VALUE:
                    return DEFAULT_VOICE_INPUT_PICKER;
                case SETTINGS_STORAGE_PROFILE_VALUE:
                    return SETTINGS_STORAGE_PROFILE;
                case ENCRYPTION_AND_CREDENTIAL_VALUE:
                    return ENCRYPTION_AND_CREDENTIAL;
                case WIFI_NETWORK_DETAILS_VALUE:
                    return WIFI_NETWORK_DETAILS;
                case SETTINGS_NETWORK_SCORER_VALUE:
                    return SETTINGS_NETWORK_SCORER;
                case DIALOG_SETTINGS_HARDWARE_INFO_VALUE:
                    return DIALOG_SETTINGS_HARDWARE_INFO;
                case SETTINGS_LOCK_SCREEN_PREFERENCES_VALUE:
                    return SETTINGS_LOCK_SCREEN_PREFERENCES;
                case VR_DISPLAY_PREFERENCE_VALUE:
                    return VR_DISPLAY_PREFERENCE;
                case ACCESSIBILITY_SCREEN_MAGNIFICATION_SETTINGS_VALUE:
                    return ACCESSIBILITY_SCREEN_MAGNIFICATION_SETTINGS;
                case RESET_DASHBOARD_VALUE:
                    return RESET_DASHBOARD;
                case FINGERPRINT_REMOVE_SIDECAR_VALUE:
                    return FINGERPRINT_REMOVE_SIDECAR;
                case APPLICATIONS_STORAGE_MOVIES_VALUE:
                    return APPLICATIONS_STORAGE_MOVIES;
                case ENTERPRISE_PRIVACY_INSTALLED_APPS_VALUE:
                    return ENTERPRISE_PRIVACY_INSTALLED_APPS;
                case ENTERPRISE_PRIVACY_PERMISSIONS_VALUE:
                    return ENTERPRISE_PRIVACY_PERMISSIONS;
                case ENTERPRISE_PRIVACY_DEFAULT_APPS_VALUE:
                    return ENTERPRISE_PRIVACY_DEFAULT_APPS;
                case SETTINGS_CHOOSE_LOCK_DIALOG_VALUE:
                    return SETTINGS_CHOOSE_LOCK_DIALOG;
                case SETTINGS_ASSIST_GESTURE_VALUE:
                    return SETTINGS_ASSIST_GESTURE;
                case 1009:
                    return BLUETOOTH_DEVICE_DETAILS;
                case 1010:
                    return CONFIGURE_KEYGUARD_DIALOG;
                case 1014:
                    return WIFI_TETHER_SETTINGS;
                case 1015:
                    return DIALOG_BLUETOOTH_PAIRED_DEVICE_RENAME;
                case 1018:
                    return BLUETOOTH_PAIRING;
                case 1031:
                    return DIALOG_BLUETOOTH_PAIRED_DEVICE_FORGET;
                case 1092:
                    return APPLICATIONS_STORAGE_PHOTOS;
                case COLOR_MODE_SETTINGS_VALUE:
                    return COLOR_MODE_SETTINGS;
                case SETTINGS_FEATURE_FLAGS_DASHBOARD_VALUE:
                    return SETTINGS_FEATURE_FLAGS_DASHBOARD;
                case NOTIFICATION_CHANNEL_GROUP_VALUE:
                    return NOTIFICATION_CHANNEL_GROUP;
                case DIALOG_ENABLE_DEVELOPMENT_OPTIONS_VALUE:
                    return DIALOG_ENABLE_DEVELOPMENT_OPTIONS;
                case DIALOG_ENABLE_OEM_UNLOCKING_VALUE:
                    return DIALOG_ENABLE_OEM_UNLOCKING;
                case FINGERPRINT_AUTHENTICATE_SIDECAR_VALUE:
                    return FINGERPRINT_AUTHENTICATE_SIDECAR;
                case DIALOG_ENABLE_ADB_VALUE:
                    return DIALOG_ENABLE_ADB;
                case DIALOG_CLEAR_ADB_KEYS_VALUE:
                    return DIALOG_CLEAR_ADB_KEYS;
                case DEVELOPMENT_QS_TILE_CONFIG_VALUE:
                    return DEVELOPMENT_QS_TILE_CONFIG;
                case DIALOG_LOG_PERSIST_VALUE:
                    return DIALOG_LOG_PERSIST;
                case WIFI_CALLING_FOR_SUB_VALUE:
                    return WIFI_CALLING_FOR_SUB;
                case DIALOG_OEM_LOCK_INFO_VALUE:
                    return DIALOG_OEM_LOCK_INFO;
                case DIALOG_IMEI_INFO_VALUE:
                    return DIALOG_IMEI_INFO;
                case DIALOG_SIM_STATUS_VALUE:
                    return DIALOG_SIM_STATUS;
                case DIALOG_FIRMWARE_VERSION_VALUE:
                    return DIALOG_FIRMWARE_VERSION;
                case FUELGAUGE_POWER_USAGE_SUMMARY_V2_VALUE:
                    return FUELGAUGE_POWER_USAGE_SUMMARY_V2;
                case CONNECTION_DEVICE_ADVANCED_VALUE:
                    return CONNECTION_DEVICE_ADVANCED;
                case SCREEN_LOCK_SETTINGS_VALUE:
                    return SCREEN_LOCK_SETTINGS;
                case NOTIFICATION_ZEN_MODE_DELETE_RULE_DIALOG_VALUE:
                    return NOTIFICATION_ZEN_MODE_DELETE_RULE_DIALOG;
                case NOTIFICATION_ZEN_MODE_RULE_NAME_DIALOG_VALUE:
                    return NOTIFICATION_ZEN_MODE_RULE_NAME_DIALOG;
                case NOTIFICATION_ZEN_MODE_RULE_SELECTION_DIALOG_VALUE:
                    return NOTIFICATION_ZEN_MODE_RULE_SELECTION_DIALOG;
                case FUELGAUGE_SMART_BATTERY_VALUE:
                    return FUELGAUGE_SMART_BATTERY;
                case FUELGAUGE_RESTRICTED_APP_DETAILS_VALUE:
                    return FUELGAUGE_RESTRICTED_APP_DETAILS;
                case NOTIFICATION_ZEN_MODE_ENABLE_DIALOG_VALUE:
                    return NOTIFICATION_ZEN_MODE_ENABLE_DIALOG;
                case USB_DEVICE_DETAILS_VALUE:
                    return USB_DEVICE_DETAILS;
                case ACCESSIBILITY_VIBRATION_VALUE:
                    return ACCESSIBILITY_VIBRATION;
                case ACCESSIBILITY_VIBRATION_NOTIFICATION_VALUE:
                    return ACCESSIBILITY_VIBRATION_NOTIFICATION;
                case ACCESSIBILITY_VIBRATION_TOUCH_VALUE:
                    return ACCESSIBILITY_VIBRATION_TOUCH;
                case USB_DEFAULT_VALUE:
                    return USB_DEFAULT;
                case FUELGAUGE_BATTERY_TIP_DIALOG_VALUE:
                    return FUELGAUGE_BATTERY_TIP_DIALOG;
                case ZEN_WHAT_TO_BLOCK_VALUE:
                    return ZEN_WHAT_TO_BLOCK;
                case NOTIFICATION_ZEN_MODE_DURATION_DIALOG_VALUE:
                    return NOTIFICATION_ZEN_MODE_DURATION_DIALOG;
                case SETTINGS_ZONE_PICKER_REGION_VALUE:
                    return SETTINGS_ZONE_PICKER_REGION;
                case SETTINGS_ZONE_PICKER_TIME_ZONE_VALUE:
                    return SETTINGS_ZONE_PICKER_TIME_ZONE;
                case SETTINGS_ZONE_PICKER_FIXED_OFFSET_VALUE:
                    return SETTINGS_ZONE_PICKER_FIXED_OFFSET;
                case SETTINGS_PREVENT_RINGING_VALUE:
                    return SETTINGS_PREVENT_RINGING;
                case SETTINGS_CONDITION_DEVICE_MUTED_VALUE:
                    return SETTINGS_CONDITION_DEVICE_MUTED;
                case SETTINGS_CONDITION_DEVICE_VIBRATE_VALUE:
                    return SETTINGS_CONDITION_DEVICE_VIBRATE;
                case PREVIOUSLY_CONNECTED_DEVICES_VALUE:
                    return PREVIOUSLY_CONNECTED_DEVICES;
                case WIFI_SCANNING_NEEDED_DIALOG_VALUE:
                    return WIFI_SCANNING_NEEDED_DIALOG;
                case SETTINGS_GESTURE_SWIPE_UP_VALUE:
                    return SETTINGS_GESTURE_SWIPE_UP;
                case DIALOG_VOLUME_FORMAT_VALUE:
                    return DIALOG_VOLUME_FORMAT;
                case SETTINGS_ZEN_ONBOARDING_VALUE:
                    return SETTINGS_ZEN_ONBOARDING;
                case SETTINGS_AUTO_BRIGHTNESS_VALUE:
                    return SETTINGS_AUTO_BRIGHTNESS;
                case BLUETOOTH_FRAGMENT_VALUE:
                    return BLUETOOTH_FRAGMENT;
                case SETTINGS_ZEN_NOTIFICATIONS_VALUE:
                    return SETTINGS_ZEN_NOTIFICATIONS;
                case SLICE_VALUE:
                    return SLICE;
                case DIALOG_BLUETOOTH_DISABLE_A2DP_HW_OFFLOAD_VALUE:
                    return DIALOG_BLUETOOTH_DISABLE_A2DP_HW_OFFLOAD;
                case SETTINGS_HOMEPAGE_VALUE:
                    return SETTINGS_HOMEPAGE;
                case SETTINGS_CREATE_SHORTCUT_VALUE:
                    return SETTINGS_CREATE_SHORTCUT;
                case FACE_ENROLL_INTRO_VALUE:
                    return FACE_ENROLL_INTRO;
                case FACE_ENROLL_ENROLLING_VALUE:
                    return FACE_ENROLL_ENROLLING;
                case FACE_ENROLL_FINISHED_VALUE:
                    return FACE_ENROLL_FINISHED;
                case FACE_ENROLL_SIDECAR_VALUE:
                    return FACE_ENROLL_SIDECAR;
                case DIALOG_FACE_ERROR_VALUE:
                    return DIALOG_FACE_ERROR;
                case FACE_VALUE:
                    return FACE;
                case DIALOG_ACCESSIBILITY_HEARINGAID_VALUE:
                    return DIALOG_ACCESSIBILITY_HEARINGAID;
                case FACE_ENROLL_PREVIEW_VALUE:
                    return FACE_ENROLL_PREVIEW;
                case SETTINGS_WIFI_ADD_NETWORK_VALUE:
                    return SETTINGS_WIFI_ADD_NETWORK;
                case SETTINGS_GESTURE_WAKE_LOCK_SCREEN_VALUE:
                    return SETTINGS_GESTURE_WAKE_LOCK_SCREEN;
                case SETTINGS_GESTURE_WAKE_SCREEN_VALUE:
                    return SETTINGS_GESTURE_WAKE_SCREEN;
                case MOBILE_NETWORK_VALUE:
                    return MOBILE_NETWORK;
                case MOBILE_NETWORK_SELECT_VALUE:
                    return MOBILE_NETWORK_SELECT;
                case MOBILE_DATA_DIALOG_VALUE:
                    return MOBILE_DATA_DIALOG;
                case MOBILE_ROAMING_DIALOG_VALUE:
                    return MOBILE_ROAMING_DIALOG;
                case LOCK_SCREEN_NOTIFICATION_CONTENT_VALUE:
                    return LOCK_SCREEN_NOTIFICATION_CONTENT;
                case BIOMETRIC_FRAGMENT_VALUE:
                    return BIOMETRIC_FRAGMENT;
                case BIOMETRIC_ENROLL_ACTIVITY_VALUE:
                    return BIOMETRIC_ENROLL_ACTIVITY;
                case TOP_LEVEL_PRIVACY_VALUE:
                    return TOP_LEVEL_PRIVACY;
                case NOTIFICATION_ZEN_MODE_OVERRIDING_APPS_VALUE:
                    return NOTIFICATION_ZEN_MODE_OVERRIDING_APPS;
                case NOTIFICATION_ZEN_MODE_OVERRIDING_APP_VALUE:
                    return NOTIFICATION_ZEN_MODE_OVERRIDING_APP;
                case DIALOG_DISABLE_DEVELOPMENT_OPTIONS_VALUE:
                    return DIALOG_DISABLE_DEVELOPMENT_OPTIONS;
                case SETTINGS_WIFI_DPP_CONFIGURATOR_VALUE:
                    return SETTINGS_WIFI_DPP_CONFIGURATOR;
                case SETTINGS_WIFI_DPP_ENROLLEE_VALUE:
                    return SETTINGS_WIFI_DPP_ENROLLEE;
                case SETTINGS_FINANCIAL_APPS_SMS_ACCESS_VALUE:
                    return SETTINGS_FINANCIAL_APPS_SMS_ACCESS;
                case ZEN_CUSTOM_RULE_SETTINGS_VALUE:
                    return ZEN_CUSTOM_RULE_SETTINGS;
                case ZEN_CUSTOM_RULE_SOUND_SETTINGS_VALUE:
                    return ZEN_CUSTOM_RULE_SOUND_SETTINGS;
                case ZEN_CUSTOM_RULE_DEFAULT_SETTINGS_VALUE:
                    return ZEN_CUSTOM_RULE_DEFAULT_SETTINGS;
                case ZEN_CUSTOM_RULE_NOTIFICATION_RESTRICTIONS_VALUE:
                    return ZEN_CUSTOM_RULE_NOTIFICATION_RESTRICTIONS;
                case ZEN_CUSTOM_RULE_VIS_EFFECTS_VALUE:
                    return ZEN_CUSTOM_RULE_VIS_EFFECTS;
                case ZEN_CUSTOM_RULE_MESSAGES_VALUE:
                    return ZEN_CUSTOM_RULE_MESSAGES;
                case ZEN_CUSTOM_RULE_CALLS_VALUE:
                    return ZEN_CUSTOM_RULE_CALLS;
                case ZEN_CUSTOM_SETTINGS_DIALOG_VALUE:
                    return ZEN_CUSTOM_SETTINGS_DIALOG;
                case SETTINGS_GAME_DRIVER_DASHBOARD_VALUE:
                    return SETTINGS_GAME_DRIVER_DASHBOARD;
                case ACCESSIBILITY_VIBRATION_RING_VALUE:
                    return ACCESSIBILITY_VIBRATION_RING;
                case SETTINGS_GESTURE_SKIP_VALUE:
                    return SETTINGS_GESTURE_SKIP;
                case SETTINGS_GESTURE_SILENCE_VALUE:
                    return SETTINGS_GESTURE_SILENCE;
                case SETTINGS_GESTURE_TAP_SCREEN_VALUE:
                    return SETTINGS_GESTURE_TAP_SCREEN;
                case MOBILE_NETWORK_LIST_VALUE:
                    return MOBILE_NETWORK_LIST;
                case SETTINGS_ADAPTIVE_SLEEP_VALUE:
                    return SETTINGS_ADAPTIVE_SLEEP;
                case SETTINGS_AWARE_VALUE:
                    return SETTINGS_AWARE;
                case DIALOG_AWARE_DISABLE_VALUE:
                    return DIALOG_AWARE_DISABLE;
                case MOBILE_NETWORK_RENAME_DIALOG_VALUE:
                    return MOBILE_NETWORK_RENAME_DIALOG;
                case SET_NEW_PASSWORD_ACTIVITY_VALUE:
                    return SET_NEW_PASSWORD_ACTIVITY;
                case PANEL_INTERNET_CONNECTIVITY_VALUE:
                    return PANEL_INTERNET_CONNECTIVITY;
                case PANEL_VOLUME_VALUE:
                    return PANEL_VOLUME;
                case PANEL_NFC_VALUE:
                    return PANEL_NFC;
                case PANEL_MEDIA_OUTPUT_VALUE:
                    return PANEL_MEDIA_OUTPUT;
                case PAGE_ATSSI_VALUE:
                    return PAGE_ATSSI;
                case PAGE_ATSII_VALUE:
                    return PAGE_ATSII;
                case PAGE_ATUS_VALUE:
                    return PAGE_ATUS;
                case PAGE_ATSSP_VALUE:
                    return PAGE_ATSSP;
                case PAGE_ATSAP_VALUE:
                    return PAGE_ATSAP;
                case PAGE_ATSCP_VALUE:
                    return PAGE_ATSCP;
                case PAGE_ATHNP_VALUE:
                    return PAGE_ATHNP;
                case ACCESSIBILITY_DETAILS_SETTINGS_VALUE:
                    return ACCESSIBILITY_DETAILS_SETTINGS;
                case SETTINGS_CONDITION_GRAYSCALE_MODE_VALUE:
                    return SETTINGS_CONDITION_GRAYSCALE_MODE;
                case PANEL_WIFI_VALUE:
                    return PANEL_WIFI;
                case ZEN_ACCESS_DETAIL_VALUE:
                    return ZEN_ACCESS_DETAIL;
                case DIALOG_FACE_REMOVE_VALUE:
                    return DIALOG_FACE_REMOVE;
                case DARK_UI_SETTINGS_VALUE:
                    return DARK_UI_SETTINGS;
                case BUBBLE_SETTINGS_VALUE:
                    return BUBBLE_SETTINGS;
                case APP_BUBBLE_SETTINGS_VALUE:
                    return APP_BUBBLE_SETTINGS;
                case DIALOG_AWARE_STATUS_VALUE:
                    return DIALOG_AWARE_STATUS;
                case DIALOG_APP_BUBBLE_SETTINGS_VALUE:
                    return DIALOG_APP_BUBBLE_SETTINGS;
                case DIALOG_SIM_LIST_VALUE:
                    return DIALOG_SIM_LIST;
                case DIALOG_CALL_SIM_LIST_VALUE:
                    return DIALOG_CALL_SIM_LIST;
                case DIALOG_PREFERRED_SIM_PICKER_VALUE:
                    return DIALOG_PREFERRED_SIM_PICKER;
                case DIALOG_DELETE_SIM_CONFIRMATION_VALUE:
                    return DIALOG_DELETE_SIM_CONFIRMATION;
                case DIALOG_DELETE_SIM_PROGRESS_VALUE:
                    return DIALOG_DELETE_SIM_PROGRESS;
                case GENTLE_NOTIFICATIONS_SCREEN_VALUE:
                    return GENTLE_NOTIFICATIONS_SCREEN;
                case GLOBAL_ACTIONS_PANEL_SETTINGS_VALUE:
                    return GLOBAL_ACTIONS_PANEL_SETTINGS;
                case DIALOG_DARK_UI_INFO_VALUE:
                    return DIALOG_DARK_UI_INFO;
                case MODULE_LICENSES_DASHBOARD_VALUE:
                    return MODULE_LICENSES_DASHBOARD;
                case SETTINGS_GESTURE_NAV_NOT_AVAILABLE_DLG_VALUE:
                    return SETTINGS_GESTURE_NAV_NOT_AVAILABLE_DLG;
                case SETTINGS_GESTURE_NAV_BACK_SENSITIVITY_DLG_VALUE:
                    return SETTINGS_GESTURE_NAV_BACK_SENSITIVITY_DLG;
                case SETTINGS_AWARE_DISPLAY_VALUE:
                    return SETTINGS_AWARE_DISPLAY;
                case SETTINGS_GESTURE_TAP_VALUE:
                    return SETTINGS_GESTURE_TAP;
                default:
                    switch (value2) {
                        case 19:
                            return APPLICATIONS_APP_STORAGE;
                        case 20:
                            return APPLICATIONS_INSTALLED_APP_DETAILS;
                        case 21:
                            return APPLICATIONS_PROCESS_STATS_DETAIL;
                        default:
                            switch (value2) {
                                case 27:
                                    return CHOOSE_LOCK_GENERIC;
                                case 28:
                                    return CHOOSE_LOCK_PASSWORD;
                                case 29:
                                    return CHOOSE_LOCK_PATTERN;
                                case 30:
                                    return CONFIRM_LOCK_PASSWORD;
                                case 31:
                                    return CONFIRM_LOCK_PATTERN;
                                case 32:
                                    return CRYPT_KEEPER;
                                case 33:
                                    return CRYPT_KEEPER_CONFIRM;
                                default:
                                    switch (value2) {
                                        case 37:
                                            return DATA_USAGE_SUMMARY;
                                        case 38:
                                            return DATE_TIME;
                                        case 39:
                                            return DEVELOPMENT;
                                        case 40:
                                            return DEVICEINFO;
                                        default:
                                            switch (value2) {
                                                case 46:
                                                    return DISPLAY;
                                                case 47:
                                                    return DREAM;
                                                case 48:
                                                    return ENCRYPTION;
                                                case 49:
                                                    return FINGERPRINT;
                                                default:
                                                    switch (value2) {
                                                        case 51:
                                                            return FUELGAUGE_BATTERY_HISTORY_DETAIL;
                                                        case 52:
                                                            return FUELGAUGE_BATTERY_SAVER;
                                                        case 53:
                                                            return FUELGAUGE_POWER_USAGE_DETAIL;
                                                        default:
                                                            switch (value2) {
                                                                case 58:
                                                                    return INPUTMETHOD_KEYBOARD;
                                                                case 59:
                                                                    return INPUTMETHOD_SPELL_CHECKERS;
                                                                case 60:
                                                                    return INPUTMETHOD_SUBTYPE_ENABLER;
                                                                case 61:
                                                                    return INPUTMETHOD_USER_DICTIONARY;
                                                                case 62:
                                                                    return INPUTMETHOD_USER_DICTIONARY_ADD_WORD;
                                                                case 63:
                                                                    return LOCATION;
                                                                default:
                                                                    switch (value2) {
                                                                        case 65:
                                                                            return MANAGE_APPLICATIONS;
                                                                        case 66:
                                                                            return MASTER_CLEAR;
                                                                        case 67:
                                                                            return MASTER_CLEAR_CONFIRM;
                                                                        default:
                                                                            return null;
                                                                    }
                                                            }
                                                    }
                                            }
                                    }
                            }
                    }
            }
        }
        return ACCESSIBILITY_TOGGLE_SCREEN_MAGNIFICATION;
    }

    public static Internal.EnumLiteMap<PageId> internalGetValueMap() {
        return internalValueMap;
    }

    private PageId(int value2) {
        this.value = value2;
    }
}
