package com.oculus.uploader;

import X.AnonymousClass0J5;
import X.AnonymousClass1Q8;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class UploaderModule extends AnonymousClass0J5 {
    public static volatile AnonymousClass1Q8 _UL__ULSEP_com_facebook_fbuploader_FbUploaderImpl_ULSEP_INSTANCE;

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForUploaderModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_facebook_fbuploader_FbUploaderImpl_ULSEP_BINDING_ID = 152;
        public static final int _UL__ULSEP_com_oculus_uploader_OculusHttpRequestExecutor_ULSEP_BINDING_ID = 79;
    }
}
