package com.oculus.common.init.impl;

import X.AbstractC03180ld;
import X.AnonymousClass0Hr;
import X.AnonymousClass0RE;
import X.AnonymousClass0VC;
import X.AnonymousClass0VF;
import X.AnonymousClass0lg;
import X.AnonymousClass1TK;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.oculus.common.init.INeedInit;
import com.oculus.managed.ManagedMode;
import java.util.Set;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_java_util_Set_ULLT_com_oculus_common_init_INeedInit_ULGT__ULSEP_com_oculus_common_init_NeedsHighPriorityInit_ULSEP_BINDING_ID", "_UL__ULSEP_java_util_Set_ULLT_com_oculus_common_init_INeedInit_ULGT__ULSEP_com_oculus_common_init_NeedsInitInEnterpriseMode_ULSEP_BINDING_ID", "_UL__ULSEP_java_util_Set_ULLT_com_oculus_common_init_INeedInit_ULGT__ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_managed_ManagedMode_ULSEP_BINDING_ID"})
public class AppInitializer {
    public static final String TAG = "AppInitializer";
    public AnonymousClass0RE _UL_mInjectionContext;

    @AutoGeneratedAccessMethod
    public static final AbstractC03180ld _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_common_init_impl_AppInitializer_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0Hr.A00(2117, r1);
    }

    @AutoGeneratedAccessMethod
    public static final AppInitializer _UL__ULSEP_com_oculus_common_init_impl_AppInitializer_ULSEP_ACCESS_METHOD(AnonymousClass0lg r2) {
        return (AppInitializer) AnonymousClass1TK.A00(2117, r2, null);
    }

    @AutoGeneratedFactoryMethod
    public static final AppInitializer _UL__ULSEP_com_oculus_common_init_impl_AppInitializer_ULSEP_FACTORY_METHOD(AnonymousClass0lg r1, Object obj) {
        return new AppInitializer(r1);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_common_init_impl_AppInitializer_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0VC.A00(2117, r1);
    }

    public void run() {
        ((Set) AnonymousClass0VF.A03(0, 9, this._UL_mInjectionContext)).size();
        for (INeedInit iNeedInit : (Set) AnonymousClass0VF.A03(0, 9, this._UL_mInjectionContext)) {
            iNeedInit.init();
        }
        AnonymousClass0RE r1 = this._UL_mInjectionContext;
        if (((ManagedMode) AnonymousClass0VF.A03(3, 82, r1)).isEnterpriseModeEnabled) {
            ((Set) AnonymousClass0VF.A03(1, 45, r1)).size();
            for (INeedInit iNeedInit2 : (Set) AnonymousClass0VF.A03(1, 45, this._UL_mInjectionContext)) {
                iNeedInit2.init();
            }
        }
        ((Set) AnonymousClass0VF.A03(2, 28, this._UL_mInjectionContext)).size();
        for (INeedInit iNeedInit3 : (Set) AnonymousClass0VF.A03(2, 28, this._UL_mInjectionContext)) {
            iNeedInit3.init();
        }
    }

    @Inject
    public AppInitializer(AnonymousClass0lg r3) {
        this._UL_mInjectionContext = new AnonymousClass0RE(4, r3);
    }
}
