package com.oculus.horizon.service_media;

import X.AnonymousClass0J5;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import com.oculus.horizon.abuse_prevention.interfaces.AbuseCaptureProvider;

@InjectorModule
public class ServiceMediaModule extends AnonymousClass0J5 {
    public static volatile AbuseCaptureProvider _UL__ULSEP_com_oculus_horizon_abuse_ULUNDERSCORE_prevention_interfaces_AbuseCaptureProvider_ULSEP_INSTANCE;

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForServiceMediaModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_horizon_abuse_ULUNDERSCORE_prevention_interfaces_AbuseCaptureProvider_ULSEP_BINDING_ID = 323;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_AppSwitchManager_ULSEP_BINDING_ID = 471;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_CaptureAnalytics_ULSEP_BINDING_ID = 275;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_FileCapture_ULSEP_BINDING_ID = 525;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_ForegroundAppChecker_ULSEP_BINDING_ID = 192;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_HorizonCallerPackageVerifier_ULSEP_BINDING_ID = 166;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_InstantReplayHelper_ULSEP_BINDING_ID = 219;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_OVRLivestreamingErrorUtility_ULSEP_BINDING_ID = 22;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_OVRMediaServiceManagerProvider_ULSEP_BINDING_ID = 427;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_OVRMediaServiceNotification_ULSEP_BINDING_ID = 149;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_SurfaceCapture_ULSEP_BINDING_ID = 125;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_WebRTCCapture_ULSEP_BINDING_ID = 536;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_screenshot_ScreenshotManager_ULSEP_BINDING_ID = 519;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_vrcast_VrCastManager_ULSEP_BINDING_ID = 232;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_vrcast_VrCastServiceConnection_ULSEP_BINDING_ID = 309;
        public static final int _UL__ULSEP_com_oculus_horizon_service_ULUNDERSCORE_media_vrcast_VrCastServicePackageVerifier_ULSEP_BINDING_ID = 352;
    }
}
