package com.oculus.friendlistcontentprovider;

import X.AbstractC03180ld;
import X.AnonymousClass0Hr;
import X.AnonymousClass0RE;
import X.AnonymousClass0VC;
import X.AnonymousClass0VF;
import X.AnonymousClass0lg;
import X.AnonymousClass1TK;
import android.content.ContentProvider;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.oculus.logging.utils.Event;
import com.oculus.logging.utils.EventManager;
import javax.annotation.concurrent.Immutable;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_com_oculus_logging_utils_EventManager_ULSEP_BINDING_ID"})
@Immutable
public final class FriendListContentProviderLogger {
    public static final String EVENT_LINKED_ACCOUNTS_QUERY = "oculus_mobile_friend_list_provider_linked_accounts_query";
    public static final String EXTRA_REQUESTING_PACKAGE = "requesting_package";
    public static final String EXTRA_RESULT = "result";
    public AnonymousClass0RE _UL_mInjectionContext;

    @AutoGeneratedAccessMethod
    public static final AbstractC03180ld _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_friendlistcontentprovider_FriendListContentProviderLogger_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0Hr.A00(66, r1);
    }

    @AutoGeneratedAccessMethod
    public static final FriendListContentProviderLogger _UL__ULSEP_com_oculus_friendlistcontentprovider_FriendListContentProviderLogger_ULSEP_ACCESS_METHOD(AnonymousClass0lg r2) {
        return (FriendListContentProviderLogger) AnonymousClass1TK.A00(66, r2, null);
    }

    @AutoGeneratedFactoryMethod
    public static final FriendListContentProviderLogger _UL__ULSEP_com_oculus_friendlistcontentprovider_FriendListContentProviderLogger_ULSEP_FACTORY_METHOD(AnonymousClass0lg r1, Object obj) {
        return new FriendListContentProviderLogger(r1);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_friendlistcontentprovider_FriendListContentProviderLogger_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0VC.A00(66, r1);
    }

    private Event createEvent(String str, ContentProvider contentProvider) {
        return ((EventManager) AnonymousClass0VF.A03(0, 92, this._UL_mInjectionContext)).createEvent(str).addExtra(EXTRA_REQUESTING_PACKAGE, contentProvider.getCallingPackage());
    }

    public void reportLinkedAccountsQuery(ContentProvider contentProvider, boolean z) {
        createEvent(EVENT_LINKED_ACCOUNTS_QUERY, contentProvider).addExtra("result", z).logAndRelease();
    }

    @Inject
    public FriendListContentProviderLogger(AnonymousClass0lg r3) {
        this._UL_mInjectionContext = new AnonymousClass0RE(1, r3);
    }
}
