package com.oculus.friendlistcontentprovider;

import X.AnonymousClass0Qr;
import X.AnonymousClass0VI;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public class FriendlistcontentproviderModule extends AnonymousClass0VI {

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_friendlistcontentprovider_FriendListContentProviderLogger_ULSEP_BINDING_ID = 66;
    }

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForFriendlistcontentproviderModule {
        public static void bind(AnonymousClass0Qr r0) {
        }
    }
}
