package com.oculus.appmanager.downloader.progress;

import X.AnonymousClass0J5;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;
import com.oculus.downloader.progress.DownloadProgressTracker;

@InjectorModule
public class OuculusDownloadProgressTrackerModule extends AnonymousClass0J5 {
    public static volatile DownloadProgressTracker _UL__ULSEP_com_oculus_downloader_progress_DownloadProgressTracker_ULSEP_INSTANCE;

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForOuculusDownloadProgressTrackerModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_appmanager_downloader_progress_OculusDownloadProgressTracker_ULSEP_BINDING_ID = 344;
        public static final int _UL__ULSEP_com_oculus_downloader_progress_DownloadProgressTracker_ULSEP_BINDING_ID = 81;
    }
}
