package com.oculus.http.useragent;

import X.AbstractC0031Bc;
import X.BZ;
import X.TW;
import com.facebook.common.stringformat.StringFormatUtil;
import com.facebook.inject.AutoGeneratedBinder;
import com.facebook.inject.InjectorModule;
import com.facebook.inject.ProviderMethod;
import com.facebook.ultralight.AutoGeneratedSwitchIdClass;

@InjectorModule
public abstract class UserAgentModule extends AbstractC0031Bc {

    @AutoGeneratedBinder
    public static class AutoGeneratedBindingsForUserAgentModule {
    }

    @AutoGeneratedSwitchIdClass
    public static final class UL_id {
        public static final int _UL__ULSEP_com_oculus_http_useragent_UserAgentFactory_ULSEP_BINDING_ID = 6;
        public static final int _UL__ULSEP_java_lang_String_ULSEP_com_oculus_http_useragent_AppNameInUserAgent_ULSEP_BINDING_ID = 37;
        public static final int _UL__ULSEP_java_lang_String_ULSEP_com_oculus_http_useragent_UserAgentAppVersionMap_ULSEP_BINDING_ID = 38;
        public static final int _UL__ULSEP_java_lang_String_ULSEP_com_oculus_http_useragent_UserAgentString_ULSEP_BINDING_ID = 77;
    }

    /* JADX DEBUG: Multi-variable search result rejected for r1v6, resolved type: java.util.Map<java.lang.String, java.lang.String> */
    /* JADX WARN: Multi-variable type inference failed */
    @ProviderMethod
    @UserAgentString
    public static String A00(UserAgentFactory userAgentFactory) {
        UserAgentBuilder userAgentBuilder = new UserAgentBuilder(userAgentFactory.mContext);
        userAgentBuilder.mHttpAgent = System.getProperty("http.agent");
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_APP_NAME, userAgentFactory.mAppNameInUserAgent);
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_APP_VERSION, userAgentFactory.mPackageInfo.versionName);
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_BUILD_VERSION, String.valueOf(userAgentFactory.mPackageInfo.versionCode));
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_LOCALE, userAgentFactory.mLocaleProvider.get().toString());
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_PACKAGE_NAME, userAgentFactory.mContext.getPackageName());
        userAgentBuilder.mProperties.put(UserAgentBuilder.FB_APP_VERSION_MAP, BZ.A02(0, 38, userAgentFactory._UL_mInjectionContext));
        String str = userAgentBuilder.mHttpAgent;
        if (str != null) {
            StringBuilder sb = new StringBuilder();
            sb.append(str);
            sb.append(" [");
            TW<String> A0H = UserAgentBuilder.FIXED_ORDER_KEYS.iterator();
            while (A0H.hasNext()) {
                String next = A0H.next();
                if (userAgentBuilder.mProperties.get(next) != null) {
                    sb.append(StringFormatUtil.formatStrLocaleSafe("%s/%s;", next, UserAgentBuilder.A00(userAgentBuilder.mProperties.get(next))));
                } else {
                    throw null;
                }
            }
            TW<String> A0H2 = UserAgentBuilder.OPTIONAL_KEYS.iterator();
            while (A0H2.hasNext()) {
                String next2 = A0H2.next();
                sb.append(StringFormatUtil.formatStrLocaleSafe("%s/%s;", next2, UserAgentBuilder.A00(userAgentBuilder.mProperties.get(next2))));
            }
            TW<String> A0H3 = UserAgentBuilder.OPTIONAL_KEYS_SKIP_IF_NULL.iterator();
            while (A0H3.hasNext()) {
                String next3 = A0H3.next();
                if (userAgentBuilder.mProperties.get(next3) != null) {
                    sb.append(StringFormatUtil.formatStrLocaleSafe("%s/%s;", next3, UserAgentBuilder.A00(userAgentBuilder.mProperties.get(next3))));
                }
            }
            sb.append("]");
            return sb.toString();
        }
        throw null;
    }
}
