package androidx.constraintlayout.widget;

public final class R {
    private R() {
    }

    public static final class attr {
        public static final int barrierAllowsGoneWidgets = 2130968594;
        public static final int barrierDirection = 2130968595;
        public static final int chainUseRtl = 2130968607;
        public static final int constraintSet = 2130968608;
        public static final int constraint_referenced_ids = 2130968609;
        public static final int content = 2130968610;
        public static final int emptyVisibility = 2130968624;
        public static final int layout_constrainedHeight = 2130968662;
        public static final int layout_constrainedWidth = 2130968663;
        public static final int layout_constraintBaseline_creator = 2130968664;
        public static final int layout_constraintBaseline_toBaselineOf = 2130968665;
        public static final int layout_constraintBottom_creator = 2130968666;
        public static final int layout_constraintBottom_toBottomOf = 2130968667;
        public static final int layout_constraintBottom_toTopOf = 2130968668;
        public static final int layout_constraintCircle = 2130968669;
        public static final int layout_constraintCircleAngle = 2130968670;
        public static final int layout_constraintCircleRadius = 2130968671;
        public static final int layout_constraintDimensionRatio = 2130968672;
        public static final int layout_constraintEnd_toEndOf = 2130968673;
        public static final int layout_constraintEnd_toStartOf = 2130968674;
        public static final int layout_constraintGuide_begin = 2130968675;
        public static final int layout_constraintGuide_end = 2130968676;
        public static final int layout_constraintGuide_percent = 2130968677;
        public static final int layout_constraintHeight_default = 2130968678;
        public static final int layout_constraintHeight_max = 2130968679;
        public static final int layout_constraintHeight_min = 2130968680;
        public static final int layout_constraintHeight_percent = 2130968681;
        public static final int layout_constraintHorizontal_bias = 2130968682;
        public static final int layout_constraintHorizontal_chainStyle = 2130968683;
        public static final int layout_constraintHorizontal_weight = 2130968684;
        public static final int layout_constraintLeft_creator = 2130968685;
        public static final int layout_constraintLeft_toLeftOf = 2130968686;
        public static final int layout_constraintLeft_toRightOf = 2130968687;
        public static final int layout_constraintRight_creator = 2130968688;
        public static final int layout_constraintRight_toLeftOf = 2130968689;
        public static final int layout_constraintRight_toRightOf = 2130968690;
        public static final int layout_constraintStart_toEndOf = 2130968691;
        public static final int layout_constraintStart_toStartOf = 2130968692;
        public static final int layout_constraintTop_creator = 2130968693;
        public static final int layout_constraintTop_toBottomOf = 2130968694;
        public static final int layout_constraintTop_toTopOf = 2130968695;
        public static final int layout_constraintVertical_bias = 2130968696;
        public static final int layout_constraintVertical_chainStyle = 2130968697;
        public static final int layout_constraintVertical_weight = 2130968698;
        public static final int layout_constraintWidth_default = 2130968699;
        public static final int layout_constraintWidth_max = 2130968700;
        public static final int layout_constraintWidth_min = 2130968701;
        public static final int layout_constraintWidth_percent = 2130968702;
        public static final int layout_editor_absoluteX = 2130968704;
        public static final int layout_editor_absoluteY = 2130968705;
        public static final int layout_goneMarginBottom = 2130968709;
        public static final int layout_goneMarginEnd = 2130968710;
        public static final int layout_goneMarginLeft = 2130968711;
        public static final int layout_goneMarginRight = 2130968712;
        public static final int layout_goneMarginStart = 2130968713;
        public static final int layout_goneMarginTop = 2130968714;
        public static final int layout_optimizationLevel = 2130968721;

        private attr() {
        }
    }

    public static final class id {
        public static final int bottom = 2131230849;
        public static final int end = 2131230984;
        public static final int gone = 2131231083;
        public static final int invisible = 2131231120;
        public static final int left = 2131231139;
        public static final int packed = 2131231269;
        public static final int parent = 2131231270;
        public static final int percent = 2131231288;
        public static final int right = 2131231348;
        public static final int spread = 2131231477;
        public static final int spread_inside = 2131231478;
        public static final int start = 2131231480;
        public static final int top = 2131231551;
        public static final int wrap = 2131231561;

        private id() {
        }
    }

    public static final class styleable {
        public static final int[] ConstraintLayout_Layout = {16842948, 16843039, 16843040, 16843071, 16843072, com.oculus.systemux.R.attr.barrierAllowsGoneWidgets, com.oculus.systemux.R.attr.barrierDirection, com.oculus.systemux.R.attr.chainUseRtl, com.oculus.systemux.R.attr.constraintSet, com.oculus.systemux.R.attr.constraint_referenced_ids, com.oculus.systemux.R.attr.layout_constrainedHeight, com.oculus.systemux.R.attr.layout_constrainedWidth, com.oculus.systemux.R.attr.layout_constraintBaseline_creator, com.oculus.systemux.R.attr.layout_constraintBaseline_toBaselineOf, com.oculus.systemux.R.attr.layout_constraintBottom_creator, com.oculus.systemux.R.attr.layout_constraintBottom_toBottomOf, com.oculus.systemux.R.attr.layout_constraintBottom_toTopOf, com.oculus.systemux.R.attr.layout_constraintCircle, com.oculus.systemux.R.attr.layout_constraintCircleAngle, com.oculus.systemux.R.attr.layout_constraintCircleRadius, com.oculus.systemux.R.attr.layout_constraintDimensionRatio, com.oculus.systemux.R.attr.layout_constraintEnd_toEndOf, com.oculus.systemux.R.attr.layout_constraintEnd_toStartOf, com.oculus.systemux.R.attr.layout_constraintGuide_begin, com.oculus.systemux.R.attr.layout_constraintGuide_end, com.oculus.systemux.R.attr.layout_constraintGuide_percent, com.oculus.systemux.R.attr.layout_constraintHeight_default, com.oculus.systemux.R.attr.layout_constraintHeight_max, com.oculus.systemux.R.attr.layout_constraintHeight_min, com.oculus.systemux.R.attr.layout_constraintHeight_percent, com.oculus.systemux.R.attr.layout_constraintHorizontal_bias, com.oculus.systemux.R.attr.layout_constraintHorizontal_chainStyle, com.oculus.systemux.R.attr.layout_constraintHorizontal_weight, com.oculus.systemux.R.attr.layout_constraintLeft_creator, com.oculus.systemux.R.attr.layout_constraintLeft_toLeftOf, com.oculus.systemux.R.attr.layout_constraintLeft_toRightOf, com.oculus.systemux.R.attr.layout_constraintRight_creator, com.oculus.systemux.R.attr.layout_constraintRight_toLeftOf, com.oculus.systemux.R.attr.layout_constraintRight_toRightOf, com.oculus.systemux.R.attr.layout_constraintStart_toEndOf, com.oculus.systemux.R.attr.layout_constraintStart_toStartOf, com.oculus.systemux.R.attr.layout_constraintTop_creator, com.oculus.systemux.R.attr.layout_constraintTop_toBottomOf, com.oculus.systemux.R.attr.layout_constraintTop_toTopOf, com.oculus.systemux.R.attr.layout_constraintVertical_bias, com.oculus.systemux.R.attr.layout_constraintVertical_chainStyle, com.oculus.systemux.R.attr.layout_constraintVertical_weight, com.oculus.systemux.R.attr.layout_constraintWidth_default, com.oculus.systemux.R.attr.layout_constraintWidth_max, com.oculus.systemux.R.attr.layout_constraintWidth_min, com.oculus.systemux.R.attr.layout_constraintWidth_percent, com.oculus.systemux.R.attr.layout_editor_absoluteX, com.oculus.systemux.R.attr.layout_editor_absoluteY, com.oculus.systemux.R.attr.layout_goneMarginBottom, com.oculus.systemux.R.attr.layout_goneMarginEnd, com.oculus.systemux.R.attr.layout_goneMarginLeft, com.oculus.systemux.R.attr.layout_goneMarginRight, com.oculus.systemux.R.attr.layout_goneMarginStart, com.oculus.systemux.R.attr.layout_goneMarginTop, com.oculus.systemux.R.attr.layout_optimizationLevel};
        public static final int ConstraintLayout_Layout_android_maxHeight = 2;
        public static final int ConstraintLayout_Layout_android_maxWidth = 1;
        public static final int ConstraintLayout_Layout_android_minHeight = 4;
        public static final int ConstraintLayout_Layout_android_minWidth = 3;
        public static final int ConstraintLayout_Layout_android_orientation = 0;
        public static final int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
        public static final int ConstraintLayout_Layout_barrierDirection = 6;
        public static final int ConstraintLayout_Layout_chainUseRtl = 7;
        public static final int ConstraintLayout_Layout_constraintSet = 8;
        public static final int ConstraintLayout_Layout_constraint_referenced_ids = 9;
        public static final int ConstraintLayout_Layout_layout_constrainedHeight = 10;
        public static final int ConstraintLayout_Layout_layout_constrainedWidth = 11;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
        public static final int ConstraintLayout_Layout_layout_constraintCircle = 17;
        public static final int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
        public static final int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight = 56;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart = 57;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop = 58;
        public static final int ConstraintLayout_Layout_layout_optimizationLevel = 59;
        public static final int[] ConstraintLayout_placeholder = {com.oculus.systemux.R.attr.content, com.oculus.systemux.R.attr.emptyVisibility};
        public static final int ConstraintLayout_placeholder_content = 0;
        public static final int ConstraintLayout_placeholder_emptyVisibility = 1;
        public static final int[] ConstraintSet = {16842948, 16842960, 16842972, 16842996, 16842997, 16842999, 16843000, 16843001, 16843002, 16843039, 16843040, 16843071, 16843072, 16843551, 16843552, 16843553, 16843554, 16843555, 16843556, 16843557, 16843558, 16843559, 16843560, 16843701, 16843702, 16843770, 16843840, com.oculus.systemux.R.attr.barrierAllowsGoneWidgets, com.oculus.systemux.R.attr.barrierDirection, com.oculus.systemux.R.attr.chainUseRtl, com.oculus.systemux.R.attr.constraint_referenced_ids, com.oculus.systemux.R.attr.layout_constrainedHeight, com.oculus.systemux.R.attr.layout_constrainedWidth, com.oculus.systemux.R.attr.layout_constraintBaseline_creator, com.oculus.systemux.R.attr.layout_constraintBaseline_toBaselineOf, com.oculus.systemux.R.attr.layout_constraintBottom_creator, com.oculus.systemux.R.attr.layout_constraintBottom_toBottomOf, com.oculus.systemux.R.attr.layout_constraintBottom_toTopOf, com.oculus.systemux.R.attr.layout_constraintCircle, com.oculus.systemux.R.attr.layout_constraintCircleAngle, com.oculus.systemux.R.attr.layout_constraintCircleRadius, com.oculus.systemux.R.attr.layout_constraintDimensionRatio, com.oculus.systemux.R.attr.layout_constraintEnd_toEndOf, com.oculus.systemux.R.attr.layout_constraintEnd_toStartOf, com.oculus.systemux.R.attr.layout_constraintGuide_begin, com.oculus.systemux.R.attr.layout_constraintGuide_end, com.oculus.systemux.R.attr.layout_constraintGuide_percent, com.oculus.systemux.R.attr.layout_constraintHeight_default, com.oculus.systemux.R.attr.layout_constraintHeight_max, com.oculus.systemux.R.attr.layout_constraintHeight_min, com.oculus.systemux.R.attr.layout_constraintHeight_percent, com.oculus.systemux.R.attr.layout_constraintHorizontal_bias, com.oculus.systemux.R.attr.layout_constraintHorizontal_chainStyle, com.oculus.systemux.R.attr.layout_constraintHorizontal_weight, com.oculus.systemux.R.attr.layout_constraintLeft_creator, com.oculus.systemux.R.attr.layout_constraintLeft_toLeftOf, com.oculus.systemux.R.attr.layout_constraintLeft_toRightOf, com.oculus.systemux.R.attr.layout_constraintRight_creator, com.oculus.systemux.R.attr.layout_constraintRight_toLeftOf, com.oculus.systemux.R.attr.layout_constraintRight_toRightOf, com.oculus.systemux.R.attr.layout_constraintStart_toEndOf, com.oculus.systemux.R.attr.layout_constraintStart_toStartOf, com.oculus.systemux.R.attr.layout_constraintTop_creator, com.oculus.systemux.R.attr.layout_constraintTop_toBottomOf, com.oculus.systemux.R.attr.layout_constraintTop_toTopOf, com.oculus.systemux.R.attr.layout_constraintVertical_bias, com.oculus.systemux.R.attr.layout_constraintVertical_chainStyle, com.oculus.systemux.R.attr.layout_constraintVertical_weight, com.oculus.systemux.R.attr.layout_constraintWidth_default, com.oculus.systemux.R.attr.layout_constraintWidth_max, com.oculus.systemux.R.attr.layout_constraintWidth_min, com.oculus.systemux.R.attr.layout_constraintWidth_percent, com.oculus.systemux.R.attr.layout_editor_absoluteX, com.oculus.systemux.R.attr.layout_editor_absoluteY, com.oculus.systemux.R.attr.layout_goneMarginBottom, com.oculus.systemux.R.attr.layout_goneMarginEnd, com.oculus.systemux.R.attr.layout_goneMarginLeft, com.oculus.systemux.R.attr.layout_goneMarginRight, com.oculus.systemux.R.attr.layout_goneMarginStart, com.oculus.systemux.R.attr.layout_goneMarginTop};
        public static final int ConstraintSet_android_alpha = 13;
        public static final int ConstraintSet_android_elevation = 26;
        public static final int ConstraintSet_android_id = 1;
        public static final int ConstraintSet_android_layout_height = 4;
        public static final int ConstraintSet_android_layout_marginBottom = 8;
        public static final int ConstraintSet_android_layout_marginEnd = 24;
        public static final int ConstraintSet_android_layout_marginLeft = 5;
        public static final int ConstraintSet_android_layout_marginRight = 7;
        public static final int ConstraintSet_android_layout_marginStart = 23;
        public static final int ConstraintSet_android_layout_marginTop = 6;
        public static final int ConstraintSet_android_layout_width = 3;
        public static final int ConstraintSet_android_maxHeight = 10;
        public static final int ConstraintSet_android_maxWidth = 9;
        public static final int ConstraintSet_android_minHeight = 12;
        public static final int ConstraintSet_android_minWidth = 11;
        public static final int ConstraintSet_android_orientation = 0;
        public static final int ConstraintSet_android_rotation = 20;
        public static final int ConstraintSet_android_rotationX = 21;
        public static final int ConstraintSet_android_rotationY = 22;
        public static final int ConstraintSet_android_scaleX = 18;
        public static final int ConstraintSet_android_scaleY = 19;
        public static final int ConstraintSet_android_transformPivotX = 14;
        public static final int ConstraintSet_android_transformPivotY = 15;
        public static final int ConstraintSet_android_translationX = 16;
        public static final int ConstraintSet_android_translationY = 17;
        public static final int ConstraintSet_android_translationZ = 25;
        public static final int ConstraintSet_android_visibility = 2;
        public static final int ConstraintSet_barrierAllowsGoneWidgets = 27;
        public static final int ConstraintSet_barrierDirection = 28;
        public static final int ConstraintSet_chainUseRtl = 29;
        public static final int ConstraintSet_constraint_referenced_ids = 30;
        public static final int ConstraintSet_layout_constrainedHeight = 31;
        public static final int ConstraintSet_layout_constrainedWidth = 32;
        public static final int ConstraintSet_layout_constraintBaseline_creator = 33;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf = 34;
        public static final int ConstraintSet_layout_constraintBottom_creator = 35;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf = 36;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf = 37;
        public static final int ConstraintSet_layout_constraintCircle = 38;
        public static final int ConstraintSet_layout_constraintCircleAngle = 39;
        public static final int ConstraintSet_layout_constraintCircleRadius = 40;
        public static final int ConstraintSet_layout_constraintDimensionRatio = 41;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf = 42;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf = 43;
        public static final int ConstraintSet_layout_constraintGuide_begin = 44;
        public static final int ConstraintSet_layout_constraintGuide_end = 45;
        public static final int ConstraintSet_layout_constraintGuide_percent = 46;
        public static final int ConstraintSet_layout_constraintHeight_default = 47;
        public static final int ConstraintSet_layout_constraintHeight_max = 48;
        public static final int ConstraintSet_layout_constraintHeight_min = 49;
        public static final int ConstraintSet_layout_constraintHeight_percent = 50;
        public static final int ConstraintSet_layout_constraintHorizontal_bias = 51;
        public static final int ConstraintSet_layout_constraintHorizontal_chainStyle = 52;
        public static final int ConstraintSet_layout_constraintHorizontal_weight = 53;
        public static final int ConstraintSet_layout_constraintLeft_creator = 54;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf = 55;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf = 56;
        public static final int ConstraintSet_layout_constraintRight_creator = 57;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf = 58;
        public static final int ConstraintSet_layout_constraintRight_toRightOf = 59;
        public static final int ConstraintSet_layout_constraintStart_toEndOf = 60;
        public static final int ConstraintSet_layout_constraintStart_toStartOf = 61;
        public static final int ConstraintSet_layout_constraintTop_creator = 62;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf = 63;
        public static final int ConstraintSet_layout_constraintTop_toTopOf = 64;
        public static final int ConstraintSet_layout_constraintVertical_bias = 65;
        public static final int ConstraintSet_layout_constraintVertical_chainStyle = 66;
        public static final int ConstraintSet_layout_constraintVertical_weight = 67;
        public static final int ConstraintSet_layout_constraintWidth_default = 68;
        public static final int ConstraintSet_layout_constraintWidth_max = 69;
        public static final int ConstraintSet_layout_constraintWidth_min = 70;
        public static final int ConstraintSet_layout_constraintWidth_percent = 71;
        public static final int ConstraintSet_layout_editor_absoluteX = 72;
        public static final int ConstraintSet_layout_editor_absoluteY = 73;
        public static final int ConstraintSet_layout_goneMarginBottom = 74;
        public static final int ConstraintSet_layout_goneMarginEnd = 75;
        public static final int ConstraintSet_layout_goneMarginLeft = 76;
        public static final int ConstraintSet_layout_goneMarginRight = 77;
        public static final int ConstraintSet_layout_goneMarginStart = 78;
        public static final int ConstraintSet_layout_goneMarginTop = 79;
        public static final int[] LinearConstraintLayout = {16842948};
        public static final int LinearConstraintLayout_android_orientation = 0;

        private styleable() {
        }
    }
}
