package com.oculus.horizon.notifications.core;

public enum NotificationType {
    OC_DEVELOPER_CREATED,
    FACEBOOK_FRIEND_ADDED,
    FBCONNECT,
    FRIEND_REQUEST,
    FRIEND_REQUEST_ACCEPT,
    FRIEND_REQUEST_REMOVE,
    MATCHMAKING_MATCHMADE,
    NETWORKING_SEND_BLOB,
    NEW_USER_ENGAGE_APP,
    NEW_USER_FEED_AWARENESS,
    APP_RECOMMENDATION,
    PARTY_INVITE,
    PARTY_INVITED_TO_APPLICATION,
    PARTY_GATHER_IN_APPLICATION,
    PUSH_TOKEN_REGISTRATION,
    ROOM_INVITE,
    ROOM_UPDATE,
    STORE_SALE_BEGINS,
    STORE_SALE_ENDS,
    TEST_DATA,
    TEST_VIEW,
    USER_STATUS,
    VIDEO_RECOMMENDATION,
    UNKNOWN
}
