package com.oculus.partystatemanager.logging;

import X.AbstractC03180ld;
import X.AnonymousClass0Hr;
import X.AnonymousClass0RE;
import X.AnonymousClass0VC;
import X.AnonymousClass0VF;
import X.AnonymousClass0lg;
import X.AnonymousClass1TK;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Inject;
import com.oculus.logging.utils.EventManager;
import com.oculus.partystatemanager.logging.PartyEventFields;
import javax.annotation.Nullable;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_com_oculus_logging_utils_EventManager_ULSEP_BINDING_ID"})
public class PartyEventFactory {
    public AnonymousClass0RE _UL_mInjectionContext;

    @AutoGeneratedAccessMethod
    public static final AbstractC03180ld _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_partystatemanager_logging_PartyEventFactory_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0Hr.A00(0, r1);
    }

    @AutoGeneratedAccessMethod
    public static final PartyEventFactory _UL__ULSEP_com_oculus_partystatemanager_logging_PartyEventFactory_ULSEP_ACCESS_METHOD(AnonymousClass0lg r2) {
        return (PartyEventFactory) AnonymousClass1TK.A00(0, r2, null);
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_partystatemanager_logging_PartyEventFactory_ULGT__ULSEP_ACCESS_METHOD(AnonymousClass0lg r1) {
        return AnonymousClass0VC.A00(0, r1);
    }

    @AutoGeneratedFactoryMethod
    public static final PartyEventFactory _UL__ULSEP_com_oculus_partystatemanager_logging_PartyEventFactory_ULSEP_FACTORY_METHOD(AnonymousClass0lg r1, Object obj) {
        return new PartyEventFactory(r1);
    }

    public PartyEvent OculusPartyVoipPauseResumeEvent(PartyEventFields.EventName eventName, String str, String str2) {
        return new OculusPartyVoipPauseResumeEvent((EventManager) AnonymousClass0VF.A03(0, 92, this._UL_mInjectionContext), eventName, str, str2);
    }

    public PartyEvent createOculusPartyVoipEvent(PartyEventFields.EventName eventName, String str, @Nullable PartyEventFields.Extra extra) {
        return new OculusPartyVoipEvent((EventManager) AnonymousClass0VF.A03(0, 92, this._UL_mInjectionContext), eventName, str, extra);
    }

    @Inject
    public PartyEventFactory(AnonymousClass0lg r3) {
        this._UL_mInjectionContext = new AnonymousClass0RE(1, r3);
    }
}
