package com.oculus.config;

import X.AbstractC06640p5;
import X.AnonymousClass006;
import X.AnonymousClass0Pi;
import X.AnonymousClass0p1;
import X.AnonymousClass117;
import X.C01010Iv;
import android.content.SharedPreferences;
import androidx.annotation.VisibleForTesting;
import com.facebook.inject.ApplicationScoped;
import com.facebook.ultralight.AutoGeneratedAccessMethod;
import com.facebook.ultralight.AutoGeneratedFactoryMethod;
import com.facebook.ultralight.Dependencies;
import com.facebook.ultralight.Eager;
import com.google.common.base.Preconditions;
import com.oculus.config.annotations.GatekeeperSharedPrefs;
import com.oculus.config.gatekeeper.DynamicGatekeeperRegistry;
import com.oculus.config.gatekeeper.GatekeeperRegistry;
import javax.inject.Inject;
import javax.inject.Provider;

@Dependencies({"_UL__ULSEP_com_oculus_config_gatekeeper_GatekeeperRegistry_ULSEP_BINDING_ID", "_UL__ULSEP_android_content_SharedPreferences_ULSEP_com_oculus_config_annotations_GatekeeperSharedPrefs_ULSEP_BINDING_ID", "_UL__ULSEP_com_oculus_config_gatekeeper_DynamicGatekeeperRegistry_ULSEP_BINDING_ID"})
@ApplicationScoped
public class ConfigController {
    public static volatile ConfigController _UL__ULSEP_com_oculus_config_ConfigController_ULSEP_INSTANCE;
    @Inject
    @Eager
    public final DynamicGatekeeperRegistry mDynamicGatekeeperRegistry;
    @Inject
    @Eager
    public final GatekeeperRegistry mGatekeeperRegistry;
    @Inject
    @Eager
    @GatekeeperSharedPrefs
    public final SharedPreferences mSharedPreferences;

    @AutoGeneratedAccessMethod
    public static final AnonymousClass0p1 _UL__ULSEP_com_facebook_inject_Lazy_ULLT_com_oculus_config_ConfigController_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C01010Iv(150, r2);
    }

    @AutoGeneratedAccessMethod
    public static final ConfigController _UL__ULSEP_com_oculus_config_ConfigController_ULSEP_ACCESS_METHOD(AbstractC06640p5 r1) {
        return (ConfigController) AnonymousClass117.A00(150, r1);
    }

    @AutoGeneratedFactoryMethod
    public static final ConfigController _UL__ULSEP_com_oculus_config_ConfigController_ULSEP_FACTORY_METHOD(AbstractC06640p5 r4) {
        if (_UL__ULSEP_com_oculus_config_ConfigController_ULSEP_INSTANCE == null) {
            synchronized (ConfigController.class) {
                AnonymousClass0Pi A00 = AnonymousClass0Pi.A00(_UL__ULSEP_com_oculus_config_ConfigController_ULSEP_INSTANCE, r4);
                if (A00 != null) {
                    try {
                        _UL__ULSEP_com_oculus_config_ConfigController_ULSEP_INSTANCE = new ConfigController(r4.getApplicationInjector());
                    } finally {
                        A00.A01();
                    }
                }
            }
        }
        return _UL__ULSEP_com_oculus_config_ConfigController_ULSEP_INSTANCE;
    }

    @AutoGeneratedAccessMethod
    public static final Provider _UL__ULSEP_javax_inject_Provider_ULLT_com_oculus_config_ConfigController_ULGT__ULSEP_ACCESS_METHOD(AbstractC06640p5 r2) {
        return new C01010Iv(150, r2);
    }

    @VisibleForTesting
    public static String getGatekeeperSharedPreferenceKey(String str) {
        return AnonymousClass006.A05(ConfigModule.SHARED_PREF_KEY_ROOT_GATEKEEPERS, str);
    }

    public static String getOverrideSharedPreferenceKey(String str) {
        return AnonymousClass006.A05(ConfigModule.SHARED_PREF_KEY_OVERRIDE_ROOT, str);
    }

    public boolean isGatekeeperRegistered(String str) {
        if (this.mGatekeeperRegistry.isGatekeeperRegistered(str) || this.mDynamicGatekeeperRegistry.isGatekeeperRegistered(str)) {
            return true;
        }
        return false;
    }

    @Inject
    public ConfigController(AbstractC06640p5 r2) {
        this.mGatekeeperRegistry = ConfigModule._UL__ULSEP_com_oculus_config_gatekeeper_GatekeeperRegistry_ULSEP_ACCESS_METHOD(r2);
        this.mSharedPreferences = ConfigModule._UL__ULSEP_android_content_SharedPreferences_ULSEP_com_oculus_config_annotations_GatekeeperSharedPrefs_ULSEP_ACCESS_METHOD(r2);
        this.mDynamicGatekeeperRegistry = ConfigModule._UL__ULSEP_com_oculus_config_gatekeeper_DynamicGatekeeperRegistry_ULSEP_ACCESS_METHOD(r2);
    }

    public boolean isGatekeeperFetched(String str) {
        Preconditions.checkArgument(isGatekeeperRegistered(str));
        return this.mSharedPreferences.contains(AnonymousClass006.A05(ConfigModule.SHARED_PREF_KEY_ROOT_GATEKEEPERS, str));
    }

    public boolean isGatekeeperOverrideEnabled(String str) {
        boolean contains;
        Preconditions.checkArgument(isGatekeeperRegistered(str));
        String A05 = AnonymousClass006.A05(ConfigModule.SHARED_PREF_KEY_OVERRIDE_ROOT, str);
        synchronized (this.mSharedPreferences) {
            contains = this.mSharedPreferences.contains(A05);
        }
        return contains;
    }

    public Boolean getGatekeeper(String str) {
        return getGatekeeper(str, false);
    }

    public Boolean getGatekeeper(String str, boolean z) {
        Preconditions.checkArgument(isGatekeeperRegistered(str));
        synchronized (this.mSharedPreferences) {
            String A05 = AnonymousClass006.A05(ConfigModule.SHARED_PREF_KEY_OVERRIDE_ROOT, str);
            if (this.mSharedPreferences.contains(A05)) {
                return Boolean.valueOf(this.mSharedPreferences.getBoolean(A05, z));
            }
            return Boolean.valueOf(this.mSharedPreferences.getBoolean(AnonymousClass006.A05(ConfigModule.SHARED_PREF_KEY_ROOT_GATEKEEPERS, str), z));
        }
    }
}
